{"name":"la/platform/external/aws-sdk-java-v2","clone_url":"https://git.codelinaro.org/clo/la/platform/external/aws-sdk-java-v2.git","description":null}
{"name":"la/platform/external/vboot_reference","clone_url":"https://git.codelinaro.org/clo/la/platform/external/vboot_reference.git","description":null}
{"name":"yocto-mirrors/github/ros2-gbp/stomp-release","clone_url":"https://git.codelinaro.org/clo/yocto-mirrors/github/ros2-gbp/stomp-release.git","description":null}
{"name":"lf/releases/l10n/sr-latn/gaia","clone_url":"https://git.codelinaro.org/clo/lf/releases/l10n/sr-latn/gaia.git","description":null}
{"name":"qsdk/oss/firmware/ath10k-firmware","clone_url":"https://git.codelinaro.org/clo/qsdk/oss/firmware/ath10k-firmware.git","description":null}
{"name":"la/platform/vendor/qcom/msm8625","clone_url":"https://git.codelinaro.org/clo/la/platform/vendor/qcom/msm8625.git","description":null}
{"name":"la/platform/frameworks/janktesthelper","clone_url":"https://git.codelinaro.org/clo/la/platform/frameworks/janktesthelper.git","description":null}
{"name":"yocto-mirrors/selinux","clone_url":"https://git.codelinaro.org/clo/yocto-mirrors/selinux.git","description":null}
{"name":"testproject/platform/external/clang","clone_url":"https://git.codelinaro.org/clo/testproject/platform/external/clang.git","description":null}
{"name":"testproject/platform/external/google-fonts/fraunces","clone_url":"https://git.codelinaro.org/clo/testproject/platform/external/google-fonts/fraunces.git","description":null}
{"name":"testproject/platform/external/compiler-rt","clone_url":"https://git.codelinaro.org/clo/testproject/platform/external/compiler-rt.git","description":null}
{"name":"qnbrd/patches","clone_url":"https://git.codelinaro.org/clo/qnbrd/patches.git","description":null}
{"name":"le/platform/external/turtlebot4_simulator","clone_url":"https://git.codelinaro.org/clo/le/platform/external/turtlebot4_simulator.git","description":null}
{"name":"le/ros-perception/image_pipeline","clone_url":"https://git.codelinaro.org/clo/le/ros-perception/image_pipeline.git","description":null}
{"name":"la/platform/external/boost-submodules/variant2","clone_url":"https://git.codelinaro.org/clo/la/platform/external/boost-submodules/variant2.git","description":null}
{"name":"la/platform/external/libese","clone_url":"https://git.codelinaro.org/clo/la/platform/external/libese.git","description":null}
{"name":"la/platform/hardware/qcom/camera-legacy","clone_url":"https://git.codelinaro.org/clo/la/platform/hardware/qcom/camera-legacy.git","description":null}
{"name":"lc/external/github.com/maruel/ut","clone_url":"https://git.codelinaro.org/clo/lc/external/github.com/maruel/ut.git","description":null}
{"name":"testproject/platform/external/python/ipaddress","clone_url":"https://git.codelinaro.org/clo/testproject/platform/external/python/ipaddress.git","description":null}
{"name":"la/platform/external/jline","clone_url":"https://git.codelinaro.org/clo/la/platform/external/jline.git","description":null}
{"name":"la/platform/tools/tradefederation/prebuilts","clone_url":"https://git.codelinaro.org/clo/la/platform/tools/tradefederation/prebuilts.git","description":null}
{"name":"la/kernelplatform/prebuilts/gcc/linux-x86/aarch64/aarch64-linux-android-4.9","clone_url":"https://git.codelinaro.org/clo/la/kernelplatform/prebuilts/gcc/linux-x86/aarch64/aarch64-linux-android-4.9.git","description":null}
{"name":"linux-kernel/gunyah-linux","clone_url":"https://git.codelinaro.org/clo/linux-kernel/gunyah-linux.git","description":null}
{"name":"la/kernel/amlogic-tv-modules/media_modules","clone_url":"https://git.codelinaro.org/clo/la/kernel/amlogic-tv-modules/media_modules.git","description":null}
{"name":"lc/chromium/src/third_party/protobuf","clone_url":"https://git.codelinaro.org/clo/lc/chromium/src/third_party/protobuf.git","description":null}
{"name":"la/platform/external/jxmpp","clone_url":"https://git.codelinaro.org/clo/la/platform/external/jxmpp.git","description":null}
{"name":"bt/platform/hardware/qcom/bt","clone_url":"https://git.codelinaro.org/clo/bt/platform/hardware/qcom/bt.git","description":null}
{"name":"lc/external/github.com/thoj/go-ircevent","clone_url":"https://git.codelinaro.org/clo/lc/external/github.com/thoj/go-ircevent.git","description":null}
{"name":"rdkb/rdk/components/generic/rdkssa","clone_url":"https://git.codelinaro.org/clo/rdkb/rdk/components/generic/rdkssa.git","description":null}
{"name":"lc/chromium/deps/jarjar","clone_url":"https://git.codelinaro.org/clo/lc/chromium/deps/jarjar.git","description":null}
{"name":"la/platform/hardware/nxp/nfc","clone_url":"https://git.codelinaro.org/clo/la/platform/hardware/nxp/nfc.git","description":null}
{"name":"la/platform/external/gradle-perf-android-large","clone_url":"https://git.codelinaro.org/clo/la/platform/external/gradle-perf-android-large.git","description":null}
{"name":"femto5g/oss/lklm/nss-speedtest","clone_url":"https://git.codelinaro.org/clo/femto5g/oss/lklm/nss-speedtest.git","description":null}
{"name":"yocto-mirrors/github/libuv/libuv","clone_url":"https://git.codelinaro.org/clo/yocto-mirrors/github/libuv/libuv.git","description":null}
{"name":"testproject/platform/external/python/cffi","clone_url":"https://git.codelinaro.org/clo/testproject/platform/external/python/cffi.git","description":null}
{"name":"testproject/platform/system/connectivity/wifilogd","clone_url":"https://git.codelinaro.org/clo/testproject/platform/system/connectivity/wifilogd.git","description":null}
{"name":"la/platform/tools/studio/google/samples","clone_url":"https://git.codelinaro.org/clo/la/platform/tools/studio/google/samples.git","description":null}
{"name":"la/platform/external/tinyxml","clone_url":"https://git.codelinaro.org/clo/la/platform/external/tinyxml.git","description":null}
{"name":"la/platform/vendor/nxp/opensource/reference","clone_url":"https://git.codelinaro.org/clo/la/platform/vendor/nxp/opensource/reference.git","description":null}
{"name":"la/platform/frameworks/opt/inputconnectioncommon","clone_url":"https://git.codelinaro.org/clo/la/platform/frameworks/opt/inputconnectioncommon.git","description":null}
{"name":"lc/codesearch/infra/infra","clone_url":"https://git.codelinaro.org/clo/lc/codesearch/infra/infra.git","description":null}
{"name":"la/platform/external/rust/crates/criterion","clone_url":"https://git.codelinaro.org/clo/la/platform/external/rust/crates/criterion.git","description":null}
{"name":"lc/infra/third_party/MarkupSafe","clone_url":"https://git.codelinaro.org/clo/lc/infra/third_party/MarkupSafe.git","description":null}
{"name":"lc/test_analyzer","clone_url":"https://git.codelinaro.org/clo/lc/test_analyzer.git","description":null}
{"name":"la/kernel/boot-wrapper-aarch64","clone_url":"https://git.codelinaro.org/clo/la/kernel/boot-wrapper-aarch64.git","description":null}
{"name":"la/platform/external/jetbrains/jdk8u_jdk","clone_url":"https://git.codelinaro.org/clo/la/platform/external/jetbrains/jdk8u_jdk.git","description":null}
{"name":"la/platform/external/python/setuptools","clone_url":"https://git.codelinaro.org/clo/la/platform/external/python/setuptools.git","description":null}
{"name":"testproject/platform/external/oss-fuzz","clone_url":"https://git.codelinaro.org/clo/testproject/platform/external/oss-fuzz.git","description":null}
{"name":"yocto-mirrors/libaio","clone_url":"https://git.codelinaro.org/clo/yocto-mirrors/libaio.git","description":null}
{"name":"qsdk/opkg","clone_url":"https://git.codelinaro.org/clo/qsdk/opkg.git","description":null}
{"name":"la/platform/external/rust/crates/no-panic","clone_url":"https://git.codelinaro.org/clo/la/platform/external/rust/crates/no-panic.git","description":null}
{"name":"le/data/hostsw_repo","clone_url":"https://git.codelinaro.org/clo/le/data/hostsw_repo.git","description":null}
{"name":"foundriesio/patches","clone_url":"https://git.codelinaro.org/clo/foundriesio/patches.git","description":null}
{"name":"la/device/google/dragon-kernel","clone_url":"https://git.codelinaro.org/clo/la/device/google/dragon-kernel.git","description":null}
{"name":"la/platform/external/google-auth-library-java","clone_url":"https://git.codelinaro.org/clo/la/platform/external/google-auth-library-java.git","description":null}
{"name":"yocto-mirrors/lapack","clone_url":"https://git.codelinaro.org/clo/yocto-mirrors/lapack.git","description":null}
{"name":"la/kernel/google-modules/display_group/watch/mcu-offload","clone_url":"https://git.codelinaro.org/clo/la/kernel/google-modules/display_group/watch/mcu-offload.git","description":null}
{"name":"testproject/platform/packages/apps/Contacts","clone_url":"https://git.codelinaro.org/clo/testproject/platform/packages/apps/Contacts.git","description":null}
{"name":"testproject/platform/external/sonic","clone_url":"https://git.codelinaro.org/clo/testproject/platform/external/sonic.git","description":null}
{"name":"la/platform/packages/apps/FM2","clone_url":"https://git.codelinaro.org/clo/la/platform/packages/apps/FM2.git","description":null}
{"name":"la/platform/system/gsid","clone_url":"https://git.codelinaro.org/clo/la/platform/system/gsid.git","description":null}
{"name":"yocto-mirrors/github/danmar/cppcheck","clone_url":"https://git.codelinaro.org/clo/yocto-mirrors/github/danmar/cppcheck.git","description":null}
{"name":"le/platform/hardware/qcom/media","clone_url":"https://git.codelinaro.org/clo/le/platform/hardware/qcom/media.git","description":null}
{"name":"lc/external/github.com/dynamorio/drmemory","clone_url":"https://git.codelinaro.org/clo/lc/external/github.com/dynamorio/drmemory.git","description":null}
{"name":"la/platform/external/aehd","clone_url":"https://git.codelinaro.org/clo/la/platform/external/aehd.git","description":null}
{"name":"lc/chromium/src/test/data/reliability","clone_url":"https://git.codelinaro.org/clo/lc/chromium/src/test/data/reliability.git","description":null}
{"name":"la/device/htc/sapphire","clone_url":"https://git.codelinaro.org/clo/la/device/htc/sapphire.git","description":null}
{"name":"la/platform/frameworks/support","clone_url":"https://git.codelinaro.org/clo/la/platform/frameworks/support.git","description":null}
{"name":"yocto-mirrors/github/kennylevinsen/seatd","clone_url":"https://git.codelinaro.org/clo/yocto-mirrors/github/kennylevinsen/seatd.git","description":null}
{"name":"le/OSGeo/shapelib","clone_url":"https://git.codelinaro.org/clo/le/OSGeo/shapelib.git","description":null}
{"name":"lc/chromiumos/platform/dump-syms","clone_url":"https://git.codelinaro.org/clo/lc/chromiumos/platform/dump-syms.git","description":null}
{"name":"la/platform/external/TestParameterInjector","clone_url":"https://git.codelinaro.org/clo/la/platform/external/TestParameterInjector.git","description":null}
{"name":"le/meta-allplay","clone_url":"https://git.codelinaro.org/clo/le/meta-allplay.git","description":null}
{"name":"yocto-mirrors/github/google/re2","clone_url":"https://git.codelinaro.org/clo/yocto-mirrors/github/google/re2.git","description":null}
{"name":"la/platform/external/v8","clone_url":"https://git.codelinaro.org/clo/la/platform/external/v8.git","description":null}
{"name":"la/external/rust/crates/autocfg","clone_url":"https://git.codelinaro.org/clo/la/external/rust/crates/autocfg.git","description":null}
{"name":"la/platform/packages/modules/Tethering","clone_url":"https://git.codelinaro.org/clo/la/platform/packages/modules/Tethering.git","description":null}
{"name":"lc/codecs/infra","clone_url":"https://git.codelinaro.org/clo/lc/codecs/infra.git","description":null}
{"name":"qsdk/system/openwrt_repo","clone_url":"https://git.codelinaro.org/clo/qsdk/system/openwrt_repo.git","description":null}
{"name":"la/platform/external/libaio","clone_url":"https://git.codelinaro.org/clo/la/platform/external/libaio.git","description":null}
{"name":"yocto-mirrors/github/go-openapi/jsonpointer","clone_url":"https://git.codelinaro.org/clo/yocto-mirrors/github/go-openapi/jsonpointer.git","description":null}
{"name":"la/platform/external/rust/crates/proc-macro2","clone_url":"https://git.codelinaro.org/clo/la/platform/external/rust/crates/proc-macro2.git","description":null}
{"name":"yocto-mirrors/runtime-tools","clone_url":"https://git.codelinaro.org/clo/yocto-mirrors/runtime-tools.git","description":null}
{"name":"la/latform/external/protobuf-javalite","clone_url":"https://git.codelinaro.org/clo/la/latform/external/protobuf-javalite.git","description":null}
{"name":"la/platform/external/honggfuzz","clone_url":"https://git.codelinaro.org/clo/la/platform/external/honggfuzz.git","description":null}
{"name":"la/platform/external/boost-submodules/any","clone_url":"https://git.codelinaro.org/clo/la/platform/external/boost-submodules/any.git","description":null}
{"name":"la/platform/external/gdata","clone_url":"https://git.codelinaro.org/clo/la/platform/external/gdata.git","description":null}
{"name":"rdkb/rdkb/components/opensource/ccsp/sysint","clone_url":"https://git.codelinaro.org/clo/rdkb/rdkb/components/opensource/ccsp/sysint.git","description":null}
{"name":"yocto-mirrors/github/moby/locker","clone_url":"https://git.codelinaro.org/clo/yocto-mirrors/github/moby/locker.git","description":null}
{"name":"la/platform/external/rust/crates/ciborium-io","clone_url":"https://git.codelinaro.org/clo/la/platform/external/rust/crates/ciborium-io.git","description":null}
{"name":"la/platform/external/google-fonts/coming-soon","clone_url":"https://git.codelinaro.org/clo/la/platform/external/google-fonts/coming-soon.git","description":null}
{"name":"testproject/platform/developers/build","clone_url":"https://git.codelinaro.org/clo/testproject/platform/developers/build.git","description":null}
{"name":"le/ros2-gbp/ros2_message_filters-release","clone_url":"https://git.codelinaro.org/clo/le/ros2-gbp/ros2_message_filters-release.git","description":null}
{"name":"ype/external/yoctoproject.org/poky","clone_url":"https://git.codelinaro.org/clo/ype/external/yoctoproject.org/poky.git","description":null}
{"name":"testproject/platform/prebuilts/fuchsia_sdk","clone_url":"https://git.codelinaro.org/clo/testproject/platform/prebuilts/fuchsia_sdk.git","description":null}
{"name":"la/device/google/fuchsia","clone_url":"https://git.codelinaro.org/clo/la/device/google/fuchsia.git","description":null}
{"name":"testproject/toolchain/pgo-profiles","clone_url":"https://git.codelinaro.org/clo/testproject/toolchain/pgo-profiles.git","description":null}
{"name":"testproject/platform/external/libvpx","clone_url":"https://git.codelinaro.org/clo/testproject/platform/external/libvpx.git","description":null}
{"name":"la/platform/prebuilts/clang/linux-x86/arm/3.3","clone_url":"https://git.codelinaro.org/clo/la/platform/prebuilts/clang/linux-x86/arm/3.3.git","description":null}
{"name":"la/platform/external/libcap-ng","clone_url":"https://git.codelinaro.org/clo/la/platform/external/libcap-ng.git","description":null}
{"name":"yocto-mirrors/k3s-io/k3s","clone_url":"https://git.codelinaro.org/clo/yocto-mirrors/k3s-io/k3s.git","description":null}
{"name":"le/platform/external/minijail","clone_url":"https://git.codelinaro.org/clo/le/platform/external/minijail.git","description":null}
{"name":"le/platform/vendor/qcom-opensource/le-services","clone_url":"https://git.codelinaro.org/clo/le/platform/vendor/qcom-opensource/le-services.git","description":null}
{"name":"qsdk/qsdk/qca/src/container_apis","clone_url":"https://git.codelinaro.org/clo/qsdk/qsdk/qca/src/container_apis.git","description":null}
{"name":"la/platform/external/python/pyyaml","clone_url":"https://git.codelinaro.org/clo/la/platform/external/python/pyyaml.git","description":null}
{"name":"yocto-mirrors/github/ros2-gbp/realtime_tools-release","clone_url":"https://git.codelinaro.org/clo/yocto-mirrors/github/ros2-gbp/realtime_tools-release.git","description":null}
{"name":"la/techpack/camera/manifest","clone_url":"https://git.codelinaro.org/clo/la/techpack/camera/manifest.git","description":null}
{"name":"le/wayland/weston","clone_url":"https://git.codelinaro.org/clo/le/wayland/weston.git","description":null}
{"name":"le/platform/vendor/qcom-opensource/audio-virtio-be","clone_url":"https://git.codelinaro.org/clo/le/platform/vendor/qcom-opensource/audio-virtio-be.git","description":null}
{"name":"le/ros2-gbp/fastcdr-release","clone_url":"https://git.codelinaro.org/clo/le/ros2-gbp/fastcdr-release.git","description":null}
{"name":"yocto-mirrors/github/ros2-gbp/foonathan_memory_vendor-release","clone_url":"https://git.codelinaro.org/clo/yocto-mirrors/github/ros2-gbp/foonathan_memory_vendor-release.git","description":null}
{"name":"la/platform/external/libvncserver","clone_url":"https://git.codelinaro.org/clo/la/platform/external/libvncserver.git","description":null}
{"name":"lc/external/github.com/googlechromelabs/pywebsocket3","clone_url":"https://git.codelinaro.org/clo/lc/external/github.com/googlechromelabs/pywebsocket3.git","description":null}
{"name":"la/toolchain/mpfr","clone_url":"https://git.codelinaro.org/clo/la/toolchain/mpfr.git","description":null}
{"name":"qrdk/squashfs-tools","clone_url":"https://git.codelinaro.org/clo/qrdk/squashfs-tools.git","description":null}
{"name":"lc/external/github.com/material-foundation/material-roboto-font-loader-ios","clone_url":"https://git.codelinaro.org/clo/lc/external/github.com/material-foundation/material-roboto-font-loader-ios.git","description":null}
{"name":"qrdk/cjwt","clone_url":"https://git.codelinaro.org/clo/qrdk/cjwt.git","description":null}
{"name":"rdkb/rdkb/components/opensource/ccsp/CcspCr","clone_url":"https://git.codelinaro.org/clo/rdkb/rdkb/components/opensource/ccsp/CcspCr.git","description":null}
{"name":"yocto-mirrors/ca-certificates","clone_url":"https://git.codelinaro.org/clo/yocto-mirrors/ca-certificates.git","description":null}
{"name":"le/vendor/qcom/opensource/eavb","clone_url":"https://git.codelinaro.org/clo/le/vendor/qcom/opensource/eavb.git","description":null}
{"name":"ype/external/github.com/meta-qt5/meta-qt5","clone_url":"https://git.codelinaro.org/clo/ype/external/github.com/meta-qt5/meta-qt5.git","description":null}
{"name":"la/platform/hardware/st/nfc","clone_url":"https://git.codelinaro.org/clo/la/platform/hardware/st/nfc.git","description":null}
{"name":"le/genivi/ipc/capicxx-dbus-runtime","clone_url":"https://git.codelinaro.org/clo/le/genivi/ipc/capicxx-dbus-runtime.git","description":null}
{"name":"la/platform/external/rust/crates/pest_meta","clone_url":"https://git.codelinaro.org/clo/la/platform/external/rust/crates/pest_meta.git","description":null}
{"name":"le/AGL/apps/phone","clone_url":"https://git.codelinaro.org/clo/le/AGL/apps/phone.git","description":null}
{"name":"la/tools/plugin-testing","clone_url":"https://git.codelinaro.org/clo/la/tools/plugin-testing.git","description":null}
{"name":"qsdk/hostap","clone_url":"https://git.codelinaro.org/clo/qsdk/hostap.git","description":null}
{"name":"lc/external/github.com/osandov/blktests","clone_url":"https://git.codelinaro.org/clo/lc/external/github.com/osandov/blktests.git","description":null}
{"name":"inferno-for-quatro-socs/patches","clone_url":"https://git.codelinaro.org/clo/inferno-for-quatro-socs/patches.git","description":null}
{"name":"yocto-mirrors/memory","clone_url":"https://git.codelinaro.org/clo/yocto-mirrors/memory.git","description":null}
{"name":"la/platform/vendor/invensense","clone_url":"https://git.codelinaro.org/clo/la/platform/vendor/invensense.git","description":null}
{"name":"la/platform/external/boost-submodules/rational","clone_url":"https://git.codelinaro.org/clo/la/platform/external/boost-submodules/rational.git","description":null}
{"name":"la/platform/prebuilts/python/darwin-x86/2.7.5","clone_url":"https://git.codelinaro.org/clo/la/platform/prebuilts/python/darwin-x86/2.7.5.git","description":null}
{"name":"la/external/github.com/quic-qrb-ros/qrb_ros_samples/simulation_sample_amr_simple_motion","clone_url":"https://git.codelinaro.org/clo/la/external/github.com/quic-qrb-ros/qrb_ros_samples/simulation_sample_amr_simple_motion.git","description":null}
{"name":"testproject/platform/packages/modules/ArtPrebuilt","clone_url":"https://git.codelinaro.org/clo/testproject/platform/packages/modules/ArtPrebuilt.git","description":null}
{"name":"yocto-mirrors/github/defanglabs/secret-detector","clone_url":"https://git.codelinaro.org/clo/yocto-mirrors/github/defanglabs/secret-detector.git","description":null}
{"name":"le/external/qtscript","clone_url":"https://git.codelinaro.org/clo/le/external/qtscript.git","description":null}
{"name":"rdkb/rdk/components/generic/rdm","clone_url":"https://git.codelinaro.org/clo/rdkb/rdk/components/generic/rdm.git","description":null}
{"name":"la/platform/external/chromium_org/third_party/angle","clone_url":"https://git.codelinaro.org/clo/la/platform/external/chromium_org/third_party/angle.git","description":null}
{"name":"la/platform/external/google-api-go-client","clone_url":"https://git.codelinaro.org/clo/la/platform/external/google-api-go-client.git","description":null}
{"name":"yocto-mirrors/libosinfo","clone_url":"https://git.codelinaro.org/clo/yocto-mirrors/libosinfo.git","description":null}
{"name":"la/platform/packages/modules/ApiExtensions","clone_url":"https://git.codelinaro.org/clo/la/platform/packages/modules/ApiExtensions.git","description":null}
{"name":"la/platform/system/server_configurable_flags","clone_url":"https://git.codelinaro.org/clo/la/platform/system/server_configurable_flags.git","description":null}
{"name":"femto5g/platform/system/core","clone_url":"https://git.codelinaro.org/clo/femto5g/platform/system/core.git","description":null}
{"name":"la/platform/external/boost-submodules/geometry","clone_url":"https://git.codelinaro.org/clo/la/platform/external/boost-submodules/geometry.git","description":null}
{"name":"la/platform/external/FreeRTOS/coreJSON","clone_url":"https://git.codelinaro.org/clo/la/platform/external/FreeRTOS/coreJSON.git","description":null}
{"name":"yocto-mirrors/github/adalogics/go-fuzz-headers","clone_url":"https://git.codelinaro.org/clo/yocto-mirrors/github/adalogics/go-fuzz-headers.git","description":null}
{"name":"yocto-mirrors/github/quic/fastrpc","clone_url":"https://git.codelinaro.org/clo/yocto-mirrors/github/quic/fastrpc.git","description":null}
{"name":"le/platform/external/virglrenderer","clone_url":"https://git.codelinaro.org/clo/le/platform/external/virglrenderer.git","description":null}
{"name":"la/platform/packages/modules/IntentResolver","clone_url":"https://git.codelinaro.org/clo/la/platform/packages/modules/IntentResolver.git","description":null}
{"name":"le/owrt/feeds/luci","clone_url":"https://git.codelinaro.org/clo/le/owrt/feeds/luci.git","description":null}
{"name":"lf/releases/l10n/hu/gaia","clone_url":"https://git.codelinaro.org/clo/lf/releases/l10n/hu/gaia.git","description":null}
{"name":"testproject/platform/external/libffi","clone_url":"https://git.codelinaro.org/clo/testproject/platform/external/libffi.git","description":null}
{"name":"qcomlt/boot/tfa","clone_url":"https://git.codelinaro.org/clo/qcomlt/boot/tfa.git","description":null}
{"name":"la/platform/external/boost-submodules/iterator","clone_url":"https://git.codelinaro.org/clo/la/platform/external/boost-submodules/iterator.git","description":null}
{"name":"la/platform/vendor/qcom/msmnileau_t","clone_url":"https://git.codelinaro.org/clo/la/platform/vendor/qcom/msmnileau_t.git","description":null}
{"name":"la/kernel/msm-modules_group/securemsm","clone_url":"https://git.codelinaro.org/clo/la/kernel/msm-modules_group/securemsm.git","description":null}
{"name":"qsdk/platform/vendor/qcom-opensource/kernel-tests/mm-audio","clone_url":"https://git.codelinaro.org/clo/qsdk/platform/vendor/qcom-opensource/kernel-tests/mm-audio.git","description":null}
{"name":"la/kernel/msm-extra_group/display-drivers","clone_url":"https://git.codelinaro.org/clo/la/kernel/msm-extra_group/display-drivers.git","description":null}
{"name":"la/platform/vendor/qcom-opensource/ts_firmware","clone_url":"https://git.codelinaro.org/clo/la/platform/vendor/qcom-opensource/ts_firmware.git","description":null}
{"name":"la/platform/packages/apps/Launcher3","clone_url":"https://git.codelinaro.org/clo/la/platform/packages/apps/Launcher3.git","description":null}
{"name":"le/le/rules","clone_url":"https://git.codelinaro.org/clo/le/le/rules.git","description":null}
{"name":"le/miracast","clone_url":"https://git.codelinaro.org/clo/le/miracast.git","description":null}
{"name":"yocto-mirrors/github/stretchr/testify","clone_url":"https://git.codelinaro.org/clo/yocto-mirrors/github/stretchr/testify.git","description":null}
{"name":"lc/chromiumos/third_party/libnox","clone_url":"https://git.codelinaro.org/clo/lc/chromiumos/third_party/libnox.git","description":null}
{"name":"la/kernel/configs","clone_url":"https://git.codelinaro.org/clo/la/kernel/configs.git","description":null}
{"name":"la/platform/vendor/nxp/opensource/external/libnfc-nci","clone_url":"https://git.codelinaro.org/clo/la/platform/vendor/nxp/opensource/external/libnfc-nci.git","description":null}
{"name":"la/platform/external/jspecify","clone_url":"https://git.codelinaro.org/clo/la/platform/external/jspecify.git","description":null}
{"name":"testproject/platform/external/modp_b64","clone_url":"https://git.codelinaro.org/clo/testproject/platform/external/modp_b64.git","description":null}
{"name":"imx-support/meta-fsl-bsp-release","clone_url":"https://git.codelinaro.org/clo/imx-support/meta-fsl-bsp-release.git","description":null}
{"name":"qsdk/breakpad","clone_url":"https://git.codelinaro.org/clo/qsdk/breakpad.git","description":null}
{"name":"la/platform/sdk","clone_url":"https://git.codelinaro.org/clo/la/platform/sdk.git","description":null}
{"name":"la/platform/vendor/qcom-opensource/ufs-tools","clone_url":"https://git.codelinaro.org/clo/la/platform/vendor/qcom-opensource/ufs-tools.git","description":null}
{"name":"yocto-mirrors/meta-security","clone_url":"https://git.codelinaro.org/clo/yocto-mirrors/meta-security.git","description":null}
{"name":"femto5g/kernel/msm-5.4","clone_url":"https://git.codelinaro.org/clo/femto5g/kernel/msm-5.4.git","description":null}
{"name":"qcomlt/debugboard-fw","clone_url":"https://git.codelinaro.org/clo/qcomlt/debugboard-fw.git","description":null}
{"name":"la/platform/external/capicxx-someip-runtime","clone_url":"https://git.codelinaro.org/clo/la/platform/external/capicxx-someip-runtime.git","description":null}
{"name":"testproject/platform/hardware/st/secure_element","clone_url":"https://git.codelinaro.org/clo/testproject/platform/hardware/st/secure_element.git","description":null}
{"name":"la/kernel/y2038-endgame","clone_url":"https://git.codelinaro.org/clo/la/kernel/y2038-endgame.git","description":null}
{"name":"la/platform/external/modp_b64","clone_url":"https://git.codelinaro.org/clo/la/platform/external/modp_b64.git","description":null}
{"name":"la/platform/packages/apps/ThemePicker","clone_url":"https://git.codelinaro.org/clo/la/platform/packages/apps/ThemePicker.git","description":null}
{"name":"la/platform/packages/modules/Telephony","clone_url":"https://git.codelinaro.org/clo/la/platform/packages/modules/Telephony.git","description":null}
{"name":"lc/external/github.com/dart-lang/http_multi_server","clone_url":"https://git.codelinaro.org/clo/lc/external/github.com/dart-lang/http_multi_server.git","description":null}
{"name":"la/platform/external/boost-submodules/preprocessor","clone_url":"https://git.codelinaro.org/clo/la/platform/external/boost-submodules/preprocessor.git","description":null}
{"name":"yocto-mirrors/github/ros2-gbp/osrf_pycommon-release","clone_url":"https://git.codelinaro.org/clo/yocto-mirrors/github/ros2-gbp/osrf_pycommon-release.git","description":null}
{"name":"le/platform/external/turtlebot4_examples","clone_url":"https://git.codelinaro.org/clo/le/platform/external/turtlebot4_examples.git","description":null}
{"name":"la/platform/prebuilts/build-artifacts","clone_url":"https://git.codelinaro.org/clo/la/platform/prebuilts/build-artifacts.git","description":null}
{"name":"yocto-mirrors/github/kylelemons/godebug","clone_url":"https://git.codelinaro.org/clo/yocto-mirrors/github/kylelemons/godebug.git","description":null}
{"name":"la/platform/external/lldb","clone_url":"https://git.codelinaro.org/clo/la/platform/external/lldb.git","description":null}
{"name":"le/external/gemmlowp","clone_url":"https://git.codelinaro.org/clo/le/external/gemmlowp.git","description":null}
{"name":"la/platform/packages/screensavers/WebView","clone_url":"https://git.codelinaro.org/clo/la/platform/packages/screensavers/WebView.git","description":null}
{"name":"imx-support/imx-linux-gatesgarth","clone_url":"https://git.codelinaro.org/clo/imx-support/imx-linux-gatesgarth.git","description":null}
{"name":"la/platform/vendor/qcom/gen4_gvm_gy_sgt","clone_url":"https://git.codelinaro.org/clo/la/platform/vendor/qcom/gen4_gvm_gy_sgt.git","description":null}
{"name":"la/platform/libcore","clone_url":"https://git.codelinaro.org/clo/la/platform/libcore.git","description":null}
{"name":"la/kernel/google-modules/touch/parade_touch","clone_url":"https://git.codelinaro.org/clo/la/kernel/google-modules/touch/parade_touch.git","description":null}
{"name":"la/platform/packages/apps/SystemUIGo","clone_url":"https://git.codelinaro.org/clo/la/platform/packages/apps/SystemUIGo.git","description":null}
{"name":"la/device/google/shusky-kernels/5.15","clone_url":"https://git.codelinaro.org/clo/la/device/google/shusky-kernels/5.15.git","description":null}
{"name":"qcomlt/pkg/gst-plugins-base1.0","clone_url":"https://git.codelinaro.org/clo/qcomlt/pkg/gst-plugins-base1.0.git","description":null}
{"name":"la/platform/external/python/pyserial","clone_url":"https://git.codelinaro.org/clo/la/platform/external/python/pyserial.git","description":null}
{"name":"la/platform/external/messageformat","clone_url":"https://git.codelinaro.org/clo/la/platform/external/messageformat.git","description":null}
{"name":"yocto-mirrors/docker/cli","clone_url":"https://git.codelinaro.org/clo/yocto-mirrors/docker/cli.git","description":null}
{"name":"la/platform/external/exfatprogs","clone_url":"https://git.codelinaro.org/clo/la/platform/external/exfatprogs.git","description":null}
{"name":"la/external/live555","clone_url":"https://git.codelinaro.org/clo/la/external/live555.git","description":null}
{"name":"la/platform/packages/modules/Bluetooth","clone_url":"https://git.codelinaro.org/clo/la/platform/packages/modules/Bluetooth.git","description":null}
{"name":"qsdk/oss/lklm/nss-ae-clients","clone_url":"https://git.codelinaro.org/clo/qsdk/oss/lklm/nss-ae-clients.git","description":null}
{"name":"le/platform/external/ros2/cartographer","clone_url":"https://git.codelinaro.org/clo/le/platform/external/ros2/cartographer.git","description":null}
{"name":"le/platform/vendor/qcom-opensource/robot-control","clone_url":"https://git.codelinaro.org/clo/le/platform/vendor/qcom-opensource/robot-control.git","description":null}
{"name":"testproject/platform/frameworks/wilhelm","clone_url":"https://git.codelinaro.org/clo/testproject/platform/frameworks/wilhelm.git","description":null}
{"name":"la/platform/prebuilts/libprotobuf/darwin-x86","clone_url":"https://git.codelinaro.org/clo/la/platform/prebuilts/libprotobuf/darwin-x86.git","description":null}
{"name":"lc/native_client/pnacl-compiler-rt","clone_url":"https://git.codelinaro.org/clo/lc/native_client/pnacl-compiler-rt.git","description":null}
{"name":"la/platform/external/objenesis","clone_url":"https://git.codelinaro.org/clo/la/platform/external/objenesis.git","description":null}
{"name":"yocto-mirrors/jitterentropy-library","clone_url":"https://git.codelinaro.org/clo/yocto-mirrors/jitterentropy-library.git","description":null}
{"name":"qcomlt/pkg/tqftpserv","clone_url":"https://git.codelinaro.org/clo/qcomlt/pkg/tqftpserv.git","description":null}
{"name":"lc/chromiumos/platform/vboot_reference","clone_url":"https://git.codelinaro.org/clo/lc/chromiumos/platform/vboot_reference.git","description":null}
{"name":"la/platform/system/vold","clone_url":"https://git.codelinaro.org/clo/la/platform/system/vold.git","description":null}
{"name":"le/ros2-gbp/demos-release","clone_url":"https://git.codelinaro.org/clo/le/ros2-gbp/demos-release.git","description":null}
{"name":"yocto-mirrors/libusb-compat-0.1","clone_url":"https://git.codelinaro.org/clo/yocto-mirrors/libusb-compat-0.1.git","description":null}
{"name":"testproject/platform/test/vts-testcase/vndk","clone_url":"https://git.codelinaro.org/clo/testproject/platform/test/vts-testcase/vndk.git","description":null}
{"name":"la/platform/external/protobuf","clone_url":"https://git.codelinaro.org/clo/la/platform/external/protobuf.git","description":null}
{"name":"le/Igalia/cog","clone_url":"https://git.codelinaro.org/clo/le/Igalia/cog.git","description":null}
{"name":"testproject/platform/frameworks/layoutlib","clone_url":"https://git.codelinaro.org/clo/testproject/platform/frameworks/layoutlib.git","description":null}
{"name":"qrdk/linux-syscall-support","clone_url":"https://git.codelinaro.org/clo/qrdk/linux-syscall-support.git","description":null}
{"name":"yocto-mirrors/github/keybase/go-keychain","clone_url":"https://git.codelinaro.org/clo/yocto-mirrors/github/keybase/go-keychain.git","description":null}
{"name":"la/device/google/redfin-sepolicy","clone_url":"https://git.codelinaro.org/clo/la/device/google/redfin-sepolicy.git","description":null}
{"name":"la/platform/hardware/qcom/msm8998","clone_url":"https://git.codelinaro.org/clo/la/platform/hardware/qcom/msm8998.git","description":null}
{"name":"qrdk/gyp","clone_url":"https://git.codelinaro.org/clo/qrdk/gyp.git","description":null}
{"name":"la/platform/external/pdfium","clone_url":"https://git.codelinaro.org/clo/la/platform/external/pdfium.git","description":null}
{"name":"yocto-mirrors/time","clone_url":"https://git.codelinaro.org/clo/yocto-mirrors/time.git","description":null}
{"name":"yocto-mirrors/ncurses","clone_url":"https://git.codelinaro.org/clo/yocto-mirrors/ncurses.git","description":null}
{"name":"la/tools/test/project-oss","clone_url":"https://git.codelinaro.org/clo/la/tools/test/project-oss.git","description":null}
{"name":"rdkb/xmidt-org/cimplog","clone_url":"https://git.codelinaro.org/clo/rdkb/xmidt-org/cimplog.git","description":null}
{"name":"le/external/nnsuite/meta-neural-network","clone_url":"https://git.codelinaro.org/clo/le/external/nnsuite/meta-neural-network.git","description":null}
{"name":"testproject/platform/hardware/st/nfc","clone_url":"https://git.codelinaro.org/clo/testproject/platform/hardware/st/nfc.git","description":null}
{"name":"qrdk/rdkcentral/rdk-wifi-hal","clone_url":"https://git.codelinaro.org/clo/qrdk/rdkcentral/rdk-wifi-hal.git","description":null}
{"name":"le/platform/vendor/qcom-opensource/cv2x-oss-other","clone_url":"https://git.codelinaro.org/clo/le/platform/vendor/qcom-opensource/cv2x-oss-other.git","description":null}
{"name":"testproject/device/google/vrservices","clone_url":"https://git.codelinaro.org/clo/testproject/device/google/vrservices.git","description":null}
{"name":"la/device/intel/edison","clone_url":"https://git.codelinaro.org/clo/la/device/intel/edison.git","description":null}
{"name":"le/gstreamer-1.14.4/gstreamer-vaapi","clone_url":"https://git.codelinaro.org/clo/le/gstreamer-1.14.4/gstreamer-vaapi.git","description":null}
{"name":"lc/external/github.com/rainycape/memcache","clone_url":"https://git.codelinaro.org/clo/lc/external/github.com/rainycape/memcache.git","description":null}
{"name":"la/platform/external/jimfs","clone_url":"https://git.codelinaro.org/clo/la/platform/external/jimfs.git","description":null}
{"name":"la/platform/external/xmlwriter","clone_url":"https://git.codelinaro.org/clo/la/platform/external/xmlwriter.git","description":null}
{"name":"la/platform/test/vti/fuzz_test_serving","clone_url":"https://git.codelinaro.org/clo/la/platform/test/vti/fuzz_test_serving.git","description":null}
{"name":"qsdk/connectedhomeip","clone_url":"https://git.codelinaro.org/clo/qsdk/connectedhomeip.git","description":null}
{"name":"femto5g/oss/releases/configs/qsdk","clone_url":"https://git.codelinaro.org/clo/femto5g/oss/releases/configs/qsdk.git","description":null}
{"name":"la/platform/external/remo_ti","clone_url":"https://git.codelinaro.org/clo/la/platform/external/remo_ti.git","description":null}
{"name":"la/platform/vendor/qcom/gen4_gvm_vcu","clone_url":"https://git.codelinaro.org/clo/la/platform/vendor/qcom/gen4_gvm_vcu.git","description":null}
{"name":"le/mesa/drm","clone_url":"https://git.codelinaro.org/clo/le/mesa/drm.git","description":null}
{"name":"la/device/moto/wingray","clone_url":"https://git.codelinaro.org/clo/la/device/moto/wingray.git","description":null}
{"name":"lf/releases/l10n/de/gecko","clone_url":"https://git.codelinaro.org/clo/lf/releases/l10n/de/gecko.git","description":null}
{"name":"la/platform/external/rust/crates/crossbeam-channel","clone_url":"https://git.codelinaro.org/clo/la/platform/external/rust/crates/crossbeam-channel.git","description":null}
{"name":"testproject/platform/packages/modules/DnsResolver","clone_url":"https://git.codelinaro.org/clo/testproject/platform/packages/modules/DnsResolver.git","description":null}
{"name":"la/platform/external/rust/crates/tikv-jemallocator","clone_url":"https://git.codelinaro.org/clo/la/platform/external/rust/crates/tikv-jemallocator.git","description":null}
{"name":"le/platform/vendor/qcom-opensource/safelinux-sec-modules","clone_url":"https://git.codelinaro.org/clo/le/platform/vendor/qcom-opensource/safelinux-sec-modules.git","description":null}
{"name":"la/platform/packages/apps/Car/RotaryImePrebuilt","clone_url":"https://git.codelinaro.org/clo/la/platform/packages/apps/Car/RotaryImePrebuilt.git","description":null}
{"name":"la/trusty/device/desktop","clone_url":"https://git.codelinaro.org/clo/la/trusty/device/desktop.git","description":null}
{"name":"la/platform/external/boost-submodules/bimap","clone_url":"https://git.codelinaro.org/clo/la/platform/external/boost-submodules/bimap.git","description":null}
{"name":"la/platform/hardware/qcom/msm8994","clone_url":"https://git.codelinaro.org/clo/la/platform/hardware/qcom/msm8994.git","description":null}
{"name":"la/platform/external/boost-submodules/icl","clone_url":"https://git.codelinaro.org/clo/la/platform/external/boost-submodules/icl.git","description":null}
{"name":"qsdk/oss/qca/src/qca-pkcs11","clone_url":"https://git.codelinaro.org/clo/qsdk/oss/qca/src/qca-pkcs11.git","description":null}
{"name":"la/platform/external/boost-submodules/mpl","clone_url":"https://git.codelinaro.org/clo/la/platform/external/boost-submodules/mpl.git","description":null}
{"name":"la/platform/external/alljoyn/alljoyn_core","clone_url":"https://git.codelinaro.org/clo/la/platform/external/alljoyn/alljoyn_core.git","description":null}
{"name":"le/AGL/DemoApps/CES2016","clone_url":"https://git.codelinaro.org/clo/le/AGL/DemoApps/CES2016.git","description":null}
{"name":"qsdk/URI.js","clone_url":"https://git.codelinaro.org/clo/qsdk/URI.js.git","description":null}
{"name":"le/meta-qti-ros","clone_url":"https://git.codelinaro.org/clo/le/meta-qti-ros.git","description":null}
{"name":"la/platform/external/rust/crates/pin-project","clone_url":"https://git.codelinaro.org/clo/la/platform/external/rust/crates/pin-project.git","description":null}
{"name":"le/unfs3/unfs3","clone_url":"https://git.codelinaro.org/clo/le/unfs3/unfs3.git","description":null}
{"name":"testproject/platform/system/libhwbinder","clone_url":"https://git.codelinaro.org/clo/testproject/platform/system/libhwbinder.git","description":null}
{"name":"yocto-mirrors/github/zaphoyd/websocketpp","clone_url":"https://git.codelinaro.org/clo/yocto-mirrors/github/zaphoyd/websocketpp.git","description":null}
{"name":"le-au-os/platform/vendor/qcom/opensource/datarmnet","clone_url":"https://git.codelinaro.org/clo/le-au-os/platform/vendor/qcom/opensource/datarmnet.git","description":null}
{"name":"la/platform/external/python/absl-py","clone_url":"https://git.codelinaro.org/clo/la/platform/external/python/absl-py.git","description":null}
{"name":"qcomlt/ci/oe/poky","clone_url":"https://git.codelinaro.org/clo/qcomlt/ci/oe/poky.git","description":null}
{"name":"le/external/github.com/DaveGamble/cJSON","clone_url":"https://git.codelinaro.org/clo/le/external/github.com/DaveGamble/cJSON.git","description":null}
{"name":"lc/external/github.com/russross/blackfriday","clone_url":"https://git.codelinaro.org/clo/lc/external/github.com/russross/blackfriday.git","description":null}
{"name":"la/platform/external/google-fonts/zilla-slab","clone_url":"https://git.codelinaro.org/clo/la/platform/external/google-fonts/zilla-slab.git","description":null}
{"name":"le/graphics/libgenlock","clone_url":"https://git.codelinaro.org/clo/le/graphics/libgenlock.git","description":null}
{"name":"le/platform/external/cartographer_ros","clone_url":"https://git.codelinaro.org/clo/le/platform/external/cartographer_ros.git","description":null}
{"name":"la/platform/packages/services/DroidfoodAttestationFixer","clone_url":"https://git.codelinaro.org/clo/la/platform/packages/services/DroidfoodAttestationFixer.git","description":null}
{"name":"la/platform/external/rust/crates/http","clone_url":"https://git.codelinaro.org/clo/la/platform/external/rust/crates/http.git","description":null}
{"name":"testproject/platform/external/nanopb-c","clone_url":"https://git.codelinaro.org/clo/testproject/platform/external/nanopb-c.git","description":null}
{"name":"la/platform/vendor/qcom/neo61","clone_url":"https://git.codelinaro.org/clo/la/platform/vendor/qcom/neo61.git","description":null}
{"name":"la/platform/hardware/google/gfxstream","clone_url":"https://git.codelinaro.org/clo/la/platform/hardware/google/gfxstream.git","description":null}
{"name":"la/platform/vendor/qcom-opensource/synx-devicetree","clone_url":"https://git.codelinaro.org/clo/la/platform/vendor/qcom-opensource/synx-devicetree.git","description":null}
{"name":"la/device/google/shusky-kernels/6.1","clone_url":"https://git.codelinaro.org/clo/la/device/google/shusky-kernels/6.1.git","description":null}
{"name":"la/device/google/bramble-kernel","clone_url":"https://git.codelinaro.org/clo/la/device/google/bramble-kernel.git","description":null}
{"name":"la/platform/prebuilts/android-emulator-build/common","clone_url":"https://git.codelinaro.org/clo/la/platform/prebuilts/android-emulator-build/common.git","description":null}
{"name":"yocto-mirrors/github/reference-lapack/lapack","clone_url":"https://git.codelinaro.org/clo/yocto-mirrors/github/reference-lapack/lapack.git","description":null}
{"name":"femto5g/kernel/msm-4.14","clone_url":"https://git.codelinaro.org/clo/femto5g/kernel/msm-4.14.git","description":null}
{"name":"la/platform/system/desktop/ap","clone_url":"https://git.codelinaro.org/clo/la/platform/system/desktop/ap.git","description":null}
{"name":"aimet/simple-ci","clone_url":"https://git.codelinaro.org/clo/aimet/simple-ci.git","description":null}
{"name":"la/platform/vendor/qcom/msm8916_32_512","clone_url":"https://git.codelinaro.org/clo/la/platform/vendor/qcom/msm8916_32_512.git","description":null}
{"name":"testproject/platform/external/libiio","clone_url":"https://git.codelinaro.org/clo/testproject/platform/external/libiio.git","description":null}
{"name":"lc/external/google-url","clone_url":"https://git.codelinaro.org/clo/lc/external/google-url.git","description":null}
{"name":"lc/chromium/src/ios","clone_url":"https://git.codelinaro.org/clo/lc/chromium/src/ios.git","description":null}
{"name":"la/platform/system/connectivity/apmanager","clone_url":"https://git.codelinaro.org/clo/la/platform/system/connectivity/apmanager.git","description":null}
{"name":"le-au-os/platform/external/wpa_supplicant_8","clone_url":"https://git.codelinaro.org/clo/le-au-os/platform/external/wpa_supplicant_8.git","description":null}
{"name":"la/platform/external/kotlinx.serialization","clone_url":"https://git.codelinaro.org/clo/la/platform/external/kotlinx.serialization.git","description":null}
{"name":"la/platform/external/libmnl","clone_url":"https://git.codelinaro.org/clo/la/platform/external/libmnl.git","description":null}
{"name":"la/platform/external/libvorbis","clone_url":"https://git.codelinaro.org/clo/la/platform/external/libvorbis.git","description":null}
{"name":"la/platform/external/rust/crates/uefi-raw","clone_url":"https://git.codelinaro.org/clo/la/platform/external/rust/crates/uefi-raw.git","description":null}
{"name":"la/platform/compatibility/cdd","clone_url":"https://git.codelinaro.org/clo/la/platform/compatibility/cdd.git","description":null}
{"name":"la/platform/external/rust/crates/foreign-types-shared","clone_url":"https://git.codelinaro.org/clo/la/platform/external/rust/crates/foreign-types-shared.git","description":null}
{"name":"la/platform/tools/doc_generation","clone_url":"https://git.codelinaro.org/clo/la/platform/tools/doc_generation.git","description":null}
{"name":"la/platform/external/ktlint","clone_url":"https://git.codelinaro.org/clo/la/platform/external/ktlint.git","description":null}
{"name":"la/platform/external/jetbrains/kotlin","clone_url":"https://git.codelinaro.org/clo/la/platform/external/jetbrains/kotlin.git","description":null}
{"name":"rdkb/rdkb/components/opensource/ccsp/MeshAgent","clone_url":"https://git.codelinaro.org/clo/rdkb/rdkb/components/opensource/ccsp/MeshAgent.git","description":null}
{"name":"testproject/platform/external/skqp","clone_url":"https://git.codelinaro.org/clo/testproject/platform/external/skqp.git","description":null}
{"name":"yocto-mirrors/github/pub/scm/linux/kernel/git/stable/linux","clone_url":"https://git.codelinaro.org/clo/yocto-mirrors/github/pub/scm/linux/kernel/git/stable/linux.git","description":null}
{"name":"la/platform/frameworks/volley","clone_url":"https://git.codelinaro.org/clo/la/platform/frameworks/volley.git","description":null}
{"name":"la/platform/system/desktop/adb-dbc-bridge","clone_url":"https://git.codelinaro.org/clo/la/platform/system/desktop/adb-dbc-bridge.git","description":null}
{"name":"qsdk/oss/system/feeds/routing","clone_url":"https://git.codelinaro.org/clo/qsdk/oss/system/feeds/routing.git","description":null}
{"name":"la/kernel/google-modules/soc/msm","clone_url":"https://git.codelinaro.org/clo/la/kernel/google-modules/soc/msm.git","description":null}
{"name":"la/platform/external/rust/crates/ident_case","clone_url":"https://git.codelinaro.org/clo/la/platform/external/rust/crates/ident_case.git","description":null}
{"name":"la/platform/prebuilts/gcc/darwin-x86/arm/arm-linux-androideabi-4.8","clone_url":"https://git.codelinaro.org/clo/la/platform/prebuilts/gcc/darwin-x86/arm/arm-linux-androideabi-4.8.git","description":null}
{"name":"testproject/platform/external/libchrome","clone_url":"https://git.codelinaro.org/clo/testproject/platform/external/libchrome.git","description":null}
{"name":"qsdk/oss/system/owrt-qti-ipq-ezmesh","clone_url":"https://git.codelinaro.org/clo/qsdk/oss/system/owrt-qti-ipq-ezmesh.git","description":null}
{"name":"lc/external/google-cache-invalidation-api/src_repo","clone_url":"https://git.codelinaro.org/clo/lc/external/google-cache-invalidation-api/src_repo.git","description":null}
{"name":"yocto-mirrors/image-spec","clone_url":"https://git.codelinaro.org/clo/yocto-mirrors/image-spec.git","description":null}
{"name":"le/platform/vendor/qcom-opensource/robot-color-convert","clone_url":"https://git.codelinaro.org/clo/le/platform/vendor/qcom-opensource/robot-color-convert.git","description":null}
{"name":"qyocto/oss/poky","clone_url":"https://git.codelinaro.org/clo/qyocto/oss/poky.git","description":null}
{"name":"rdkb/mobile-broadband/libqmi","clone_url":"https://git.codelinaro.org/clo/rdkb/mobile-broadband/libqmi.git","description":null}
{"name":"qrdk/rdkcentral/persistent-storage-manager","clone_url":"https://git.codelinaro.org/clo/qrdk/rdkcentral/persistent-storage-manager.git","description":null}
{"name":"la/platform/external/speex","clone_url":"https://git.codelinaro.org/clo/la/platform/external/speex.git","description":null}
{"name":"la/platform/vendor/qcom/monaco_group/codeaurora/tinyalsa","clone_url":"https://git.codelinaro.org/clo/la/platform/vendor/qcom/monaco_group/codeaurora/tinyalsa.git","description":null}
{"name":"la/platform/external/neon_2_sse","clone_url":"https://git.codelinaro.org/clo/la/platform/external/neon_2_sse.git","description":null}
{"name":"qsdk/tensorflow","clone_url":"https://git.codelinaro.org/clo/qsdk/tensorflow.git","description":null}
{"name":"qcomlt/lt-ci","clone_url":"https://git.codelinaro.org/clo/qcomlt/lt-ci.git","description":null}
{"name":"la/hardware/qcom/audio","clone_url":"https://git.codelinaro.org/clo/la/hardware/qcom/audio.git","description":null}
{"name":"la/platform/vendor/qcom/opensource/psi_daemon","clone_url":"https://git.codelinaro.org/clo/la/platform/vendor/qcom/opensource/psi_daemon.git","description":null}
{"name":"le/AGL/apps/settings","clone_url":"https://git.codelinaro.org/clo/le/AGL/apps/settings.git","description":null}
{"name":"la/platform/external/libdav1d","clone_url":"https://git.codelinaro.org/clo/la/platform/external/libdav1d.git","description":null}
{"name":"la/device/marvell/abox_edge","clone_url":"https://git.codelinaro.org/clo/la/device/marvell/abox_edge.git","description":null}
{"name":"la/platform/frameworks/opt/bitmap","clone_url":"https://git.codelinaro.org/clo/la/platform/frameworks/opt/bitmap.git","description":null}
{"name":"automotive/alsa-utils","clone_url":"https://git.codelinaro.org/clo/automotive/alsa-utils.git","description":null}
{"name":"la/platform/external/boost-submodules/tokenizer","clone_url":"https://git.codelinaro.org/clo/la/platform/external/boost-submodules/tokenizer.git","description":null}
{"name":"la/platform/prebuilts/swig/windows-x86","clone_url":"https://git.codelinaro.org/clo/la/platform/prebuilts/swig/windows-x86.git","description":null}
{"name":"le/NetworkManager/NetworkManager","clone_url":"https://git.codelinaro.org/clo/le/NetworkManager/NetworkManager.git","description":null}
{"name":"rdkb/akheron/jansson","clone_url":"https://git.codelinaro.org/clo/rdkb/akheron/jansson.git","description":null}
{"name":"la/platform/prebuilts/gcc/linux-x86/arm/arm-eabi-4.7","clone_url":"https://git.codelinaro.org/clo/la/platform/prebuilts/gcc/linux-x86/arm/arm-eabi-4.7.git","description":null}
{"name":"la/external/github.com/quic-qrb-ros/qrb_ros_samples/simulation_sample_pick_and_place","clone_url":"https://git.codelinaro.org/clo/la/external/github.com/quic-qrb-ros/qrb_ros_samples/simulation_sample_pick_and_place.git","description":null}
{"name":"la/platform/vendor/qcom/mpq8092","clone_url":"https://git.codelinaro.org/clo/la/platform/vendor/qcom/mpq8092.git","description":null}
{"name":"lc/chromiumos/platform/glbench/images","clone_url":"https://git.codelinaro.org/clo/lc/chromiumos/platform/glbench/images.git","description":null}
{"name":"la/toolchain/go","clone_url":"https://git.codelinaro.org/clo/la/toolchain/go.git","description":null}
{"name":"kernel-platform-2-0-os/kernel_platform/system/tools/mkbootimg","clone_url":"https://git.codelinaro.org/clo/kernel-platform-2-0-os/kernel_platform/system/tools/mkbootimg.git","description":null}
{"name":"la/platform/packages/apps/Music","clone_url":"https://git.codelinaro.org/clo/la/platform/packages/apps/Music.git","description":null}
{"name":"la/platform/external/boost-submodules/numeric_conversion","clone_url":"https://git.codelinaro.org/clo/la/platform/external/boost-submodules/numeric_conversion.git","description":null}
{"name":"testproject/platform/packages/screensavers/PhotoTable","clone_url":"https://git.codelinaro.org/clo/testproject/platform/packages/screensavers/PhotoTable.git","description":null}
{"name":"lc/external/github.com/domokit/cassowary","clone_url":"https://git.codelinaro.org/clo/lc/external/github.com/domokit/cassowary.git","description":null}
{"name":"la/platform/tools/lint_checks","clone_url":"https://git.codelinaro.org/clo/la/platform/tools/lint_checks.git","description":null}
{"name":"le/external/github.com/quic-qrb-ros/qrb_ros_samples","clone_url":"https://git.codelinaro.org/clo/le/external/github.com/quic-qrb-ros/qrb_ros_samples.git","description":null}
{"name":"le/qti-conf","clone_url":"https://git.codelinaro.org/clo/le/qti-conf.git","description":null}
{"name":"qsdk/oss/lklm/shortcut-fe","clone_url":"https://git.codelinaro.org/clo/qsdk/oss/lklm/shortcut-fe.git","description":null}
{"name":"le/owrt/feeds/feed_board_configuration","clone_url":"https://git.codelinaro.org/clo/le/owrt/feeds/feed_board_configuration.git","description":null}
{"name":"le/OTA/system/extras","clone_url":"https://git.codelinaro.org/clo/le/OTA/system/extras.git","description":null}
{"name":"femto5g/fsm/external/qoriq-components/linux_5.4-rt","clone_url":"https://git.codelinaro.org/clo/femto5g/fsm/external/qoriq-components/linux_5.4-rt.git","description":null}
{"name":"qrdk/protobuf","clone_url":"https://git.codelinaro.org/clo/qrdk/protobuf.git","description":null}
{"name":"la/platform/vendor/qcom-opensource/twowheeler/apps/Notification","clone_url":"https://git.codelinaro.org/clo/la/platform/vendor/qcom-opensource/twowheeler/apps/Notification.git","description":null}
{"name":"qsdk/oss/lklm/qca-mmap-telemetry","clone_url":"https://git.codelinaro.org/clo/qsdk/oss/lklm/qca-mmap-telemetry.git","description":null}
{"name":"la/platform/prebuilts/google-breakpad/windows-x86","clone_url":"https://git.codelinaro.org/clo/la/platform/prebuilts/google-breakpad/windows-x86.git","description":null}
{"name":"la/platform/external/autoconf","clone_url":"https://git.codelinaro.org/clo/la/platform/external/autoconf.git","description":null}
{"name":"le/ca-certificates","clone_url":"https://git.codelinaro.org/clo/le/ca-certificates.git","description":null}
{"name":"testproject/platform/packages/apps/Dialer","clone_url":"https://git.codelinaro.org/clo/testproject/platform/packages/apps/Dialer.git","description":null}
{"name":"la/platform/packages/modules/NetworkPermissionConfig","clone_url":"https://git.codelinaro.org/clo/la/platform/packages/modules/NetworkPermissionConfig.git","description":null}
{"name":"testproject/platform/external/sfntly","clone_url":"https://git.codelinaro.org/clo/testproject/platform/external/sfntly.git","description":null}
{"name":"qcomlt/pkg/pipewire","clone_url":"https://git.codelinaro.org/clo/qcomlt/pkg/pipewire.git","description":null}
{"name":"le/platform/vendor/qcom-opensource/data-kernel_group/drivers/alphawaveip","clone_url":"https://git.codelinaro.org/clo/le/platform/vendor/qcom-opensource/data-kernel_group/drivers/alphawaveip.git","description":null}
{"name":"yocto-mirrors/github/mariusmuja/flann","clone_url":"https://git.codelinaro.org/clo/yocto-mirrors/github/mariusmuja/flann.git","description":null}
{"name":"la/platform/prebuilts/gcc/linux-x86/arm/arm-linux-androideabi-4.7","clone_url":"https://git.codelinaro.org/clo/la/platform/prebuilts/gcc/linux-x86/arm/arm-linux-androideabi-4.7.git","description":null}
{"name":"testproject/platform/system/bpfprogs","clone_url":"https://git.codelinaro.org/clo/testproject/platform/system/bpfprogs.git","description":null}
{"name":"testproject/platform/tools/tradefederation","clone_url":"https://git.codelinaro.org/clo/testproject/platform/tools/tradefederation.git","description":null}
{"name":"la/platform/external/boost-submodules/fiber","clone_url":"https://git.codelinaro.org/clo/la/platform/external/boost-submodules/fiber.git","description":null}
{"name":"le/platform/vendor/qcom-opensource/bluetooth","clone_url":"https://git.codelinaro.org/clo/le/platform/vendor/qcom-opensource/bluetooth.git","description":null}
{"name":"la/platform/packages/apps/WallpaperPicker2","clone_url":"https://git.codelinaro.org/clo/la/platform/packages/apps/WallpaperPicker2.git","description":null}
{"name":"la/kernel/msm-modules_group/qcacld","clone_url":"https://git.codelinaro.org/clo/la/kernel/msm-modules_group/qcacld.git","description":null}
{"name":"yocto-mirrors/github/andersson/tqftpserv","clone_url":"https://git.codelinaro.org/clo/yocto-mirrors/github/andersson/tqftpserv.git","description":null}
{"name":"testproject/platform/prebuilts/gcc/linux-x86/host/x86_64-linux-glibc2.17-4.8","clone_url":"https://git.codelinaro.org/clo/testproject/platform/prebuilts/gcc/linux-x86/host/x86_64-linux-glibc2.17-4.8.git","description":null}
{"name":"le-au-os/oss/lklm/qca-ssdk","clone_url":"https://git.codelinaro.org/clo/le-au-os/oss/lklm/qca-ssdk.git","description":null}
{"name":"la/trusty/extras/simple-tipc","clone_url":"https://git.codelinaro.org/clo/la/trusty/extras/simple-tipc.git","description":null}
{"name":"le-au-os/platform/vendor/qcom-opensource/wlan/fw-api","clone_url":"https://git.codelinaro.org/clo/le-au-os/platform/vendor/qcom-opensource/wlan/fw-api.git","description":null}
{"name":"qyocto/oss/system/recipes/meta-lgi-ipq","clone_url":"https://git.codelinaro.org/clo/qyocto/oss/system/recipes/meta-lgi-ipq.git","description":null}
{"name":"yocto-mirrors/github/intelrealsense/realsense-ros","clone_url":"https://git.codelinaro.org/clo/yocto-mirrors/github/intelrealsense/realsense-ros.git","description":null}
{"name":"yocto-mirrors/glibc","clone_url":"https://git.codelinaro.org/clo/yocto-mirrors/glibc.git","description":null}
{"name":"lc/chromium/src/base/trace_event/common","clone_url":"https://git.codelinaro.org/clo/lc/chromium/src/base/trace_event/common.git","description":null}
{"name":"la/platform/external/rust/crates/bstr","clone_url":"https://git.codelinaro.org/clo/la/platform/external/rust/crates/bstr.git","description":null}
{"name":"la/platform/build/release","clone_url":"https://git.codelinaro.org/clo/la/platform/build/release.git","description":null}
{"name":"la/platform/vendor/asus/eee_701","clone_url":"https://git.codelinaro.org/clo/la/platform/vendor/asus/eee_701.git","description":null}
{"name":"la/platform/external/icu4c","clone_url":"https://git.codelinaro.org/clo/la/platform/external/icu4c.git","description":null}
{"name":"la/platform/external/crosvm","clone_url":"https://git.codelinaro.org/clo/la/platform/external/crosvm.git","description":null}
{"name":"lc/external/github.com/distrotech/autoconf","clone_url":"https://git.codelinaro.org/clo/lc/external/github.com/distrotech/autoconf.git","description":null}
{"name":"la/platform/external/caliper","clone_url":"https://git.codelinaro.org/clo/la/platform/external/caliper.git","description":null}
{"name":"la/platform/external/chromium_org/third_party/usrsctp/usrsctplib","clone_url":"https://git.codelinaro.org/clo/la/platform/external/chromium_org/third_party/usrsctp/usrsctplib.git","description":null}
{"name":"lf/ProtoBuf.js","clone_url":"https://git.codelinaro.org/clo/lf/ProtoBuf.js.git","description":null}
{"name":"le/golang/text","clone_url":"https://git.codelinaro.org/clo/le/golang/text.git","description":null}
{"name":"testproject/platform/external/google-fonts/big-shoulders-text","clone_url":"https://git.codelinaro.org/clo/testproject/platform/external/google-fonts/big-shoulders-text.git","description":null}
{"name":"la/platform/external/truth","clone_url":"https://git.codelinaro.org/clo/la/platform/external/truth.git","description":null}
{"name":"la/platform/vendor/qcom-opensource/multimodule-mgr-oss","clone_url":"https://git.codelinaro.org/clo/la/platform/vendor/qcom-opensource/multimodule-mgr-oss.git","description":null}
{"name":"lc/chromium/src/ppapi","clone_url":"https://git.codelinaro.org/clo/lc/chromium/src/ppapi.git","description":null}
{"name":"lc/lakitu-kernel","clone_url":"https://git.codelinaro.org/clo/lc/lakitu-kernel.git","description":null}
{"name":"la/platform/external/rust/crates/atomic-polyfill","clone_url":"https://git.codelinaro.org/clo/la/platform/external/rust/crates/atomic-polyfill.git","description":null}
{"name":"yocto-mirrors/github/stretchr/objx","clone_url":"https://git.codelinaro.org/clo/yocto-mirrors/github/stretchr/objx.git","description":null}
{"name":"le/platform/external/ros2/amr_cartographer","clone_url":"https://git.codelinaro.org/clo/le/platform/external/ros2/amr_cartographer.git","description":null}
{"name":"le-au-os/platform/external/armmbed/mbedtls","clone_url":"https://git.codelinaro.org/clo/le-au-os/platform/external/armmbed/mbedtls.git","description":null}
{"name":"external-ubicom/ubi32-toolchain","clone_url":"https://git.codelinaro.org/clo/external-ubicom/ubi32-toolchain.git","description":null}
{"name":"femto5g/oss/lklm/nss-crypto","clone_url":"https://git.codelinaro.org/clo/femto5g/oss/lklm/nss-crypto.git","description":null}
{"name":"yocto-mirrors/github/docker/buildx","clone_url":"https://git.codelinaro.org/clo/yocto-mirrors/github/docker/buildx.git","description":null}
{"name":"testproject/platform/prebuilts/checkcolor","clone_url":"https://git.codelinaro.org/clo/testproject/platform/prebuilts/checkcolor.git","description":null}
{"name":"la/platform/system/desktop/security","clone_url":"https://git.codelinaro.org/clo/la/platform/system/desktop/security.git","description":null}
{"name":"qsdk/oss/lklm/nss-ppe-uio","clone_url":"https://git.codelinaro.org/clo/qsdk/oss/lklm/nss-ppe-uio.git","description":null}
{"name":"rdkb/rdkb/components/opensource/ccsp/RdkXdslManager","clone_url":"https://git.codelinaro.org/clo/rdkb/rdkb/components/opensource/ccsp/RdkXdslManager.git","description":null}
{"name":"le/AGL/apps/hvac","clone_url":"https://git.codelinaro.org/clo/le/AGL/apps/hvac.git","description":null}
{"name":"qcomlt/ci/staging/linux-build-pipeline","clone_url":"https://git.codelinaro.org/clo/qcomlt/ci/staging/linux-build-pipeline.git","description":null}
{"name":"la/platform/external/python/google-auth","clone_url":"https://git.codelinaro.org/clo/la/platform/external/python/google-auth.git","description":null}
{"name":"lc/external/github.com/contain-rs/vec-map","clone_url":"https://git.codelinaro.org/clo/lc/external/github.com/contain-rs/vec-map.git","description":null}
{"name":"yocto-mirrors/debianutils","clone_url":"https://git.codelinaro.org/clo/yocto-mirrors/debianutils.git","description":null}
{"name":"la/platform/build/bazel","clone_url":"https://git.codelinaro.org/clo/la/platform/build/bazel.git","description":null}
{"name":"la/kernel_platform/test/dittosuite","clone_url":"https://git.codelinaro.org/clo/la/kernel_platform/test/dittosuite.git","description":null}
{"name":"la/platform/external/linux-tools-perf","clone_url":"https://git.codelinaro.org/clo/la/platform/external/linux-tools-perf.git","description":null}
{"name":"la/platform/packages/apps/TvSystemUI","clone_url":"https://git.codelinaro.org/clo/la/platform/packages/apps/TvSystemUI.git","description":null}
{"name":"la/platform/prebuilts/gcc/darwin-x86/mips/mipsel-linux-android-4.7","clone_url":"https://git.codelinaro.org/clo/la/platform/prebuilts/gcc/darwin-x86/mips/mipsel-linux-android-4.7.git","description":null}
{"name":"lc/external/sigrok.org/pulseview","clone_url":"https://git.codelinaro.org/clo/lc/external/sigrok.org/pulseview.git","description":null}
{"name":"la/platform/system/tpm","clone_url":"https://git.codelinaro.org/clo/la/platform/system/tpm.git","description":null}
{"name":"la/platform/vendor/qcom/wlan","clone_url":"https://git.codelinaro.org/clo/la/platform/vendor/qcom/wlan.git","description":null}
{"name":"le/ros2-gbp/ros2cli-release","clone_url":"https://git.codelinaro.org/clo/le/ros2-gbp/ros2cli-release.git","description":null}
{"name":"yocto-mirrors/github/ros2-gbp/geometry2-release","clone_url":"https://git.codelinaro.org/clo/yocto-mirrors/github/ros2-gbp/geometry2-release.git","description":null}
{"name":"qrdk/code.rdkcentral.com/rdk/components/generic/rdm","clone_url":"https://git.codelinaro.org/clo/qrdk/code.rdkcentral.com/rdk/components/generic/rdm.git","description":null}
{"name":"yocto-mirrors/github/santhosh-tekuri/jsonschema","clone_url":"https://git.codelinaro.org/clo/yocto-mirrors/github/santhosh-tekuri/jsonschema.git","description":null}
{"name":"la/platform/hardware/google/easel","clone_url":"https://git.codelinaro.org/clo/la/platform/hardware/google/easel.git","description":null}
{"name":"le/virtio/qcvirtio-coqoshv-guest-driver-linux","clone_url":"https://git.codelinaro.org/clo/le/virtio/qcvirtio-coqoshv-guest-driver-linux.git","description":null}
{"name":"la/platform/external/python/httplib2","clone_url":"https://git.codelinaro.org/clo/la/platform/external/python/httplib2.git","description":null}
{"name":"la/platform/external/libwebsockets","clone_url":"https://git.codelinaro.org/clo/la/platform/external/libwebsockets.git","description":null}
{"name":"la/platform/packages/providers/ApplicationsProvider","clone_url":"https://git.codelinaro.org/clo/la/platform/packages/providers/ApplicationsProvider.git","description":null}
