{"name":"le/gitpan/SGMLSpm","clone_url":"https://git.codelinaro.org/clo/le/gitpan/SGMLSpm.git","description":null}
{"name":"le/platform/vendor/qcom-opensource/robot-base","clone_url":"https://git.codelinaro.org/clo/le/platform/vendor/qcom-opensource/robot-base.git","description":null}
{"name":"la/platform/external/tpm_manager","clone_url":"https://git.codelinaro.org/clo/la/platform/external/tpm_manager.git","description":null}
{"name":"toolchain-for-hexagon/hexagon-builder","clone_url":"https://git.codelinaro.org/clo/toolchain-for-hexagon/hexagon-builder.git","description":null}
{"name":"qsdk/netifd","clone_url":"https://git.codelinaro.org/clo/qsdk/netifd.git","description":null}
{"name":"le/platform/external/bluetooth/bluez","clone_url":"https://git.codelinaro.org/clo/le/platform/external/bluetooth/bluez.git","description":null}
{"name":"la/platform/external/rust/crates/num-integer","clone_url":"https://git.codelinaro.org/clo/la/platform/external/rust/crates/num-integer.git","description":null}
{"name":"la/platform/prebuilts/cmake/linux-arm64","clone_url":"https://git.codelinaro.org/clo/la/platform/prebuilts/cmake/linux-arm64.git","description":null}
{"name":"le/platform/external/crosvm","clone_url":"https://git.codelinaro.org/clo/le/platform/external/crosvm.git","description":null}
{"name":"la/kernel/prebuilts/common-modules/virtual-device/5.4/x86-64","clone_url":"https://git.codelinaro.org/clo/la/kernel/prebuilts/common-modules/virtual-device/5.4/x86-64.git","description":null}
{"name":"testproject/platform/external/python/pybind11","clone_url":"https://git.codelinaro.org/clo/testproject/platform/external/python/pybind11.git","description":null}
{"name":"la/platform/vendor/st/opensource/eSE-driver","clone_url":"https://git.codelinaro.org/clo/la/platform/vendor/st/opensource/eSE-driver.git","description":null}
{"name":"le-au-os/platform/vendor/qcom-opensource/wlan/qcacld-3.0","clone_url":"https://git.codelinaro.org/clo/le-au-os/platform/vendor/qcom-opensource/wlan/qcacld-3.0.git","description":null}
{"name":"la/platform/hardware/knowles/athletico/sound_trigger_hal","clone_url":"https://git.codelinaro.org/clo/la/platform/hardware/knowles/athletico/sound_trigger_hal.git","description":null}
{"name":"femto5g/oss/lklm/shortcut-fe","clone_url":"https://git.codelinaro.org/clo/femto5g/oss/lklm/shortcut-fe.git","description":null}
{"name":"la/platform/packages/modules/Connectivity","clone_url":"https://git.codelinaro.org/clo/la/platform/packages/modules/Connectivity.git","description":null}
{"name":"le/robosdk/oss/robot-control","clone_url":"https://git.codelinaro.org/clo/le/robosdk/oss/robot-control.git","description":null}
{"name":"la/platform/vendor/qcom/opensource/graphics-kernel","clone_url":"https://git.codelinaro.org/clo/la/platform/vendor/qcom/opensource/graphics-kernel.git","description":null}
{"name":"la/toolchain/jdk/jdk9_corba","clone_url":"https://git.codelinaro.org/clo/la/toolchain/jdk/jdk9_corba.git","description":null}
{"name":"la/platform/external/mbedtls","clone_url":"https://git.codelinaro.org/clo/la/platform/external/mbedtls.git","description":null}
{"name":"la/platform/prebuilts/r8","clone_url":"https://git.codelinaro.org/clo/la/platform/prebuilts/r8.git","description":null}
{"name":"la/platform/external/bazelbuild-rules_java","clone_url":"https://git.codelinaro.org/clo/la/platform/external/bazelbuild-rules_java.git","description":null}
{"name":"le/gorilla/websocket","clone_url":"https://git.codelinaro.org/clo/le/gorilla/websocket.git","description":null}
{"name":"le/platform/vendor/qcom-opensource/shortcut-fe","clone_url":"https://git.codelinaro.org/clo/le/platform/vendor/qcom-opensource/shortcut-fe.git","description":null}
{"name":"le/platform/vendor/opensource/video-driver","clone_url":"https://git.codelinaro.org/clo/le/platform/vendor/opensource/video-driver.git","description":null}
{"name":"le/platform/external/libuv","clone_url":"https://git.codelinaro.org/clo/le/platform/external/libuv.git","description":null}
{"name":"la/platform/external/apache-commons-math","clone_url":"https://git.codelinaro.org/clo/la/platform/external/apache-commons-math.git","description":null}
{"name":"lc/external/gsutil/src","clone_url":"https://git.codelinaro.org/clo/lc/external/gsutil/src.git","description":null}
{"name":"la/platform/vendor/qcom-proprietary/iot-retail","clone_url":"https://git.codelinaro.org/clo/la/platform/vendor/qcom-proprietary/iot-retail.git","description":null}
{"name":"la/platform/external/google-diff-match-patch","clone_url":"https://git.codelinaro.org/clo/la/platform/external/google-diff-match-patch.git","description":null}
{"name":"qsdk/oss/system/openwrt/feeds/qca-wifi","clone_url":"https://git.codelinaro.org/clo/qsdk/oss/system/openwrt/feeds/qca-wifi.git","description":null}
{"name":"kernel-platform-2-0-os/abl/tianocore/edk2","clone_url":"https://git.codelinaro.org/clo/kernel-platform-2-0-os/abl/tianocore/edk2.git","description":null}
{"name":"le/platform/external/adhd","clone_url":"https://git.codelinaro.org/clo/le/platform/external/adhd.git","description":null}
{"name":"qsdk/boot/u-boot","clone_url":"https://git.codelinaro.org/clo/qsdk/boot/u-boot.git","description":null}
{"name":"yocto-mirrors/platform","clone_url":"https://git.codelinaro.org/clo/yocto-mirrors/platform.git","description":null}
{"name":"la/platform/external/rust/crates/tower-service","clone_url":"https://git.codelinaro.org/clo/la/platform/external/rust/crates/tower-service.git","description":null}
{"name":"la/platform/vendor/qcom/msm8916_64_LMT","clone_url":"https://git.codelinaro.org/clo/la/platform/vendor/qcom/msm8916_64_LMT.git","description":null}
{"name":"la/platform/external/python/cpython2","clone_url":"https://git.codelinaro.org/clo/la/platform/external/python/cpython2.git","description":null}
{"name":"la/platform/vendor/qcom/monaco_group/codeaurora/time-services","clone_url":"https://git.codelinaro.org/clo/la/platform/vendor/qcom/monaco_group/codeaurora/time-services.git","description":null}
{"name":"la/platform/frameworks/opt/data","clone_url":"https://git.codelinaro.org/clo/la/platform/frameworks/opt/data.git","description":null}
{"name":"le/platform/vendor/qcom-opensource/wlan/qca-hyfi-bridge","clone_url":"https://git.codelinaro.org/clo/le/platform/vendor/qcom-opensource/wlan/qca-hyfi-bridge.git","description":null}
{"name":"lc/external/github.com/cld2owners/cld2","clone_url":"https://git.codelinaro.org/clo/lc/external/github.com/cld2owners/cld2.git","description":null}
{"name":"yocto-mirrors/github/moby/term","clone_url":"https://git.codelinaro.org/clo/yocto-mirrors/github/moby/term.git","description":null}
{"name":"la/platform/frameworks/opt/mms","clone_url":"https://git.codelinaro.org/clo/la/platform/frameworks/opt/mms.git","description":null}
{"name":"la/platform/vendor/qcom/opensource/audioreach/audioreach-pipewire-plugin","clone_url":"https://git.codelinaro.org/clo/la/platform/vendor/qcom/opensource/audioreach/audioreach-pipewire-plugin.git","description":null}
{"name":"la/platform/hardware/bsp/kernel/intel/broxton-v4.4","clone_url":"https://git.codelinaro.org/clo/la/platform/hardware/bsp/kernel/intel/broxton-v4.4.git","description":null}
{"name":"la/platform/external/srec","clone_url":"https://git.codelinaro.org/clo/la/platform/external/srec.git","description":null}
{"name":"qsdk/oss/src/mac80211/wlan-open","clone_url":"https://git.codelinaro.org/clo/qsdk/oss/src/mac80211/wlan-open.git","description":null}
{"name":"la/platform/external/python/pytest","clone_url":"https://git.codelinaro.org/clo/la/platform/external/python/pytest.git","description":null}
{"name":"le/qccsdk/oss/mbedtls","clone_url":"https://git.codelinaro.org/clo/le/qccsdk/oss/mbedtls.git","description":null}
{"name":"le/platform/external/wpa_supplicant_8","clone_url":"https://git.codelinaro.org/clo/le/platform/external/wpa_supplicant_8.git","description":null}
{"name":"la/platform/vendor/qcom/gen4_gvm_cdccomm","clone_url":"https://git.codelinaro.org/clo/la/platform/vendor/qcom/gen4_gvm_cdccomm.git","description":null}
{"name":"la/platform/external/starlark-go","clone_url":"https://git.codelinaro.org/clo/la/platform/external/starlark-go.git","description":null}
{"name":"la/platform/vendor/qcom-opensource/wlan/fw-api-win","clone_url":"https://git.codelinaro.org/clo/la/platform/vendor/qcom-opensource/wlan/fw-api-win.git","description":null}
{"name":"la/device/google/gs-common","clone_url":"https://git.codelinaro.org/clo/la/device/google/gs-common.git","description":null}
{"name":"yocto-mirrors/github/ros2-gbp/ament_lint-release","clone_url":"https://git.codelinaro.org/clo/yocto-mirrors/github/ros2-gbp/ament_lint-release.git","description":null}
{"name":"lc/native_client/pnacl-llvm","clone_url":"https://git.codelinaro.org/clo/lc/native_client/pnacl-llvm.git","description":null}
{"name":"testproject/platform/prebuilts/go/linux-x86","clone_url":"https://git.codelinaro.org/clo/testproject/platform/prebuilts/go/linux-x86.git","description":null}
{"name":"femto5g/platform/vendor/qcom-opensource/hsi2s-kernel","clone_url":"https://git.codelinaro.org/clo/femto5g/platform/vendor/qcom-opensource/hsi2s-kernel.git","description":null}
{"name":"femto5g/oss/lklm/qca-ovsmgr","clone_url":"https://git.codelinaro.org/clo/femto5g/oss/lklm/qca-ovsmgr.git","description":null}
{"name":"testproject/platform/external/doclava","clone_url":"https://git.codelinaro.org/clo/testproject/platform/external/doclava.git","description":null}
{"name":"la/platform/packages/apps/SpeechRecorder","clone_url":"https://git.codelinaro.org/clo/la/platform/packages/apps/SpeechRecorder.git","description":null}
{"name":"la/Platform-Chromium-Projects","clone_url":"https://git.codelinaro.org/clo/la/Platform-Chromium-Projects.git","description":null}
{"name":"la/platform/external/flashbench","clone_url":"https://git.codelinaro.org/clo/la/platform/external/flashbench.git","description":null}
{"name":"sba-patches/wlan_patches","clone_url":"https://git.codelinaro.org/clo/sba-patches/wlan_patches.git","description":null}
{"name":"testproject/platform/external/flac","clone_url":"https://git.codelinaro.org/clo/testproject/platform/external/flac.git","description":null}
{"name":"la/platform/prebuilts/androidx/exoplayer","clone_url":"https://git.codelinaro.org/clo/la/platform/prebuilts/androidx/exoplayer.git","description":null}
{"name":"yocto-mirrors/github/alecthomas/gometalinter","clone_url":"https://git.codelinaro.org/clo/yocto-mirrors/github/alecthomas/gometalinter.git","description":null}
{"name":"qsdk/oss/kernel/linux-ipq-6.1","clone_url":"https://git.codelinaro.org/clo/qsdk/oss/kernel/linux-ipq-6.1.git","description":null}
{"name":"testproject/platform/test/vts-testcase/vndk","clone_url":"https://git.codelinaro.org/clo/testproject/platform/test/vts-testcase/vndk.git","description":null}
{"name":"caf-patches/patches","clone_url":"https://git.codelinaro.org/clo/caf-patches/patches.git","description":null}
{"name":"la/platform/system/libcppbor","clone_url":"https://git.codelinaro.org/clo/la/platform/system/libcppbor.git","description":null}
{"name":"la/platform/external/wayland/wayland-ivi-extension","clone_url":"https://git.codelinaro.org/clo/la/platform/external/wayland/wayland-ivi-extension.git","description":null}
{"name":"rdkb/rdk/components/generic/syslog_helper","clone_url":"https://git.codelinaro.org/clo/rdkb/rdk/components/generic/syslog_helper.git","description":null}
{"name":"la/platform/external/utf8proc","clone_url":"https://git.codelinaro.org/clo/la/platform/external/utf8proc.git","description":null}
{"name":"qcomlt/libadsprpc","clone_url":"https://git.codelinaro.org/clo/qcomlt/libadsprpc.git","description":null}
{"name":"qsdk/rstp","clone_url":"https://git.codelinaro.org/clo/qsdk/rstp.git","description":null}
{"name":"qrdk/rpm","clone_url":"https://git.codelinaro.org/clo/qrdk/rpm.git","description":null}
{"name":"le/external/qtquickcontrols2","clone_url":"https://git.codelinaro.org/clo/le/external/qtquickcontrols2.git","description":null}
{"name":"la/toolchain/jdk/jdk9_nashorn","clone_url":"https://git.codelinaro.org/clo/la/toolchain/jdk/jdk9_nashorn.git","description":null}
{"name":"le/platform/vendor/qcom-opensource/synergy","clone_url":"https://git.codelinaro.org/clo/le/platform/vendor/qcom-opensource/synergy.git","description":null}
{"name":"la/platform/external/oprofile","clone_url":"https://git.codelinaro.org/clo/la/platform/external/oprofile.git","description":null}
{"name":"la/platform/external/libjxl","clone_url":"https://git.codelinaro.org/clo/la/platform/external/libjxl.git","description":null}
{"name":"la/platform/tools/studio/google/play","clone_url":"https://git.codelinaro.org/clo/la/platform/tools/studio/google/play.git","description":null}
{"name":"la/platform/prebuilts/jdk/jdk17","clone_url":"https://git.codelinaro.org/clo/la/platform/prebuilts/jdk/jdk17.git","description":null}
{"name":"yocto-mirrors/github/konsorten/go-windows-terminal-sequences","clone_url":"https://git.codelinaro.org/clo/yocto-mirrors/github/konsorten/go-windows-terminal-sequences.git","description":null}
{"name":"qsdk/platform/vendor/qcom/opensource/agm","clone_url":"https://git.codelinaro.org/clo/qsdk/platform/vendor/qcom/opensource/agm.git","description":null}
{"name":"la/platform/prebuilts/google-breakpad/windows-x86","clone_url":"https://git.codelinaro.org/clo/la/platform/prebuilts/google-breakpad/windows-x86.git","description":null}
{"name":"yocto-mirrors/github/ros2-gbp/xacro-release","clone_url":"https://git.codelinaro.org/clo/yocto-mirrors/github/ros2-gbp/xacro-release.git","description":null}
{"name":"la/platform/packages/modules/UprobeStats","clone_url":"https://git.codelinaro.org/clo/la/platform/packages/modules/UprobeStats.git","description":null}
{"name":"lc/chromiumos/platform/spigots","clone_url":"https://git.codelinaro.org/clo/lc/chromiumos/platform/spigots.git","description":null}
{"name":"la/platform/prebuilts/gcc/linux-x86/arm/arm-eabi-4.6","clone_url":"https://git.codelinaro.org/clo/la/platform/prebuilts/gcc/linux-x86/arm/arm-eabi-4.6.git","description":null}
{"name":"le/openwrt/openwrt-patches","clone_url":"https://git.codelinaro.org/clo/le/openwrt/openwrt-patches.git","description":null}
{"name":"testproject/platform/external/fmtlib","clone_url":"https://git.codelinaro.org/clo/testproject/platform/external/fmtlib.git","description":null}
{"name":"qrdk/heaptrack","clone_url":"https://git.codelinaro.org/clo/qrdk/heaptrack.git","description":null}
{"name":"testproject/platform/external/glide","clone_url":"https://git.codelinaro.org/clo/testproject/platform/external/glide.git","description":null}
{"name":"la/platform/hardware/qcom/audio","clone_url":"https://git.codelinaro.org/clo/la/platform/hardware/qcom/audio.git","description":null}
{"name":"lc/external/github.com/dart-lang/utf","clone_url":"https://git.codelinaro.org/clo/lc/external/github.com/dart-lang/utf.git","description":null}
{"name":"la/platform/external/cros_kernel","clone_url":"https://git.codelinaro.org/clo/la/platform/external/cros_kernel.git","description":null}
{"name":"la/platform/vendor/qcom/gen4_gvm_vcu","clone_url":"https://git.codelinaro.org/clo/la/platform/vendor/qcom/gen4_gvm_vcu.git","description":null}
{"name":"lf/releases/l10n/zh-tw/gaia","clone_url":"https://git.codelinaro.org/clo/lf/releases/l10n/zh-tw/gaia.git","description":null}
{"name":"qsdk/oss/boot/bootdrv","clone_url":"https://git.codelinaro.org/clo/qsdk/oss/boot/bootdrv.git","description":null}
{"name":"femto5g/oss/kernel/linux-ipq-files","clone_url":"https://git.codelinaro.org/clo/femto5g/oss/kernel/linux-ipq-files.git","description":null}
{"name":"rdkb/rdkb/components/opensource/ccsp/RdkTelcoVoiceManager","clone_url":"https://git.codelinaro.org/clo/rdkb/rdkb/components/opensource/ccsp/RdkTelcoVoiceManager.git","description":null}
{"name":"yocto-mirrors/ptest-runner2","clone_url":"https://git.codelinaro.org/clo/yocto-mirrors/ptest-runner2.git","description":null}
{"name":"lc/chromiumos/platform/init","clone_url":"https://git.codelinaro.org/clo/lc/chromiumos/platform/init.git","description":null}
{"name":"le/vendor/qcom/opensource/eavb","clone_url":"https://git.codelinaro.org/clo/le/vendor/qcom/opensource/eavb.git","description":null}
{"name":"lc/chromium/src/tools/generate_library_loader","clone_url":"https://git.codelinaro.org/clo/lc/chromium/src/tools/generate_library_loader.git","description":null}
{"name":"la/platform/external/chromium_org/third_party/boringssl/src","clone_url":"https://git.codelinaro.org/clo/la/platform/external/chromium_org/third_party/boringssl/src.git","description":null}
{"name":"testproject/platform/external/jsoncpp","clone_url":"https://git.codelinaro.org/clo/testproject/platform/external/jsoncpp.git","description":null}
{"name":"la/platform/prebuilts/fullsdk-darwin/build-tools_group/31.0.0","clone_url":"https://git.codelinaro.org/clo/la/platform/prebuilts/fullsdk-darwin/build-tools_group/31.0.0.git","description":null}
{"name":"la/platform/cts","clone_url":"https://git.codelinaro.org/clo/la/platform/cts.git","description":null}
{"name":"le/coqoshv/coqoshv-abi","clone_url":"https://git.codelinaro.org/clo/le/coqoshv/coqoshv-abi.git","description":null}
{"name":"la/external/github.com/quic-qrb-ros/qrb_ros_samples/sample_depth_estimation","clone_url":"https://git.codelinaro.org/clo/la/external/github.com/quic-qrb-ros/qrb_ros_samples/sample_depth_estimation.git","description":null}
{"name":"lf/releases/l10n/ro/gaia","clone_url":"https://git.codelinaro.org/clo/lf/releases/l10n/ro/gaia.git","description":null}
{"name":"yocto-mirrors/github/intelrealsense/librealsense","clone_url":"https://git.codelinaro.org/clo/yocto-mirrors/github/intelrealsense/librealsense.git","description":null}
{"name":"yocto-mirrors/bridge-utils","clone_url":"https://git.codelinaro.org/clo/yocto-mirrors/bridge-utils.git","description":null}
{"name":"le/platform/system/bt","clone_url":"https://git.codelinaro.org/clo/le/platform/system/bt.git","description":null}
{"name":"la/platform/prebuilts/fullsdk/platforms/android-system-29","clone_url":"https://git.codelinaro.org/clo/la/platform/prebuilts/fullsdk/platforms/android-system-29.git","description":null}
{"name":"la/platform/packages/apps/Car/RadioPrebuilt","clone_url":"https://git.codelinaro.org/clo/la/platform/packages/apps/Car/RadioPrebuilt.git","description":null}
{"name":"la/platform/external/rust/crates/psci","clone_url":"https://git.codelinaro.org/clo/la/platform/external/rust/crates/psci.git","description":null}
{"name":"la/platform/prebuilts/libprotobuf/linux-x86","clone_url":"https://git.codelinaro.org/clo/la/platform/prebuilts/libprotobuf/linux-x86.git","description":null}
{"name":"la/platform/system/libbase","clone_url":"https://git.codelinaro.org/clo/la/platform/system/libbase.git","description":null}
{"name":"la/platform/external/rust/crates/shared_child","clone_url":"https://git.codelinaro.org/clo/la/platform/external/rust/crates/shared_child.git","description":null}
{"name":"testproject/platform/packages/apps/car/libs","clone_url":"https://git.codelinaro.org/clo/testproject/platform/packages/apps/car/libs.git","description":null}
{"name":"yocto-mirrors/kubernetes","clone_url":"https://git.codelinaro.org/clo/yocto-mirrors/kubernetes.git","description":null}
{"name":"la/kernel/google-modules/amplifiers","clone_url":"https://git.codelinaro.org/clo/la/kernel/google-modules/amplifiers.git","description":null}
{"name":"yocto-mirrors/libslirp","clone_url":"https://git.codelinaro.org/clo/yocto-mirrors/libslirp.git","description":null}
{"name":"yocto-mirrors/github/hashicorp/hcl","clone_url":"https://git.codelinaro.org/clo/yocto-mirrors/github/hashicorp/hcl.git","description":null}
{"name":"la/platform/external/junit","clone_url":"https://git.codelinaro.org/clo/la/platform/external/junit.git","description":null}
{"name":"lc/cros/qc/overlays/overlay-variant-qc-8084","clone_url":"https://git.codelinaro.org/clo/lc/cros/qc/overlays/overlay-variant-qc-8084.git","description":null}
{"name":"le/platform/vendor/qcom-opensource/data-ipa-cfg-mgr","clone_url":"https://git.codelinaro.org/clo/le/platform/vendor/qcom-opensource/data-ipa-cfg-mgr.git","description":null}
{"name":"lc/external/github.com/dpranke/typ","clone_url":"https://git.codelinaro.org/clo/lc/external/github.com/dpranke/typ.git","description":null}
{"name":"qsdk/oss/trex/tools/util-ubus","clone_url":"https://git.codelinaro.org/clo/qsdk/oss/trex/tools/util-ubus.git","description":null}
{"name":"lc/chromiumos/platform/dump-syms","clone_url":"https://git.codelinaro.org/clo/lc/chromiumos/platform/dump-syms.git","description":null}
{"name":"la/platform/vendor/qcom-opensource/synx-devicetree","clone_url":"https://git.codelinaro.org/clo/la/platform/vendor/qcom-opensource/synx-devicetree.git","description":null}
{"name":"la/platform/external/python/absl-py","clone_url":"https://git.codelinaro.org/clo/la/platform/external/python/absl-py.git","description":null}
{"name":"femto5g/kernel/build","clone_url":"https://git.codelinaro.org/clo/femto5g/kernel/build.git","description":null}
{"name":"la/kernel_platform/prebuilts/bazel/linux-x86_64","clone_url":"https://git.codelinaro.org/clo/la/kernel_platform/prebuilts/bazel/linux-x86_64.git","description":null}
{"name":"rdkb/rdkb/components/opensource/ccsp/CcspWifiAgent","clone_url":"https://git.codelinaro.org/clo/rdkb/rdkb/components/opensource/ccsp/CcspWifiAgent.git","description":null}
{"name":"testproject/platform/frameworks/opt/net/ethernet","clone_url":"https://git.codelinaro.org/clo/testproject/platform/frameworks/opt/net/ethernet.git","description":null}
{"name":"kernel-platform-2-0-os/kernel_platform/external/stardoc","clone_url":"https://git.codelinaro.org/clo/kernel-platform-2-0-os/kernel_platform/external/stardoc.git","description":null}
{"name":"la/device/google/raviole","clone_url":"https://git.codelinaro.org/clo/la/device/google/raviole.git","description":null}
{"name":"la/platform/external/rust/crates/pkcs1","clone_url":"https://git.codelinaro.org/clo/la/platform/external/rust/crates/pkcs1.git","description":null}
{"name":"le/platform/vendor/qcom-opensource/bluetooth_ext","clone_url":"https://git.codelinaro.org/clo/le/platform/vendor/qcom-opensource/bluetooth_ext.git","description":null}
{"name":"la/platform/external/rust/crates/iana-time-zone","clone_url":"https://git.codelinaro.org/clo/la/platform/external/rust/crates/iana-time-zone.git","description":null}
{"name":"testproject/platform/prebuilts/manifest-merger","clone_url":"https://git.codelinaro.org/clo/testproject/platform/prebuilts/manifest-merger.git","description":null}
{"name":"le/meta-qti-mplane","clone_url":"https://git.codelinaro.org/clo/le/meta-qti-mplane.git","description":null}
{"name":"la/ernel/devices/google/eos","clone_url":"https://git.codelinaro.org/clo/la/ernel/devices/google/eos.git","description":null}
{"name":"la/platform/external/golang-glog","clone_url":"https://git.codelinaro.org/clo/la/platform/external/golang-glog.git","description":null}
{"name":"la/platform/test/vts-testcase/vndk","clone_url":"https://git.codelinaro.org/clo/la/platform/test/vts-testcase/vndk.git","description":null}
{"name":"qsdk/oss/lklm/shortcut-fe","clone_url":"https://git.codelinaro.org/clo/qsdk/oss/lklm/shortcut-fe.git","description":null}
{"name":"la/platform/prebuilts/android-emulator-build/mesa-deps","clone_url":"https://git.codelinaro.org/clo/la/platform/prebuilts/android-emulator-build/mesa-deps.git","description":null}
{"name":"yocto-mirrors/github/bmizerany/assert","clone_url":"https://git.codelinaro.org/clo/yocto-mirrors/github/bmizerany/assert.git","description":null}
{"name":"le/qc/components/le-codec2-frameworks-lnx/oe-recipes-oss","clone_url":"https://git.codelinaro.org/clo/le/qc/components/le-codec2-frameworks-lnx/oe-recipes-oss.git","description":null}
{"name":"la/platform/frameworks/opt/pc/windowmanager","clone_url":"https://git.codelinaro.org/clo/la/platform/frameworks/opt/pc/windowmanager.git","description":null}
{"name":"la/platform/vendor/st/opensource/packages/apps/Nfc","clone_url":"https://git.codelinaro.org/clo/la/platform/vendor/st/opensource/packages/apps/Nfc.git","description":null}
{"name":"yocto-mirrors/github/x448/float16","clone_url":"https://git.codelinaro.org/clo/yocto-mirrors/github/x448/float16.git","description":null}
{"name":"lc/external/elfutils","clone_url":"https://git.codelinaro.org/clo/lc/external/elfutils.git","description":null}
{"name":"testproject/platform/external/wycheproof","clone_url":"https://git.codelinaro.org/clo/testproject/platform/external/wycheproof.git","description":null}
{"name":"qrdk/localedef","clone_url":"https://git.codelinaro.org/clo/qrdk/localedef.git","description":null}
{"name":"le/platform/vendor/qcom/opensource/platform-kernel","clone_url":"https://git.codelinaro.org/clo/le/platform/vendor/qcom/opensource/platform-kernel.git","description":null}
{"name":"lc/external/github.com/flutter/packages","clone_url":"https://git.codelinaro.org/clo/lc/external/github.com/flutter/packages.git","description":null}
{"name":"la/platform/external/sil-fonts","clone_url":"https://git.codelinaro.org/clo/la/platform/external/sil-fonts.git","description":null}
{"name":"la/platform/vendor/qcom/monaco_group/codeaurora/dataservices","clone_url":"https://git.codelinaro.org/clo/la/platform/vendor/qcom/monaco_group/codeaurora/dataservices.git","description":null}
{"name":"le-au-os/ota/system/extras","clone_url":"https://git.codelinaro.org/clo/le-au-os/ota/system/extras.git","description":null}
{"name":"le/platform/hardware/qcom/media","clone_url":"https://git.codelinaro.org/clo/le/platform/hardware/qcom/media.git","description":null}
{"name":"yocto-mirrors/github/codahale/rfc6979","clone_url":"https://git.codelinaro.org/clo/yocto-mirrors/github/codahale/rfc6979.git","description":null}
{"name":"la/platform/external/liburing","clone_url":"https://git.codelinaro.org/clo/la/platform/external/liburing.git","description":null}
{"name":"la/platform/external/pixman","clone_url":"https://git.codelinaro.org/clo/la/platform/external/pixman.git","description":null}
{"name":"la/platform/packages/apps/Car/UserManagement","clone_url":"https://git.codelinaro.org/clo/la/platform/packages/apps/Car/UserManagement.git","description":null}
{"name":"qsdk/oss/linux/linux-mips","clone_url":"https://git.codelinaro.org/clo/qsdk/oss/linux/linux-mips.git","description":null}
{"name":"yocto-mirrors/github/flann-lib/flann","clone_url":"https://git.codelinaro.org/clo/yocto-mirrors/github/flann-lib/flann.git","description":null}
{"name":"qrdk/parodus2ccsp","clone_url":"https://git.codelinaro.org/clo/qrdk/parodus2ccsp.git","description":null}
{"name":"la/platform/external/chromium_org/third_party/smhasher/src","clone_url":"https://git.codelinaro.org/clo/la/platform/external/chromium_org/third_party/smhasher/src.git","description":null}
{"name":"la/platform/prebuilts/androidx/traceprocessor","clone_url":"https://git.codelinaro.org/clo/la/platform/prebuilts/androidx/traceprocessor.git","description":null}
{"name":"la/platform/external/rust/crates/mockall_derive","clone_url":"https://git.codelinaro.org/clo/la/platform/external/rust/crates/mockall_derive.git","description":null}
{"name":"la/platform/external/oauth","clone_url":"https://git.codelinaro.org/clo/la/platform/external/oauth.git","description":null}
{"name":"testproject/platform/external/libdaemon","clone_url":"https://git.codelinaro.org/clo/testproject/platform/external/libdaemon.git","description":null}
{"name":"la/platform/external/google-fruit","clone_url":"https://git.codelinaro.org/clo/la/platform/external/google-fruit.git","description":null}
{"name":"la/platform/external/truth","clone_url":"https://git.codelinaro.org/clo/la/platform/external/truth.git","description":null}
{"name":"la/platform/external/boost-submodules/graph_parallel","clone_url":"https://git.codelinaro.org/clo/la/platform/external/boost-submodules/graph_parallel.git","description":null}
{"name":"la/toolchain/llvm","clone_url":"https://git.codelinaro.org/clo/la/toolchain/llvm.git","description":null}
{"name":"la/platform/prebuilts/jdk/jdk8","clone_url":"https://git.codelinaro.org/clo/la/platform/prebuilts/jdk/jdk8.git","description":null}
{"name":"la/platform/tools/test/connectivity","clone_url":"https://git.codelinaro.org/clo/la/platform/tools/test/connectivity.git","description":null}
{"name":"lc/external/github.com/python/cpython","clone_url":"https://git.codelinaro.org/clo/lc/external/github.com/python/cpython.git","description":null}
{"name":"qsdk/wifi/qca-wifi-oss","clone_url":"https://git.codelinaro.org/clo/qsdk/wifi/qca-wifi-oss.git","description":null}
{"name":"la/platform/external/boost-submodules/multiprecision","clone_url":"https://git.codelinaro.org/clo/la/platform/external/boost-submodules/multiprecision.git","description":null}
{"name":"testproject/platform/external/zlib","clone_url":"https://git.codelinaro.org/clo/testproject/platform/external/zlib.git","description":null}
{"name":"lc/chromiumos/infra_repo","clone_url":"https://git.codelinaro.org/clo/lc/chromiumos/infra_repo.git","description":null}
{"name":"testproject/platform/test/mlts/benchmark","clone_url":"https://git.codelinaro.org/clo/testproject/platform/test/mlts/benchmark.git","description":null}
{"name":"la/platform/external/python/more-itertools","clone_url":"https://git.codelinaro.org/clo/la/platform/external/python/more-itertools.git","description":null}
{"name":"la/platform/external/chromium_org_repo","clone_url":"https://git.codelinaro.org/clo/la/platform/external/chromium_org_repo.git","description":null}
{"name":"la/platform/system/qcom","clone_url":"https://git.codelinaro.org/clo/la/platform/system/qcom.git","description":null}
{"name":"la/platform/external/rust/crates/asn1-rs-derive","clone_url":"https://git.codelinaro.org/clo/la/platform/external/rust/crates/asn1-rs-derive.git","description":null}
{"name":"la/platform/hardware/nxp/uwb","clone_url":"https://git.codelinaro.org/clo/la/platform/hardware/nxp/uwb.git","description":null}
{"name":"testproject/platform/external/kernel-headers","clone_url":"https://git.codelinaro.org/clo/testproject/platform/external/kernel-headers.git","description":null}
{"name":"testproject/platform/external/nist-pkits","clone_url":"https://git.codelinaro.org/clo/testproject/platform/external/nist-pkits.git","description":null}
{"name":"la/kernel/devices/google/eos","clone_url":"https://git.codelinaro.org/clo/la/kernel/devices/google/eos.git","description":null}
{"name":"la/platform/external/webrtc_legacy","clone_url":"https://git.codelinaro.org/clo/la/platform/external/webrtc_legacy.git","description":null}
{"name":"rdkb/rdkb/components/opensource/ccsp/Utopia","clone_url":"https://git.codelinaro.org/clo/rdkb/rdkb/components/opensource/ccsp/Utopia.git","description":null}
{"name":"lc/external/github.com/googlefonts/sfntly","clone_url":"https://git.codelinaro.org/clo/lc/external/github.com/googlefonts/sfntly.git","description":null}
{"name":"lc/external/github.com/dart-lang/usage","clone_url":"https://git.codelinaro.org/clo/lc/external/github.com/dart-lang/usage.git","description":null}
{"name":"qcomlt/pkg/linux-board-support-package-dragonboard820c","clone_url":"https://git.codelinaro.org/clo/qcomlt/pkg/linux-board-support-package-dragonboard820c.git","description":null}
{"name":"lc/external/github.com/khaledhosny/ots","clone_url":"https://git.codelinaro.org/clo/lc/external/github.com/khaledhosny/ots.git","description":null}
{"name":"la/cts_drno_filter","clone_url":"https://git.codelinaro.org/clo/la/cts_drno_filter.git","description":null}
{"name":"testproject/platform/external/jline","clone_url":"https://git.codelinaro.org/clo/testproject/platform/external/jline.git","description":null}
{"name":"testproject/device/generic/goldfish-opengl","clone_url":"https://git.codelinaro.org/clo/testproject/device/generic/goldfish-opengl.git","description":null}
{"name":"rdkb/rdkb/devices/rdkbemu/rdkbemu_xb3","clone_url":"https://git.codelinaro.org/clo/rdkb/rdkb/devices/rdkbemu/rdkbemu_xb3.git","description":null}
{"name":"testproject/platform/external/python/cpython3","clone_url":"https://git.codelinaro.org/clo/testproject/platform/external/python/cpython3.git","description":null}
{"name":"la/platform/external/owasp/java-encoder","clone_url":"https://git.codelinaro.org/clo/la/platform/external/owasp/java-encoder.git","description":null}
{"name":"la/platform/external/jhead","clone_url":"https://git.codelinaro.org/clo/la/platform/external/jhead.git","description":null}
{"name":"la/platform/external/freedesktop.org/wayland/wayland-protocols","clone_url":"https://git.codelinaro.org/clo/la/platform/external/freedesktop.org/wayland/wayland-protocols.git","description":null}
{"name":"la/platform/hardware/bsp/kernel/imagination/v4.1","clone_url":"https://git.codelinaro.org/clo/la/platform/hardware/bsp/kernel/imagination/v4.1.git","description":null}
{"name":"le/platform/external/x264","clone_url":"https://git.codelinaro.org/clo/le/platform/external/x264.git","description":null}
{"name":"la/platform/vendor/qcom-opensource/fingerprint-devicetree","clone_url":"https://git.codelinaro.org/clo/la/platform/vendor/qcom-opensource/fingerprint-devicetree.git","description":null}
{"name":"lc/chromium/deps/mozprofile","clone_url":"https://git.codelinaro.org/clo/lc/chromium/deps/mozprofile.git","description":null}
{"name":"la/platform/vendor/qcom-opensource/omx/mm-video","clone_url":"https://git.codelinaro.org/clo/la/platform/vendor/qcom-opensource/omx/mm-video.git","description":null}
{"name":"kernel-platform-2-0-os/kernel_platform/external/python/absl-py","clone_url":"https://git.codelinaro.org/clo/kernel-platform-2-0-os/kernel_platform/external/python/absl-py.git","description":null}
{"name":"yocto-mirrors/github/libvirt/libvirt","clone_url":"https://git.codelinaro.org/clo/yocto-mirrors/github/libvirt/libvirt.git","description":null}
{"name":"la/platform/external/boost-submodules/parameter_python","clone_url":"https://git.codelinaro.org/clo/la/platform/external/boost-submodules/parameter_python.git","description":null}
{"name":"lc/chromium/deps/sqlite","clone_url":"https://git.codelinaro.org/clo/lc/chromium/deps/sqlite.git","description":null}
{"name":"testproject/platform/packages/providers/CallLogProvider","clone_url":"https://git.codelinaro.org/clo/testproject/platform/packages/providers/CallLogProvider.git","description":null}
{"name":"la/platform/external/rust/crates/lock_api","clone_url":"https://git.codelinaro.org/clo/la/platform/external/rust/crates/lock_api.git","description":null}
{"name":"la/platform/vendor/qcom/opensource/audio-vibrator","clone_url":"https://git.codelinaro.org/clo/la/platform/vendor/qcom/opensource/audio-vibrator.git","description":null}
{"name":"yocto-mirrors/github/ros2-gbp/geometric_shapes-release","clone_url":"https://git.codelinaro.org/clo/yocto-mirrors/github/ros2-gbp/geometric_shapes-release.git","description":null}
{"name":"lc/external/github.com/tmc/scp","clone_url":"https://git.codelinaro.org/clo/lc/external/github.com/tmc/scp.git","description":null}
{"name":"testproject/platform/packages/wallpapers/LivePicker","clone_url":"https://git.codelinaro.org/clo/testproject/platform/packages/wallpapers/LivePicker.git","description":null}
{"name":"qsdk/oss/system/feeds/wlan-hostapd","clone_url":"https://git.codelinaro.org/clo/qsdk/oss/system/feeds/wlan-hostapd.git","description":null}
{"name":"la/toolchain/build","clone_url":"https://git.codelinaro.org/clo/la/toolchain/build.git","description":null}
{"name":"qsdk/platform/vendor/qcom-opensource/drone/QOpenHD","clone_url":"https://git.codelinaro.org/clo/qsdk/platform/vendor/qcom-opensource/drone/QOpenHD.git","description":null}
{"name":"qsdk/oss/system/feeds/luci","clone_url":"https://git.codelinaro.org/clo/qsdk/oss/system/feeds/luci.git","description":null}
{"name":"la/platform/hardware/intel/common/libstagefrighthw","clone_url":"https://git.codelinaro.org/clo/la/platform/hardware/intel/common/libstagefrighthw.git","description":null}
{"name":"le/platform/hardware/qcom/gps","clone_url":"https://git.codelinaro.org/clo/le/platform/hardware/qcom/gps.git","description":null}
{"name":"le/external/libinput/libinput","clone_url":"https://git.codelinaro.org/clo/le/external/libinput/libinput.git","description":null}
{"name":"la/platform/external/boost-submodules/phoenix","clone_url":"https://git.codelinaro.org/clo/la/platform/external/boost-submodules/phoenix.git","description":null}
{"name":"la/platform/external/netcat","clone_url":"https://git.codelinaro.org/clo/la/platform/external/netcat.git","description":null}
{"name":"atlas7-automotive-linux/kernel/modules/secpub","clone_url":"https://git.codelinaro.org/clo/atlas7-automotive-linux/kernel/modules/secpub.git","description":null}
{"name":"la/platform/external/setupcompat","clone_url":"https://git.codelinaro.org/clo/la/platform/external/setupcompat.git","description":null}
{"name":"la/platform/prebuilts/fullsdk/platforms/android-21","clone_url":"https://git.codelinaro.org/clo/la/platform/prebuilts/fullsdk/platforms/android-21.git","description":null}
{"name":"automotive/platform/xen","clone_url":"https://git.codelinaro.org/clo/automotive/platform/xen.git","description":null}
{"name":"la/platform/hardware/qcom/wlan","clone_url":"https://git.codelinaro.org/clo/la/platform/hardware/qcom/wlan.git","description":null}
{"name":"rdkb/rdkb/components/opensource/ccsp/webui-bwg","clone_url":"https://git.codelinaro.org/clo/rdkb/rdkb/components/opensource/ccsp/webui-bwg.git","description":null}
{"name":"la/platform/prebuilts/siso","clone_url":"https://git.codelinaro.org/clo/la/platform/prebuilts/siso.git","description":null}
{"name":"la/platform/external/angle","clone_url":"https://git.codelinaro.org/clo/la/platform/external/angle.git","description":null}
{"name":"la/platform/external/rust/crates/coset","clone_url":"https://git.codelinaro.org/clo/la/platform/external/rust/crates/coset.git","description":null}
{"name":"la/platform/external/aws/aws-iot-device-sdk-embedded-C","clone_url":"https://git.codelinaro.org/clo/la/platform/external/aws/aws-iot-device-sdk-embedded-C.git","description":null}
{"name":"la/platform/external/toolchain-utils","clone_url":"https://git.codelinaro.org/clo/la/platform/external/toolchain-utils.git","description":null}
{"name":"health-checker/emailcheck","clone_url":"https://git.codelinaro.org/clo/health-checker/emailcheck.git","description":null}
{"name":"le-au-os/platform/system/core","clone_url":"https://git.codelinaro.org/clo/le-au-os/platform/system/core.git","description":null}
{"name":"testproject/platform/external/libcups","clone_url":"https://git.codelinaro.org/clo/testproject/platform/external/libcups.git","description":null}
{"name":"la/platform/tools/external/gradle","clone_url":"https://git.codelinaro.org/clo/la/platform/tools/external/gradle.git","description":null}
{"name":"qsdk/mwlwifi","clone_url":"https://git.codelinaro.org/clo/qsdk/mwlwifi.git","description":null}
{"name":"femto5g/fsm/external/qoriq-components/linux_5.10","clone_url":"https://git.codelinaro.org/clo/femto5g/fsm/external/qoriq-components/linux_5.10.git","description":null}
{"name":"la/platform/packages/apps/TimeZoneUpdater","clone_url":"https://git.codelinaro.org/clo/la/platform/packages/apps/TimeZoneUpdater.git","description":null}
{"name":"yocto-mirrors/github/fedora-selinux/seinux-policy","clone_url":"https://git.codelinaro.org/clo/yocto-mirrors/github/fedora-selinux/seinux-policy.git","description":null}
{"name":"lc/infra/gerrit-plugins/git-number-verifier","clone_url":"https://git.codelinaro.org/clo/lc/infra/gerrit-plugins/git-number-verifier.git","description":null}
{"name":"lc/external/github.com/brendan-duncan/archive","clone_url":"https://git.codelinaro.org/clo/lc/external/github.com/brendan-duncan/archive.git","description":null}
{"name":"bt/platform/packages/apps/Bluetooth","clone_url":"https://git.codelinaro.org/clo/bt/platform/packages/apps/Bluetooth.git","description":null}
{"name":"la/platform/vendor/qcom-opensource/iot-media-app","clone_url":"https://git.codelinaro.org/clo/la/platform/vendor/qcom-opensource/iot-media-app.git","description":null}
{"name":"qsdk/libvpx","clone_url":"https://git.codelinaro.org/clo/qsdk/libvpx.git","description":null}
{"name":"la/toolchain/gmp","clone_url":"https://git.codelinaro.org/clo/la/toolchain/gmp.git","description":null}
{"name":"le/qzephyr/zephyrproject-rtos/littlefs","clone_url":"https://git.codelinaro.org/clo/le/qzephyr/zephyrproject-rtos/littlefs.git","description":null}
{"name":"la/platform/vendor/qcom/msmnileau_gvmq_vcu","clone_url":"https://git.codelinaro.org/clo/la/platform/vendor/qcom/msmnileau_gvmq_vcu.git","description":null}
{"name":"la/platform/external/rust/crates/zerocopy","clone_url":"https://git.codelinaro.org/clo/la/platform/external/rust/crates/zerocopy.git","description":null}
{"name":"qsdk/mmcclint-qca","clone_url":"https://git.codelinaro.org/clo/qsdk/mmcclint-qca.git","description":null}
{"name":"qsdk/open-thread/openthread","clone_url":"https://git.codelinaro.org/clo/qsdk/open-thread/openthread.git","description":null}
{"name":"testproject/platform/external/javapoet","clone_url":"https://git.codelinaro.org/clo/testproject/platform/external/javapoet.git","description":null}
{"name":"la/platform/external/rust/crates/env_logger","clone_url":"https://git.codelinaro.org/clo/la/platform/external/rust/crates/env_logger.git","description":null}
{"name":"la/platform/external/libdisplay-info","clone_url":"https://git.codelinaro.org/clo/la/platform/external/libdisplay-info.git","description":null}
{"name":"le/platform/external/realsense-ros-release","clone_url":"https://git.codelinaro.org/clo/le/platform/external/realsense-ros-release.git","description":null}
{"name":"yocto-mirrors/github/go-jose/go-jose","clone_url":"https://git.codelinaro.org/clo/yocto-mirrors/github/go-jose/go-jose.git","description":null}
{"name":"la/platform/external/libavc","clone_url":"https://git.codelinaro.org/clo/la/platform/external/libavc.git","description":null}
{"name":"la/platform/external/libpalmrejection","clone_url":"https://git.codelinaro.org/clo/la/platform/external/libpalmrejection.git","description":null}
{"name":"la/platform/vendor/qcom/monaco_group/codeaurora/tinycompress","clone_url":"https://git.codelinaro.org/clo/la/platform/vendor/qcom/monaco_group/codeaurora/tinycompress.git","description":null}
{"name":"lc/external/github.com/square/go-jose","clone_url":"https://git.codelinaro.org/clo/lc/external/github.com/square/go-jose.git","description":null}
{"name":"lc/infra/third_party/six","clone_url":"https://git.codelinaro.org/clo/lc/infra/third_party/six.git","description":null}
{"name":"qcc7xx/patches","clone_url":"https://git.codelinaro.org/clo/qcc7xx/patches.git","description":null}
{"name":"testproject/toolchain/pgo-profiles","clone_url":"https://git.codelinaro.org/clo/testproject/toolchain/pgo-profiles.git","description":null}
{"name":"la/platform/external/boost-submodules/regex","clone_url":"https://git.codelinaro.org/clo/la/platform/external/boost-submodules/regex.git","description":null}
{"name":"qrdk/yajl","clone_url":"https://git.codelinaro.org/clo/qrdk/yajl.git","description":null}
{"name":"la/platform/external/wayland-protocols","clone_url":"https://git.codelinaro.org/clo/la/platform/external/wayland-protocols.git","description":null}
{"name":"yocto-mirrors/github/keybase/go-keychain","clone_url":"https://git.codelinaro.org/clo/yocto-mirrors/github/keybase/go-keychain.git","description":null}
{"name":"la/platform/vendor/qcom-opensource/wlan/qca-wifi-host-cmn-win","clone_url":"https://git.codelinaro.org/clo/la/platform/vendor/qcom-opensource/wlan/qca-wifi-host-cmn-win.git","description":null}
{"name":"la/platform/external/nos/host/generic","clone_url":"https://git.codelinaro.org/clo/la/platform/external/nos/host/generic.git","description":null}
{"name":"le/meta-qti-oss-gst","clone_url":"https://git.codelinaro.org/clo/le/meta-qti-oss-gst.git","description":null}
{"name":"la/kernel/prebuilts/common-modules/virtual-device/mainline/x86-64","clone_url":"https://git.codelinaro.org/clo/la/kernel/prebuilts/common-modules/virtual-device/mainline/x86-64.git","description":null}
{"name":"la/platform/external/libkmsxx","clone_url":"https://git.codelinaro.org/clo/la/platform/external/libkmsxx.git","description":null}
{"name":"lc/chromium/src/third_party/android_platform","clone_url":"https://git.codelinaro.org/clo/lc/chromium/src/third_party/android_platform.git","description":null}
{"name":"la/platform/prebuilts/python/linux-x86_repo","clone_url":"https://git.codelinaro.org/clo/la/platform/prebuilts/python/linux-x86_repo.git","description":null}
{"name":"le/platform/external/nuttx-apps","clone_url":"https://git.codelinaro.org/clo/le/platform/external/nuttx-apps.git","description":null}
{"name":"le/platform/vendor/qcom-opensource/cv2x-security-aerolink-public","clone_url":"https://git.codelinaro.org/clo/le/platform/vendor/qcom-opensource/cv2x-security-aerolink-public.git","description":null}
{"name":"yocto-mirrors/iputils","clone_url":"https://git.codelinaro.org/clo/yocto-mirrors/iputils.git","description":null}
{"name":"la/platform/vendor/qcom/sdm429w_law","clone_url":"https://git.codelinaro.org/clo/la/platform/vendor/qcom/sdm429w_law.git","description":null}
{"name":"la/platform/external/rust/crates/rustversion","clone_url":"https://git.codelinaro.org/clo/la/platform/external/rust/crates/rustversion.git","description":null}
{"name":"le/platform/external/ROBOTIS-GIT/open_manipulator_applications","clone_url":"https://git.codelinaro.org/clo/le/platform/external/ROBOTIS-GIT/open_manipulator_applications.git","description":null}
{"name":"la/platform/hardware/broadcom/wlan","clone_url":"https://git.codelinaro.org/clo/la/platform/hardware/broadcom/wlan.git","description":null}
{"name":"la/platform/external/bc","clone_url":"https://git.codelinaro.org/clo/la/platform/external/bc.git","description":null}
{"name":"qsdk/oss/system/openwrt_repo","clone_url":"https://git.codelinaro.org/clo/qsdk/oss/system/openwrt_repo.git","description":null}
{"name":"femto5g/oss/lklm/qca-ssdk","clone_url":"https://git.codelinaro.org/clo/femto5g/oss/lklm/qca-ssdk.git","description":null}
{"name":"lc/chromiumos/ide_tooling","clone_url":"https://git.codelinaro.org/clo/lc/chromiumos/ide_tooling.git","description":null}
{"name":"la/platform/vendor/qcom/opensource/datarmnet-ext","clone_url":"https://git.codelinaro.org/clo/la/platform/vendor/qcom/opensource/datarmnet-ext.git","description":null}
{"name":"la/platform/prebuilts/studio/skiaparser","clone_url":"https://git.codelinaro.org/clo/la/platform/prebuilts/studio/skiaparser.git","description":null}
{"name":"qsdk/easy-rsa","clone_url":"https://git.codelinaro.org/clo/qsdk/easy-rsa.git","description":null}
{"name":"femto/platform/vendor/qcom-opensource/location","clone_url":"https://git.codelinaro.org/clo/femto/platform/vendor/qcom-opensource/location.git","description":null}
{"name":"testproject/platform/external/lua","clone_url":"https://git.codelinaro.org/clo/testproject/platform/external/lua.git","description":null}
{"name":"la/platform/hardware/qcom/sdm429w/bootctrl","clone_url":"https://git.codelinaro.org/clo/la/platform/hardware/qcom/sdm429w/bootctrl.git","description":null}
{"name":"la/platform/external/iosched","clone_url":"https://git.codelinaro.org/clo/la/platform/external/iosched.git","description":null}
{"name":"testproject/platform/external/protobuf","clone_url":"https://git.codelinaro.org/clo/testproject/platform/external/protobuf.git","description":null}
{"name":"qsdk/platform/vendor/qcom-opensource/wlan/fw-api","clone_url":"https://git.codelinaro.org/clo/qsdk/platform/vendor/qcom-opensource/wlan/fw-api.git","description":null}
{"name":"la/platform/hardware/qcom/msm8x26","clone_url":"https://git.codelinaro.org/clo/la/platform/hardware/qcom/msm8x26.git","description":null}
{"name":"la/platform/external/capicxx-someip-tools","clone_url":"https://git.codelinaro.org/clo/la/platform/external/capicxx-someip-tools.git","description":null}
{"name":"la/platform/external/ThrowTheSwitch-Unity","clone_url":"https://git.codelinaro.org/clo/la/platform/external/ThrowTheSwitch-Unity.git","description":null}
{"name":"yocto-mirrors/github/flannel-io/cni-plugin","clone_url":"https://git.codelinaro.org/clo/yocto-mirrors/github/flannel-io/cni-plugin.git","description":null}
{"name":"le-au-os/platform/vendor/qcom-opensource/snaptel-sdk","clone_url":"https://git.codelinaro.org/clo/le-au-os/platform/vendor/qcom-opensource/snaptel-sdk.git","description":null}
{"name":"le/platform/external/compat-wireless","clone_url":"https://git.codelinaro.org/clo/le/platform/external/compat-wireless.git","description":null}
{"name":"la/platform/external/rust/crates/winapi-util","clone_url":"https://git.codelinaro.org/clo/la/platform/external/rust/crates/winapi-util.git","description":null}
{"name":"qsdk/libwebsockets","clone_url":"https://git.codelinaro.org/clo/qsdk/libwebsockets.git","description":null}
{"name":"testproject/platform/packages/apps/SettingsIntelligence","clone_url":"https://git.codelinaro.org/clo/testproject/platform/packages/apps/SettingsIntelligence.git","description":null}
{"name":"la/platform/frameworks/opt/telephony-msim","clone_url":"https://git.codelinaro.org/clo/la/platform/frameworks/opt/telephony-msim.git","description":null}
{"name":"lc/external/github.com/eliben/pycparser","clone_url":"https://git.codelinaro.org/clo/lc/external/github.com/eliben/pycparser.git","description":null}
{"name":"le/snap/yaml-gadget","clone_url":"https://git.codelinaro.org/clo/le/snap/yaml-gadget.git","description":null}
{"name":"lc/chromiumos/third_party/hwcplus","clone_url":"https://git.codelinaro.org/clo/lc/chromiumos/third_party/hwcplus.git","description":null}
{"name":"la/kernel/prebuilts/6.12/x86-64","clone_url":"https://git.codelinaro.org/clo/la/kernel/prebuilts/6.12/x86-64.git","description":null}
{"name":"qsdk/platform/vendor/qcom-opensource/dataservices","clone_url":"https://git.codelinaro.org/clo/qsdk/platform/vendor/qcom-opensource/dataservices.git","description":null}
{"name":"la/platform/external/mtools","clone_url":"https://git.codelinaro.org/clo/la/platform/external/mtools.git","description":null}
{"name":"yocto-mirrors/github/prometheus/client_model","clone_url":"https://git.codelinaro.org/clo/yocto-mirrors/github/prometheus/client_model.git","description":null}
{"name":"la/platform/packages/apps/SmartCardService","clone_url":"https://git.codelinaro.org/clo/la/platform/packages/apps/SmartCardService.git","description":null}
{"name":"la/platform/external/boost-submodules/dll","clone_url":"https://git.codelinaro.org/clo/la/platform/external/boost-submodules/dll.git","description":null}
{"name":"la/virtio/qcvirtio-virtio-rtc-driver-linux","clone_url":"https://git.codelinaro.org/clo/la/virtio/qcvirtio-virtio-rtc-driver-linux.git","description":null}
{"name":"la/platform/external/rp-pppoe","clone_url":"https://git.codelinaro.org/clo/la/platform/external/rp-pppoe.git","description":null}
{"name":"qsdk/oss/system/feeds/owrt-qti-ipq","clone_url":"https://git.codelinaro.org/clo/qsdk/oss/system/feeds/owrt-qti-ipq.git","description":null}
{"name":"testproject/platform/external/rootdev","clone_url":"https://git.codelinaro.org/clo/testproject/platform/external/rootdev.git","description":null}
{"name":"lc/external/jsoncpp/jsoncpp_repo","clone_url":"https://git.codelinaro.org/clo/lc/external/jsoncpp/jsoncpp_repo.git","description":null}
{"name":"yocto-mirrors/github/apparentlymart/go-cidr","clone_url":"https://git.codelinaro.org/clo/yocto-mirrors/github/apparentlymart/go-cidr.git","description":null}
{"name":"la/platform/external/obstack","clone_url":"https://git.codelinaro.org/clo/la/platform/external/obstack.git","description":null}
{"name":"la/platform/external/libwebsockets","clone_url":"https://git.codelinaro.org/clo/la/platform/external/libwebsockets.git","description":null}
{"name":"qsdk/platform/vendor/qcom-opensource/drone/OpenHD","clone_url":"https://git.codelinaro.org/clo/qsdk/platform/vendor/qcom-opensource/drone/OpenHD.git","description":null}
{"name":"lc/coreboot","clone_url":"https://git.codelinaro.org/clo/lc/coreboot.git","description":null}
{"name":"bt/platform/hardware/qcom/bt","clone_url":"https://git.codelinaro.org/clo/bt/platform/hardware/qcom/bt.git","description":null}
{"name":"lc/chromium/src/media_repo","clone_url":"https://git.codelinaro.org/clo/lc/chromium/src/media_repo.git","description":null}
{"name":"yocto-mirrors/github/shibumi/go-pathspec","clone_url":"https://git.codelinaro.org/clo/yocto-mirrors/github/shibumi/go-pathspec.git","description":null}
{"name":"la/platform/system/libfmq","clone_url":"https://git.codelinaro.org/clo/la/platform/system/libfmq.git","description":null}
{"name":"la/platform/vendor/qcom-opensource/wlan/wlan-devicetree","clone_url":"https://git.codelinaro.org/clo/la/platform/vendor/qcom-opensource/wlan/wlan-devicetree.git","description":null}
{"name":"la/device/sony/lt26","clone_url":"https://git.codelinaro.org/clo/la/device/sony/lt26.git","description":null}
{"name":"la/platform/prebuilts/fullsdk/sources/android-TPS","clone_url":"https://git.codelinaro.org/clo/la/platform/prebuilts/fullsdk/sources/android-TPS.git","description":null}
{"name":"iris-video-driver/patches","clone_url":"https://git.codelinaro.org/clo/iris-video-driver/patches.git","description":null}
{"name":"qsdk/oss/lklm/nss-ppe-uio","clone_url":"https://git.codelinaro.org/clo/qsdk/oss/lklm/nss-ppe-uio.git","description":null}
{"name":"yocto-mirrors/github/ros2-gbp/pcl_msgs-release","clone_url":"https://git.codelinaro.org/clo/yocto-mirrors/github/ros2-gbp/pcl_msgs-release.git","description":null}
{"name":"trusted-firmware/optee_test/optee_test","clone_url":"https://git.codelinaro.org/clo/trusted-firmware/optee_test/optee_test.git","description":null}
{"name":"qsdk/oss/releases/configs/qsdk","clone_url":"https://git.codelinaro.org/clo/qsdk/oss/releases/configs/qsdk.git","description":null}
{"name":"le/platform/external/sos","clone_url":"https://git.codelinaro.org/clo/le/platform/external/sos.git","description":null}
{"name":"la/platform/test/vts-testcase/performance","clone_url":"https://git.codelinaro.org/clo/la/platform/test/vts-testcase/performance.git","description":null}
{"name":"la/platform/external/google-auth-library-java","clone_url":"https://git.codelinaro.org/clo/la/platform/external/google-auth-library-java.git","description":null}
{"name":"le/platform/external/mctp","clone_url":"https://git.codelinaro.org/clo/le/platform/external/mctp.git","description":null}
{"name":"la/platform/prebuilts/module_sdk/AdServices","clone_url":"https://git.codelinaro.org/clo/la/platform/prebuilts/module_sdk/AdServices.git","description":null}
{"name":"la/platform/external/cmockery","clone_url":"https://git.codelinaro.org/clo/la/platform/external/cmockery.git","description":null}
{"name":"la/platform/prebuilts/clang/linux-x86/mips/3.3","clone_url":"https://git.codelinaro.org/clo/la/platform/prebuilts/clang/linux-x86/mips/3.3.git","description":null}
{"name":"la/platform/external/bzip2","clone_url":"https://git.codelinaro.org/clo/la/platform/external/bzip2.git","description":null}
{"name":"testproject/platform/external/bc","clone_url":"https://git.codelinaro.org/clo/testproject/platform/external/bc.git","description":null}
{"name":"la/platform/hardware/qcom/msm8994","clone_url":"https://git.codelinaro.org/clo/la/platform/hardware/qcom/msm8994.git","description":null}
{"name":"lc/chromium/src/third_party/boringssl","clone_url":"https://git.codelinaro.org/clo/lc/chromium/src/third_party/boringssl.git","description":null}
{"name":"lc/chromium/deps/psyco_win32","clone_url":"https://git.codelinaro.org/clo/lc/chromium/deps/psyco_win32.git","description":null}
{"name":"la/platform/external/puffin","clone_url":"https://git.codelinaro.org/clo/la/platform/external/puffin.git","description":null}
{"name":"la/platform/external/rust/crates/argh_shared","clone_url":"https://git.codelinaro.org/clo/la/platform/external/rust/crates/argh_shared.git","description":null}
{"name":"la/platform/external/unikraft/unikraft","clone_url":"https://git.codelinaro.org/clo/la/platform/external/unikraft/unikraft.git","description":null}
{"name":"yocto-mirrors/github/ros2-gbp/rmw-release","clone_url":"https://git.codelinaro.org/clo/yocto-mirrors/github/ros2-gbp/rmw-release.git","description":null}
{"name":"lc/aosp_repo","clone_url":"https://git.codelinaro.org/clo/lc/aosp_repo.git","description":null}
{"name":"yocto-mirrors/pflag","clone_url":"https://git.codelinaro.org/clo/yocto-mirrors/pflag.git","description":null}
{"name":"la/platform/test/robolectric-extensions","clone_url":"https://git.codelinaro.org/clo/la/platform/test/robolectric-extensions.git","description":null}
{"name":"la/platform/hardware/qcom/sdm429w/display","clone_url":"https://git.codelinaro.org/clo/la/platform/hardware/qcom/sdm429w/display.git","description":null}
{"name":"la/platform/external/rust/crates/sync_wrapper","clone_url":"https://git.codelinaro.org/clo/la/platform/external/rust/crates/sync_wrapper.git","description":null}
{"name":"yocto-mirrors/gitlab/pipewire/pipewire","clone_url":"https://git.codelinaro.org/clo/yocto-mirrors/gitlab/pipewire/pipewire.git","description":null}
{"name":"le/systemd-stable","clone_url":"https://git.codelinaro.org/clo/le/systemd-stable.git","description":null}
{"name":"le/platform/vendor/qcom-opensource/audio_mcs","clone_url":"https://git.codelinaro.org/clo/le/platform/vendor/qcom-opensource/audio_mcs.git","description":null}
{"name":"le/ros2-gbp/rcl-release","clone_url":"https://git.codelinaro.org/clo/le/ros2-gbp/rcl-release.git","description":null}
{"name":"la/device/amlogic/yukawa-kernel","clone_url":"https://git.codelinaro.org/clo/la/device/amlogic/yukawa-kernel.git","description":null}
{"name":"le/genivi/ipc/common-api-runtime","clone_url":"https://git.codelinaro.org/clo/le/genivi/ipc/common-api-runtime.git","description":null}
{"name":"kernel-platform-2-0-os/kernel/msm-5.15","clone_url":"https://git.codelinaro.org/clo/kernel-platform-2-0-os/kernel/msm-5.15.git","description":null}
{"name":"la/kernel/google-modules/wlan/qcom/wcn6740/wlan","clone_url":"https://git.codelinaro.org/clo/la/kernel/google-modules/wlan/qcom/wcn6740/wlan.git","description":null}
{"name":"la/platform/vendor/qcom/sdm429w/codeaurora/recovery-ext","clone_url":"https://git.codelinaro.org/clo/la/platform/vendor/qcom/sdm429w/codeaurora/recovery-ext.git","description":null}
{"name":"le/external/github.com/TC956X/TC9564_Host_Driver","clone_url":"https://git.codelinaro.org/clo/le/external/github.com/TC956X/TC9564_Host_Driver.git","description":null}
{"name":"lc/chromiumos/third_party/coreboot_repo","clone_url":"https://git.codelinaro.org/clo/lc/chromiumos/third_party/coreboot_repo.git","description":null}
{"name":"la/platform/external/jcommander","clone_url":"https://git.codelinaro.org/clo/la/platform/external/jcommander.git","description":null}
{"name":"le/AGL/src/can-lin","clone_url":"https://git.codelinaro.org/clo/le/AGL/src/can-lin.git","description":null}
{"name":"la/platform/prebuilts/libedit/darwin-x86","clone_url":"https://git.codelinaro.org/clo/la/platform/prebuilts/libedit/darwin-x86.git","description":null}
{"name":"qsdk/oss/lklm/nss-netfn","clone_url":"https://git.codelinaro.org/clo/qsdk/oss/lklm/nss-netfn.git","description":null}
{"name":"la/platform/external/modelcontextprotocol/kotlin-sdk","clone_url":"https://git.codelinaro.org/clo/la/platform/external/modelcontextprotocol/kotlin-sdk.git","description":null}
{"name":"la/device/google/caimito","clone_url":"https://git.codelinaro.org/clo/la/device/google/caimito.git","description":null}
{"name":"testproject/platform/packages/services/Telecomm","clone_url":"https://git.codelinaro.org/clo/testproject/platform/packages/services/Telecomm.git","description":null}
{"name":"testproject/platform/prebuilts/r8","clone_url":"https://git.codelinaro.org/clo/testproject/platform/prebuilts/r8.git","description":null}
{"name":"lc/external/webrtc/deps/third_party/openmax","clone_url":"https://git.codelinaro.org/clo/lc/external/webrtc/deps/third_party/openmax.git","description":null}
{"name":"la/platform/vendor/qcom-opensource/ts_firmware","clone_url":"https://git.codelinaro.org/clo/la/platform/vendor/qcom-opensource/ts_firmware.git","description":null}
{"name":"la/platform/external/wuffs-mirror-release-c","clone_url":"https://git.codelinaro.org/clo/la/platform/external/wuffs-mirror-release-c.git","description":null}
{"name":"la/platform/packages/services/Mms","clone_url":"https://git.codelinaro.org/clo/la/platform/packages/services/Mms.git","description":null}
{"name":"la/platform/test/dittosuite","clone_url":"https://git.codelinaro.org/clo/la/platform/test/dittosuite.git","description":null}
{"name":"la/platform/prebuilts/cmake/linux-x86","clone_url":"https://git.codelinaro.org/clo/la/platform/prebuilts/cmake/linux-x86.git","description":null}
{"name":"la/platform/external/rust/crates/lz4_flex","clone_url":"https://git.codelinaro.org/clo/la/platform/external/rust/crates/lz4_flex.git","description":null}
{"name":"la/platform/packages/apps/UnifiedEmail","clone_url":"https://git.codelinaro.org/clo/la/platform/packages/apps/UnifiedEmail.git","description":null}
{"name":"yocto-mirrors/ncurses","clone_url":"https://git.codelinaro.org/clo/yocto-mirrors/ncurses.git","description":null}
{"name":"lf/ByteBuffer.js","clone_url":"https://git.codelinaro.org/clo/lf/ByteBuffer.js.git","description":null}
{"name":"la/platform/vendor/qcom-opensource/stm-log","clone_url":"https://git.codelinaro.org/clo/la/platform/vendor/qcom-opensource/stm-log.git","description":null}
{"name":"la/platform/external/autoconf","clone_url":"https://git.codelinaro.org/clo/la/platform/external/autoconf.git","description":null}
{"name":"la/platform/packages/apps/TvFeedbackConsent","clone_url":"https://git.codelinaro.org/clo/la/platform/packages/apps/TvFeedbackConsent.git","description":null}
{"name":"la/platform/external/virglrenderer","clone_url":"https://git.codelinaro.org/clo/la/platform/external/virglrenderer.git","description":null}
{"name":"la/platform/external/rust/crates/config","clone_url":"https://git.codelinaro.org/clo/la/platform/external/rust/crates/config.git","description":null}
{"name":"le/Iotivity","clone_url":"https://git.codelinaro.org/clo/le/Iotivity.git","description":null}
{"name":"la/platform/prebuilts/androidx/ink","clone_url":"https://git.codelinaro.org/clo/la/platform/prebuilts/androidx/ink.git","description":null}
{"name":"la/platform/packages/apps/VoiceDialer","clone_url":"https://git.codelinaro.org/clo/la/platform/packages/apps/VoiceDialer.git","description":null}
{"name":"le/platform/telaf-pa-default","clone_url":"https://git.codelinaro.org/clo/le/platform/telaf-pa-default.git","description":null}
{"name":"le/platform/external/ros-perception/image_transport_plugins","clone_url":"https://git.codelinaro.org/clo/le/platform/external/ros-perception/image_transport_plugins.git","description":null}
{"name":"testproject/platform/external/libfuse","clone_url":"https://git.codelinaro.org/clo/testproject/platform/external/libfuse.git","description":null}
{"name":"la/toolchain/jdk/jdk9_jaxws","clone_url":"https://git.codelinaro.org/clo/la/toolchain/jdk/jdk9_jaxws.git","description":null}
{"name":"lc/external/github.com/go-warnings/warnings","clone_url":"https://git.codelinaro.org/clo/lc/external/github.com/go-warnings/warnings.git","description":null}
{"name":"la/Kernel-Projects","clone_url":"https://git.codelinaro.org/clo/la/Kernel-Projects.git","description":null}
{"name":"yocto-mirrors/github/danmar/cppcheck","clone_url":"https://git.codelinaro.org/clo/yocto-mirrors/github/danmar/cppcheck.git","description":null}
{"name":"la/platform/hardware/ti/omap4-aah","clone_url":"https://git.codelinaro.org/clo/la/platform/hardware/ti/omap4-aah.git","description":null}
{"name":"la/platform/vendor/sample","clone_url":"https://git.codelinaro.org/clo/la/platform/vendor/sample.git","description":null}
{"name":"le/miracast","clone_url":"https://git.codelinaro.org/clo/le/miracast.git","description":null}
{"name":"yocto-mirrors/github/docker/cli-docs-tool","clone_url":"https://git.codelinaro.org/clo/yocto-mirrors/github/docker/cli-docs-tool.git","description":null}
{"name":"la/platform/external/rust/crates/ucs2","clone_url":"https://git.codelinaro.org/clo/la/platform/external/rust/crates/ucs2.git","description":null}
{"name":"lc/chromiumos/third_party/upstart","clone_url":"https://git.codelinaro.org/clo/lc/chromiumos/third_party/upstart.git","description":null}
{"name":"atlas7-automotive-linux/build/meta-csr-bsp","clone_url":"https://git.codelinaro.org/clo/atlas7-automotive-linux/build/meta-csr-bsp.git","description":null}
