{"name":"la/platform/external/yapf","clone_url":"https://git.codelinaro.org/clo/la/platform/external/yapf.git","description":null}
{"name":"le/platform/external/bluetooth/bluez","clone_url":"https://git.codelinaro.org/clo/le/platform/external/bluetooth/bluez.git","description":null}
{"name":"la/platform/external/rust/crates/thiserror","clone_url":"https://git.codelinaro.org/clo/la/platform/external/rust/crates/thiserror.git","description":null}
{"name":"le/platform/hardware/qcom/display","clone_url":"https://git.codelinaro.org/clo/le/platform/hardware/qcom/display.git","description":null}
{"name":"testproject/platform/frameworks/multidex","clone_url":"https://git.codelinaro.org/clo/testproject/platform/frameworks/multidex.git","description":null}
{"name":"la/platform/packages/apps/OneTimeInitializer","clone_url":"https://git.codelinaro.org/clo/la/platform/packages/apps/OneTimeInitializer.git","description":null}
{"name":"la/platform/external/rust/crates/kernlog","clone_url":"https://git.codelinaro.org/clo/la/platform/external/rust/crates/kernlog.git","description":null}
{"name":"la/platform/prebuilts/module_sdk/MediaProvider","clone_url":"https://git.codelinaro.org/clo/la/platform/prebuilts/module_sdk/MediaProvider.git","description":null}
{"name":"la/platform/prebuilts/vndk/v32","clone_url":"https://git.codelinaro.org/clo/la/platform/prebuilts/vndk/v32.git","description":null}
{"name":"la/platform/external/rust/crates/parking_lot_core","clone_url":"https://git.codelinaro.org/clo/la/platform/external/rust/crates/parking_lot_core.git","description":null}
{"name":"la/platform/external/rust/crates/userfaultfd","clone_url":"https://git.codelinaro.org/clo/la/platform/external/rust/crates/userfaultfd.git","description":null}
{"name":"qsdk/system/owrt-qti-ipq-ezmesh","clone_url":"https://git.codelinaro.org/clo/qsdk/system/owrt-qti-ipq-ezmesh.git","description":null}
{"name":"la/platform/test/mlts/models","clone_url":"https://git.codelinaro.org/clo/la/platform/test/mlts/models.git","description":null}
{"name":"la/platform/vendor/qcom/msm8916_64","clone_url":"https://git.codelinaro.org/clo/la/platform/vendor/qcom/msm8916_64.git","description":null}
{"name":"la/platform/external/dynamic_depth","clone_url":"https://git.codelinaro.org/clo/la/platform/external/dynamic_depth.git","description":null}
{"name":"qrdk/rdkcentral/ppp-manager","clone_url":"https://git.codelinaro.org/clo/qrdk/rdkcentral/ppp-manager.git","description":null}
{"name":"testproject/platform/external/jsr305","clone_url":"https://git.codelinaro.org/clo/testproject/platform/external/jsr305.git","description":null}
{"name":"la/platform/vendor/qcom/monaco_group/codeaurora/mmc-utils","clone_url":"https://git.codelinaro.org/clo/la/platform/vendor/qcom/monaco_group/codeaurora/mmc-utils.git","description":null}
{"name":"la/platform/hardware/qcom/msm8996","clone_url":"https://git.codelinaro.org/clo/la/platform/hardware/qcom/msm8996.git","description":null}
{"name":"la/platform/hardware/ti/omap4-aah","clone_url":"https://git.codelinaro.org/clo/la/platform/hardware/ti/omap4-aah.git","description":null}
{"name":"testproject/platform/build_group/blueprint","clone_url":"https://git.codelinaro.org/clo/testproject/platform/build_group/blueprint.git","description":null}
{"name":"la/platform/external/rust/crates/mls-rs-core","clone_url":"https://git.codelinaro.org/clo/la/platform/external/rust/crates/mls-rs-core.git","description":null}
{"name":"testproject/platform/packages/apps/TimeZoneData","clone_url":"https://git.codelinaro.org/clo/testproject/platform/packages/apps/TimeZoneData.git","description":null}
{"name":"la/platform/external/google-api-services-storage","clone_url":"https://git.codelinaro.org/clo/la/platform/external/google-api-services-storage.git","description":null}
{"name":"testproject/platform/packages/providers/CallLogProvider","clone_url":"https://git.codelinaro.org/clo/testproject/platform/packages/providers/CallLogProvider.git","description":null}
{"name":"la/platform/external/chromium_org/third_party/brotli/src","clone_url":"https://git.codelinaro.org/clo/la/platform/external/chromium_org/third_party/brotli/src.git","description":null}
{"name":"qsdk/oss/system/feeds/alljoyn","clone_url":"https://git.codelinaro.org/clo/qsdk/oss/system/feeds/alljoyn.git","description":null}
{"name":"la/platform/prebuilts/fullsdk-linux/build-tools_group/29.0.0","clone_url":"https://git.codelinaro.org/clo/la/platform/prebuilts/fullsdk-linux/build-tools_group/29.0.0.git","description":null}
{"name":"la/platform/external/deqp-deps/SPIRV-Headers","clone_url":"https://git.codelinaro.org/clo/la/platform/external/deqp-deps/SPIRV-Headers.git","description":null}
{"name":"le/gstreamer/gst-omx","clone_url":"https://git.codelinaro.org/clo/le/gstreamer/gst-omx.git","description":null}
{"name":"la/platform/packages/apps/VoiceDialer","clone_url":"https://git.codelinaro.org/clo/la/platform/packages/apps/VoiceDialer.git","description":null}
{"name":"le/meta-qti-connectivity","clone_url":"https://git.codelinaro.org/clo/le/meta-qti-connectivity.git","description":null}
{"name":"la/platform/external/pogreb","clone_url":"https://git.codelinaro.org/clo/la/platform/external/pogreb.git","description":null}
{"name":"la/toolchain/ndk-kokoro","clone_url":"https://git.codelinaro.org/clo/la/toolchain/ndk-kokoro.git","description":null}
{"name":"yocto-mirrors/github/knqyf263/go-plugin","clone_url":"https://git.codelinaro.org/clo/yocto-mirrors/github/knqyf263/go-plugin.git","description":null}
{"name":"le/platform/vendor/qcom-opensource/meta-audioreach","clone_url":"https://git.codelinaro.org/clo/le/platform/vendor/qcom-opensource/meta-audioreach.git","description":null}
{"name":"lc/external/github.com/google/eDistantObject","clone_url":"https://git.codelinaro.org/clo/lc/external/github.com/google/eDistantObject.git","description":null}
{"name":"la/platform/hardware/qcom/camera","clone_url":"https://git.codelinaro.org/clo/la/platform/hardware/qcom/camera.git","description":null}
{"name":"la/toolchain/jdk/jdk21","clone_url":"https://git.codelinaro.org/clo/la/toolchain/jdk/jdk21.git","description":null}
{"name":"la/platform/vendor/qcom-opensource/omx/mm-core","clone_url":"https://git.codelinaro.org/clo/la/platform/vendor/qcom-opensource/omx/mm-core.git","description":null}
{"name":"la/device/google/caimito","clone_url":"https://git.codelinaro.org/clo/la/device/google/caimito.git","description":null}
{"name":"lf/releases/l10n/nl/gaia","clone_url":"https://git.codelinaro.org/clo/lf/releases/l10n/nl/gaia.git","description":null}
{"name":"la/platform/prebuilts/libprotobuf/windows","clone_url":"https://git.codelinaro.org/clo/la/platform/prebuilts/libprotobuf/windows.git","description":null}
{"name":"lc/external/github.com/kripken/emscripten-fastcomp-clang","clone_url":"https://git.codelinaro.org/clo/lc/external/github.com/kripken/emscripten-fastcomp-clang.git","description":null}
{"name":"la/platform/packages/modules/ArtPrebuilt","clone_url":"https://git.codelinaro.org/clo/la/platform/packages/modules/ArtPrebuilt.git","description":null}
{"name":"qcomlt/demos/linux","clone_url":"https://git.codelinaro.org/clo/qcomlt/demos/linux.git","description":"Qualcomm Landing Team Linux Demo trees\r\n\r\nDo not remove branches or tags, those are expected to be stable and valid for blog posts and marketing purposes.\r\n\r\ntopic/* branches are protected against modifications, do not change.\r\n\r\nDo not push work-in-progress or working branches here, only marketing/demo material."}
{"name":"yocto-mirrors/github/ros2-gbp/rmw-release","clone_url":"https://git.codelinaro.org/clo/yocto-mirrors/github/ros2-gbp/rmw-release.git","description":null}
{"name":"yocto-mirrors/gitlab/pipewire/wireplumber","clone_url":"https://git.codelinaro.org/clo/yocto-mirrors/gitlab/pipewire/wireplumber.git","description":null}
{"name":"le/external/qt/qtnetworkauth","clone_url":"https://git.codelinaro.org/clo/le/external/qt/qtnetworkauth.git","description":null}
{"name":"la/platform/packages/modules/ThreadNetwork","clone_url":"https://git.codelinaro.org/clo/la/platform/packages/modules/ThreadNetwork.git","description":null}
{"name":"la/platform/external/XNNPACK","clone_url":"https://git.codelinaro.org/clo/la/platform/external/XNNPACK.git","description":null}
{"name":"la/platform/packages/services/Iwlan","clone_url":"https://git.codelinaro.org/clo/la/platform/packages/services/Iwlan.git","description":null}
{"name":"la/platform/vendor/qcom-opensource/system/bt","clone_url":"https://git.codelinaro.org/clo/la/platform/vendor/qcom-opensource/system/bt.git","description":null}
{"name":"le/platform/vendor/qcom-opensource/adk-message-lib","clone_url":"https://git.codelinaro.org/clo/le/platform/vendor/qcom-opensource/adk-message-lib.git","description":null}
{"name":"le/platform/vendor/qcom-opensource/audio_ftm","clone_url":"https://git.codelinaro.org/clo/le/platform/vendor/qcom-opensource/audio_ftm.git","description":null}
{"name":"la/platform/external/noto-fonts","clone_url":"https://git.codelinaro.org/clo/la/platform/external/noto-fonts.git","description":null}
{"name":"la/platform/external/rust/crates/uniffi_core","clone_url":"https://git.codelinaro.org/clo/la/platform/external/rust/crates/uniffi_core.git","description":null}
{"name":"la/platform/external/rust/crates/fnv","clone_url":"https://git.codelinaro.org/clo/la/platform/external/rust/crates/fnv.git","description":null}
{"name":"la/platform/prebuilts/fullsdk/build-tools/21-linux","clone_url":"https://git.codelinaro.org/clo/la/platform/prebuilts/fullsdk/build-tools/21-linux.git","description":null}
{"name":"le/platform/external/turtlebot4_robot","clone_url":"https://git.codelinaro.org/clo/le/platform/external/turtlebot4_robot.git","description":null}
{"name":"la/platform/external/apache-commons-lang","clone_url":"https://git.codelinaro.org/clo/la/platform/external/apache-commons-lang.git","description":null}
{"name":"le/ros2-gbp/launch-release","clone_url":"https://git.codelinaro.org/clo/le/ros2-gbp/launch-release.git","description":null}
{"name":"la/toolchain/jdk/jdk9_jaxws","clone_url":"https://git.codelinaro.org/clo/la/toolchain/jdk/jdk9_jaxws.git","description":null}
{"name":"yocto-mirrors/github/ros2-gbp/rpyutils-release","clone_url":"https://git.codelinaro.org/clo/yocto-mirrors/github/ros2-gbp/rpyutils-release.git","description":null}
{"name":"yocto-mirrors/libepoxy","clone_url":"https://git.codelinaro.org/clo/yocto-mirrors/libepoxy.git","description":null}
{"name":"qcomlt/pkg/cogl","clone_url":"https://git.codelinaro.org/clo/qcomlt/pkg/cogl.git","description":null}
{"name":"external-ubicom/ubicom32-toolchain","clone_url":"https://git.codelinaro.org/clo/external-ubicom/ubicom32-toolchain.git","description":null}
{"name":"le/external/qtsvg","clone_url":"https://git.codelinaro.org/clo/le/external/qtsvg.git","description":null}
{"name":"qcomlt/pkg/fastrpc","clone_url":"https://git.codelinaro.org/clo/qcomlt/pkg/fastrpc.git","description":null}
{"name":"yocto-mirrors/github/hashicorp/hcl","clone_url":"https://git.codelinaro.org/clo/yocto-mirrors/github/hashicorp/hcl.git","description":null}
{"name":"la/platform/external/rust/crates/fallible-iterator","clone_url":"https://git.codelinaro.org/clo/la/platform/external/rust/crates/fallible-iterator.git","description":null}
{"name":"la/platform/vendor/qcom/cobalt_32","clone_url":"https://git.codelinaro.org/clo/la/platform/vendor/qcom/cobalt_32.git","description":null}
{"name":"yocto-mirrors/github/google/go-dap","clone_url":"https://git.codelinaro.org/clo/yocto-mirrors/github/google/go-dap.git","description":null}
{"name":"le/meta-qcom-abota","clone_url":"https://git.codelinaro.org/clo/le/meta-qcom-abota.git","description":null}
{"name":"qsdk/oss/container/container_apis","clone_url":"https://git.codelinaro.org/clo/qsdk/oss/container/container_apis.git","description":null}
{"name":"qsdk/libwebsockets","clone_url":"https://git.codelinaro.org/clo/qsdk/libwebsockets.git","description":null}
{"name":"la/platform/external/chromium_org/third_party/openmax_dl","clone_url":"https://git.codelinaro.org/clo/la/platform/external/chromium_org/third_party/openmax_dl.git","description":null}
{"name":"lc/external/github.com/intel/tinycbor","clone_url":"https://git.codelinaro.org/clo/lc/external/github.com/intel/tinycbor.git","description":null}
{"name":"la/platform/prebuilts/gradle-plugin","clone_url":"https://git.codelinaro.org/clo/la/platform/prebuilts/gradle-plugin.git","description":null}
{"name":"la/platform/vendor/qcom/msmnileau_gvmq_s_u","clone_url":"https://git.codelinaro.org/clo/la/platform/vendor/qcom/msmnileau_gvmq_s_u.git","description":null}
{"name":"yocto-mirrors/exp","clone_url":"https://git.codelinaro.org/clo/yocto-mirrors/exp.git","description":null}
{"name":"la/platform/external/markdown","clone_url":"https://git.codelinaro.org/clo/la/platform/external/markdown.git","description":null}
{"name":"lc/external/libphonenumber/resources","clone_url":"https://git.codelinaro.org/clo/lc/external/libphonenumber/resources.git","description":null}
{"name":"la/platform/vendor/opensource/mmrm-driver-test","clone_url":"https://git.codelinaro.org/clo/la/platform/vendor/opensource/mmrm-driver-test.git","description":null}
{"name":"lc/external/github.com/googlecloudplatform/compute-image-packages","clone_url":"https://git.codelinaro.org/clo/lc/external/github.com/googlecloudplatform/compute-image-packages.git","description":null}
{"name":"la/platform/external/boost-submodules/numeric/ublas","clone_url":"https://git.codelinaro.org/clo/la/platform/external/boost-submodules/numeric/ublas.git","description":null}
{"name":"le/ca-certificates","clone_url":"https://git.codelinaro.org/clo/le/ca-certificates.git","description":null}
{"name":"la/external/github.com/quic-qrb-ros/qrb_ros_samples/sample_apriltag","clone_url":"https://git.codelinaro.org/clo/la/external/github.com/quic-qrb-ros/qrb_ros_samples/sample_apriltag.git","description":null}
{"name":"la/platform/external/rust/crates/xml-rs","clone_url":"https://git.codelinaro.org/clo/la/platform/external/rust/crates/xml-rs.git","description":null}
{"name":"testproject/platform/external/proguard","clone_url":"https://git.codelinaro.org/clo/testproject/platform/external/proguard.git","description":null}
{"name":"la/platform/hardware/st/secure_element2","clone_url":"https://git.codelinaro.org/clo/la/platform/hardware/st/secure_element2.git","description":null}
{"name":"lc/webm/webm-dash-javascript","clone_url":"https://git.codelinaro.org/clo/lc/webm/webm-dash-javascript.git","description":null}
{"name":"la/ernel/devices/google/eos","clone_url":"https://git.codelinaro.org/clo/la/ernel/devices/google/eos.git","description":null}
{"name":"la/platform/vendor/qcom/msm7627a","clone_url":"https://git.codelinaro.org/clo/la/platform/vendor/qcom/msm7627a.git","description":null}
{"name":"la/platform/external/oss-fuzz","clone_url":"https://git.codelinaro.org/clo/la/platform/external/oss-fuzz.git","description":null}
{"name":"la/platform/vendor/qcom/opensource/bt-external","clone_url":"https://git.codelinaro.org/clo/la/platform/vendor/qcom/opensource/bt-external.git","description":null}
{"name":"la/platform/external/mesa3d","clone_url":"https://git.codelinaro.org/clo/la/platform/external/mesa3d.git","description":null}
{"name":"la/platform/external/mockwebserver","clone_url":"https://git.codelinaro.org/clo/la/platform/external/mockwebserver.git","description":null}
{"name":"la/toolchain/prebuilts/ndk/r13","clone_url":"https://git.codelinaro.org/clo/la/toolchain/prebuilts/ndk/r13.git","description":null}
{"name":"la/platform/external/boost-submodules/move","clone_url":"https://git.codelinaro.org/clo/la/platform/external/boost-submodules/move.git","description":null}
{"name":"la/platform/external/go-subcommands","clone_url":"https://git.codelinaro.org/clo/la/platform/external/go-subcommands.git","description":null}
{"name":"qsdk/platform/vendor/qcom-opensource/data-kernel","clone_url":"https://git.codelinaro.org/clo/qsdk/platform/vendor/qcom-opensource/data-kernel.git","description":null}
{"name":"la/device/google/bramble-sepolicy","clone_url":"https://git.codelinaro.org/clo/la/device/google/bramble-sepolicy.git","description":null}
{"name":"la/platform/external/error_prone","clone_url":"https://git.codelinaro.org/clo/la/platform/external/error_prone.git","description":null}
{"name":"qsdk/qsdk/qca/src/container_apis","clone_url":"https://git.codelinaro.org/clo/qsdk/qsdk/qca/src/container_apis.git","description":null}
{"name":"la/kernel/google-modules/touch/goodix_touch","clone_url":"https://git.codelinaro.org/clo/la/kernel/google-modules/touch/goodix_touch.git","description":null}
{"name":"yocto-mirrors/github/agext/levenshtein","clone_url":"https://git.codelinaro.org/clo/yocto-mirrors/github/agext/levenshtein.git","description":null}
{"name":"lc/infra/third_party/appengine-pipeline","clone_url":"https://git.codelinaro.org/clo/lc/infra/third_party/appengine-pipeline.git","description":null}
{"name":"qsdk/system/openwrt/feeds/packages","clone_url":"https://git.codelinaro.org/clo/qsdk/system/openwrt/feeds/packages.git","description":null}
{"name":"testproject/device/generic/qemu","clone_url":"https://git.codelinaro.org/clo/testproject/device/generic/qemu.git","description":null}
{"name":"yocto-mirrors/github/ros2-gbp/ament_cmake-release","clone_url":"https://git.codelinaro.org/clo/yocto-mirrors/github/ros2-gbp/ament_cmake-release.git","description":null}
{"name":"testproject/platform/frameworks/wilhelm","clone_url":"https://git.codelinaro.org/clo/testproject/platform/frameworks/wilhelm.git","description":null}
{"name":"qsdk/wifi/iw-patches-oss","clone_url":"https://git.codelinaro.org/clo/qsdk/wifi/iw-patches-oss.git","description":null}
{"name":"femto5g/lldp/meta-browser","clone_url":"https://git.codelinaro.org/clo/femto5g/lldp/meta-browser.git","description":null}
{"name":"la/platform/external/boost-submodules/auto_index","clone_url":"https://git.codelinaro.org/clo/la/platform/external/boost-submodules/auto_index.git","description":null}
{"name":"la/platform/packages/apps/Browser2","clone_url":"https://git.codelinaro.org/clo/la/platform/packages/apps/Browser2.git","description":null}
{"name":"la/device/moto/stingray","clone_url":"https://git.codelinaro.org/clo/la/device/moto/stingray.git","description":null}
{"name":"femto5g/oss/lklm/qca-nss-ecm","clone_url":"https://git.codelinaro.org/clo/femto5g/oss/lklm/qca-nss-ecm.git","description":null}
{"name":"la/platform/external/rust/crates/tracing-subscriber","clone_url":"https://git.codelinaro.org/clo/la/platform/external/rust/crates/tracing-subscriber.git","description":null}
{"name":"qsdk/linux-firmware","clone_url":"https://git.codelinaro.org/clo/qsdk/linux-firmware.git","description":null}
{"name":"le/meta-qti-auto-sepolicy","clone_url":"https://git.codelinaro.org/clo/le/meta-qti-auto-sepolicy.git","description":null}
{"name":"yocto-mirrors/github/hailocab/go-hostpool","clone_url":"https://git.codelinaro.org/clo/yocto-mirrors/github/hailocab/go-hostpool.git","description":null}
{"name":"la/platform/external/rust/crates/zerocopy","clone_url":"https://git.codelinaro.org/clo/la/platform/external/rust/crates/zerocopy.git","description":null}
{"name":"yocto-mirrors/github/tonistiigi/vt100","clone_url":"https://git.codelinaro.org/clo/yocto-mirrors/github/tonistiigi/vt100.git","description":null}
{"name":"yocto-mirrors/github/quic-qrb-ros/qrb_ros_video","clone_url":"https://git.codelinaro.org/clo/yocto-mirrors/github/quic-qrb-ros/qrb_ros_video.git","description":null}
{"name":"le-kernel-changes-for-mdm-9x50-atlas-modem/patches","clone_url":"https://git.codelinaro.org/clo/le-kernel-changes-for-mdm-9x50-atlas-modem/patches.git","description":null}
{"name":"yocto-mirrors/init-system-helpers","clone_url":"https://git.codelinaro.org/clo/yocto-mirrors/init-system-helpers.git","description":null}
{"name":"la/platform/external/ml_dtypes","clone_url":"https://git.codelinaro.org/clo/la/platform/external/ml_dtypes.git","description":null}
{"name":"la/platform/vendor/qcom-opensource/iot-core-oss","clone_url":"https://git.codelinaro.org/clo/la/platform/vendor/qcom-opensource/iot-core-oss.git","description":null}
{"name":"testproject/platform/hardware/st/secure_element","clone_url":"https://git.codelinaro.org/clo/testproject/platform/hardware/st/secure_element.git","description":null}
{"name":"la/platform/external/boost-submodules/integer","clone_url":"https://git.codelinaro.org/clo/la/platform/external/boost-submodules/integer.git","description":null}
{"name":"la/platform/external/jline","clone_url":"https://git.codelinaro.org/clo/la/platform/external/jline.git","description":null}
{"name":"la/platform/packages/services/NetworkRecommendation","clone_url":"https://git.codelinaro.org/clo/la/platform/packages/services/NetworkRecommendation.git","description":null}
{"name":"lc/external/github.com/google/dart-gl","clone_url":"https://git.codelinaro.org/clo/lc/external/github.com/google/dart-gl.git","description":null}
{"name":"le/meta-qti-eap-langdale","clone_url":"https://git.codelinaro.org/clo/le/meta-qti-eap-langdale.git","description":null}
{"name":"le/qcom-opensource/mdm-init","clone_url":"https://git.codelinaro.org/clo/le/qcom-opensource/mdm-init.git","description":null}
{"name":"la/platform/external/volley","clone_url":"https://git.codelinaro.org/clo/la/platform/external/volley.git","description":null}
{"name":"la/platform/external/jetbrains/intellij-rust","clone_url":"https://git.codelinaro.org/clo/la/platform/external/jetbrains/intellij-rust.git","description":null}
{"name":"la/platform/vendor/qcom/thorium_64","clone_url":"https://git.codelinaro.org/clo/la/platform/vendor/qcom/thorium_64.git","description":null}
{"name":"la/platform/external/accessibility-test-framework","clone_url":"https://git.codelinaro.org/clo/la/platform/external/accessibility-test-framework.git","description":null}
{"name":"la/platform/packages/modules/Bluetooth","clone_url":"https://git.codelinaro.org/clo/la/platform/packages/modules/Bluetooth.git","description":null}
{"name":"le/external/yoctoproject.org/poky","clone_url":"https://git.codelinaro.org/clo/le/external/yoctoproject.org/poky.git","description":null}
{"name":"la/platform/bootable/deprecated-ota","clone_url":"https://git.codelinaro.org/clo/la/platform/bootable/deprecated-ota.git","description":null}
{"name":"la/device/google/crosshatch-kernel","clone_url":"https://git.codelinaro.org/clo/la/device/google/crosshatch-kernel.git","description":null}
{"name":"la/platform/external/rust/crates/jni","clone_url":"https://git.codelinaro.org/clo/la/platform/external/rust/crates/jni.git","description":null}
{"name":"la/platform/vendor/opensource/synx-kernel","clone_url":"https://git.codelinaro.org/clo/la/platform/vendor/opensource/synx-kernel.git","description":null}
{"name":"testproject/platform/external/jsilver","clone_url":"https://git.codelinaro.org/clo/testproject/platform/external/jsilver.git","description":null}
{"name":"la/platform/packages/apps/SnapdragonLauncher","clone_url":"https://git.codelinaro.org/clo/la/platform/packages/apps/SnapdragonLauncher.git","description":null}
{"name":"la/platform/system/memory/libdmabufheap","clone_url":"https://git.codelinaro.org/clo/la/platform/system/memory/libdmabufheap.git","description":null}
{"name":"la/device/moto/common","clone_url":"https://git.codelinaro.org/clo/la/device/moto/common.git","description":null}
{"name":"testproject/platform/external/python/dateutil","clone_url":"https://git.codelinaro.org/clo/testproject/platform/external/python/dateutil.git","description":null}
{"name":"la/platform/vendor/qcom/anorak","clone_url":"https://git.codelinaro.org/clo/la/platform/vendor/qcom/anorak.git","description":null}
{"name":"yocto-mirrors/github/tencent/ncnn","clone_url":"https://git.codelinaro.org/clo/yocto-mirrors/github/tencent/ncnn.git","description":null}
{"name":"la/platform/external/compose-hero-benchmarks/pokedex-compose","clone_url":"https://git.codelinaro.org/clo/la/platform/external/compose-hero-benchmarks/pokedex-compose.git","description":null}
{"name":"qrdk/rdkcentral/DHCPManager","clone_url":"https://git.codelinaro.org/clo/qrdk/rdkcentral/DHCPManager.git","description":null}
{"name":"la/platform/prebuilts/clang/darwin-x86/3.2","clone_url":"https://git.codelinaro.org/clo/la/platform/prebuilts/clang/darwin-x86/3.2.git","description":null}
{"name":"la/platform/external/gentoo/integration","clone_url":"https://git.codelinaro.org/clo/la/platform/external/gentoo/integration.git","description":null}
{"name":"la/platform/external/marisa-trie","clone_url":"https://git.codelinaro.org/clo/la/platform/external/marisa-trie.git","description":null}
{"name":"lc/external/github.com/dart-lang/source_maps","clone_url":"https://git.codelinaro.org/clo/lc/external/github.com/dart-lang/source_maps.git","description":null}
{"name":"la/platform/external/iosched","clone_url":"https://git.codelinaro.org/clo/la/platform/external/iosched.git","description":null}
{"name":"la/platform/system/tools/bpt","clone_url":"https://git.codelinaro.org/clo/la/platform/system/tools/bpt.git","description":null}
{"name":"yocto-mirrors/logrus","clone_url":"https://git.codelinaro.org/clo/yocto-mirrors/logrus.git","description":null}
{"name":"atlas7-automotive-linux/kernel/modules/sgx-km","clone_url":"https://git.codelinaro.org/clo/atlas7-automotive-linux/kernel/modules/sgx-km.git","description":null}
{"name":"yocto-mirrors/github/skratchdot/open-golang","clone_url":"https://git.codelinaro.org/clo/yocto-mirrors/github/skratchdot/open-golang.git","description":null}
{"name":"testproject/platform/external/opencensus-java","clone_url":"https://git.codelinaro.org/clo/testproject/platform/external/opencensus-java.git","description":null}
{"name":"la/platform/external/effcee","clone_url":"https://git.codelinaro.org/clo/la/platform/external/effcee.git","description":null}
{"name":"la/platform/external/rust/crates/quiche","clone_url":"https://git.codelinaro.org/clo/la/platform/external/rust/crates/quiche.git","description":null}
{"name":"le/AGL/meta-agl-demo","clone_url":"https://git.codelinaro.org/clo/le/AGL/meta-agl-demo.git","description":null}
{"name":"la/platform/frameworks/multidex","clone_url":"https://git.codelinaro.org/clo/la/platform/frameworks/multidex.git","description":null}
{"name":"le/meta-qti-linuxsecurity","clone_url":"https://git.codelinaro.org/clo/le/meta-qti-linuxsecurity.git","description":null}
{"name":"yocto-mirrors/github/unfs3/unfs3","clone_url":"https://git.codelinaro.org/clo/yocto-mirrors/github/unfs3/unfs3.git","description":null}
{"name":"le/platform/vendor/qcom-opensource/robot-control","clone_url":"https://git.codelinaro.org/clo/le/platform/vendor/qcom-opensource/robot-control.git","description":null}
{"name":"la/platform/tools/treble","clone_url":"https://git.codelinaro.org/clo/la/platform/tools/treble.git","description":null}
{"name":"la/platform/external/mock","clone_url":"https://git.codelinaro.org/clo/la/platform/external/mock.git","description":null}
{"name":"la/platform/vendor/qcom/monaco_group/codeaurora/dpm","clone_url":"https://git.codelinaro.org/clo/la/platform/vendor/qcom/monaco_group/codeaurora/dpm.git","description":null}
{"name":"la/trusty/host/aidl","clone_url":"https://git.codelinaro.org/clo/la/trusty/host/aidl.git","description":null}
{"name":"la/platform/system/libprocinfo","clone_url":"https://git.codelinaro.org/clo/la/platform/system/libprocinfo.git","description":null}
{"name":"yocto-mirrors/github/oneapi-src/oneTBB","clone_url":"https://git.codelinaro.org/clo/yocto-mirrors/github/oneapi-src/oneTBB.git","description":null}
{"name":"lc/external_repo","clone_url":"https://git.codelinaro.org/clo/lc/external_repo.git","description":null}
{"name":"qsdk/oss/upstream/libiota","clone_url":"https://git.codelinaro.org/clo/qsdk/oss/upstream/libiota.git","description":null}
{"name":"ype/external/github.com/meta-clang","clone_url":"https://git.codelinaro.org/clo/ype/external/github.com/meta-clang.git","description":null}
{"name":"le/meta-qti-ss-mgr","clone_url":"https://git.codelinaro.org/clo/le/meta-qti-ss-mgr.git","description":null}
{"name":"qrdk/yocto-kernel-tools","clone_url":"https://git.codelinaro.org/clo/qrdk/yocto-kernel-tools.git","description":null}
{"name":"external-wlan/prima","clone_url":"https://git.codelinaro.org/clo/external-wlan/prima.git","description":null}
{"name":"yocto-mirrors/rust-hello-world","clone_url":"https://git.codelinaro.org/clo/yocto-mirrors/rust-hello-world.git","description":null}
{"name":"qcomlt/ci/kernel","clone_url":"https://git.codelinaro.org/clo/qcomlt/ci/kernel.git","description":null}
{"name":"la/kernel_platform/external/ltp","clone_url":"https://git.codelinaro.org/clo/la/kernel_platform/external/ltp.git","description":null}
{"name":"la/platform/prebuilts/fullsdk-darwin/build-tools_group/27.0.3","clone_url":"https://git.codelinaro.org/clo/la/platform/prebuilts/fullsdk-darwin/build-tools_group/27.0.3.git","description":null}
{"name":"la/platform/packages/apps/DocumentsUI","clone_url":"https://git.codelinaro.org/clo/la/platform/packages/apps/DocumentsUI.git","description":null}
{"name":"la/device/generic/mips","clone_url":"https://git.codelinaro.org/clo/la/device/generic/mips.git","description":null}
{"name":"rdkb/rdkb/components/generic/notify_comp","clone_url":"https://git.codelinaro.org/clo/rdkb/rdkb/components/generic/notify_comp.git","description":null}
{"name":"le/platform/vendor/qcom-opensource/cv2x-security-aerolink-public","clone_url":"https://git.codelinaro.org/clo/le/platform/vendor/qcom-opensource/cv2x-security-aerolink-public.git","description":null}
{"name":"le/mobile-broadband/libqmi","clone_url":"https://git.codelinaro.org/clo/le/mobile-broadband/libqmi.git","description":null}
{"name":"qsdk/hyfi/qca-hyfi-qdisc","clone_url":"https://git.codelinaro.org/clo/qsdk/hyfi/qca-hyfi-qdisc.git","description":null}
{"name":"lc/external/github.com/dynamorio/drmemory","clone_url":"https://git.codelinaro.org/clo/lc/external/github.com/dynamorio/drmemory.git","description":null}
{"name":"le/ros2-gbp/rcl_logging-release","clone_url":"https://git.codelinaro.org/clo/le/ros2-gbp/rcl_logging-release.git","description":null}
{"name":"la/platform/prebuilts/protobuf","clone_url":"https://git.codelinaro.org/clo/la/platform/prebuilts/protobuf.git","description":null}
{"name":"la/toolchain/gcc","clone_url":"https://git.codelinaro.org/clo/la/toolchain/gcc.git","description":null}
{"name":"le/platform/hardware/qcom/thermal","clone_url":"https://git.codelinaro.org/clo/le/platform/hardware/qcom/thermal.git","description":null}
{"name":"le/platform/external/compat-wireless","clone_url":"https://git.codelinaro.org/clo/le/platform/external/compat-wireless.git","description":null}
{"name":"testproject/platform/external/parameter-framework","clone_url":"https://git.codelinaro.org/clo/testproject/platform/external/parameter-framework.git","description":null}
{"name":"femto5g/platform/hardware/libhardware","clone_url":"https://git.codelinaro.org/clo/femto5g/platform/hardware/libhardware.git","description":null}
{"name":"la/platform/vendor/qcom/bengal_515tiny_32go","clone_url":"https://git.codelinaro.org/clo/la/platform/vendor/qcom/bengal_515tiny_32go.git","description":null}
{"name":"qrdk/libnftnl","clone_url":"https://git.codelinaro.org/clo/qrdk/libnftnl.git","description":null}
{"name":"femto5g/lldp/meta-cloud-services","clone_url":"https://git.codelinaro.org/clo/femto5g/lldp/meta-cloud-services.git","description":null}
{"name":"la/platform/vendor/qcom/monaco_group/codeaurora/healthd-ext","clone_url":"https://git.codelinaro.org/clo/la/platform/vendor/qcom/monaco_group/codeaurora/healthd-ext.git","description":null}
{"name":"la/platform/external/boost-submodules/align","clone_url":"https://git.codelinaro.org/clo/la/platform/external/boost-submodules/align.git","description":null}
{"name":"la/platform/vendor/qcom-opensource/dataservices","clone_url":"https://git.codelinaro.org/clo/la/platform/vendor/qcom-opensource/dataservices.git","description":null}
{"name":"la/kernel/msm-extra_group/mmrm-devicetree","clone_url":"https://git.codelinaro.org/clo/la/kernel/msm-extra_group/mmrm-devicetree.git","description":null}
{"name":"la/platform/external/rust/crates/num_enum","clone_url":"https://git.codelinaro.org/clo/la/platform/external/rust/crates/num_enum.git","description":null}
{"name":"lc/chromiumos/platform/mist","clone_url":"https://git.codelinaro.org/clo/lc/chromiumos/platform/mist.git","description":null}
{"name":"la/device/lge/mako","clone_url":"https://git.codelinaro.org/clo/la/device/lge/mako.git","description":null}
{"name":"la/platform/hardware/ti/wlan","clone_url":"https://git.codelinaro.org/clo/la/platform/hardware/ti/wlan.git","description":null}
{"name":"le/platform/vendor/qcom-opensource/wlan/fw-api","clone_url":"https://git.codelinaro.org/clo/le/platform/vendor/qcom-opensource/wlan/fw-api.git","description":null}
{"name":"testproject/platform/hardware/nxp/nfc","clone_url":"https://git.codelinaro.org/clo/testproject/platform/hardware/nxp/nfc.git","description":null}
{"name":"la/platform/external/rust/crates/fallible-streaming-iterator","clone_url":"https://git.codelinaro.org/clo/la/platform/external/rust/crates/fallible-streaming-iterator.git","description":null}
{"name":"yocto-mirrors/github/stackexchange/wmi","clone_url":"https://git.codelinaro.org/clo/yocto-mirrors/github/stackexchange/wmi.git","description":null}
{"name":"imx-support/imx-android-10","clone_url":"https://git.codelinaro.org/clo/imx-support/imx-android-10.git","description":null}
{"name":"yocto-mirrors/github/lathiat/nss-mdns","clone_url":"https://git.codelinaro.org/clo/yocto-mirrors/github/lathiat/nss-mdns.git","description":null}
{"name":"la/platform/packages/apps/Contacts","clone_url":"https://git.codelinaro.org/clo/la/platform/packages/apps/Contacts.git","description":null}
{"name":"la/platform/hardware/google/interfaces","clone_url":"https://git.codelinaro.org/clo/la/platform/hardware/google/interfaces.git","description":null}
{"name":"le/platform/vendor/opensource/mm-drivers","clone_url":"https://git.codelinaro.org/clo/le/platform/vendor/opensource/mm-drivers.git","description":null}
{"name":"yocto-mirrors/github/ros2-gbp/cpp_polyfills-release","clone_url":"https://git.codelinaro.org/clo/yocto-mirrors/github/ros2-gbp/cpp_polyfills-release.git","description":null}
{"name":"la/platform/external/rust/crates/tokio-io-timeout","clone_url":"https://git.codelinaro.org/clo/la/platform/external/rust/crates/tokio-io-timeout.git","description":null}
{"name":"testproject/platform/system/bpfprogs","clone_url":"https://git.codelinaro.org/clo/testproject/platform/system/bpfprogs.git","description":null}
{"name":"femto5g/agl/meta-agl-devel","clone_url":"https://git.codelinaro.org/clo/femto5g/agl/meta-agl-devel.git","description":null}
{"name":"le/platform/system/extras","clone_url":"https://git.codelinaro.org/clo/le/platform/system/extras.git","description":null}
{"name":"la/platform/prebuilts/fullsdk-linux/build-tools_group/29.0.3","clone_url":"https://git.codelinaro.org/clo/la/platform/prebuilts/fullsdk-linux/build-tools_group/29.0.3.git","description":null}
{"name":"sba-patches/linux-wireless_patches","clone_url":"https://git.codelinaro.org/clo/sba-patches/linux-wireless_patches.git","description":null}
{"name":"yocto-mirrors/github/mdlayher/vsock","clone_url":"https://git.codelinaro.org/clo/yocto-mirrors/github/mdlayher/vsock.git","description":null}
{"name":"la/kernel/google-modules/lwis","clone_url":"https://git.codelinaro.org/clo/la/kernel/google-modules/lwis.git","description":null}
{"name":"qcc7xx/QCCSDK-QCC74x","clone_url":"https://git.codelinaro.org/clo/qcc7xx/QCCSDK-QCC74x.git","description":null}
{"name":"la/platform/test/mlts/benchmark","clone_url":"https://git.codelinaro.org/clo/la/platform/test/mlts/benchmark.git","description":null}
{"name":"qsdk/bridge-utils","clone_url":"https://git.codelinaro.org/clo/qsdk/bridge-utils.git","description":null}
{"name":"la/platform/packages/apps/GlobalSearch","clone_url":"https://git.codelinaro.org/clo/la/platform/packages/apps/GlobalSearch.git","description":null}
{"name":"la/platform/external/liburing","clone_url":"https://git.codelinaro.org/clo/la/platform/external/liburing.git","description":null}
{"name":"le/platform/vendor/qcom/opensource/audio-kernel-ar","clone_url":"https://git.codelinaro.org/clo/le/platform/vendor/qcom/opensource/audio-kernel-ar.git","description":null}
{"name":"le/platform/vendor/qcom-opensource/audio-awe-service","clone_url":"https://git.codelinaro.org/clo/le/platform/vendor/qcom-opensource/audio-awe-service.git","description":null}
{"name":"lc/chromium/llvm-project/llvm/lib/Fuzzer","clone_url":"https://git.codelinaro.org/clo/lc/chromium/llvm-project/llvm/lib/Fuzzer.git","description":null}
{"name":"external-wlan/qca-wifi-host-cmn","clone_url":"https://git.codelinaro.org/clo/external-wlan/qca-wifi-host-cmn.git","description":null}
{"name":"lc/infra/tricium","clone_url":"https://git.codelinaro.org/clo/lc/infra/tricium.git","description":null}
{"name":"la/platform/external/connectedappssdk","clone_url":"https://git.codelinaro.org/clo/la/platform/external/connectedappssdk.git","description":null}
{"name":"la/tools/aospstats","clone_url":"https://git.codelinaro.org/clo/la/tools/aospstats.git","description":null}
{"name":"la/platform/packages/modules/MediaSwCodec","clone_url":"https://git.codelinaro.org/clo/la/platform/packages/modules/MediaSwCodec.git","description":null}
{"name":"qrdk/file","clone_url":"https://git.codelinaro.org/clo/qrdk/file.git","description":null}
{"name":"la/platform/external/rust/crates/winapi-util","clone_url":"https://git.codelinaro.org/clo/la/platform/external/rust/crates/winapi-util.git","description":null}
{"name":"la/platform/external/python/liboqs-python","clone_url":"https://git.codelinaro.org/clo/la/platform/external/python/liboqs-python.git","description":null}
{"name":"la/platform/external/rust/crates/cfg-if","clone_url":"https://git.codelinaro.org/clo/la/platform/external/rust/crates/cfg-if.git","description":null}
{"name":"la/platform/vendor/qcom-opensource/recovery-ext","clone_url":"https://git.codelinaro.org/clo/la/platform/vendor/qcom-opensource/recovery-ext.git","description":null}
{"name":"qcomlt/ci/staging/linux","clone_url":"https://git.codelinaro.org/clo/qcomlt/ci/staging/linux.git","description":""}
{"name":"la/platform/external/python/oauth2client","clone_url":"https://git.codelinaro.org/clo/la/platform/external/python/oauth2client.git","description":null}
{"name":"le/libxcrypt","clone_url":"https://git.codelinaro.org/clo/le/libxcrypt.git","description":null}
{"name":"la/platform/external/gcc-demangle","clone_url":"https://git.codelinaro.org/clo/la/platform/external/gcc-demangle.git","description":null}
{"name":"la/platform/external/boost-submodules/numeric_conversion","clone_url":"https://git.codelinaro.org/clo/la/platform/external/boost-submodules/numeric_conversion.git","description":null}
{"name":"la/platform/external/oj-libjdwp","clone_url":"https://git.codelinaro.org/clo/la/platform/external/oj-libjdwp.git","description":null}
{"name":"la/platform/vendor/qcom-opensource/crash","clone_url":"https://git.codelinaro.org/clo/la/platform/vendor/qcom-opensource/crash.git","description":null}
{"name":"testproject/platform/frameworks/opt/net/wifi","clone_url":"https://git.codelinaro.org/clo/testproject/platform/frameworks/opt/net/wifi.git","description":null}
{"name":"wiki2022/notice","clone_url":"https://git.codelinaro.org/clo/wiki2022/notice.git","description":null}
{"name":"qrdk/libxcrypt","clone_url":"https://git.codelinaro.org/clo/qrdk/libxcrypt.git","description":null}
{"name":"la/platform/prebuilts/gcc/darwin-x86/host/headers","clone_url":"https://git.codelinaro.org/clo/la/platform/prebuilts/gcc/darwin-x86/host/headers.git","description":null}
{"name":"sba-patches/bt_patches","clone_url":"https://git.codelinaro.org/clo/sba-patches/bt_patches.git","description":null}
{"name":"linux-kernel/patches","clone_url":"https://git.codelinaro.org/clo/linux-kernel/patches.git","description":null}
{"name":"la/platform/external/libiota","clone_url":"https://git.codelinaro.org/clo/la/platform/external/libiota.git","description":null}
{"name":"la/platform/external/neven","clone_url":"https://git.codelinaro.org/clo/la/platform/external/neven.git","description":null}
{"name":"la/platform/external/rust/crates/idna","clone_url":"https://git.codelinaro.org/clo/la/platform/external/rust/crates/idna.git","description":null}
{"name":"la/platform/external/rust/crates/plotters-svg","clone_url":"https://git.codelinaro.org/clo/la/platform/external/rust/crates/plotters-svg.git","description":null}
{"name":"la/toolchain/jdk/jdk9_corba","clone_url":"https://git.codelinaro.org/clo/la/toolchain/jdk/jdk9_corba.git","description":null}
{"name":"le/platform/vendor/qcom-opensource/sensing-hub","clone_url":"https://git.codelinaro.org/clo/le/platform/vendor/qcom-opensource/sensing-hub.git","description":null}
{"name":"la/platform/external/rust/crates/ucs2","clone_url":"https://git.codelinaro.org/clo/la/platform/external/rust/crates/ucs2.git","description":null}
{"name":"lc/external/github.com/jmoiron/sqlx","clone_url":"https://git.codelinaro.org/clo/lc/external/github.com/jmoiron/sqlx.git","description":null}
{"name":"la/platform/vendor/qcom/neo","clone_url":"https://git.codelinaro.org/clo/la/platform/vendor/qcom/neo.git","description":null}
{"name":"le/qcom-device-config","clone_url":"https://git.codelinaro.org/clo/le/qcom-device-config.git","description":null}
{"name":"le/googleapis/google-cloud-go","clone_url":"https://git.codelinaro.org/clo/le/googleapis/google-cloud-go.git","description":null}
{"name":"la/platform/external/rust/crates/octets","clone_url":"https://git.codelinaro.org/clo/la/platform/external/rust/crates/octets.git","description":null}
{"name":"la/platform/external/google-cloud-go","clone_url":"https://git.codelinaro.org/clo/la/platform/external/google-cloud-go.git","description":null}
{"name":"qrdk/code.rdkcentral.com/rdkb/components/opensource/ccsp/hal_group/rdk-wifi-hal","clone_url":"https://git.codelinaro.org/clo/qrdk/code.rdkcentral.com/rdkb/components/opensource/ccsp/hal_group/rdk-wifi-hal.git","description":null}
{"name":"le/libnetconf2","clone_url":"https://git.codelinaro.org/clo/le/libnetconf2.git","description":null}
{"name":"la/platform/external/rust/crates/lazy_static","clone_url":"https://git.codelinaro.org/clo/la/platform/external/rust/crates/lazy_static.git","description":null}
{"name":"la/platform/external/rust/crates/ron","clone_url":"https://git.codelinaro.org/clo/la/platform/external/rust/crates/ron.git","description":null}
{"name":"la/platform/vendor/qcom-opensource/ecosw","clone_url":"https://git.codelinaro.org/clo/la/platform/vendor/qcom-opensource/ecosw.git","description":null}
{"name":"le/AGL/apps/agl-service-bluetooth","clone_url":"https://git.codelinaro.org/clo/le/AGL/apps/agl-service-bluetooth.git","description":null}
{"name":"la/platform/external/libevent","clone_url":"https://git.codelinaro.org/clo/la/platform/external/libevent.git","description":null}
{"name":"le/leethomason/tinyxml2","clone_url":"https://git.codelinaro.org/clo/le/leethomason/tinyxml2.git","description":null}
{"name":"la/platform/vendor/nxp/opensource/halimpl","clone_url":"https://git.codelinaro.org/clo/la/platform/vendor/nxp/opensource/halimpl.git","description":null}
{"name":"la/platform/external/OpenCSD","clone_url":"https://git.codelinaro.org/clo/la/platform/external/OpenCSD.git","description":null}
{"name":"la/platform/external/python/httplib2","clone_url":"https://git.codelinaro.org/clo/la/platform/external/python/httplib2.git","description":null}
{"name":"le/platform/vendor/qcom-opensource/ts_firmware","clone_url":"https://git.codelinaro.org/clo/le/platform/vendor/qcom-opensource/ts_firmware.git","description":null}
{"name":"le/platform/vendor/opensource/touch-drivers","clone_url":"https://git.codelinaro.org/clo/le/platform/vendor/opensource/touch-drivers.git","description":null}
{"name":"yocto-mirrors/github/nhorman/rng-tools","clone_url":"https://git.codelinaro.org/clo/yocto-mirrors/github/nhorman/rng-tools.git","description":null}
{"name":"le/platform/vendor/qcom-opensource/sail-mailbox-devicetree","clone_url":"https://git.codelinaro.org/clo/le/platform/vendor/qcom-opensource/sail-mailbox-devicetree.git","description":null}
{"name":"le/meta-ivi/meta-ivi-test","clone_url":"https://git.codelinaro.org/clo/le/meta-ivi/meta-ivi-test.git","description":null}
{"name":"la/toolchain/perl","clone_url":"https://git.codelinaro.org/clo/la/toolchain/perl.git","description":null}
{"name":"la/platform/prebuilts/bazel/darwin-x86_64","clone_url":"https://git.codelinaro.org/clo/la/platform/prebuilts/bazel/darwin-x86_64.git","description":null}
{"name":"lc/external/github.com/sabhiram/go-gitignore","clone_url":"https://git.codelinaro.org/clo/lc/external/github.com/sabhiram/go-gitignore.git","description":null}
{"name":"yocto-mirrors/netcf","clone_url":"https://git.codelinaro.org/clo/yocto-mirrors/netcf.git","description":null}
{"name":"la/platform/vendor/qcom-opensource/mm-audio","clone_url":"https://git.codelinaro.org/clo/la/platform/vendor/qcom-opensource/mm-audio.git","description":null}
{"name":"lc/chromiumos/platform/cromo","clone_url":"https://git.codelinaro.org/clo/lc/chromiumos/platform/cromo.git","description":null}
{"name":"le/AGL/src/hvacplugin","clone_url":"https://git.codelinaro.org/clo/le/AGL/src/hvacplugin.git","description":null}
{"name":"la/platform/packages/wallpapers/Galaxy4","clone_url":"https://git.codelinaro.org/clo/la/platform/packages/wallpapers/Galaxy4.git","description":null}
{"name":"le/platform/external/update-rc.d","clone_url":"https://git.codelinaro.org/clo/le/platform/external/update-rc.d.git","description":null}
{"name":"qsdk/wifi/qca-telemetry-agent-oss","clone_url":"https://git.codelinaro.org/clo/qsdk/wifi/qca-telemetry-agent-oss.git","description":null}
{"name":"le/legatoproject/legato-3rdParty-jansson","clone_url":"https://git.codelinaro.org/clo/le/legatoproject/legato-3rdParty-jansson.git","description":null}
{"name":"la/device/linaro/bootloader/OpenPlatformPkg","clone_url":"https://git.codelinaro.org/clo/la/device/linaro/bootloader/OpenPlatformPkg.git","description":null}
{"name":"qrdk/squashfs-tools","clone_url":"https://git.codelinaro.org/clo/qrdk/squashfs-tools.git","description":null}
{"name":"testproject/platform/packages/modules/NetworkPermissionConfig","clone_url":"https://git.codelinaro.org/clo/testproject/platform/packages/modules/NetworkPermissionConfig.git","description":null}
{"name":"le/OTA/system/extras","clone_url":"https://git.codelinaro.org/clo/le/OTA/system/extras.git","description":null}
{"name":"la/platform/vendor/opensource/audio-kernel","clone_url":"https://git.codelinaro.org/clo/la/platform/vendor/opensource/audio-kernel.git","description":null}
{"name":"la/platform/external/ow2-asm","clone_url":"https://git.codelinaro.org/clo/la/platform/external/ow2-asm.git","description":null}
{"name":"lc/chromiumos/platform/dump-syms","clone_url":"https://git.codelinaro.org/clo/lc/chromiumos/platform/dump-syms.git","description":null}
{"name":"la/platform/platform_testing","clone_url":"https://git.codelinaro.org/clo/la/platform/platform_testing.git","description":null}
{"name":"la/kernel/google-modules/display_group/panels/tegu","clone_url":"https://git.codelinaro.org/clo/la/kernel/google-modules/display_group/panels/tegu.git","description":null}
{"name":"la/platform/prebuilts/manifest-merger","clone_url":"https://git.codelinaro.org/clo/la/platform/prebuilts/manifest-merger.git","description":null}
{"name":"testproject/platform/external/fec","clone_url":"https://git.codelinaro.org/clo/testproject/platform/external/fec.git","description":null}
{"name":"la/platform/vendor/nxp/opensource/libnfc_vendor_extn","clone_url":"https://git.codelinaro.org/clo/la/platform/vendor/nxp/opensource/libnfc_vendor_extn.git","description":null}
{"name":"qrdk/rdkcentral/rdkb-halif-wifi","clone_url":"https://git.codelinaro.org/clo/qrdk/rdkcentral/rdkb-halif-wifi.git","description":null}
{"name":"la/platform/vendor/qcom-opensource/qti-can-kernel","clone_url":"https://git.codelinaro.org/clo/la/platform/vendor/qcom-opensource/qti-can-kernel.git","description":null}
{"name":"le/platform/external/infralogmgr","clone_url":"https://git.codelinaro.org/clo/le/platform/external/infralogmgr.git","description":null}
{"name":"qsdk/fstools","clone_url":"https://git.codelinaro.org/clo/qsdk/fstools.git","description":null}
{"name":"la/platform/vendor/qcom/msm8916_64_LMT","clone_url":"https://git.codelinaro.org/clo/la/platform/vendor/qcom/msm8916_64_LMT.git","description":null}
{"name":"la/platform/packages/apps/Car/MultiDisplay","clone_url":"https://git.codelinaro.org/clo/la/platform/packages/apps/Car/MultiDisplay.git","description":null}
{"name":"lc/chromiumos/platform/tpm_init","clone_url":"https://git.codelinaro.org/clo/lc/chromiumos/platform/tpm_init.git","description":null}
{"name":"le-au-os/qc/components/le-frameworks.lnx/oe-recipes-oss","clone_url":"https://git.codelinaro.org/clo/le-au-os/qc/components/le-frameworks.lnx/oe-recipes-oss.git","description":null}
{"name":"la/toolchain/jdk/jdk9_hotspot","clone_url":"https://git.codelinaro.org/clo/la/toolchain/jdk/jdk9_hotspot.git","description":null}
{"name":"la/platform/external/boost-submodules/ublas","clone_url":"https://git.codelinaro.org/clo/la/platform/external/boost-submodules/ublas.git","description":null}
{"name":"testproject/platform/system/media","clone_url":"https://git.codelinaro.org/clo/testproject/platform/system/media.git","description":null}
{"name":"le/qti-conf","clone_url":"https://git.codelinaro.org/clo/le/qti-conf.git","description":null}
{"name":"la/kernel/build","clone_url":"https://git.codelinaro.org/clo/la/kernel/build.git","description":null}
{"name":"la/platform/vendor/opensource/dataipa","clone_url":"https://git.codelinaro.org/clo/la/platform/vendor/opensource/dataipa.git","description":null}
{"name":"testproject/platform/frameworks/opt/net/ethernet","clone_url":"https://git.codelinaro.org/clo/testproject/platform/frameworks/opt/net/ethernet.git","description":null}
{"name":"yocto-mirrors/oneTBB","clone_url":"https://git.codelinaro.org/clo/yocto-mirrors/oneTBB.git","description":null}
{"name":"la/device/linaro/poplar","clone_url":"https://git.codelinaro.org/clo/la/device/linaro/poplar.git","description":null}
{"name":"testproject/platform/external/easymock","clone_url":"https://git.codelinaro.org/clo/testproject/platform/external/easymock.git","description":null}
{"name":"le-au-os/platform/vendor/qcom-opensource/shortcut-fe","clone_url":"https://git.codelinaro.org/clo/le-au-os/platform/vendor/qcom-opensource/shortcut-fe.git","description":null}
{"name":"lf/b2g/platform_external_apriori","clone_url":"https://git.codelinaro.org/clo/lf/b2g/platform_external_apriori.git","description":null}
{"name":"testproject/platform/external/libtextclassifier","clone_url":"https://git.codelinaro.org/clo/testproject/platform/external/libtextclassifier.git","description":null}
{"name":"testproject/platform/external/fmtlib","clone_url":"https://git.codelinaro.org/clo/testproject/platform/external/fmtlib.git","description":null}
{"name":"la/platform/external/genext2fs","clone_url":"https://git.codelinaro.org/clo/la/platform/external/genext2fs.git","description":null}
{"name":"la/platform/external/jetbrains/intellij-kotlin","clone_url":"https://git.codelinaro.org/clo/la/platform/external/jetbrains/intellij-kotlin.git","description":null}
{"name":"la/platform/test/gots","clone_url":"https://git.codelinaro.org/clo/la/platform/test/gots.git","description":null}
{"name":"qrdk/systemd-stable","clone_url":"https://git.codelinaro.org/clo/qrdk/systemd-stable.git","description":null}
{"name":"qsdk/oss/kernel/linux-mips","clone_url":"https://git.codelinaro.org/clo/qsdk/oss/kernel/linux-mips.git","description":null}
{"name":"la/platform/system/ucontainer","clone_url":"https://git.codelinaro.org/clo/la/platform/system/ucontainer.git","description":null}
{"name":"kernel-platform-2-0-os/patches","clone_url":"https://git.codelinaro.org/clo/kernel-platform-2-0-os/patches.git","description":null}
{"name":"la/device/google/akita-sepolicy","clone_url":"https://git.codelinaro.org/clo/la/device/google/akita-sepolicy.git","description":null}
{"name":"la/device/pifoundation/rpi3","clone_url":"https://git.codelinaro.org/clo/la/device/pifoundation/rpi3.git","description":null}
{"name":"yocto-mirrors/github/shibumi/go-pathspec","clone_url":"https://git.codelinaro.org/clo/yocto-mirrors/github/shibumi/go-pathspec.git","description":null}
{"name":"testproject/platform/external/libunwind","clone_url":"https://git.codelinaro.org/clo/testproject/platform/external/libunwind.git","description":null}
{"name":"la/platform/external/rust/crates/serde_json","clone_url":"https://git.codelinaro.org/clo/la/platform/external/rust/crates/serde_json.git","description":null}
{"name":"yocto-mirrors/procps","clone_url":"https://git.codelinaro.org/clo/yocto-mirrors/procps.git","description":null}
{"name":"la/device/linaro/bootloader/arm-trusted-firmware","clone_url":"https://git.codelinaro.org/clo/la/device/linaro/bootloader/arm-trusted-firmware.git","description":null}
{"name":"la/platform/prebuilts/gcc/linux-x86/x86/i686-android-linux-4.4.3","clone_url":"https://git.codelinaro.org/clo/la/platform/prebuilts/gcc/linux-x86/x86/i686-android-linux-4.4.3.git","description":null}
{"name":"la/platform/hardware/qcom/msm8x84","clone_url":"https://git.codelinaro.org/clo/la/platform/hardware/qcom/msm8x84.git","description":null}
{"name":"la/platform/external/boost-submodules/spirit","clone_url":"https://git.codelinaro.org/clo/la/platform/external/boost-submodules/spirit.git","description":null}
{"name":"la/platform/vendor/qcom-opensource/hsi2s-kernel","clone_url":"https://git.codelinaro.org/clo/la/platform/vendor/qcom-opensource/hsi2s-kernel.git","description":null}
{"name":"le-au-os/platform/vendor/qcom/wlan","clone_url":"https://git.codelinaro.org/clo/le-au-os/platform/vendor/qcom/wlan.git","description":null}
{"name":"la/kernel/msm-modules_group/securemsm","clone_url":"https://git.codelinaro.org/clo/la/kernel/msm-modules_group/securemsm.git","description":null}
{"name":"la/platform/libcore","clone_url":"https://git.codelinaro.org/clo/la/platform/libcore.git","description":null}
{"name":"la/platform/vendor/qcom-opensource/vibrator","clone_url":"https://git.codelinaro.org/clo/la/platform/vendor/qcom-opensource/vibrator.git","description":null}
{"name":"la/platform/external/gradle-profiler","clone_url":"https://git.codelinaro.org/clo/la/platform/external/gradle-profiler.git","description":null}
{"name":"qcomlt/ci/test","clone_url":"https://git.codelinaro.org/clo/qcomlt/ci/test.git","description":null}
{"name":"la/platform/prebuilts/asuite","clone_url":"https://git.codelinaro.org/clo/la/platform/prebuilts/asuite.git","description":null}
{"name":"testproject/platform/external/piex","clone_url":"https://git.codelinaro.org/clo/testproject/platform/external/piex.git","description":null}
{"name":"qsdk/oss/lklm/nss-drv","clone_url":"https://git.codelinaro.org/clo/qsdk/oss/lklm/nss-drv.git","description":null}
{"name":"la/platform/external/clang_35a","clone_url":"https://git.codelinaro.org/clo/la/platform/external/clang_35a.git","description":null}
{"name":"la/platform/vendor/qcom/monaco_group/codeaurora/bluetooth","clone_url":"https://git.codelinaro.org/clo/la/platform/vendor/qcom/monaco_group/codeaurora/bluetooth.git","description":null}
{"name":"la/platform/external/boost-submodules/multi_index","clone_url":"https://git.codelinaro.org/clo/la/platform/external/boost-submodules/multi_index.git","description":null}
{"name":"yocto-mirrors/github/jbeder/yaml-cpp","clone_url":"https://git.codelinaro.org/clo/yocto-mirrors/github/jbeder/yaml-cpp.git","description":null}
{"name":"imx-support/imx-linux-sumo","clone_url":"https://git.codelinaro.org/clo/imx-support/imx-linux-sumo.git","description":null}
{"name":"yocto-mirrors/github/libinput/libinput","clone_url":"https://git.codelinaro.org/clo/yocto-mirrors/github/libinput/libinput.git","description":null}
{"name":"le/ros2-gbp/examples-release","clone_url":"https://git.codelinaro.org/clo/le/ros2-gbp/examples-release.git","description":null}
{"name":"yocto-mirrors/ncnn","clone_url":"https://git.codelinaro.org/clo/yocto-mirrors/ncnn.git","description":null}
{"name":"la/euvirt/os/unikraft/app-helloworld","clone_url":"https://git.codelinaro.org/clo/la/euvirt/os/unikraft/app-helloworld.git","description":null}
{"name":"lc/external/github.com/intel/ARM_NEON_2_x86_SSE","clone_url":"https://git.codelinaro.org/clo/lc/external/github.com/intel/ARM_NEON_2_x86_SSE.git","description":null}
{"name":"la/platform/hardware/intel/common/bd_prov","clone_url":"https://git.codelinaro.org/clo/la/platform/hardware/intel/common/bd_prov.git","description":null}
{"name":"testproject/platform/packages/providers/DownloadProvider","clone_url":"https://git.codelinaro.org/clo/testproject/platform/packages/providers/DownloadProvider.git","description":null}
{"name":"le/AGL/apps/phone","clone_url":"https://git.codelinaro.org/clo/le/AGL/apps/phone.git","description":null}
{"name":"la/platform/hardware/nxp/nxp_mcu_loader","clone_url":"https://git.codelinaro.org/clo/la/platform/hardware/nxp/nxp_mcu_loader.git","description":null}
{"name":"qsdk/gstreamer-1.14.4/gst-libav","clone_url":"https://git.codelinaro.org/clo/qsdk/gstreamer-1.14.4/gst-libav.git","description":null}
{"name":"la/device/google/bluejay-kernels/5.10","clone_url":"https://git.codelinaro.org/clo/la/device/google/bluejay-kernels/5.10.git","description":null}
{"name":"lc/external/github.com/khronosgroup/OpenCL-CTS","clone_url":"https://git.codelinaro.org/clo/lc/external/github.com/khronosgroup/OpenCL-CTS.git","description":null}
{"name":"le/timezone-boundary-builder","clone_url":"https://git.codelinaro.org/clo/le/timezone-boundary-builder.git","description":null}
{"name":"lc/chromiumos/third_party/espeak-ng","clone_url":"https://git.codelinaro.org/clo/lc/chromiumos/third_party/espeak-ng.git","description":null}
{"name":"testproject/platform/packages/apps/Bluetooth","clone_url":"https://git.codelinaro.org/clo/testproject/platform/packages/apps/Bluetooth.git","description":null}
{"name":"la/platform/vendor/qcom-opensource/wigig","clone_url":"https://git.codelinaro.org/clo/la/platform/vendor/qcom-opensource/wigig.git","description":null}
{"name":"la/platform/hardware/bsp/kernel/raspberrypi/pi-v4.1","clone_url":"https://git.codelinaro.org/clo/la/platform/hardware/bsp/kernel/raspberrypi/pi-v4.1.git","description":null}
{"name":"la/platform/prebuilts/fullsdk-darwin/cmdline-tools","clone_url":"https://git.codelinaro.org/clo/la/platform/prebuilts/fullsdk-darwin/cmdline-tools.git","description":null}
{"name":"la/platform/external/boost-submodules/vmd","clone_url":"https://git.codelinaro.org/clo/la/platform/external/boost-submodules/vmd.git","description":null}
{"name":"la/platform/external/Microsoft-unittest-cpp","clone_url":"https://git.codelinaro.org/clo/la/platform/external/Microsoft-unittest-cpp.git","description":null}
{"name":"femto/oss/lklm/nss-crypto","clone_url":"https://git.codelinaro.org/clo/femto/oss/lklm/nss-crypto.git","description":null}
{"name":"la/platform/tools/external/go/src/github.com/golang/protobuf","clone_url":"https://git.codelinaro.org/clo/la/platform/tools/external/go/src/github.com/golang/protobuf.git","description":null}
{"name":"sba-patches/qwrap_patches","clone_url":"https://git.codelinaro.org/clo/sba-patches/qwrap_patches.git","description":null}
{"name":"la/platform/external/rust/crates/android-tzdata","clone_url":"https://git.codelinaro.org/clo/la/platform/external/rust/crates/android-tzdata.git","description":null}
{"name":"la/platform/external/trace-cmd","clone_url":"https://git.codelinaro.org/clo/la/platform/external/trace-cmd.git","description":null}
{"name":"lc/external/github.com/bazelbuild/remote-apis-sdks","clone_url":"https://git.codelinaro.org/clo/lc/external/github.com/bazelbuild/remote-apis-sdks.git","description":null}
{"name":"la/platform/external/ksoap2","clone_url":"https://git.codelinaro.org/clo/la/platform/external/ksoap2.git","description":null}
{"name":"la/platform/external/libchromeos","clone_url":"https://git.codelinaro.org/clo/la/platform/external/libchromeos.git","description":null}
{"name":"la/platform/external/rust/crates/rand_chacha","clone_url":"https://git.codelinaro.org/clo/la/platform/external/rust/crates/rand_chacha.git","description":null}
{"name":"le/freedreno/linux","clone_url":"https://git.codelinaro.org/clo/le/freedreno/linux.git","description":null}
{"name":"la/platform/external/sdv/vsomeip","clone_url":"https://git.codelinaro.org/clo/la/platform/external/sdv/vsomeip.git","description":null}
{"name":"le-au-os/platform/vendor/qcom-opensource/data-kernel","clone_url":"https://git.codelinaro.org/clo/le-au-os/platform/vendor/qcom-opensource/data-kernel.git","description":null}
{"name":"yocto-mirrors/iputils","clone_url":"https://git.codelinaro.org/clo/yocto-mirrors/iputils.git","description":null}
{"name":"la/platform/vendor/qcom/msm7630_fusion","clone_url":"https://git.codelinaro.org/clo/la/platform/vendor/qcom/msm7630_fusion.git","description":null}
{"name":"le-au-os/ota/platform/external/libdivsufsort","clone_url":"https://git.codelinaro.org/clo/le-au-os/ota/platform/external/libdivsufsort.git","description":null}
{"name":"la/platform/vendor/qcom/gen5_gvm_gy","clone_url":"https://git.codelinaro.org/clo/la/platform/vendor/qcom/gen5_gvm_gy.git","description":null}
{"name":"testproject/platform/external/dynamic_depth","clone_url":"https://git.codelinaro.org/clo/testproject/platform/external/dynamic_depth.git","description":null}
{"name":"la/platform/external/alljoyn/notification","clone_url":"https://git.codelinaro.org/clo/la/platform/external/alljoyn/notification.git","description":null}
{"name":"le/external/profusion/lightmediascanner","clone_url":"https://git.codelinaro.org/clo/le/external/profusion/lightmediascanner.git","description":null}
{"name":"la/platform/vendor/qcom-opensource/twowheeler/services","clone_url":"https://git.codelinaro.org/clo/la/platform/vendor/qcom-opensource/twowheeler/services.git","description":null}
{"name":"yocto-mirrors/github/golang-jwt/jwt","clone_url":"https://git.codelinaro.org/clo/yocto-mirrors/github/golang-jwt/jwt.git","description":null}
{"name":"la/platform/external/python/typing","clone_url":"https://git.codelinaro.org/clo/la/platform/external/python/typing.git","description":null}
{"name":"la/kernel/exynos-modules/devicetree","clone_url":"https://git.codelinaro.org/clo/la/kernel/exynos-modules/devicetree.git","description":null}
{"name":"yocto-mirrors/github/linux-can/can-utils","clone_url":"https://git.codelinaro.org/clo/yocto-mirrors/github/linux-can/can-utils.git","description":null}
{"name":"la/platform/external/eclipse-windowbuilder","clone_url":"https://git.codelinaro.org/clo/la/platform/external/eclipse-windowbuilder.git","description":null}
{"name":"la/device/imagination/creatorci41","clone_url":"https://git.codelinaro.org/clo/la/device/imagination/creatorci41.git","description":null}
{"name":"le/platform/vendor/qcom-opensource/adk-iot-sys","clone_url":"https://git.codelinaro.org/clo/le/platform/vendor/qcom-opensource/adk-iot-sys.git","description":null}
{"name":"le/platform/hardware/qcom/camera-legacy","clone_url":"https://git.codelinaro.org/clo/le/platform/hardware/qcom/camera-legacy.git","description":null}
{"name":"la/platform/external/rust/crates/anes","clone_url":"https://git.codelinaro.org/clo/la/platform/external/rust/crates/anes.git","description":null}
{"name":"la/platform/packages/apps/Car/Media","clone_url":"https://git.codelinaro.org/clo/la/platform/packages/apps/Car/Media.git","description":null}
{"name":"qsdk/lklm/nss-eip","clone_url":"https://git.codelinaro.org/clo/qsdk/lklm/nss-eip.git","description":null}
{"name":"testproject/platform/system/libhwbinder","clone_url":"https://git.codelinaro.org/clo/testproject/platform/system/libhwbinder.git","description":null}
{"name":"le/tokio-uds-windows","clone_url":"https://git.codelinaro.org/clo/le/tokio-uds-windows.git","description":null}
{"name":"lc/chromiumos/platform/touch_noise_filter","clone_url":"https://git.codelinaro.org/clo/lc/chromiumos/platform/touch_noise_filter.git","description":null}
{"name":"la/platform/vendor/qcom/tellurium_64","clone_url":"https://git.codelinaro.org/clo/la/platform/vendor/qcom/tellurium_64.git","description":null}
