{"name":"le/external/GSL","clone_url":"https://git.codelinaro.org/clo/le/external/GSL.git","description":null}
{"name":"la/platform/external/rust/crates/ring","clone_url":"https://git.codelinaro.org/clo/la/platform/external/rust/crates/ring.git","description":null}
{"name":"lc/external/github.com/googlecloudplatform/google-cloud-go-testing","clone_url":"https://git.codelinaro.org/clo/lc/external/github.com/googlecloudplatform/google-cloud-go-testing.git","description":null}
{"name":"le-au-os/patches","clone_url":"https://git.codelinaro.org/clo/le-au-os/patches.git","description":null}
{"name":"external-wlan/prima","clone_url":"https://git.codelinaro.org/clo/external-wlan/prima.git","description":null}
{"name":"le/platform/external/libuv","clone_url":"https://git.codelinaro.org/clo/le/platform/external/libuv.git","description":null}
{"name":"la/platform/external/rust/crates/tracing-subscriber","clone_url":"https://git.codelinaro.org/clo/la/platform/external/rust/crates/tracing-subscriber.git","description":null}
{"name":"la/platform/external/chromium_org/third_party/libjpeg_turbo","clone_url":"https://git.codelinaro.org/clo/la/platform/external/chromium_org/third_party/libjpeg_turbo.git","description":null}
{"name":"la/platform/external/fec","clone_url":"https://git.codelinaro.org/clo/la/platform/external/fec.git","description":null}
{"name":"le/owrt/feeds/feed_net_hl_services","clone_url":"https://git.codelinaro.org/clo/le/owrt/feeds/feed_net_hl_services.git","description":null}
{"name":"qsdk/system/owrt-qti-ipq-ezmesh","clone_url":"https://git.codelinaro.org/clo/qsdk/system/owrt-qti-ipq-ezmesh.git","description":null}
{"name":"la/platform/packages/apps/EyeDropper","clone_url":"https://git.codelinaro.org/clo/la/platform/packages/apps/EyeDropper.git","description":null}
{"name":"la/platform/external/pffft","clone_url":"https://git.codelinaro.org/clo/la/platform/external/pffft.git","description":null}
{"name":"qcomlt/libadsprpc","clone_url":"https://git.codelinaro.org/clo/qcomlt/libadsprpc.git","description":null}
{"name":"yocto-mirrors/glog","clone_url":"https://git.codelinaro.org/clo/yocto-mirrors/glog.git","description":null}
{"name":"yocto-mirrors/github/hashicorp/golang-lru","clone_url":"https://git.codelinaro.org/clo/yocto-mirrors/github/hashicorp/golang-lru.git","description":null}
{"name":"yocto-mirrors/yajl","clone_url":"https://git.codelinaro.org/clo/yocto-mirrors/yajl.git","description":null}
{"name":"testproject/platform/tools/tradefederation_group/contrib","clone_url":"https://git.codelinaro.org/clo/testproject/platform/tools/tradefederation_group/contrib.git","description":null}
{"name":"testproject/platform/external/caliper","clone_url":"https://git.codelinaro.org/clo/testproject/platform/external/caliper.git","description":null}
{"name":"la/platform/bootable/bootloader/legacy","clone_url":"https://git.codelinaro.org/clo/la/platform/bootable/bootloader/legacy.git","description":null}
{"name":"lc/gsubtreed-template","clone_url":"https://git.codelinaro.org/clo/lc/gsubtreed-template.git","description":null}
{"name":"femto5g/platform/external/libdrm","clone_url":"https://git.codelinaro.org/clo/femto5g/platform/external/libdrm.git","description":null}
{"name":"la/platform/external/connectivity","clone_url":"https://git.codelinaro.org/clo/la/platform/external/connectivity.git","description":null}
{"name":"la/platform/vendor/qcom/gen5_gvm_qmaa","clone_url":"https://git.codelinaro.org/clo/la/platform/vendor/qcom/gen5_gvm_qmaa.git","description":null}
{"name":"lf/b2g/rilproxy","clone_url":"https://git.codelinaro.org/clo/lf/b2g/rilproxy.git","description":null}
{"name":"testproject/device/linaro/poplar","clone_url":"https://git.codelinaro.org/clo/testproject/device/linaro/poplar.git","description":null}
{"name":"qsdk/acl","clone_url":"https://git.codelinaro.org/clo/qsdk/acl.git","description":null}
{"name":"la/platform/external/tpm2","clone_url":"https://git.codelinaro.org/clo/la/platform/external/tpm2.git","description":null}
{"name":"le/ros2-gbp/rmw_cyclonedds-release","clone_url":"https://git.codelinaro.org/clo/le/ros2-gbp/rmw_cyclonedds-release.git","description":null}
{"name":"le/meta-qti-display","clone_url":"https://git.codelinaro.org/clo/le/meta-qti-display.git","description":null}
{"name":"lc/chromiumos/third_party/shellcheck","clone_url":"https://git.codelinaro.org/clo/lc/chromiumos/third_party/shellcheck.git","description":null}
{"name":"testproject/platform/packages/apps/car/LatinIME","clone_url":"https://git.codelinaro.org/clo/testproject/platform/packages/apps/car/LatinIME.git","description":null}
{"name":"testproject/platform/external/guice","clone_url":"https://git.codelinaro.org/clo/testproject/platform/external/guice.git","description":null}
{"name":"la/platform/external/fft2d","clone_url":"https://git.codelinaro.org/clo/la/platform/external/fft2d.git","description":null}
{"name":"lc/external/github.com/google/gofountain","clone_url":"https://git.codelinaro.org/clo/lc/external/github.com/google/gofountain.git","description":null}
{"name":"la/trusty/device/arm/generic-arm64","clone_url":"https://git.codelinaro.org/clo/la/trusty/device/arm/generic-arm64.git","description":null}
{"name":"la/platform/external/boost-submodules/program_options","clone_url":"https://git.codelinaro.org/clo/la/platform/external/boost-submodules/program_options.git","description":null}
{"name":"k2c-yocto-track1/meta-qcom-realtime","clone_url":"https://git.codelinaro.org/clo/k2c-yocto-track1/meta-qcom-realtime.git","description":null}
{"name":"la/kernel/google-modules/gpu","clone_url":"https://git.codelinaro.org/clo/la/kernel/google-modules/gpu.git","description":null}
{"name":"lc/external/github.com/gnome/gtk","clone_url":"https://git.codelinaro.org/clo/lc/external/github.com/gnome/gtk.git","description":null}
{"name":"la/platform/bbuildbot_config","clone_url":"https://git.codelinaro.org/clo/la/platform/bbuildbot_config.git","description":null}
{"name":"la/platform/prebuilts/gcc/linux-x86/aarch64/aarch64-linux-android-4.9","clone_url":"https://git.codelinaro.org/clo/la/platform/prebuilts/gcc/linux-x86/aarch64/aarch64-linux-android-4.9.git","description":null}
{"name":"lc/external/bitbucket.org/stoneleaf/enum34","clone_url":"https://git.codelinaro.org/clo/lc/external/bitbucket.org/stoneleaf/enum34.git","description":null}
{"name":"lc/chromiumos/platform/modem-utilities","clone_url":"https://git.codelinaro.org/clo/lc/chromiumos/platform/modem-utilities.git","description":null}
{"name":"testproject/platform/packages/apps/KeyChain","clone_url":"https://git.codelinaro.org/clo/testproject/platform/packages/apps/KeyChain.git","description":null}
{"name":"la/kernel/google-modules/gxp/gs201","clone_url":"https://git.codelinaro.org/clo/la/kernel/google-modules/gxp/gs201.git","description":null}
{"name":"la/platform/external/rust/crates/byteorder","clone_url":"https://git.codelinaro.org/clo/la/platform/external/rust/crates/byteorder.git","description":null}
{"name":"rdkb/rdkb/components/opensource/ccsp/GwProvApp-ePON","clone_url":"https://git.codelinaro.org/clo/rdkb/rdkb/components/opensource/ccsp/GwProvApp-ePON.git","description":null}
{"name":"yocto-mirrors/github/hashicorp/go-immutable-radix","clone_url":"https://git.codelinaro.org/clo/yocto-mirrors/github/hashicorp/go-immutable-radix.git","description":null}
{"name":"qrdk/code.rdkcentral.com/rdkb/components/opensource/ccsp/sysint","clone_url":"https://git.codelinaro.org/clo/qrdk/code.rdkcentral.com/rdkb/components/opensource/ccsp/sysint.git","description":null}
{"name":"le/ros2-gbp/ament_package-release","clone_url":"https://git.codelinaro.org/clo/le/ros2-gbp/ament_package-release.git","description":null}
{"name":"la/platform/packages/modules/SdkExtensions","clone_url":"https://git.codelinaro.org/clo/la/platform/packages/modules/SdkExtensions.git","description":null}
{"name":"la/device/generic/brillo","clone_url":"https://git.codelinaro.org/clo/la/device/generic/brillo.git","description":null}
{"name":"le/platform/external/mtpserver","clone_url":"https://git.codelinaro.org/clo/le/platform/external/mtpserver.git","description":null}
{"name":"la/device/google/trout","clone_url":"https://git.codelinaro.org/clo/la/device/google/trout.git","description":null}
{"name":"la/device/qcom/common","clone_url":"https://git.codelinaro.org/clo/la/device/qcom/common.git","description":null}
{"name":"yocto-mirrors/github/qemu/dtc","clone_url":"https://git.codelinaro.org/clo/yocto-mirrors/github/qemu/dtc.git","description":null}
{"name":"la/platform/vendor/qcom/msmnileau_gvmq_ext4","clone_url":"https://git.codelinaro.org/clo/la/platform/vendor/qcom/msmnileau_gvmq_ext4.git","description":null}
{"name":"lc/chromiumos/platform/wireless_automation","clone_url":"https://git.codelinaro.org/clo/lc/chromiumos/platform/wireless_automation.git","description":null}
{"name":"la/platform/frameworks/opt/widget","clone_url":"https://git.codelinaro.org/clo/la/platform/frameworks/opt/widget.git","description":null}
{"name":"la/platform/vendor/qcom/msm8660_surf","clone_url":"https://git.codelinaro.org/clo/la/platform/vendor/qcom/msm8660_surf.git","description":null}
{"name":"la/platform/external/rust/crates/debug_tree","clone_url":"https://git.codelinaro.org/clo/la/platform/external/rust/crates/debug_tree.git","description":null}
{"name":"qrdk/rdkcentral/provisioning-and-management","clone_url":"https://git.codelinaro.org/clo/qrdk/rdkcentral/provisioning-and-management.git","description":null}
{"name":"la/platform/prebuilts/androidx/javascript-for-kotlin","clone_url":"https://git.codelinaro.org/clo/la/platform/prebuilts/androidx/javascript-for-kotlin.git","description":null}
{"name":"la/platform/external/rust/crates/fs-err","clone_url":"https://git.codelinaro.org/clo/la/platform/external/rust/crates/fs-err.git","description":null}
{"name":"la/scopetrace/manifest","clone_url":"https://git.codelinaro.org/clo/la/scopetrace/manifest.git","description":null}
{"name":"le/platform/external/update-rc.d","clone_url":"https://git.codelinaro.org/clo/le/platform/external/update-rc.d.git","description":null}
{"name":"la/platform/external/rust/crates/rand_chacha","clone_url":"https://git.codelinaro.org/clo/la/platform/external/rust/crates/rand_chacha.git","description":null}
{"name":"la/platform/vendor/qcom-opensource/core-utils","clone_url":"https://git.codelinaro.org/clo/la/platform/vendor/qcom-opensource/core-utils.git","description":null}
{"name":"testproject/platform/external/libaom","clone_url":"https://git.codelinaro.org/clo/testproject/platform/external/libaom.git","description":null}
{"name":"yocto-mirrors/github/ros2-gbp/xacro-release","clone_url":"https://git.codelinaro.org/clo/yocto-mirrors/github/ros2-gbp/xacro-release.git","description":null}
{"name":"la/platform/prebuilts/gcc/linux-x86/host/i686-linux-glibc2.7-4.4.3","clone_url":"https://git.codelinaro.org/clo/la/platform/prebuilts/gcc/linux-x86/host/i686-linux-glibc2.7-4.4.3.git","description":null}
{"name":"la/platform/vendor/qcom-opensource/omx/mm-core","clone_url":"https://git.codelinaro.org/clo/la/platform/vendor/qcom-opensource/omx/mm-core.git","description":null}
{"name":"la/platform/vendor/qcom/sdm429w/codeaurora/dataservices","clone_url":"https://git.codelinaro.org/clo/la/platform/vendor/qcom/sdm429w/codeaurora/dataservices.git","description":null}
{"name":"yocto-mirrors/github/ros2-gbp/tinyxml2_vendor-release","clone_url":"https://git.codelinaro.org/clo/yocto-mirrors/github/ros2-gbp/tinyxml2_vendor-release.git","description":null}
{"name":"la/external/github.com/quic-qrb-ros/qrb_ros_benchmark","clone_url":"https://git.codelinaro.org/clo/la/external/github.com/quic-qrb-ros/qrb_ros_benchmark.git","description":null}
{"name":"la/platform/system/connectivity/dhcp_client","clone_url":"https://git.codelinaro.org/clo/la/platform/system/connectivity/dhcp_client.git","description":null}
{"name":"lc/infra/luci/luci-py_repo","clone_url":"https://git.codelinaro.org/clo/lc/infra/luci/luci-py_repo.git","description":null}
{"name":"la/platform/external/rust/crates/ron","clone_url":"https://git.codelinaro.org/clo/la/platform/external/rust/crates/ron.git","description":null}
{"name":"yocto-mirrors/github/ros2-gbp/rclpy-release","clone_url":"https://git.codelinaro.org/clo/yocto-mirrors/github/ros2-gbp/rclpy-release.git","description":null}
{"name":"la/platform/external/cros/system_api","clone_url":"https://git.codelinaro.org/clo/la/platform/external/cros/system_api.git","description":null}
{"name":"la/platform/hardware/invensense","clone_url":"https://git.codelinaro.org/clo/la/platform/hardware/invensense.git","description":null}
{"name":"le/pps-tools","clone_url":"https://git.codelinaro.org/clo/le/pps-tools.git","description":null}
{"name":"la/platform/external/rust/crates/grpcio","clone_url":"https://git.codelinaro.org/clo/la/platform/external/rust/crates/grpcio.git","description":null}
{"name":"la/device/marvell/abox_edge","clone_url":"https://git.codelinaro.org/clo/la/device/marvell/abox_edge.git","description":null}
{"name":"ath-firmware/ath12k-firmware","clone_url":"https://git.codelinaro.org/clo/ath-firmware/ath12k-firmware.git","description":null}
{"name":"la/platform/external/rust/crates/futures-macro","clone_url":"https://git.codelinaro.org/clo/la/platform/external/rust/crates/futures-macro.git","description":null}
{"name":"yocto-mirrors/github/mobile-broadband/libqrtr-glib","clone_url":"https://git.codelinaro.org/clo/yocto-mirrors/github/mobile-broadband/libqrtr-glib.git","description":null}
{"name":"le/external/linux-kernel","clone_url":"https://git.codelinaro.org/clo/le/external/linux-kernel.git","description":null}
{"name":"le/platform/vendor/qcom-opensource/robot-motion-service","clone_url":"https://git.codelinaro.org/clo/le/platform/vendor/qcom-opensource/robot-motion-service.git","description":null}
{"name":"la/platform/external/mobile-data-download","clone_url":"https://git.codelinaro.org/clo/la/platform/external/mobile-data-download.git","description":null}
{"name":"le/platform/external/ROBOTIS-GIT/turtlebot3_msgs","clone_url":"https://git.codelinaro.org/clo/le/platform/external/ROBOTIS-GIT/turtlebot3_msgs.git","description":null}
{"name":"lc/external/github.com/flutter/packages","clone_url":"https://git.codelinaro.org/clo/lc/external/github.com/flutter/packages.git","description":null}
{"name":"qcomlt/demos/device_linaro_dragonboard","clone_url":"https://git.codelinaro.org/clo/qcomlt/demos/device_linaro_dragonboard.git","description":"Qualcomm Landing Team AOSP Dragonboard Demo trees\r\n\r\nDo not remove branches or tags, those are expected to be stable and valid for blog posts and marketing purposes.\r\n\r\nDo not push work-in-progress or working branches here, only marketing/demo material."}
{"name":"la/platform/prebuilts/clang/linux-x86/host/3.6","clone_url":"https://git.codelinaro.org/clo/la/platform/prebuilts/clang/linux-x86/host/3.6.git","description":null}
{"name":"le/owrt/feeds/luci","clone_url":"https://git.codelinaro.org/clo/le/owrt/feeds/luci.git","description":null}
{"name":"la/platform/external/rust/autocxx","clone_url":"https://git.codelinaro.org/clo/la/platform/external/rust/autocxx.git","description":null}
{"name":"la/platform/prebuilts/maven_repo/android","clone_url":"https://git.codelinaro.org/clo/la/platform/prebuilts/maven_repo/android.git","description":null}
{"name":"la/platform/vendor/qcom/gen4_gvm_dc","clone_url":"https://git.codelinaro.org/clo/la/platform/vendor/qcom/gen4_gvm_dc.git","description":null}
{"name":"la/device/google/sunfish-kernel","clone_url":"https://git.codelinaro.org/clo/la/device/google/sunfish-kernel.git","description":null}
{"name":"le/WPEBackend-fdo","clone_url":"https://git.codelinaro.org/clo/le/WPEBackend-fdo.git","description":null}
{"name":"la/platform/prebuilts/renderscript/host/windows-x86","clone_url":"https://git.codelinaro.org/clo/la/platform/prebuilts/renderscript/host/windows-x86.git","description":null}
{"name":"lf/releases/l10n/el/gecko","clone_url":"https://git.codelinaro.org/clo/lf/releases/l10n/el/gecko.git","description":null}
{"name":"la/platform/external/checkstyle","clone_url":"https://git.codelinaro.org/clo/la/platform/external/checkstyle.git","description":null}
{"name":"lc/patches","clone_url":"https://git.codelinaro.org/clo/lc/patches.git","description":null}
{"name":"la/platform/frameworks/opt/mms","clone_url":"https://git.codelinaro.org/clo/la/platform/frameworks/opt/mms.git","description":null}
{"name":"la/tools/manifest","clone_url":"https://git.codelinaro.org/clo/la/tools/manifest.git","description":null}
{"name":"yocto-mirrors/github/ros2-gbp/cyclonedds-release","clone_url":"https://git.codelinaro.org/clo/yocto-mirrors/github/ros2-gbp/cyclonedds-release.git","description":null}
{"name":"la/platform/brillo","clone_url":"https://git.codelinaro.org/clo/la/platform/brillo.git","description":null}
{"name":"la/platform/system/hwservicemanager","clone_url":"https://git.codelinaro.org/clo/la/platform/system/hwservicemanager.git","description":null}
{"name":"la/platform/external/rust/crates/cast","clone_url":"https://git.codelinaro.org/clo/la/platform/external/rust/crates/cast.git","description":null}
{"name":"le/unfs3/unfs3","clone_url":"https://git.codelinaro.org/clo/le/unfs3/unfs3.git","description":null}
{"name":"la/device/google/bramble","clone_url":"https://git.codelinaro.org/clo/la/device/google/bramble.git","description":null}
{"name":"le/owrt/feeds/routing","clone_url":"https://git.codelinaro.org/clo/le/owrt/feeds/routing.git","description":null}
{"name":"yocto-mirrors/github/ros2-gbp/rcl-release","clone_url":"https://git.codelinaro.org/clo/yocto-mirrors/github/ros2-gbp/rcl-release.git","description":null}
{"name":"la/platform/external/kmod","clone_url":"https://git.codelinaro.org/clo/la/platform/external/kmod.git","description":null}
{"name":"qsdk/oss/system/feeds/wlan/qca-wifi-apps","clone_url":"https://git.codelinaro.org/clo/qsdk/oss/system/feeds/wlan/qca-wifi-apps.git","description":null}
{"name":"lc/external/gsutil/src","clone_url":"https://git.codelinaro.org/clo/lc/external/gsutil/src.git","description":null}
{"name":"testproject/platform/prebuilts/asuite","clone_url":"https://git.codelinaro.org/clo/testproject/platform/prebuilts/asuite.git","description":null}
{"name":"qsdk/gstreamer-1.14.4/gst-plugins-bad","clone_url":"https://git.codelinaro.org/clo/qsdk/gstreamer-1.14.4/gst-plugins-bad.git","description":null}
{"name":"qsdk/oss/ath11k-bdf","clone_url":"https://git.codelinaro.org/clo/qsdk/oss/ath11k-bdf.git","description":null}
{"name":"la/platform/external/ktfmt","clone_url":"https://git.codelinaro.org/clo/la/platform/external/ktfmt.git","description":null}
{"name":"la/platform/system/media","clone_url":"https://git.codelinaro.org/clo/la/platform/system/media.git","description":null}
{"name":"la/platform/prebuilts/rust-toolchain/darwin","clone_url":"https://git.codelinaro.org/clo/la/platform/prebuilts/rust-toolchain/darwin.git","description":null}
{"name":"le/wayland/efl","clone_url":"https://git.codelinaro.org/clo/le/wayland/efl.git","description":null}
{"name":"le/platform/vendor/qcom-opensource/system/bt","clone_url":"https://git.codelinaro.org/clo/le/platform/vendor/qcom-opensource/system/bt.git","description":null}
{"name":"la/platform/prebuilts/fuchsia_sdk","clone_url":"https://git.codelinaro.org/clo/la/platform/prebuilts/fuchsia_sdk.git","description":null}
{"name":"yocto-mirrors/github/fmtlib/fmt","clone_url":"https://git.codelinaro.org/clo/yocto-mirrors/github/fmtlib/fmt.git","description":null}
{"name":"la/device/samsung/tuna","clone_url":"https://git.codelinaro.org/clo/la/device/samsung/tuna.git","description":null}
{"name":"la/platform/external/gtest","clone_url":"https://git.codelinaro.org/clo/la/platform/external/gtest.git","description":null}
{"name":"la/tools/plugin-testing","clone_url":"https://git.codelinaro.org/clo/la/tools/plugin-testing.git","description":null}
{"name":"yocto-mirrors/procps","clone_url":"https://git.codelinaro.org/clo/yocto-mirrors/procps.git","description":null}
{"name":"rdkb/rdkb/components/opensource/ccsp/CcspEthAgent","clone_url":"https://git.codelinaro.org/clo/rdkb/rdkb/components/opensource/ccsp/CcspEthAgent.git","description":null}
{"name":"qsdk/oss/prpl-foundation/prplmesh/prplMesh","clone_url":"https://git.codelinaro.org/clo/qsdk/oss/prpl-foundation/prplmesh/prplMesh.git","description":null}
{"name":"lc/external/github.com/data-dog/go-sqlmock","clone_url":"https://git.codelinaro.org/clo/lc/external/github.com/data-dog/go-sqlmock.git","description":null}
{"name":"la/platform/hardware/google/gchips","clone_url":"https://git.codelinaro.org/clo/la/platform/hardware/google/gchips.git","description":null}
{"name":"le/meta-qti-eva","clone_url":"https://git.codelinaro.org/clo/le/meta-qti-eva.git","description":null}
{"name":"la/platform/external/jdiff","clone_url":"https://git.codelinaro.org/clo/la/platform/external/jdiff.git","description":null}
{"name":"le/wayland/enlightenment","clone_url":"https://git.codelinaro.org/clo/le/wayland/enlightenment.git","description":null}
{"name":"la/platform/external/boost-submodules/geometry","clone_url":"https://git.codelinaro.org/clo/la/platform/external/boost-submodules/geometry.git","description":null}
{"name":"lc/external/github.com/sabhiram/go-gitignore","clone_url":"https://git.codelinaro.org/clo/lc/external/github.com/sabhiram/go-gitignore.git","description":null}
{"name":"femto5g/oss/lklm/nss-ppe","clone_url":"https://git.codelinaro.org/clo/femto5g/oss/lklm/nss-ppe.git","description":null}
{"name":"femto5g/oss/kernel/linux-ipq-6.1","clone_url":"https://git.codelinaro.org/clo/femto5g/oss/kernel/linux-ipq-6.1.git","description":null}
{"name":"la/platform/external/lua","clone_url":"https://git.codelinaro.org/clo/la/platform/external/lua.git","description":null}
{"name":"le/meta-qti-qcawifi","clone_url":"https://git.codelinaro.org/clo/le/meta-qti-qcawifi.git","description":null}
{"name":"la/platform/hardware/st/secure_element","clone_url":"https://git.codelinaro.org/clo/la/platform/hardware/st/secure_element.git","description":null}
{"name":"la/platform/external/boost-submodules/property_map","clone_url":"https://git.codelinaro.org/clo/la/platform/external/boost-submodules/property_map.git","description":null}
{"name":"imm/imm/meta-browser","clone_url":"https://git.codelinaro.org/clo/imm/imm/meta-browser.git","description":null}
{"name":"la/platform/external/libdivsufsort","clone_url":"https://git.codelinaro.org/clo/la/platform/external/libdivsufsort.git","description":null}
{"name":"la/device/generic/mips","clone_url":"https://git.codelinaro.org/clo/la/device/generic/mips.git","description":null}
{"name":"testproject/platform/frameworks/libs/native_bridge_support","clone_url":"https://git.codelinaro.org/clo/testproject/platform/frameworks/libs/native_bridge_support.git","description":null}
{"name":"testproject/platform/external/skia","clone_url":"https://git.codelinaro.org/clo/testproject/platform/external/skia.git","description":null}
{"name":"la/toolchain/prebuilts/ndk/r19","clone_url":"https://git.codelinaro.org/clo/la/toolchain/prebuilts/ndk/r19.git","description":null}
{"name":"lc/chromiumos/platform2/system_api","clone_url":"https://git.codelinaro.org/clo/lc/chromiumos/platform2/system_api.git","description":null}
{"name":"imx-support/imx-android-12","clone_url":"https://git.codelinaro.org/clo/imx-support/imx-android-12.git","description":null}
{"name":"la/platform/external/rust/crates/const_fn","clone_url":"https://git.codelinaro.org/clo/la/platform/external/rust/crates/const_fn.git","description":null}
{"name":"la/platform/external/v8","clone_url":"https://git.codelinaro.org/clo/la/platform/external/v8.git","description":null}
{"name":"la/device/qcom/sdm429w/common","clone_url":"https://git.codelinaro.org/clo/la/device/qcom/sdm429w/common.git","description":null}
{"name":"la/device/generic/car","clone_url":"https://git.codelinaro.org/clo/la/device/generic/car.git","description":null}
{"name":"qsdk/patches","clone_url":"https://git.codelinaro.org/clo/qsdk/patches.git","description":null}
{"name":"la/openocd-org/openocd","clone_url":"https://git.codelinaro.org/clo/la/openocd-org/openocd.git","description":null}
{"name":"testproject/platform/system/memory/libmeminfo","clone_url":"https://git.codelinaro.org/clo/testproject/platform/system/memory/libmeminfo.git","description":null}
{"name":"la/platform/external/jackson-core","clone_url":"https://git.codelinaro.org/clo/la/platform/external/jackson-core.git","description":null}
{"name":"la/platform/external/rust/crates/icu_capi","clone_url":"https://git.codelinaro.org/clo/la/platform/external/rust/crates/icu_capi.git","description":null}
{"name":"lc/external/github.com/flintwork/mccabe","clone_url":"https://git.codelinaro.org/clo/lc/external/github.com/flintwork/mccabe.git","description":null}
{"name":"le/hostap","clone_url":"https://git.codelinaro.org/clo/le/hostap.git","description":null}
{"name":"la/platform/vendor/qcom-opensource/display-commonsys-intf","clone_url":"https://git.codelinaro.org/clo/la/platform/vendor/qcom-opensource/display-commonsys-intf.git","description":null}
{"name":"la/device/qcom/qssi_64go","clone_url":"https://git.codelinaro.org/clo/la/device/qcom/qssi_64go.git","description":null}
{"name":"yocto-mirrors/github/mwitkow/go-conntrack","clone_url":"https://git.codelinaro.org/clo/yocto-mirrors/github/mwitkow/go-conntrack.git","description":null}
{"name":"la/platform/prebuilts/python/darwin-x86_repo","clone_url":"https://git.codelinaro.org/clo/la/platform/prebuilts/python/darwin-x86_repo.git","description":null}
{"name":"la/platform/packages/modules/bootprebuilt/5.4/arm64","clone_url":"https://git.codelinaro.org/clo/la/platform/packages/modules/bootprebuilt/5.4/arm64.git","description":null}
{"name":"yocto-mirrors/github/opencv/opencv","clone_url":"https://git.codelinaro.org/clo/yocto-mirrors/github/opencv/opencv.git","description":null}
{"name":"yocto-mirrors/github/golang/protobuf","clone_url":"https://git.codelinaro.org/clo/yocto-mirrors/github/golang/protobuf.git","description":null}
{"name":"la/device/qcom/qssi_au_cf","clone_url":"https://git.codelinaro.org/clo/la/device/qcom/qssi_au_cf.git","description":null}
{"name":"testproject/platform/external/google-fonts/lato","clone_url":"https://git.codelinaro.org/clo/testproject/platform/external/google-fonts/lato.git","description":null}
{"name":"la/platform/external/openscreen","clone_url":"https://git.codelinaro.org/clo/la/platform/external/openscreen.git","description":null}
{"name":"debug/skqp","clone_url":"https://git.codelinaro.org/clo/debug/skqp.git","description":null}
{"name":"la/platform/tools/tradefederation/prebuilts","clone_url":"https://git.codelinaro.org/clo/la/platform/tools/tradefederation/prebuilts.git","description":null}
{"name":"la/device/pifoundation/rpi3","clone_url":"https://git.codelinaro.org/clo/la/device/pifoundation/rpi3.git","description":null}
{"name":"la/platform/external/google-fonts/barlow","clone_url":"https://git.codelinaro.org/clo/la/platform/external/google-fonts/barlow.git","description":null}
{"name":"la/platform/external/javassist","clone_url":"https://git.codelinaro.org/clo/la/platform/external/javassist.git","description":null}
{"name":"la/platform/external/exoplayer","clone_url":"https://git.codelinaro.org/clo/la/platform/external/exoplayer.git","description":null}
{"name":"la/platform/external/geojson-jackson","clone_url":"https://git.codelinaro.org/clo/la/platform/external/geojson-jackson.git","description":null}
{"name":"qcomlt/demos/linux","clone_url":"https://git.codelinaro.org/clo/qcomlt/demos/linux.git","description":"Qualcomm Landing Team Linux Demo trees\r\n\r\nDo not remove branches or tags, those are expected to be stable and valid for blog posts and marketing purposes.\r\n\r\ntopic/* branches are protected against modifications, do not change.\r\n\r\nDo not push work-in-progress or working branches here, only marketing/demo material."}
{"name":"yocto-mirrors/github/google/pprof","clone_url":"https://git.codelinaro.org/clo/yocto-mirrors/github/google/pprof.git","description":null}
{"name":"testproject/platform/external/grpc-grpc","clone_url":"https://git.codelinaro.org/clo/testproject/platform/external/grpc-grpc.git","description":null}
{"name":"la/platform/vendor/qcom/sdm429w/codeaurora/core-utils","clone_url":"https://git.codelinaro.org/clo/la/platform/vendor/qcom/sdm429w/codeaurora/core-utils.git","description":null}
{"name":"la/platform/vendor/qcom/monaco_group/codeaurora/healthd-ext","clone_url":"https://git.codelinaro.org/clo/la/platform/vendor/qcom/monaco_group/codeaurora/healthd-ext.git","description":null}
{"name":"la/platform/vendor/qcom-opensource/audio-hal/st-hal","clone_url":"https://git.codelinaro.org/clo/la/platform/vendor/qcom-opensource/audio-hal/st-hal.git","description":null}
{"name":"yocto-mirrors/github/ros2-gbp/osrf_pycommon-release","clone_url":"https://git.codelinaro.org/clo/yocto-mirrors/github/ros2-gbp/osrf_pycommon-release.git","description":null}
{"name":"la/platform/hardware/google/easel","clone_url":"https://git.codelinaro.org/clo/la/platform/hardware/google/easel.git","description":null}
{"name":"la/platform/external/rust/crates/log","clone_url":"https://git.codelinaro.org/clo/la/platform/external/rust/crates/log.git","description":null}
{"name":"lc/external/github.com/dart-lang/observe","clone_url":"https://git.codelinaro.org/clo/lc/external/github.com/dart-lang/observe.git","description":null}
{"name":"lc/chromium/src/chrome/test/pyautolib","clone_url":"https://git.codelinaro.org/clo/lc/chromium/src/chrome/test/pyautolib.git","description":null}
{"name":"kernel-platform-2-0-os/kernel_platform/external/stardoc","clone_url":"https://git.codelinaro.org/clo/kernel-platform-2-0-os/kernel_platform/external/stardoc.git","description":null}
{"name":"lc/external/github.com/hamcrest/OCHamcrest","clone_url":"https://git.codelinaro.org/clo/lc/external/github.com/hamcrest/OCHamcrest.git","description":null}
{"name":"la/platform/external/rust/crates/pkcs1","clone_url":"https://git.codelinaro.org/clo/la/platform/external/rust/crates/pkcs1.git","description":null}
{"name":"testproject/platform/external/libxml2","clone_url":"https://git.codelinaro.org/clo/testproject/platform/external/libxml2.git","description":null}
{"name":"la/platform/external/okhttp4","clone_url":"https://git.codelinaro.org/clo/la/platform/external/okhttp4.git","description":null}
{"name":"yocto-mirrors/u-boot/u-boot","clone_url":"https://git.codelinaro.org/clo/yocto-mirrors/u-boot/u-boot.git","description":null}
{"name":"yocto-mirrors/github/protocolbuffers/protobuf","clone_url":"https://git.codelinaro.org/clo/yocto-mirrors/github/protocolbuffers/protobuf.git","description":null}
{"name":"external-wlan/kernel","clone_url":"https://git.codelinaro.org/clo/external-wlan/kernel.git","description":null}
{"name":"la/device/htc/flounder","clone_url":"https://git.codelinaro.org/clo/la/device/htc/flounder.git","description":null}
{"name":"le/vendor/arm/ComputeLibrary","clone_url":"https://git.codelinaro.org/clo/le/vendor/arm/ComputeLibrary.git","description":null}
{"name":"la/platform/prebuilts/misc","clone_url":"https://git.codelinaro.org/clo/la/platform/prebuilts/misc.git","description":null}
{"name":"la/platform/external/musl","clone_url":"https://git.codelinaro.org/clo/la/platform/external/musl.git","description":null}
{"name":"la/platform/prebuilts/clang/host/windows-x86_32","clone_url":"https://git.codelinaro.org/clo/la/platform/prebuilts/clang/host/windows-x86_32.git","description":null}
{"name":"la/platform/external/boost-submodules/integer","clone_url":"https://git.codelinaro.org/clo/la/platform/external/boost-submodules/integer.git","description":null}
{"name":"testproject/platform/tools/tradefederation","clone_url":"https://git.codelinaro.org/clo/testproject/platform/tools/tradefederation.git","description":null}
{"name":"qcomlt/pkg/gst-libav1.0","clone_url":"https://git.codelinaro.org/clo/qcomlt/pkg/gst-libav1.0.git","description":null}
{"name":"yocto-mirrors/github/sirupsen/logrus","clone_url":"https://git.codelinaro.org/clo/yocto-mirrors/github/sirupsen/logrus.git","description":null}
{"name":"le/platform/vendor/qcom-opensource/adk-managers","clone_url":"https://git.codelinaro.org/clo/le/platform/vendor/qcom-opensource/adk-managers.git","description":null}
{"name":"la/kernel_platform/external/bazelbuild-rules_java","clone_url":"https://git.codelinaro.org/clo/la/kernel_platform/external/bazelbuild-rules_java.git","description":null}
{"name":"la/platform/vendor/qcom-opensource/capicxx-someip-runtime","clone_url":"https://git.codelinaro.org/clo/la/platform/vendor/qcom-opensource/capicxx-someip-runtime.git","description":null}
{"name":"la/platform/vendor/qcom-opensource/wlan/qca-wifi-host-cmn-win","clone_url":"https://git.codelinaro.org/clo/la/platform/vendor/qcom-opensource/wlan/qca-wifi-host-cmn-win.git","description":null}
{"name":"la/virtio/qcvirtio-virtio-camera-driver-linux","clone_url":"https://git.codelinaro.org/clo/la/virtio/qcvirtio-virtio-camera-driver-linux.git","description":null}
{"name":"la/platform/packages/modules/WebViewBootstrap","clone_url":"https://git.codelinaro.org/clo/la/platform/packages/modules/WebViewBootstrap.git","description":null}
{"name":"femto5g/platform/vendor/qcom-opensource/gst-plugins-qti-oss","clone_url":"https://git.codelinaro.org/clo/femto5g/platform/vendor/qcom-opensource/gst-plugins-qti-oss.git","description":null}
{"name":"testproject/platform/external/python/mock","clone_url":"https://git.codelinaro.org/clo/testproject/platform/external/python/mock.git","description":null}
{"name":"lc/chromium/src/components/timers","clone_url":"https://git.codelinaro.org/clo/lc/chromium/src/components/timers.git","description":null}
{"name":"la/platform/external/rust/crates/want","clone_url":"https://git.codelinaro.org/clo/la/platform/external/rust/crates/want.git","description":null}
{"name":"la/kernel/prebuilts/common-modules/virtual-device/5.10/x86-64","clone_url":"https://git.codelinaro.org/clo/la/kernel/prebuilts/common-modules/virtual-device/5.10/x86-64.git","description":null}
{"name":"la/platform/vendor/qcom-opensource/audiolite","clone_url":"https://git.codelinaro.org/clo/la/platform/vendor/qcom-opensource/audiolite.git","description":null}
{"name":"yocto-mirrors/github/boostorg/build","clone_url":"https://git.codelinaro.org/clo/yocto-mirrors/github/boostorg/build.git","description":null}
{"name":"la/platform/vendor/qcom/sdm429w/codeaurora/time-services","clone_url":"https://git.codelinaro.org/clo/la/platform/vendor/qcom/sdm429w/codeaurora/time-services.git","description":null}
{"name":"la/platform/external/ktlint","clone_url":"https://git.codelinaro.org/clo/la/platform/external/ktlint.git","description":null}
{"name":"lc/chromiumos/third_party/sound-open-firmware-tools","clone_url":"https://git.codelinaro.org/clo/lc/chromiumos/third_party/sound-open-firmware-tools.git","description":null}
{"name":"testproject/platform/external/vixl","clone_url":"https://git.codelinaro.org/clo/testproject/platform/external/vixl.git","description":null}
{"name":"lc/chromium/deps/findbugs","clone_url":"https://git.codelinaro.org/clo/lc/chromium/deps/findbugs.git","description":null}
{"name":"qrdk/rdkcentral/ipoe-health-check","clone_url":"https://git.codelinaro.org/clo/qrdk/rdkcentral/ipoe-health-check.git","description":null}
{"name":"la/platform/prebuilts/fullsdk-darwin/build-tools_group/30.0.2","clone_url":"https://git.codelinaro.org/clo/la/platform/prebuilts/fullsdk-darwin/build-tools_group/30.0.2.git","description":null}
{"name":"testproject/platform/external/rmi4utils","clone_url":"https://git.codelinaro.org/clo/testproject/platform/external/rmi4utils.git","description":null}
{"name":"la/platform/tools/repohooks-trampoline","clone_url":"https://git.codelinaro.org/clo/la/platform/tools/repohooks-trampoline.git","description":null}
{"name":"la/platform/external/redhat-developer/lsp4ij","clone_url":"https://git.codelinaro.org/clo/la/platform/external/redhat-developer/lsp4ij.git","description":null}
{"name":"yocto-mirrors/init-system-helpers","clone_url":"https://git.codelinaro.org/clo/yocto-mirrors/init-system-helpers.git","description":null}
{"name":"la/kernel/google-modules/raviole-device","clone_url":"https://git.codelinaro.org/clo/la/kernel/google-modules/raviole-device.git","description":null}
{"name":"boot/tf-a","clone_url":"https://git.codelinaro.org/clo/boot/tf-a.git","description":null}
{"name":"la/platform/packages/apps/concam","clone_url":"https://git.codelinaro.org/clo/la/platform/packages/apps/concam.git","description":null}
{"name":"le/platform/vendor/qcom-opensource/perfhal","clone_url":"https://git.codelinaro.org/clo/le/platform/vendor/qcom-opensource/perfhal.git","description":null}
{"name":"le/platform/vendor/qcom-opensource/vhost-user-scmi","clone_url":"https://git.codelinaro.org/clo/le/platform/vendor/qcom-opensource/vhost-user-scmi.git","description":null}
{"name":"lc/external/github.com/op/go-logging","clone_url":"https://git.codelinaro.org/clo/lc/external/github.com/op/go-logging.git","description":null}
{"name":"yocto-mirrors/virt-manager","clone_url":"https://git.codelinaro.org/clo/yocto-mirrors/virt-manager.git","description":null}
{"name":"la/platform/external/boost-submodules/function_types","clone_url":"https://git.codelinaro.org/clo/la/platform/external/boost-submodules/function_types.git","description":null}
{"name":"yocto-mirrors/tinyxml2","clone_url":"https://git.codelinaro.org/clo/yocto-mirrors/tinyxml2.git","description":null}
{"name":"la/platform/system/extras","clone_url":"https://git.codelinaro.org/clo/la/platform/system/extras.git","description":null}
{"name":"yocto-mirrors/github/xhit/go-str2duration","clone_url":"https://git.codelinaro.org/clo/yocto-mirrors/github/xhit/go-str2duration.git","description":null}
{"name":"boot/zephyr","clone_url":"https://git.codelinaro.org/clo/boot/zephyr.git","description":null}
{"name":"la/platform/external/sil-fonts","clone_url":"https://git.codelinaro.org/clo/la/platform/external/sil-fonts.git","description":null}
{"name":"lc/chromium/src/ios","clone_url":"https://git.codelinaro.org/clo/lc/chromium/src/ios.git","description":null}
{"name":"la/platform/external/apache-apr-util","clone_url":"https://git.codelinaro.org/clo/la/platform/external/apache-apr-util.git","description":null}
{"name":"la/platform/external/rust/crates/uniffi","clone_url":"https://git.codelinaro.org/clo/la/platform/external/rust/crates/uniffi.git","description":null}
{"name":"le/rtsp-linux-v2.6","clone_url":"https://git.codelinaro.org/clo/le/rtsp-linux-v2.6.git","description":null}
{"name":"testproject/platform/external/rust/crates/byteorder","clone_url":"https://git.codelinaro.org/clo/testproject/platform/external/rust/crates/byteorder.git","description":null}
{"name":"yocto-mirrors/term","clone_url":"https://git.codelinaro.org/clo/yocto-mirrors/term.git","description":null}
{"name":"lc/external/github.com/webkit/webkit","clone_url":"https://git.codelinaro.org/clo/lc/external/github.com/webkit/webkit.git","description":null}
{"name":"la/platform/vendor/qcom/sun","clone_url":"https://git.codelinaro.org/clo/la/platform/vendor/qcom/sun.git","description":null}
{"name":"lc/chromium/src/third_party/six","clone_url":"https://git.codelinaro.org/clo/lc/chromium/src/third_party/six.git","description":null}
{"name":"le/prelink-cross","clone_url":"https://git.codelinaro.org/clo/le/prelink-cross.git","description":null}
{"name":"la/platform/external/r8","clone_url":"https://git.codelinaro.org/clo/la/platform/external/r8.git","description":null}
{"name":"le/qzephyr/zephyrproject-rtos/segger","clone_url":"https://git.codelinaro.org/clo/le/qzephyr/zephyrproject-rtos/segger.git","description":null}
{"name":"la/pdk_review_filter","clone_url":"https://git.codelinaro.org/clo/la/pdk_review_filter.git","description":null}
{"name":"testproject/platform/external/elfutils","clone_url":"https://git.codelinaro.org/clo/testproject/platform/external/elfutils.git","description":null}
{"name":"la/platform/packages/apps/Car/DebuggingRestrictionController","clone_url":"https://git.codelinaro.org/clo/la/platform/packages/apps/Car/DebuggingRestrictionController.git","description":null}
{"name":"la/platform/prebuilts/asuite","clone_url":"https://git.codelinaro.org/clo/la/platform/prebuilts/asuite.git","description":null}
{"name":"le/external/qtgraphicaleffects","clone_url":"https://git.codelinaro.org/clo/le/external/qtgraphicaleffects.git","description":null}
{"name":"la/platform/packages/apps/RemoteProvisioner","clone_url":"https://git.codelinaro.org/clo/la/platform/packages/apps/RemoteProvisioner.git","description":null}
{"name":"lc/infra/third_party/sphinx","clone_url":"https://git.codelinaro.org/clo/lc/infra/third_party/sphinx.git","description":null}
{"name":"le/gstreamer/gstreamer","clone_url":"https://git.codelinaro.org/clo/le/gstreamer/gstreamer.git","description":null}
{"name":"la/platform/external/apache-velocity-engine","clone_url":"https://git.codelinaro.org/clo/la/platform/external/apache-velocity-engine.git","description":null}
{"name":"femto5g/oss/boot/lk-af","clone_url":"https://git.codelinaro.org/clo/femto5g/oss/boot/lk-af.git","description":null}
{"name":"testproject/platform/prebuilts/remoteexecution-client","clone_url":"https://git.codelinaro.org/clo/testproject/platform/prebuilts/remoteexecution-client.git","description":null}
{"name":"la/platform/vendor/nxp/opensource/keymaster","clone_url":"https://git.codelinaro.org/clo/la/platform/vendor/nxp/opensource/keymaster.git","description":null}
{"name":"yocto-mirrors/github/davecgh/go-spew","clone_url":"https://git.codelinaro.org/clo/yocto-mirrors/github/davecgh/go-spew.git","description":null}
{"name":"le/AGL/apps/phone","clone_url":"https://git.codelinaro.org/clo/le/AGL/apps/phone.git","description":null}
{"name":"le/platform/vendor/qcom-opensource/robot-navigation","clone_url":"https://git.codelinaro.org/clo/le/platform/vendor/qcom-opensource/robot-navigation.git","description":null}
{"name":"la/platform/prebuilts/clang/darwin-x86/x86/3.3","clone_url":"https://git.codelinaro.org/clo/la/platform/prebuilts/clang/darwin-x86/x86/3.3.git","description":null}
{"name":"la/platform/external/Reactive-Extensions/RxCpp","clone_url":"https://git.codelinaro.org/clo/la/platform/external/Reactive-Extensions/RxCpp.git","description":null}
{"name":"la/device/samsung/toro","clone_url":"https://git.codelinaro.org/clo/la/device/samsung/toro.git","description":null}
{"name":"la/platform/prebuilts/fullsdk-darwin/build-tools_group/31.0.0","clone_url":"https://git.codelinaro.org/clo/la/platform/prebuilts/fullsdk-darwin/build-tools_group/31.0.0.git","description":null}
{"name":"la/platform/packages/apps/SystemUIGo","clone_url":"https://git.codelinaro.org/clo/la/platform/packages/apps/SystemUIGo.git","description":null}
{"name":"testproject/platform/packages/apps/Messaging","clone_url":"https://git.codelinaro.org/clo/testproject/platform/packages/apps/Messaging.git","description":null}
{"name":"la/platform/system/memory/libdmabufheap","clone_url":"https://git.codelinaro.org/clo/la/platform/system/memory/libdmabufheap.git","description":null}
{"name":"la/platform/prebuilts/build-tools","clone_url":"https://git.codelinaro.org/clo/la/platform/prebuilts/build-tools.git","description":null}
{"name":"la/kernel/msm-extra_group/nfc-devicetree","clone_url":"https://git.codelinaro.org/clo/la/kernel/msm-extra_group/nfc-devicetree.git","description":null}
{"name":"la/device/google/crosshatch-sepolicy","clone_url":"https://git.codelinaro.org/clo/la/device/google/crosshatch-sepolicy.git","description":null}
{"name":"la/platform/external/ppp","clone_url":"https://git.codelinaro.org/clo/la/platform/external/ppp.git","description":null}
{"name":"qsdk/oss/system/openwrt_repo","clone_url":"https://git.codelinaro.org/clo/qsdk/oss/system/openwrt_repo.git","description":null}
{"name":"la/platform/system/desktop/ec","clone_url":"https://git.codelinaro.org/clo/la/platform/system/desktop/ec.git","description":null}
{"name":"la/platform/vendor/qcom/sdm429w/codeaurora/wlan/prima","clone_url":"https://git.codelinaro.org/clo/la/platform/vendor/qcom/sdm429w/codeaurora/wlan/prima.git","description":null}
{"name":"sba-patches/wfr_patches","clone_url":"https://git.codelinaro.org/clo/sba-patches/wfr_patches.git","description":null}
{"name":"la/platform/hardware/qcom/data/ipa-cfg-mgr","clone_url":"https://git.codelinaro.org/clo/la/platform/hardware/qcom/data/ipa-cfg-mgr.git","description":null}
{"name":"la/platform/vendor/qcom/opensource/datarmnet","clone_url":"https://git.codelinaro.org/clo/la/platform/vendor/qcom/opensource/datarmnet.git","description":null}
{"name":"qsdk/oss/system/feeds/packages","clone_url":"https://git.codelinaro.org/clo/qsdk/oss/system/feeds/packages.git","description":null}
{"name":"yocto-mirrors/github/jackaudio/jack2","clone_url":"https://git.codelinaro.org/clo/yocto-mirrors/github/jackaudio/jack2.git","description":null}
{"name":"la/platform/external/vixl","clone_url":"https://git.codelinaro.org/clo/la/platform/external/vixl.git","description":null}
{"name":"la/platform/external/linux-firmware","clone_url":"https://git.codelinaro.org/clo/la/platform/external/linux-firmware.git","description":null}
{"name":"la/tee/optee/ta/keymint","clone_url":"https://git.codelinaro.org/clo/la/tee/optee/ta/keymint.git","description":null}
{"name":"la/device/google/gs101-sepolicy","clone_url":"https://git.codelinaro.org/clo/la/device/google/gs101-sepolicy.git","description":null}
{"name":"le/owrt/openwrt-patches","clone_url":"https://git.codelinaro.org/clo/le/owrt/openwrt-patches.git","description":null}
{"name":"testproject/platform/packages/wallpapers/ImageWallpaper","clone_url":"https://git.codelinaro.org/clo/testproject/platform/packages/wallpapers/ImageWallpaper.git","description":null}
{"name":"la/platform/external/google-styleguide","clone_url":"https://git.codelinaro.org/clo/la/platform/external/google-styleguide.git","description":null}
{"name":"la/platform/external/boost-submodules/numeric/conversion","clone_url":"https://git.codelinaro.org/clo/la/platform/external/boost-submodules/numeric/conversion.git","description":null}
{"name":"la/platform/external/one-true-awk","clone_url":"https://git.codelinaro.org/clo/la/platform/external/one-true-awk.git","description":null}
{"name":"la/platform/external/googleapis-go-genproto","clone_url":"https://git.codelinaro.org/clo/la/platform/external/googleapis-go-genproto.git","description":null}
{"name":"le/qc/components/le-codec2-frameworks-lnx/oe-recipes-oss","clone_url":"https://git.codelinaro.org/clo/le/qc/components/le-codec2-frameworks-lnx/oe-recipes-oss.git","description":null}
{"name":"la/platform/system/tools/aidl","clone_url":"https://git.codelinaro.org/clo/la/platform/system/tools/aidl.git","description":null}
{"name":"la/platform/external/rust/crates/num_cpus","clone_url":"https://git.codelinaro.org/clo/la/platform/external/rust/crates/num_cpus.git","description":null}
{"name":"la/platform/prebuilts/renderscript/host/linux-x86","clone_url":"https://git.codelinaro.org/clo/la/platform/prebuilts/renderscript/host/linux-x86.git","description":null}
{"name":"testproject/platform/packages/providers/UserDictionaryProvider","clone_url":"https://git.codelinaro.org/clo/testproject/platform/packages/providers/UserDictionaryProvider.git","description":null}
{"name":"la/platform/external/jarjar","clone_url":"https://git.codelinaro.org/clo/la/platform/external/jarjar.git","description":null}
{"name":"qrdk/rdkcentral/media-terminal-adapter-agent","clone_url":"https://git.codelinaro.org/clo/qrdk/rdkcentral/media-terminal-adapter-agent.git","description":null}
{"name":"qsdk/agm","clone_url":"https://git.codelinaro.org/clo/qsdk/agm.git","description":null}
{"name":"la/vendor/maxim/tfcrypt","clone_url":"https://git.codelinaro.org/clo/la/vendor/maxim/tfcrypt.git","description":null}
{"name":"la/device/google/dragon","clone_url":"https://git.codelinaro.org/clo/la/device/google/dragon.git","description":null}
{"name":"la/platform/vendor/qcom-opensource/vibrator","clone_url":"https://git.codelinaro.org/clo/la/platform/vendor/qcom-opensource/vibrator.git","description":null}
{"name":"le/external/googletest","clone_url":"https://git.codelinaro.org/clo/le/external/googletest.git","description":null}
{"name":"la/platform/external/rust/crates/axum-core","clone_url":"https://git.codelinaro.org/clo/la/platform/external/rust/crates/axum-core.git","description":null}
{"name":"ype/external/yoctoproject.org/meta-tensorflow","clone_url":"https://git.codelinaro.org/clo/ype/external/yoctoproject.org/meta-tensorflow.git","description":null}
{"name":"la/platform/external/alsa-lib","clone_url":"https://git.codelinaro.org/clo/la/platform/external/alsa-lib.git","description":null}
{"name":"ath-firmware/patches","clone_url":"https://git.codelinaro.org/clo/ath-firmware/patches.git","description":null}
{"name":"la/platform/external/rust/crates/lock_api","clone_url":"https://git.codelinaro.org/clo/la/platform/external/rust/crates/lock_api.git","description":null}
{"name":"la/platform/external/libweave","clone_url":"https://git.codelinaro.org/clo/la/platform/external/libweave.git","description":null}
{"name":"la/platform/external/mock","clone_url":"https://git.codelinaro.org/clo/la/platform/external/mock.git","description":null}
{"name":"le/platform/system/QPlatformUtils","clone_url":"https://git.codelinaro.org/clo/le/platform/system/QPlatformUtils.git","description":null}
{"name":"la/kernel/common-patches","clone_url":"https://git.codelinaro.org/clo/la/kernel/common-patches.git","description":null}
{"name":"yocto-mirrors/github/tensorflow/tensorflow","clone_url":"https://git.codelinaro.org/clo/yocto-mirrors/github/tensorflow/tensorflow.git","description":null}
{"name":"la/platform/external/flac","clone_url":"https://git.codelinaro.org/clo/la/platform/external/flac.git","description":null}
{"name":"yocto-mirrors/github/defanglabs/secret-detector","clone_url":"https://git.codelinaro.org/clo/yocto-mirrors/github/defanglabs/secret-detector.git","description":null}
{"name":"la/platform/external/mpdecimal","clone_url":"https://git.codelinaro.org/clo/la/platform/external/mpdecimal.git","description":null}
{"name":"lc/chromiumos/overlays/portage","clone_url":"https://git.codelinaro.org/clo/lc/chromiumos/overlays/portage.git","description":null}
{"name":"la/platform/external/rust/crates/uefi-macros","clone_url":"https://git.codelinaro.org/clo/la/platform/external/rust/crates/uefi-macros.git","description":null}
{"name":"qsdk/oss/ubicom32-toolchain/linux-2.6.36-android","clone_url":"https://git.codelinaro.org/clo/qsdk/oss/ubicom32-toolchain/linux-2.6.36-android.git","description":null}
{"name":"le/AGL/iotbzh/agl-audio-plugin","clone_url":"https://git.codelinaro.org/clo/le/AGL/iotbzh/agl-audio-plugin.git","description":null}
{"name":"la/platform/hardware/bsp/bootloader/intel/edison-u-boot","clone_url":"https://git.codelinaro.org/clo/la/platform/hardware/bsp/bootloader/intel/edison-u-boot.git","description":null}
{"name":"la/platform/external/apache-http","clone_url":"https://git.codelinaro.org/clo/la/platform/external/apache-http.git","description":null}
{"name":"lc/external/coreboot.org/flashrom","clone_url":"https://git.codelinaro.org/clo/lc/external/coreboot.org/flashrom.git","description":null}
{"name":"la/platform/hardware/google/graphics/gs101","clone_url":"https://git.codelinaro.org/clo/la/platform/hardware/google/graphics/gs101.git","description":null}
{"name":"la/device/google/lynx-kernel","clone_url":"https://git.codelinaro.org/clo/la/device/google/lynx-kernel.git","description":null}
{"name":"testproject/platform/external/cros/system_api","clone_url":"https://git.codelinaro.org/clo/testproject/platform/external/cros/system_api.git","description":null}
{"name":"la/platform/external/wpa_supplicant","clone_url":"https://git.codelinaro.org/clo/la/platform/external/wpa_supplicant.git","description":null}
{"name":"le/ros2-gbp/rosidl_runtime_py-release","clone_url":"https://git.codelinaro.org/clo/le/ros2-gbp/rosidl_runtime_py-release.git","description":null}
{"name":"la/platform/external/libdrm","clone_url":"https://git.codelinaro.org/clo/la/platform/external/libdrm.git","description":null}
{"name":"yocto-mirrors/github/bugsnag/bugsnag-go","clone_url":"https://git.codelinaro.org/clo/yocto-mirrors/github/bugsnag/bugsnag-go.git","description":null}
{"name":"la/kernel/prebuilts/6.12/x86-64","clone_url":"https://git.codelinaro.org/clo/la/kernel/prebuilts/6.12/x86-64.git","description":null}
{"name":"testproject/platform/packages/modules/DnsResolver","clone_url":"https://git.codelinaro.org/clo/testproject/platform/packages/modules/DnsResolver.git","description":null}
{"name":"la/platform/frameworks/support","clone_url":"https://git.codelinaro.org/clo/la/platform/frameworks/support.git","description":null}
{"name":"la/trusty/app/sample","clone_url":"https://git.codelinaro.org/clo/la/trusty/app/sample.git","description":null}
{"name":"la/kernel_platform/external/rust/crates/smoltcp","clone_url":"https://git.codelinaro.org/clo/la/kernel_platform/external/rust/crates/smoltcp.git","description":null}
{"name":"lc/native_client/pnacl-compiler-rt","clone_url":"https://git.codelinaro.org/clo/lc/native_client/pnacl-compiler-rt.git","description":null}
{"name":"la/toolchain/ppl","clone_url":"https://git.codelinaro.org/clo/la/toolchain/ppl.git","description":null}
{"name":"le/platform/external/node","clone_url":"https://git.codelinaro.org/clo/le/platform/external/node.git","description":null}
{"name":"qsdk/platform/vendor/qcom-opensource/drone/wifibroadcast","clone_url":"https://git.codelinaro.org/clo/qsdk/platform/vendor/qcom-opensource/drone/wifibroadcast.git","description":null}
{"name":"la/platform/external/protobuf2.5","clone_url":"https://git.codelinaro.org/clo/la/platform/external/protobuf2.5.git","description":null}
{"name":"la/platform/system/server_configurable_flags","clone_url":"https://git.codelinaro.org/clo/la/platform/system/server_configurable_flags.git","description":null}
{"name":"le/meta-qti-cv","clone_url":"https://git.codelinaro.org/clo/le/meta-qti-cv.git","description":null}
{"name":"la/device/google/bramble-kernel","clone_url":"https://git.codelinaro.org/clo/la/device/google/bramble-kernel.git","description":null}
{"name":"la/platform/packages/apps/SettingsIntelligence","clone_url":"https://git.codelinaro.org/clo/la/platform/packages/apps/SettingsIntelligence.git","description":null}
{"name":"la/platform/vendor/qcom-opensource/rcs-service","clone_url":"https://git.codelinaro.org/clo/la/platform/vendor/qcom-opensource/rcs-service.git","description":null}
{"name":"le/mdm/manifest","clone_url":"https://git.codelinaro.org/clo/le/mdm/manifest.git","description":null}
{"name":"qcomlt/dhry-frequency","clone_url":"https://git.codelinaro.org/clo/qcomlt/dhry-frequency.git","description":null}
{"name":"la/platform/hardware/nvidia/tegra124","clone_url":"https://git.codelinaro.org/clo/la/platform/hardware/nvidia/tegra124.git","description":null}
{"name":"la/platform/external/eyes-free","clone_url":"https://git.codelinaro.org/clo/la/platform/external/eyes-free.git","description":null}
{"name":"la/platform/external/apache-apr","clone_url":"https://git.codelinaro.org/clo/la/platform/external/apache-apr.git","description":null}
{"name":"la/platform/packages/apps/Car/Hvac","clone_url":"https://git.codelinaro.org/clo/la/platform/packages/apps/Car/Hvac.git","description":null}
{"name":"la/platform/packages/modules/MediaSwCodec","clone_url":"https://git.codelinaro.org/clo/la/platform/packages/modules/MediaSwCodec.git","description":null}
{"name":"kernel-platform-2-0-os/kernel/build","clone_url":"https://git.codelinaro.org/clo/kernel-platform-2-0-os/kernel/build.git","description":null}
{"name":"le/tokio-uds-windows","clone_url":"https://git.codelinaro.org/clo/le/tokio-uds-windows.git","description":null}
{"name":"le/AGL/apps/mediaplayer","clone_url":"https://git.codelinaro.org/clo/le/AGL/apps/mediaplayer.git","description":null}
{"name":"la/platform/external/chromium_org_repo","clone_url":"https://git.codelinaro.org/clo/la/platform/external/chromium_org_repo.git","description":null}
{"name":"yocto-mirrors/github/google/glog","clone_url":"https://git.codelinaro.org/clo/yocto-mirrors/github/google/glog.git","description":null}
{"name":"qcomlt/pkg/rmtfs","clone_url":"https://git.codelinaro.org/clo/qcomlt/pkg/rmtfs.git","description":null}
{"name":"la/device/qcom/qssi_tiny_32go","clone_url":"https://git.codelinaro.org/clo/la/device/qcom/qssi_tiny_32go.git","description":null}
{"name":"yocto-mirrors/github/ros2-gbp/libyaml_vendor-release","clone_url":"https://git.codelinaro.org/clo/yocto-mirrors/github/ros2-gbp/libyaml_vendor-release.git","description":null}
{"name":"la/platform/frameworks/media/libvideoeditor","clone_url":"https://git.codelinaro.org/clo/la/platform/frameworks/media/libvideoeditor.git","description":null}
{"name":"lc/external/github.com/google/emoji-segmenter","clone_url":"https://git.codelinaro.org/clo/lc/external/github.com/google/emoji-segmenter.git","description":null}
{"name":"la/platform/external/boost-submodules/flyweight","clone_url":"https://git.codelinaro.org/clo/la/platform/external/boost-submodules/flyweight.git","description":null}
{"name":"la/platform/external/TestParameterInjector","clone_url":"https://git.codelinaro.org/clo/la/platform/external/TestParameterInjector.git","description":null}
{"name":"external-wlan/tools","clone_url":"https://git.codelinaro.org/clo/external-wlan/tools.git","description":null}
{"name":"external-ubicom/ubi32-newlib","clone_url":"https://git.codelinaro.org/clo/external-ubicom/ubi32-newlib.git","description":null}
{"name":"la/platform/external/libffi","clone_url":"https://git.codelinaro.org/clo/la/platform/external/libffi.git","description":null}
{"name":"la/platform/system/acpi/bert_collector","clone_url":"https://git.codelinaro.org/clo/la/platform/system/acpi/bert_collector.git","description":null}
{"name":"testproject/platform/external/selinux","clone_url":"https://git.codelinaro.org/clo/testproject/platform/external/selinux.git","description":null}
{"name":"le/gstreamer/gst-mprtp","clone_url":"https://git.codelinaro.org/clo/le/gstreamer/gst-mprtp.git","description":null}
{"name":"yocto-mirrors/github/golang-sql/civil","clone_url":"https://git.codelinaro.org/clo/yocto-mirrors/github/golang-sql/civil.git","description":null}
{"name":"yocto-mirrors/github/mattn/go-runewidth","clone_url":"https://git.codelinaro.org/clo/yocto-mirrors/github/mattn/go-runewidth.git","description":null}
{"name":"lc/weave/cocoapods","clone_url":"https://git.codelinaro.org/clo/lc/weave/cocoapods.git","description":null}
{"name":"le/ros2-gbp/fastrtps-release","clone_url":"https://git.codelinaro.org/clo/le/ros2-gbp/fastrtps-release.git","description":null}
{"name":"testproject/device/generic/uml","clone_url":"https://git.codelinaro.org/clo/testproject/device/generic/uml.git","description":null}
{"name":"la/meta-qti-eva","clone_url":"https://git.codelinaro.org/clo/la/meta-qti-eva.git","description":null}
{"name":"la/platform/external/opencl/llvm-project","clone_url":"https://git.codelinaro.org/clo/la/platform/external/opencl/llvm-project.git","description":null}
{"name":"la/platform/external/flex","clone_url":"https://git.codelinaro.org/clo/la/platform/external/flex.git","description":null}
{"name":"le/genivi/persistence/persistence-client-library","clone_url":"https://git.codelinaro.org/clo/le/genivi/persistence/persistence-client-library.git","description":null}
{"name":"la/platform/external/rust/crates/adler","clone_url":"https://git.codelinaro.org/clo/la/platform/external/rust/crates/adler.git","description":null}
{"name":"lc/infra/rietveld","clone_url":"https://git.codelinaro.org/clo/lc/infra/rietveld.git","description":null}
{"name":"la/platform/external/rust/crates/drm-fourcc","clone_url":"https://git.codelinaro.org/clo/la/platform/external/rust/crates/drm-fourcc.git","description":null}
{"name":"la/platform/external/google-breakpad","clone_url":"https://git.codelinaro.org/clo/la/platform/external/google-breakpad.git","description":null}
{"name":"testproject/platform/external/rust/crates/quote","clone_url":"https://git.codelinaro.org/clo/testproject/platform/external/rust/crates/quote.git","description":null}
{"name":"la/toolchain/capnproto","clone_url":"https://git.codelinaro.org/clo/la/toolchain/capnproto.git","description":null}
{"name":"la/platform/prebuilts/rust-toolchain/linux-x86","clone_url":"https://git.codelinaro.org/clo/la/platform/prebuilts/rust-toolchain/linux-x86.git","description":null}
{"name":"la/platform/vendor/qcom/tellurium_32","clone_url":"https://git.codelinaro.org/clo/la/platform/vendor/qcom/tellurium_32.git","description":null}
{"name":"le/platform/external/libweave","clone_url":"https://git.codelinaro.org/clo/le/platform/external/libweave.git","description":null}
{"name":"la/platform/external/libopenapv","clone_url":"https://git.codelinaro.org/clo/la/platform/external/libopenapv.git","description":null}
{"name":"yocto-mirrors/github/google/shaderc","clone_url":"https://git.codelinaro.org/clo/yocto-mirrors/github/google/shaderc.git","description":null}
{"name":"la/platform/packages/apps/QuickAccessWallet","clone_url":"https://git.codelinaro.org/clo/la/platform/packages/apps/QuickAccessWallet.git","description":null}
{"name":"la/platform/tools/content_addressed_storage/src","clone_url":"https://git.codelinaro.org/clo/la/platform/tools/content_addressed_storage/src.git","description":null}
{"name":"la/platform/vendor/qcom-opensource/adk-tools","clone_url":"https://git.codelinaro.org/clo/la/platform/vendor/qcom-opensource/adk-tools.git","description":null}
{"name":"rdkb/rdk/components/generic/rdk_logger","clone_url":"https://git.codelinaro.org/clo/rdkb/rdk/components/generic/rdk_logger.git","description":null}
{"name":"la/device/google/wahoo-kernel","clone_url":"https://git.codelinaro.org/clo/la/device/google/wahoo-kernel.git","description":null}
{"name":"la/kernel/msm-3.18","clone_url":"https://git.codelinaro.org/clo/la/kernel/msm-3.18.git","description":null}
{"name":"la/platform/external/python/httplib2","clone_url":"https://git.codelinaro.org/clo/la/platform/external/python/httplib2.git","description":null}
{"name":"le/platform/vendor/qcom-opensource/audio_mcs","clone_url":"https://git.codelinaro.org/clo/le/platform/vendor/qcom-opensource/audio_mcs.git","description":null}
{"name":"la/platform/external/rust/crates/num_enum_derive","clone_url":"https://git.codelinaro.org/clo/la/platform/external/rust/crates/num_enum_derive.git","description":null}
{"name":"yocto-mirrors/github/gofrs/flock","clone_url":"https://git.codelinaro.org/clo/yocto-mirrors/github/gofrs/flock.git","description":null}
{"name":"testproject/platform/prebuilts/gcc/linux-x86/arm/arm-eabi-4.8","clone_url":"https://git.codelinaro.org/clo/testproject/platform/prebuilts/gcc/linux-x86/arm/arm-eabi-4.8.git","description":null}
{"name":"la/platform/hardware/ti/wpan","clone_url":"https://git.codelinaro.org/clo/la/platform/hardware/ti/wpan.git","description":null}
{"name":"la/platform/prebuilts/fullsdk-linux/build-tools_group/32.0.0","clone_url":"https://git.codelinaro.org/clo/la/platform/prebuilts/fullsdk-linux/build-tools_group/32.0.0.git","description":null}
{"name":"la/platform/vendor/qcom/mpq8092","clone_url":"https://git.codelinaro.org/clo/la/platform/vendor/qcom/mpq8092.git","description":null}
{"name":"le/meta-genivi-demo","clone_url":"https://git.codelinaro.org/clo/le/meta-genivi-demo.git","description":null}
{"name":"la/platform/prebuilts/cmake/linux-arm64","clone_url":"https://git.codelinaro.org/clo/la/platform/prebuilts/cmake/linux-arm64.git","description":null}
{"name":"le/external/civetweb","clone_url":"https://git.codelinaro.org/clo/le/external/civetweb.git","description":null}
{"name":"la/toolchain/jdk/jdk9_nashorn","clone_url":"https://git.codelinaro.org/clo/la/toolchain/jdk/jdk9_nashorn.git","description":null}
{"name":"le/matter","clone_url":"https://git.codelinaro.org/clo/le/matter.git","description":null}
{"name":"le/meta-qti-qmmf","clone_url":"https://git.codelinaro.org/clo/le/meta-qti-qmmf.git","description":null}
{"name":"la/platform/prebuilts/module_sdk/WebViewBootstrap","clone_url":"https://git.codelinaro.org/clo/la/platform/prebuilts/module_sdk/WebViewBootstrap.git","description":null}
{"name":"yocto-mirrors/github/thkukuk/libnsl","clone_url":"https://git.codelinaro.org/clo/yocto-mirrors/github/thkukuk/libnsl.git","description":null}
{"name":"la/platform/external/vulkan-headers","clone_url":"https://git.codelinaro.org/clo/la/platform/external/vulkan-headers.git","description":null}
