{"name":"le/external/github.com/DaveGamble/cJSON","clone_url":"https://git.codelinaro.org/clo/le/external/github.com/DaveGamble/cJSON.git","description":null}
{"name":"qrdk/pps-tools","clone_url":"https://git.codelinaro.org/clo/qrdk/pps-tools.git","description":null}
{"name":"testproject/device/generic/x86_64","clone_url":"https://git.codelinaro.org/clo/testproject/device/generic/x86_64.git","description":null}
{"name":"testproject/platform/prebuilts/gcc/linux-x86/host/x86_64-linux-glibc2.17-4.8","clone_url":"https://git.codelinaro.org/clo/testproject/platform/prebuilts/gcc/linux-x86/host/x86_64-linux-glibc2.17-4.8.git","description":null}
{"name":"la/platform/external/rust/crates/tungstenite","clone_url":"https://git.codelinaro.org/clo/la/platform/external/rust/crates/tungstenite.git","description":null}
{"name":"la/platform/external/lldb-utils","clone_url":"https://git.codelinaro.org/clo/la/platform/external/lldb-utils.git","description":null}
{"name":"la/platform/hardware/qcom/sm8150/gps","clone_url":"https://git.codelinaro.org/clo/la/platform/hardware/qcom/sm8150/gps.git","description":null}
{"name":"la/platform/external/rust/crates/combine","clone_url":"https://git.codelinaro.org/clo/la/platform/external/rust/crates/combine.git","description":null}
{"name":"la/packages/apps/car/DriverUIPrebuilt","clone_url":"https://git.codelinaro.org/clo/la/packages/apps/car/DriverUIPrebuilt.git","description":null}
{"name":"la/platform/external/jcommander","clone_url":"https://git.codelinaro.org/clo/la/platform/external/jcommander.git","description":null}
{"name":"la/platform/external/rust/crates/toml","clone_url":"https://git.codelinaro.org/clo/la/platform/external/rust/crates/toml.git","description":null}
{"name":"testproject/platform/external/FXdiv","clone_url":"https://git.codelinaro.org/clo/testproject/platform/external/FXdiv.git","description":null}
{"name":"la/platform/packages/services/LockAndWipe","clone_url":"https://git.codelinaro.org/clo/la/platform/packages/services/LockAndWipe.git","description":null}
{"name":"testproject/platform/tools/currysrc","clone_url":"https://git.codelinaro.org/clo/testproject/platform/tools/currysrc.git","description":null}
{"name":"testproject/platform/prebuilts/abi-dumps/vndk","clone_url":"https://git.codelinaro.org/clo/testproject/platform/prebuilts/abi-dumps/vndk.git","description":null}
{"name":"lc/external/github.com/polymer/polymer-expressions","clone_url":"https://git.codelinaro.org/clo/lc/external/github.com/polymer/polymer-expressions.git","description":null}
{"name":"yocto-mirrors/github/ros2-gbp/urdf-release","clone_url":"https://git.codelinaro.org/clo/yocto-mirrors/github/ros2-gbp/urdf-release.git","description":null}
{"name":"testproject/platform/system/tools/sysprop","clone_url":"https://git.codelinaro.org/clo/testproject/platform/system/tools/sysprop.git","description":null}
{"name":"la/platform/external/rust/crates/spin","clone_url":"https://git.codelinaro.org/clo/la/platform/external/rust/crates/spin.git","description":null}
{"name":"la/platform/system/libvintf","clone_url":"https://git.codelinaro.org/clo/la/platform/system/libvintf.git","description":null}
{"name":"la/platform/prebuilts/fullsdk-linux/build-tools_group/28.0.2","clone_url":"https://git.codelinaro.org/clo/la/platform/prebuilts/fullsdk-linux/build-tools_group/28.0.2.git","description":null}
{"name":"la/platform/prebuilts/gdb/linux-x86","clone_url":"https://git.codelinaro.org/clo/la/platform/prebuilts/gdb/linux-x86.git","description":null}
{"name":"qsdk/qca/feeds/qca-son-mem-debug","clone_url":"https://git.codelinaro.org/clo/qsdk/qca/feeds/qca-son-mem-debug.git","description":null}
{"name":"qsdk/oss/lklm/qca-ssdk","clone_url":"https://git.codelinaro.org/clo/qsdk/oss/lklm/qca-ssdk.git","description":null}
{"name":"qrdk/cimplog","clone_url":"https://git.codelinaro.org/clo/qrdk/cimplog.git","description":null}
{"name":"femto5g/oss/lklm/nss-macsec","clone_url":"https://git.codelinaro.org/clo/femto5g/oss/lklm/nss-macsec.git","description":null}
{"name":"testproject/device/generic/art","clone_url":"https://git.codelinaro.org/clo/testproject/device/generic/art.git","description":null}
{"name":"la/toolchain/prebuilts/ndk/r26","clone_url":"https://git.codelinaro.org/clo/la/toolchain/prebuilts/ndk/r26.git","description":null}
{"name":"la/platform/packages/providers/ContactsProvider","clone_url":"https://git.codelinaro.org/clo/la/platform/packages/providers/ContactsProvider.git","description":null}
{"name":"lc/chromiumos/third_party/libc-bench","clone_url":"https://git.codelinaro.org/clo/lc/chromiumos/third_party/libc-bench.git","description":null}
{"name":"la/platform/vendor/qcom/msm7627_surf","clone_url":"https://git.codelinaro.org/clo/la/platform/vendor/qcom/msm7627_surf.git","description":null}
{"name":"lc/apps/screensaver","clone_url":"https://git.codelinaro.org/clo/lc/apps/screensaver.git","description":null}
{"name":"kernel-platform-2-0-os/abl/tianocore/edk2","clone_url":"https://git.codelinaro.org/clo/kernel-platform-2-0-os/abl/tianocore/edk2.git","description":null}
{"name":"femto5g/platform/system/core","clone_url":"https://git.codelinaro.org/clo/femto5g/platform/system/core.git","description":null}
{"name":"la/platform/external/google-fonts/coming-soon","clone_url":"https://git.codelinaro.org/clo/la/platform/external/google-fonts/coming-soon.git","description":null}
{"name":"le/external/civetweb","clone_url":"https://git.codelinaro.org/clo/le/external/civetweb.git","description":null}
{"name":"k2c-yocto-track1/meta-qcom-robotics-sdk","clone_url":"https://git.codelinaro.org/clo/k2c-yocto-track1/meta-qcom-robotics-sdk.git","description":null}
{"name":"la/platform/prebuilts/fullsdk/sources/android-32","clone_url":"https://git.codelinaro.org/clo/la/platform/prebuilts/fullsdk/sources/android-32.git","description":null}
{"name":"caf-patches/patches","clone_url":"https://git.codelinaro.org/clo/caf-patches/patches.git","description":null}
{"name":"le/platform/external/libusb","clone_url":"https://git.codelinaro.org/clo/le/platform/external/libusb.git","description":null}
{"name":"la/platform/vendor/qcom-opensource/crosvm-gunyah","clone_url":"https://git.codelinaro.org/clo/la/platform/vendor/qcom-opensource/crosvm-gunyah.git","description":null}
{"name":"le/platform/vendor/qcom-opensource/bt-devicetree","clone_url":"https://git.codelinaro.org/clo/le/platform/vendor/qcom-opensource/bt-devicetree.git","description":null}
{"name":"la/platform/external/rust/crates/memmap2","clone_url":"https://git.codelinaro.org/clo/la/platform/external/rust/crates/memmap2.git","description":null}
{"name":"la/platform/external/rust/crates/unicode-bidi","clone_url":"https://git.codelinaro.org/clo/la/platform/external/rust/crates/unicode-bidi.git","description":null}
{"name":"testproject/platform/external/xz-java","clone_url":"https://git.codelinaro.org/clo/testproject/platform/external/xz-java.git","description":null}
{"name":"testproject/platform/external/parameter-framework","clone_url":"https://git.codelinaro.org/clo/testproject/platform/external/parameter-framework.git","description":null}
{"name":"la/external/github.com/quic-qrb-ros/qrb_ros_video","clone_url":"https://git.codelinaro.org/clo/la/external/github.com/quic-qrb-ros/qrb_ros_video.git","description":null}
{"name":"le/ros2-gbp/rosidl_runtime_py-release","clone_url":"https://git.codelinaro.org/clo/le/ros2-gbp/rosidl_runtime_py-release.git","description":null}
{"name":"yocto-mirrors/glibc","clone_url":"https://git.codelinaro.org/clo/yocto-mirrors/glibc.git","description":null}
{"name":"la/platform/external/bazelbuild-rules_pkg","clone_url":"https://git.codelinaro.org/clo/la/platform/external/bazelbuild-rules_pkg.git","description":null}
{"name":"le/platform/external/ofono","clone_url":"https://git.codelinaro.org/clo/le/platform/external/ofono.git","description":null}
{"name":"la/platform/prebuilts/bundletool","clone_url":"https://git.codelinaro.org/clo/la/platform/prebuilts/bundletool.git","description":null}
{"name":"le/qc/components/videotxr-userspace-lnx/oe-recipes-oss","clone_url":"https://git.codelinaro.org/clo/le/qc/components/videotxr-userspace-lnx/oe-recipes-oss.git","description":null}
{"name":"la/platform/libcore-snapshot","clone_url":"https://git.codelinaro.org/clo/la/platform/libcore-snapshot.git","description":null}
{"name":"le/ros2-gbp/rcl-release","clone_url":"https://git.codelinaro.org/clo/le/ros2-gbp/rcl-release.git","description":null}
{"name":"le/TresysTechnology/refpolicy","clone_url":"https://git.codelinaro.org/clo/le/TresysTechnology/refpolicy.git","description":null}
{"name":"la/kernel_platform/external/bazelbuild-rules_shell","clone_url":"https://git.codelinaro.org/clo/la/kernel_platform/external/bazelbuild-rules_shell.git","description":null}
{"name":"testproject/platform/external/okhttp","clone_url":"https://git.codelinaro.org/clo/testproject/platform/external/okhttp.git","description":null}
{"name":"la/platform/frameworks/support-golden","clone_url":"https://git.codelinaro.org/clo/la/platform/frameworks/support-golden.git","description":null}
{"name":"la/platform/vendor/qcom-opensource/wlan/qca-wifi-host-cmn","clone_url":"https://git.codelinaro.org/clo/la/platform/vendor/qcom-opensource/wlan/qca-wifi-host-cmn.git","description":null}
{"name":"la/la/vendor/manifest","clone_url":"https://git.codelinaro.org/clo/la/la/vendor/manifest.git","description":null}
{"name":"la/platform/prebuilts/abi-dumps/ndk","clone_url":"https://git.codelinaro.org/clo/la/platform/prebuilts/abi-dumps/ndk.git","description":null}
{"name":"rdkb/rdkb/components/opensource/ccsp/GwProvApp-ePON","clone_url":"https://git.codelinaro.org/clo/rdkb/rdkb/components/opensource/ccsp/GwProvApp-ePON.git","description":null}
{"name":"la/platform/prebuilts/gcc/darwin-x86/x86/i686-linux-android-4.7","clone_url":"https://git.codelinaro.org/clo/la/platform/prebuilts/gcc/darwin-x86/x86/i686-linux-android-4.7.git","description":null}
{"name":"la/platform/external/yapf","clone_url":"https://git.codelinaro.org/clo/la/platform/external/yapf.git","description":null}
{"name":"lc/external/github.com/square/go-jose","clone_url":"https://git.codelinaro.org/clo/lc/external/github.com/square/go-jose.git","description":null}
{"name":"lc/external/github.com/googlecloudplatform/appengine-pipelines","clone_url":"https://git.codelinaro.org/clo/lc/external/github.com/googlecloudplatform/appengine-pipelines.git","description":null}
{"name":"la/platform/external/sfntly","clone_url":"https://git.codelinaro.org/clo/la/platform/external/sfntly.git","description":null}
{"name":"le/sba_patches","clone_url":"https://git.codelinaro.org/clo/le/sba_patches.git","description":null}
{"name":"la/device/marvell/abox_edge","clone_url":"https://git.codelinaro.org/clo/la/device/marvell/abox_edge.git","description":null}
{"name":"la/platform/external/apache-harmony","clone_url":"https://git.codelinaro.org/clo/la/platform/external/apache-harmony.git","description":null}
{"name":"la/platform/external/libudev-zero","clone_url":"https://git.codelinaro.org/clo/la/platform/external/libudev-zero.git","description":null}
{"name":"la/platform/external/proguard","clone_url":"https://git.codelinaro.org/clo/la/platform/external/proguard.git","description":null}
{"name":"le/meta-genivi-demo","clone_url":"https://git.codelinaro.org/clo/le/meta-genivi-demo.git","description":null}
{"name":"le/legatoproject/legato-3rdParty-jansson","clone_url":"https://git.codelinaro.org/clo/le/legatoproject/legato-3rdParty-jansson.git","description":null}
{"name":"la/platform/external/libnl-headers","clone_url":"https://git.codelinaro.org/clo/la/platform/external/libnl-headers.git","description":null}
{"name":"le/OTA/external/bsdiff","clone_url":"https://git.codelinaro.org/clo/le/OTA/external/bsdiff.git","description":null}
{"name":"la/platform/external/patchelf","clone_url":"https://git.codelinaro.org/clo/la/platform/external/patchelf.git","description":null}
{"name":"testproject/platform/prebuilts/asuite","clone_url":"https://git.codelinaro.org/clo/testproject/platform/prebuilts/asuite.git","description":null}
{"name":"la/platform/prebuilts/gas/linux-x86","clone_url":"https://git.codelinaro.org/clo/la/platform/prebuilts/gas/linux-x86.git","description":null}
{"name":"la/platform/external/neven","clone_url":"https://git.codelinaro.org/clo/la/platform/external/neven.git","description":null}
{"name":"la/kernel/msm-4.4","clone_url":"https://git.codelinaro.org/clo/la/kernel/msm-4.4.git","description":null}
{"name":"lc/chromiumos/third_party/coreboot/blobs","clone_url":"https://git.codelinaro.org/clo/lc/chromiumos/third_party/coreboot/blobs.git","description":null}
{"name":"testproject/platform/packages/apps/SampleLocationAttribution","clone_url":"https://git.codelinaro.org/clo/testproject/platform/packages/apps/SampleLocationAttribution.git","description":null}
{"name":"le/genivi/persistence/persistence-client-library","clone_url":"https://git.codelinaro.org/clo/le/genivi/persistence/persistence-client-library.git","description":null}
{"name":"le/meta-qti-bsp","clone_url":"https://git.codelinaro.org/clo/le/meta-qti-bsp.git","description":null}
{"name":"le/external/github.com/maratyszcza/FP16","clone_url":"https://git.codelinaro.org/clo/le/external/github.com/maratyszcza/FP16.git","description":null}
{"name":"le/platform/vendor/qcom-opensource/dp-lib","clone_url":"https://git.codelinaro.org/clo/le/platform/vendor/qcom-opensource/dp-lib.git","description":null}
{"name":"lc/external/github.com/rlovelett/eigen","clone_url":"https://git.codelinaro.org/clo/lc/external/github.com/rlovelett/eigen.git","description":null}
{"name":"la/platform/external/checkstyle","clone_url":"https://git.codelinaro.org/clo/la/platform/external/checkstyle.git","description":null}
{"name":"la/platform/prebuilts/module_sdk/Permission","clone_url":"https://git.codelinaro.org/clo/la/platform/prebuilts/module_sdk/Permission.git","description":null}
{"name":"la/techpack/audio/manifest","clone_url":"https://git.codelinaro.org/clo/la/techpack/audio/manifest.git","description":null}
{"name":"la/trusty/device/x86/generic-x86_64","clone_url":"https://git.codelinaro.org/clo/la/trusty/device/x86/generic-x86_64.git","description":null}
{"name":"la/platform/external/rust/crates/addr2line","clone_url":"https://git.codelinaro.org/clo/la/platform/external/rust/crates/addr2line.git","description":null}
{"name":"la/platform/external/python/astroid","clone_url":"https://git.codelinaro.org/clo/la/platform/external/python/astroid.git","description":null}
{"name":"le/qcom-docker","clone_url":"https://git.codelinaro.org/clo/le/qcom-docker.git","description":null}
{"name":"qrdk/rdkcentral/rdkb-halif-wifi","clone_url":"https://git.codelinaro.org/clo/qrdk/rdkcentral/rdkb-halif-wifi.git","description":null}
{"name":"yocto-mirrors/benchmark","clone_url":"https://git.codelinaro.org/clo/yocto-mirrors/benchmark.git","description":null}
{"name":"qcomlt/wcnss-config","clone_url":"https://git.codelinaro.org/clo/qcomlt/wcnss-config.git","description":null}
{"name":"la/platform/external/cros_vboot_reference","clone_url":"https://git.codelinaro.org/clo/la/platform/external/cros_vboot_reference.git","description":null}
{"name":"qrdk/protobuf","clone_url":"https://git.codelinaro.org/clo/qrdk/protobuf.git","description":null}
{"name":"yocto-mirrors/github/k3s-io/k3s","clone_url":"https://git.codelinaro.org/clo/yocto-mirrors/github/k3s-io/k3s.git","description":null}
{"name":"la/platform/system/wlan/ti","clone_url":"https://git.codelinaro.org/clo/la/platform/system/wlan/ti.git","description":null}
{"name":"la/kernel_platform/toolchain/prebuilts/ndk/r23","clone_url":"https://git.codelinaro.org/clo/la/kernel_platform/toolchain/prebuilts/ndk/r23.git","description":null}
{"name":"yocto-mirrors/github/cisco/libsrtp","clone_url":"https://git.codelinaro.org/clo/yocto-mirrors/github/cisco/libsrtp.git","description":null}
{"name":"le/platform/vendor/qcom-opensource/system/bt","clone_url":"https://git.codelinaro.org/clo/le/platform/vendor/qcom-opensource/system/bt.git","description":null}
{"name":"lc/chromium/pipa","clone_url":"https://git.codelinaro.org/clo/lc/chromium/pipa.git","description":null}
{"name":"la/platform/external/pandora/avatar","clone_url":"https://git.codelinaro.org/clo/la/platform/external/pandora/avatar.git","description":null}
{"name":"qsdk/oss/feeds/nss","clone_url":"https://git.codelinaro.org/clo/qsdk/oss/feeds/nss.git","description":null}
{"name":"yocto-mirrors/github/containers/fuse-overlayfs","clone_url":"https://git.codelinaro.org/clo/yocto-mirrors/github/containers/fuse-overlayfs.git","description":null}
{"name":"lf/patches","clone_url":"https://git.codelinaro.org/clo/lf/patches.git","description":null}
{"name":"le/platform/external/world_canvas_msgs","clone_url":"https://git.codelinaro.org/clo/le/platform/external/world_canvas_msgs.git","description":null}
{"name":"testproject/platform/system/gsid","clone_url":"https://git.codelinaro.org/clo/testproject/platform/system/gsid.git","description":null}
{"name":"testproject/platform/external/libcxx","clone_url":"https://git.codelinaro.org/clo/testproject/platform/external/libcxx.git","description":null}
{"name":"yocto-mirrors/github/ros2-gbp/launch-release","clone_url":"https://git.codelinaro.org/clo/yocto-mirrors/github/ros2-gbp/launch-release.git","description":null}
{"name":"lc/external/github.com/google/cld_3","clone_url":"https://git.codelinaro.org/clo/lc/external/github.com/google/cld_3.git","description":null}
{"name":"le/platform/external/libweave","clone_url":"https://git.codelinaro.org/clo/le/platform/external/libweave.git","description":null}
{"name":"la/platform/vendor/qcom/tellurium_32","clone_url":"https://git.codelinaro.org/clo/la/platform/vendor/qcom/tellurium_32.git","description":null}
{"name":"sba-patches/qdt_dfc_patches","clone_url":"https://git.codelinaro.org/clo/sba-patches/qdt_dfc_patches.git","description":null}
{"name":"la/platform/packages/apps/Multiuser","clone_url":"https://git.codelinaro.org/clo/la/platform/packages/apps/Multiuser.git","description":null}
{"name":"la/platform/vendor/codeaurora/packages/apps/SoundRecorder","clone_url":"https://git.codelinaro.org/clo/la/platform/vendor/codeaurora/packages/apps/SoundRecorder.git","description":null}
{"name":"le/flatbuffers","clone_url":"https://git.codelinaro.org/clo/le/flatbuffers.git","description":null}
{"name":"yocto-mirrors/github/mxk/go-flowrate","clone_url":"https://git.codelinaro.org/clo/yocto-mirrors/github/mxk/go-flowrate.git","description":null}
{"name":"qsdk/oss/kernel/linux-ipq-patches-6.6","clone_url":"https://git.codelinaro.org/clo/qsdk/oss/kernel/linux-ipq-patches-6.6.git","description":null}
{"name":"la/platform/hardware/intel/common/libmix","clone_url":"https://git.codelinaro.org/clo/la/platform/hardware/intel/common/libmix.git","description":null}
{"name":"qcomlt/ci/linux-automerge","clone_url":"https://git.codelinaro.org/clo/qcomlt/ci/linux-automerge.git","description":null}
{"name":"le/platform/external/wireshark-fapi-ecpri","clone_url":"https://git.codelinaro.org/clo/le/platform/external/wireshark-fapi-ecpri.git","description":null}
{"name":"la/platform/external/rust/crates/uniffi_core","clone_url":"https://git.codelinaro.org/clo/la/platform/external/rust/crates/uniffi_core.git","description":null}
{"name":"lc/infra/infra_repo","clone_url":"https://git.codelinaro.org/clo/lc/infra/infra_repo.git","description":null}
{"name":"la/kernel_platform/prebuilts/rust","clone_url":"https://git.codelinaro.org/clo/la/kernel_platform/prebuilts/rust.git","description":null}
{"name":"yocto-mirrors/github/hashicorp/hcl","clone_url":"https://git.codelinaro.org/clo/yocto-mirrors/github/hashicorp/hcl.git","description":null}
{"name":"le/owrt/feeds/feed_opensource","clone_url":"https://git.codelinaro.org/clo/le/owrt/feeds/feed_opensource.git","description":null}
{"name":"rdkb/rdkb/components/opensource/ccsp/RdkVlanBridgingManager","clone_url":"https://git.codelinaro.org/clo/rdkb/rdkb/components/opensource/ccsp/RdkVlanBridgingManager.git","description":null}
{"name":"qrdk/rdkcentral/hotspot","clone_url":"https://git.codelinaro.org/clo/qrdk/rdkcentral/hotspot.git","description":null}
{"name":"la/kernel/devices/google/eos","clone_url":"https://git.codelinaro.org/clo/la/kernel/devices/google/eos.git","description":null}
{"name":"la/platform/prebuilts/cmake/linux-arm64","clone_url":"https://git.codelinaro.org/clo/la/platform/prebuilts/cmake/linux-arm64.git","description":null}
{"name":"qsdk/jsoncpp","clone_url":"https://git.codelinaro.org/clo/qsdk/jsoncpp.git","description":null}
{"name":"la/platform/test/AfwTestHarness","clone_url":"https://git.codelinaro.org/clo/la/platform/test/AfwTestHarness.git","description":null}
{"name":"lc/external/bidichecker/lib","clone_url":"https://git.codelinaro.org/clo/lc/external/bidichecker/lib.git","description":null}
{"name":"la/platform/packages/wallpapers/ImageWallpaper","clone_url":"https://git.codelinaro.org/clo/la/platform/packages/wallpapers/ImageWallpaper.git","description":null}
{"name":"la/kernel/devices/google/lynx","clone_url":"https://git.codelinaro.org/clo/la/kernel/devices/google/lynx.git","description":null}
{"name":"testproject/platform/packages/modules/vndk","clone_url":"https://git.codelinaro.org/clo/testproject/platform/packages/modules/vndk.git","description":null}
{"name":"qcomlt/ci/u-boot/configs","clone_url":"https://git.codelinaro.org/clo/qcomlt/ci/u-boot/configs.git","description":null}
{"name":"la/platform/external/python/dill","clone_url":"https://git.codelinaro.org/clo/la/platform/external/python/dill.git","description":null}
{"name":"la/platform/vendor/qcom/sdw3100alpha","clone_url":"https://git.codelinaro.org/clo/la/platform/vendor/qcom/sdw3100alpha.git","description":null}
{"name":"lc/external/webrtc/trunk/samples/js","clone_url":"https://git.codelinaro.org/clo/lc/external/webrtc/trunk/samples/js.git","description":null}
{"name":"qsdk/oss/qca/src/btconfig","clone_url":"https://git.codelinaro.org/clo/qsdk/oss/qca/src/btconfig.git","description":null}
{"name":"lc/external/github.com/pkg/errors","clone_url":"https://git.codelinaro.org/clo/lc/external/github.com/pkg/errors.git","description":null}
{"name":"lc/external/github.com/stackexchange/wmi","clone_url":"https://git.codelinaro.org/clo/lc/external/github.com/stackexchange/wmi.git","description":null}
{"name":"lc/external/github.com/square/leakcanary","clone_url":"https://git.codelinaro.org/clo/lc/external/github.com/square/leakcanary.git","description":null}
{"name":"la/platform/prebuilts/androidx/xr","clone_url":"https://git.codelinaro.org/clo/la/platform/prebuilts/androidx/xr.git","description":null}
{"name":"la/platform/external/rust/crates/gbm","clone_url":"https://git.codelinaro.org/clo/la/platform/external/rust/crates/gbm.git","description":null}
{"name":"lc/chromiumos/platform/recovery_installer","clone_url":"https://git.codelinaro.org/clo/lc/chromiumos/platform/recovery_installer.git","description":null}
{"name":"le/ros-perception/image_common","clone_url":"https://git.codelinaro.org/clo/le/ros-perception/image_common.git","description":null}
{"name":"testproject/platform/external/python/pyasn1","clone_url":"https://git.codelinaro.org/clo/testproject/platform/external/python/pyasn1.git","description":null}
{"name":"la/platform/external/python/ptyprocess","clone_url":"https://git.codelinaro.org/clo/la/platform/external/python/ptyprocess.git","description":null}
{"name":"le/softwarecontainer","clone_url":"https://git.codelinaro.org/clo/le/softwarecontainer.git","description":null}
{"name":"lc/infra/testing_support","clone_url":"https://git.codelinaro.org/clo/lc/infra/testing_support.git","description":null}
{"name":"la/device/asus/fugu-kernel","clone_url":"https://git.codelinaro.org/clo/la/device/asus/fugu-kernel.git","description":null}
{"name":"le/platform/vendor/qcom-opensource/display-commonsys-intf","clone_url":"https://git.codelinaro.org/clo/le/platform/vendor/qcom-opensource/display-commonsys-intf.git","description":null}
{"name":"le/meta-qti-sepolicy","clone_url":"https://git.codelinaro.org/clo/le/meta-qti-sepolicy.git","description":null}
{"name":"qsdk/agm","clone_url":"https://git.codelinaro.org/clo/qsdk/agm.git","description":null}
{"name":"la/platform/external/rust/crates/http","clone_url":"https://git.codelinaro.org/clo/la/platform/external/rust/crates/http.git","description":null}
{"name":"lc/external/github.com/sergiobenitez/version_check","clone_url":"https://git.codelinaro.org/clo/lc/external/github.com/sergiobenitez/version_check.git","description":null}
{"name":"lc/external/github.com/dart-lang/isolate","clone_url":"https://git.codelinaro.org/clo/lc/external/github.com/dart-lang/isolate.git","description":null}
{"name":"la/prs/aosp-delta","clone_url":"https://git.codelinaro.org/clo/la/prs/aosp-delta.git","description":null}
{"name":"yocto-mirrors/github/ros2-gbp/examples-release","clone_url":"https://git.codelinaro.org/clo/yocto-mirrors/github/ros2-gbp/examples-release.git","description":null}
{"name":"qsdk/oss/lklm/nss-dpdk-kmod","clone_url":"https://git.codelinaro.org/clo/qsdk/oss/lklm/nss-dpdk-kmod.git","description":null}
{"name":"la/platform/external/eglib","clone_url":"https://git.codelinaro.org/clo/la/platform/external/eglib.git","description":null}
{"name":"la/platform/external/rust/crates/vsprintf","clone_url":"https://git.codelinaro.org/clo/la/platform/external/rust/crates/vsprintf.git","description":null}
{"name":"la/device/google/cuttlefish_common","clone_url":"https://git.codelinaro.org/clo/la/device/google/cuttlefish_common.git","description":null}
{"name":"la/platform/packages/apps/SmartCardService","clone_url":"https://git.codelinaro.org/clo/la/platform/packages/apps/SmartCardService.git","description":null}
{"name":"la/platform/external/libepoxy","clone_url":"https://git.codelinaro.org/clo/la/platform/external/libepoxy.git","description":null}
{"name":"la/platform/test/vts-testcase/vndk","clone_url":"https://git.codelinaro.org/clo/la/platform/test/vts-testcase/vndk.git","description":null}
{"name":"la/external/github.com/quic-qrb-ros/qrb_ros_samples/sample_depth_estimation","clone_url":"https://git.codelinaro.org/clo/la/external/github.com/quic-qrb-ros/qrb_ros_samples/sample_depth_estimation.git","description":null}
{"name":"rdkb/rdk/components/generic/rdk-oe/meta-rdk","clone_url":"https://git.codelinaro.org/clo/rdkb/rdk/components/generic/rdk-oe/meta-rdk.git","description":null}
{"name":"le/AGL/apps/controls","clone_url":"https://git.codelinaro.org/clo/le/AGL/apps/controls.git","description":null}
{"name":"la/platform/external/node-sqlite-async","clone_url":"https://git.codelinaro.org/clo/la/platform/external/node-sqlite-async.git","description":null}
{"name":"la/platform/external/shaderc/shaderc","clone_url":"https://git.codelinaro.org/clo/la/platform/external/shaderc/shaderc.git","description":null}
{"name":"la/live555","clone_url":"https://git.codelinaro.org/clo/la/live555.git","description":null}
{"name":"la/platform/prebuilts/cmake/darwin-x86","clone_url":"https://git.codelinaro.org/clo/la/platform/prebuilts/cmake/darwin-x86.git","description":null}
{"name":"la/platform/external/rust/crates/ciborium","clone_url":"https://git.codelinaro.org/clo/la/platform/external/rust/crates/ciborium.git","description":null}
{"name":"la/platform/external/libuv","clone_url":"https://git.codelinaro.org/clo/la/platform/external/libuv.git","description":null}
{"name":"la/platform/vendor/google_tradefederation/partner","clone_url":"https://git.codelinaro.org/clo/la/platform/vendor/google_tradefederation/partner.git","description":null}
{"name":"yocto-mirrors/github/grpc/grpc","clone_url":"https://git.codelinaro.org/clo/yocto-mirrors/github/grpc/grpc.git","description":null}
{"name":"imx-support/master","clone_url":"https://git.codelinaro.org/clo/imx-support/master.git","description":null}
{"name":"la/platform/system/gsid","clone_url":"https://git.codelinaro.org/clo/la/platform/system/gsid.git","description":null}
{"name":"la/platform/external/rust/crates/protobuf-parse","clone_url":"https://git.codelinaro.org/clo/la/platform/external/rust/crates/protobuf-parse.git","description":null}
{"name":"la/external/acrn-hypervisor","clone_url":"https://git.codelinaro.org/clo/la/external/acrn-hypervisor.git","description":null}
{"name":"le/sdkproduct/qim/manifest","clone_url":"https://git.codelinaro.org/clo/le/sdkproduct/qim/manifest.git","description":null}
{"name":"femto5g/platform/external/libunwind","clone_url":"https://git.codelinaro.org/clo/femto5g/platform/external/libunwind.git","description":null}
{"name":"lc/chromium/src/tools/grit","clone_url":"https://git.codelinaro.org/clo/lc/chromium/src/tools/grit.git","description":null}
{"name":"la/platform/packages/modules/bootprebuilt/5.10/arm64","clone_url":"https://git.codelinaro.org/clo/la/platform/packages/modules/bootprebuilt/5.10/arm64.git","description":null}
{"name":"testproject/platform/external/javapoet","clone_url":"https://git.codelinaro.org/clo/testproject/platform/external/javapoet.git","description":null}
{"name":"la/platform/external/rust/crates/proc-macro-nested","clone_url":"https://git.codelinaro.org/clo/la/platform/external/rust/crates/proc-macro-nested.git","description":null}
{"name":"testproject/platform/packages/apps/PackageInstaller","clone_url":"https://git.codelinaro.org/clo/testproject/platform/packages/apps/PackageInstaller.git","description":null}
{"name":"yocto-mirrors/github/google/pprof","clone_url":"https://git.codelinaro.org/clo/yocto-mirrors/github/google/pprof.git","description":null}
{"name":"la/platform/external/fastrpc","clone_url":"https://git.codelinaro.org/clo/la/platform/external/fastrpc.git","description":null}
{"name":"testproject/platform/tools/test/graphicsbenchmark","clone_url":"https://git.codelinaro.org/clo/testproject/platform/tools/test/graphicsbenchmark.git","description":null}
{"name":"lc/webm/vp8-test-vectors","clone_url":"https://git.codelinaro.org/clo/lc/webm/vp8-test-vectors.git","description":null}
{"name":"la/platform/external/google-fonts/arvo","clone_url":"https://git.codelinaro.org/clo/la/platform/external/google-fonts/arvo.git","description":null}
{"name":"la/platform/external/Reactive-Extensions/RxCpp","clone_url":"https://git.codelinaro.org/clo/la/platform/external/Reactive-Extensions/RxCpp.git","description":null}
{"name":"qsdk/wifi/cfg80211-backports-patches-oss","clone_url":"https://git.codelinaro.org/clo/qsdk/wifi/cfg80211-backports-patches-oss.git","description":null}
{"name":"la/platform/external/rust/crates/paste-impl","clone_url":"https://git.codelinaro.org/clo/la/platform/external/rust/crates/paste-impl.git","description":null}
{"name":"la/platform/external/nasm","clone_url":"https://git.codelinaro.org/clo/la/platform/external/nasm.git","description":null}
{"name":"le/platform/external/hrnr/m-explore","clone_url":"https://git.codelinaro.org/clo/le/platform/external/hrnr/m-explore.git","description":null}
{"name":"la/platform/external/libgav1","clone_url":"https://git.codelinaro.org/clo/la/platform/external/libgav1.git","description":null}
{"name":"la/platform/external/seccomp-tests","clone_url":"https://git.codelinaro.org/clo/la/platform/external/seccomp-tests.git","description":null}
{"name":"la/platform/external/python/enum34","clone_url":"https://git.codelinaro.org/clo/la/platform/external/python/enum34.git","description":null}
{"name":"qsdk/libnl","clone_url":"https://git.codelinaro.org/clo/qsdk/libnl.git","description":null}
{"name":"la/platform/packages/apps/McLauncher","clone_url":"https://git.codelinaro.org/clo/la/platform/packages/apps/McLauncher.git","description":null}
{"name":"la/platform/packages/apps/Calendar","clone_url":"https://git.codelinaro.org/clo/la/platform/packages/apps/Calendar.git","description":null}
{"name":"qsdk/oss/lklm/qca-nss-phy","clone_url":"https://git.codelinaro.org/clo/qsdk/oss/lklm/qca-nss-phy.git","description":null}
{"name":"le/external/github.com/aquantia/linux-aqr-phy-only","clone_url":"https://git.codelinaro.org/clo/le/external/github.com/aquantia/linux-aqr-phy-only.git","description":null}
{"name":"la/platform/vendor/qcom/apq8064","clone_url":"https://git.codelinaro.org/clo/la/platform/vendor/qcom/apq8064.git","description":null}
{"name":"qsdk/oss/system/feeds/wigig-utils","clone_url":"https://git.codelinaro.org/clo/qsdk/oss/system/feeds/wigig-utils.git","description":null}
{"name":"testproject/platform/external/mockito","clone_url":"https://git.codelinaro.org/clo/testproject/platform/external/mockito.git","description":null}
{"name":"la/platform/external/dnsmasq","clone_url":"https://git.codelinaro.org/clo/la/platform/external/dnsmasq.git","description":null}
{"name":"la/platform/system/libhidl","clone_url":"https://git.codelinaro.org/clo/la/platform/system/libhidl.git","description":null}
{"name":"le/platform/vendor/qcom-opensource/wlan/fw-api","clone_url":"https://git.codelinaro.org/clo/le/platform/vendor/qcom-opensource/wlan/fw-api.git","description":null}
{"name":"la/platform/external/rust/crates/darling_macro","clone_url":"https://git.codelinaro.org/clo/la/platform/external/rust/crates/darling_macro.git","description":null}
{"name":"la/kernel/nxp","clone_url":"https://git.codelinaro.org/clo/la/kernel/nxp.git","description":null}
{"name":"lc/aosp/platform/system/webservd","clone_url":"https://git.codelinaro.org/clo/lc/aosp/platform/system/webservd.git","description":null}
{"name":"testproject/platform/external/libogg","clone_url":"https://git.codelinaro.org/clo/testproject/platform/external/libogg.git","description":null}
{"name":"la/toolchain/mpc-1.2.1","clone_url":"https://git.codelinaro.org/clo/la/toolchain/mpc-1.2.1.git","description":null}
{"name":"le/qccsdk/oss/posix","clone_url":"https://git.codelinaro.org/clo/le/qccsdk/oss/posix.git","description":null}
{"name":"le/meta-qti-matter","clone_url":"https://git.codelinaro.org/clo/le/meta-qti-matter.git","description":null}
{"name":"la/kernel/google-modules/sensors/hall_sensor","clone_url":"https://git.codelinaro.org/clo/la/kernel/google-modules/sensors/hall_sensor.git","description":null}
{"name":"la/kernel/msm-extra_group/wlan-devicetree","clone_url":"https://git.codelinaro.org/clo/la/kernel/msm-extra_group/wlan-devicetree.git","description":null}
{"name":"lc/external/github.com/dynamorio/drmemory","clone_url":"https://git.codelinaro.org/clo/lc/external/github.com/dynamorio/drmemory.git","description":null}
{"name":"le/platform/vendor/qcom-opensource/auto-linux-unit-test-kernel","clone_url":"https://git.codelinaro.org/clo/le/platform/vendor/qcom-opensource/auto-linux-unit-test-kernel.git","description":null}
{"name":"femto5g/external/yoctoproject.org/meta-virtualization","clone_url":"https://git.codelinaro.org/clo/femto5g/external/yoctoproject.org/meta-virtualization.git","description":null}
{"name":"yocto-mirrors/iso-codes","clone_url":"https://git.codelinaro.org/clo/yocto-mirrors/iso-codes.git","description":null}
{"name":"la/trusty/app/gatekeeper","clone_url":"https://git.codelinaro.org/clo/la/trusty/app/gatekeeper.git","description":null}
{"name":"la/platform/test/vts-testcase/hal-trace","clone_url":"https://git.codelinaro.org/clo/la/platform/test/vts-testcase/hal-trace.git","description":null}
{"name":"le/platform/external/minijail","clone_url":"https://git.codelinaro.org/clo/le/platform/external/minijail.git","description":null}
{"name":"yocto-mirrors/pkg-config","clone_url":"https://git.codelinaro.org/clo/yocto-mirrors/pkg-config.git","description":null}
{"name":"external-ubicom/ubicom32-android","clone_url":"https://git.codelinaro.org/clo/external-ubicom/ubicom32-android.git","description":null}
{"name":"yocto-mirrors/github/urfave/cli","clone_url":"https://git.codelinaro.org/clo/yocto-mirrors/github/urfave/cli.git","description":null}
{"name":"lc/external/github.com/webassembly/v8-native-prototype","clone_url":"https://git.codelinaro.org/clo/lc/external/github.com/webassembly/v8-native-prototype.git","description":null}
{"name":"le/meta-qti-qirp","clone_url":"https://git.codelinaro.org/clo/le/meta-qti-qirp.git","description":null}
{"name":"la/platform/external/mesa3d","clone_url":"https://git.codelinaro.org/clo/la/platform/external/mesa3d.git","description":null}
{"name":"la/platform/external/vboot_reference","clone_url":"https://git.codelinaro.org/clo/la/platform/external/vboot_reference.git","description":null}
{"name":"yocto-mirrors/github/ros2-gbp/ament_package-release","clone_url":"https://git.codelinaro.org/clo/yocto-mirrors/github/ros2-gbp/ament_package-release.git","description":null}
{"name":"la/platform/external/tinycompress","clone_url":"https://git.codelinaro.org/clo/la/platform/external/tinycompress.git","description":null}
{"name":"la/platform/external/rust/rutabaga_gfx","clone_url":"https://git.codelinaro.org/clo/la/platform/external/rust/rutabaga_gfx.git","description":null}
{"name":"lc/chromium/src/third_party/markupsafe","clone_url":"https://git.codelinaro.org/clo/lc/chromium/src/third_party/markupsafe.git","description":null}
{"name":"le/gstreamer-1.14.4/gst-rtsp-server","clone_url":"https://git.codelinaro.org/clo/le/gstreamer-1.14.4/gst-rtsp-server.git","description":null}
{"name":"la/platform/external/rust/crates/chrono","clone_url":"https://git.codelinaro.org/clo/la/platform/external/rust/crates/chrono.git","description":null}
{"name":"la/platform/external/cros_linux-firmware","clone_url":"https://git.codelinaro.org/clo/la/platform/external/cros_linux-firmware.git","description":null}
{"name":"la/platform/external/wayland-protocols","clone_url":"https://git.codelinaro.org/clo/la/platform/external/wayland-protocols.git","description":null}
{"name":"lc/external/github.com/googlei18n/emoji-segmenter","clone_url":"https://git.codelinaro.org/clo/lc/external/github.com/googlei18n/emoji-segmenter.git","description":null}
{"name":"la/platform/external/chromium_org/third_party/yasm/source/patched-yasm","clone_url":"https://git.codelinaro.org/clo/la/platform/external/chromium_org/third_party/yasm/source/patched-yasm.git","description":null}
{"name":"lc/external/github.com/valvesoftware/openvr","clone_url":"https://git.codelinaro.org/clo/lc/external/github.com/valvesoftware/openvr.git","description":null}
{"name":"yocto-mirrors/github/gflags/gflags","clone_url":"https://git.codelinaro.org/clo/yocto-mirrors/github/gflags/gflags.git","description":null}
{"name":"imx-support/imx-linux-sumo","clone_url":"https://git.codelinaro.org/clo/imx-support/imx-linux-sumo.git","description":null}
{"name":"yocto-mirrors/github/onsi/gomega","clone_url":"https://git.codelinaro.org/clo/yocto-mirrors/github/onsi/gomega.git","description":null}
{"name":"testproject/platform/packages/apps/TimeZoneData","clone_url":"https://git.codelinaro.org/clo/testproject/platform/packages/apps/TimeZoneData.git","description":null}
{"name":"la/platform/vendor/opensource/display-drivers","clone_url":"https://git.codelinaro.org/clo/la/platform/vendor/opensource/display-drivers.git","description":null}
{"name":"qsdk/oss/lklm/nss-clients","clone_url":"https://git.codelinaro.org/clo/qsdk/oss/lklm/nss-clients.git","description":null}
{"name":"le/grpc_repo","clone_url":"https://git.codelinaro.org/clo/le/grpc_repo.git","description":null}
{"name":"la/platform/test/framework","clone_url":"https://git.codelinaro.org/clo/la/platform/test/framework.git","description":null}
{"name":"femto/fsm/rules","clone_url":"https://git.codelinaro.org/clo/femto/fsm/rules.git","description":null}
{"name":"la/kernel/exynos-modules/config","clone_url":"https://git.codelinaro.org/clo/la/kernel/exynos-modules/config.git","description":null}
{"name":"la/platform/vendor/st/opensource/system/nfc","clone_url":"https://git.codelinaro.org/clo/la/platform/vendor/st/opensource/system/nfc.git","description":null}
{"name":"la/platform/external/rust/crates/tokio","clone_url":"https://git.codelinaro.org/clo/la/platform/external/rust/crates/tokio.git","description":null}
{"name":"le/platform/external/rincat/RTL88x2BU-Linux-Driver","clone_url":"https://git.codelinaro.org/clo/le/platform/external/rincat/RTL88x2BU-Linux-Driver.git","description":null}
{"name":"la/platform/external/rust/crates/lazycell","clone_url":"https://git.codelinaro.org/clo/la/platform/external/rust/crates/lazycell.git","description":null}
{"name":"le/oe/recipes-old","clone_url":"https://git.codelinaro.org/clo/le/oe/recipes-old.git","description":null}
{"name":"testproject/platform/vendor/qcom-opensource/system/bt","clone_url":"https://git.codelinaro.org/clo/testproject/platform/vendor/qcom-opensource/system/bt.git","description":null}
{"name":"lc/codesearch/infra/infra","clone_url":"https://git.codelinaro.org/clo/lc/codesearch/infra/infra.git","description":null}
{"name":"la/platform/external/boost-submodules/disjoint_sets","clone_url":"https://git.codelinaro.org/clo/la/platform/external/boost-submodules/disjoint_sets.git","description":null}
{"name":"qsdk/oss/upstream/openwrt","clone_url":"https://git.codelinaro.org/clo/qsdk/oss/upstream/openwrt.git","description":null}
{"name":"la/platform/external/rust/crates/uguid","clone_url":"https://git.codelinaro.org/clo/la/platform/external/rust/crates/uguid.git","description":null}
{"name":"yocto-mirrors/github/aws/smithy-go","clone_url":"https://git.codelinaro.org/clo/yocto-mirrors/github/aws/smithy-go.git","description":null}
{"name":"le/platform/vendor/qcom-opensource/snaptel-sdk","clone_url":"https://git.codelinaro.org/clo/le/platform/vendor/qcom-opensource/snaptel-sdk.git","description":null}
{"name":"la/platform/tools/gpu","clone_url":"https://git.codelinaro.org/clo/la/platform/tools/gpu.git","description":null}
{"name":"la/platform/hardware/qcom/boot-ctl","clone_url":"https://git.codelinaro.org/clo/la/platform/hardware/qcom/boot-ctl.git","description":null}
{"name":"la/platform/prebuilts/abi-dumps/vndk","clone_url":"https://git.codelinaro.org/clo/la/platform/prebuilts/abi-dumps/vndk.git","description":null}
{"name":"lc/external/github.com/luci/gtreap","clone_url":"https://git.codelinaro.org/clo/lc/external/github.com/luci/gtreap.git","description":null}
{"name":"la/platform/external/freetype","clone_url":"https://git.codelinaro.org/clo/la/platform/external/freetype.git","description":null}
{"name":"la/platform/vendor/qcom/android-open","clone_url":"https://git.codelinaro.org/clo/la/platform/vendor/qcom/android-open.git","description":null}
{"name":"automotive/platform/xen","clone_url":"https://git.codelinaro.org/clo/automotive/platform/xen.git","description":null}
{"name":"lc/chromiumos/third_party/wayland","clone_url":"https://git.codelinaro.org/clo/lc/chromiumos/third_party/wayland.git","description":null}
{"name":"external-wlan/wlan-cnss-core","clone_url":"https://git.codelinaro.org/clo/external-wlan/wlan-cnss-core.git","description":null}
{"name":"la/toolchain/llvm-project","clone_url":"https://git.codelinaro.org/clo/la/toolchain/llvm-project.git","description":null}
{"name":"qrdk/rdkgithub/comcast/nopoll","clone_url":"https://git.codelinaro.org/clo/qrdk/rdkgithub/comcast/nopoll.git","description":null}
{"name":"la/platform/external/accessibility-test-framework","clone_url":"https://git.codelinaro.org/clo/la/platform/external/accessibility-test-framework.git","description":null}
{"name":"testproject/platform/test/vts-testcase/performance","clone_url":"https://git.codelinaro.org/clo/testproject/platform/test/vts-testcase/performance.git","description":null}
{"name":"lc/external/github.com/aclements/go-moremath","clone_url":"https://git.codelinaro.org/clo/lc/external/github.com/aclements/go-moremath.git","description":null}
{"name":"le/platform/external/JSON-Java","clone_url":"https://git.codelinaro.org/clo/le/platform/external/JSON-Java.git","description":null}
{"name":"le/mio-uds-windows","clone_url":"https://git.codelinaro.org/clo/le/mio-uds-windows.git","description":null}
{"name":"la/platform/vendor/qcom/msm8916_64_LMT","clone_url":"https://git.codelinaro.org/clo/la/platform/vendor/qcom/msm8916_64_LMT.git","description":null}
{"name":"yocto-mirrors/github/masterminds/semver","clone_url":"https://git.codelinaro.org/clo/yocto-mirrors/github/masterminds/semver.git","description":null}
{"name":"la/device/generic/goldfish-opengl","clone_url":"https://git.codelinaro.org/clo/la/device/generic/goldfish-opengl.git","description":null}
{"name":"le/AGL/src/hvacplugin","clone_url":"https://git.codelinaro.org/clo/le/AGL/src/hvacplugin.git","description":null}
{"name":"la/kernel_platform/external/rust/android-crates-io","clone_url":"https://git.codelinaro.org/clo/la/kernel_platform/external/rust/android-crates-io.git","description":null}
{"name":"qcomlt/pkg/tqftpserv","clone_url":"https://git.codelinaro.org/clo/qcomlt/pkg/tqftpserv.git","description":null}
{"name":"la/platform/external/rust/crates/miette","clone_url":"https://git.codelinaro.org/clo/la/platform/external/rust/crates/miette.git","description":null}
{"name":"le/e2fsprogs","clone_url":"https://git.codelinaro.org/clo/le/e2fsprogs.git","description":null}
{"name":"testproject/platform/external/one-true-awk","clone_url":"https://git.codelinaro.org/clo/testproject/platform/external/one-true-awk.git","description":null}
{"name":"la/platform/system/keymint","clone_url":"https://git.codelinaro.org/clo/la/platform/system/keymint.git","description":null}
{"name":"la/platform/external/webview_support_interfaces","clone_url":"https://git.codelinaro.org/clo/la/platform/external/webview_support_interfaces.git","description":null}
{"name":"qrdk/rdkcentral/crashupload","clone_url":"https://git.codelinaro.org/clo/qrdk/rdkcentral/crashupload.git","description":null}
{"name":"la/platform/vendor/qcom/monaco_group/codeaurora/tinycompress","clone_url":"https://git.codelinaro.org/clo/la/platform/vendor/qcom/monaco_group/codeaurora/tinycompress.git","description":null}
{"name":"la/platform/external/boost-submodules/context","clone_url":"https://git.codelinaro.org/clo/la/platform/external/boost-submodules/context.git","description":null}
{"name":"le/techpack/camera/manifest","clone_url":"https://git.codelinaro.org/clo/le/techpack/camera/manifest.git","description":null}
{"name":"yocto-mirrors/github/ros2-gbp/vision_msgs-release","clone_url":"https://git.codelinaro.org/clo/yocto-mirrors/github/ros2-gbp/vision_msgs-release.git","description":null}
{"name":"la/platform/external/expat","clone_url":"https://git.codelinaro.org/clo/la/platform/external/expat.git","description":null}
{"name":"la/platform/external/dbus","clone_url":"https://git.codelinaro.org/clo/la/platform/external/dbus.git","description":null}
{"name":"ype/external/gstreamer.org/gstreamer/gstreamer","clone_url":"https://git.codelinaro.org/clo/ype/external/gstreamer.org/gstreamer/gstreamer.git","description":null}
{"name":"la/platform/external/python/pylint","clone_url":"https://git.codelinaro.org/clo/la/platform/external/python/pylint.git","description":null}
{"name":"le/unfs3/unfs3","clone_url":"https://git.codelinaro.org/clo/le/unfs3/unfs3.git","description":null}
{"name":"la/platform/external/libva-utils","clone_url":"https://git.codelinaro.org/clo/la/platform/external/libva-utils.git","description":null}
{"name":"la/platform/vendor/qcom-opensource/bluetooth_lea","clone_url":"https://git.codelinaro.org/clo/la/platform/vendor/qcom-opensource/bluetooth_lea.git","description":null}
{"name":"la/platform/external/unicode","clone_url":"https://git.codelinaro.org/clo/la/platform/external/unicode.git","description":null}
{"name":"le/platform/vendor/qcom-opensource/robot-object-detect","clone_url":"https://git.codelinaro.org/clo/le/platform/vendor/qcom-opensource/robot-object-detect.git","description":null}
{"name":"la/platform/vendor/qcom/sdm429w/codeaurora/location","clone_url":"https://git.codelinaro.org/clo/la/platform/vendor/qcom/sdm429w/codeaurora/location.git","description":null}
{"name":"la/platform/hardware/bsp/freescale","clone_url":"https://git.codelinaro.org/clo/la/platform/hardware/bsp/freescale.git","description":null}
{"name":"la/platform/prebuilts/fullsdk-linux/build-tools_group/26.0.1","clone_url":"https://git.codelinaro.org/clo/la/platform/prebuilts/fullsdk-linux/build-tools_group/26.0.1.git","description":null}
{"name":"la/platform/packages/apps/InCallUI","clone_url":"https://git.codelinaro.org/clo/la/platform/packages/apps/InCallUI.git","description":null}
{"name":"la/platform/prebuilts/clang/host/windows-x86","clone_url":"https://git.codelinaro.org/clo/la/platform/prebuilts/clang/host/windows-x86.git","description":null}
{"name":"lc/chromiumos/third_party/dpkt","clone_url":"https://git.codelinaro.org/clo/lc/chromiumos/third_party/dpkt.git","description":null}
{"name":"qrdk/rdkcentral/rdkb-halif-platform","clone_url":"https://git.codelinaro.org/clo/qrdk/rdkcentral/rdkb-halif-platform.git","description":null}
{"name":"la/platform/hardware/qcom/sdm429w/display","clone_url":"https://git.codelinaro.org/clo/la/platform/hardware/qcom/sdm429w/display.git","description":null}
{"name":"la/platform/vendor/qcom-opensource/mmtests","clone_url":"https://git.codelinaro.org/clo/la/platform/vendor/qcom-opensource/mmtests.git","description":null}
{"name":"lc/chromiumos/third_party/libdrm","clone_url":"https://git.codelinaro.org/clo/lc/chromiumos/third_party/libdrm.git","description":null}
{"name":"le/meta-qti-ml","clone_url":"https://git.codelinaro.org/clo/le/meta-qti-ml.git","description":null}
{"name":"lf/releases/l10n/ar/gaia","clone_url":"https://git.codelinaro.org/clo/lf/releases/l10n/ar/gaia.git","description":null}
{"name":"lc/chromium/src/components/arc/mojom","clone_url":"https://git.codelinaro.org/clo/lc/chromium/src/components/arc/mojom.git","description":null}
{"name":"la/platform/external/python/atomicwrites","clone_url":"https://git.codelinaro.org/clo/la/platform/external/python/atomicwrites.git","description":null}
{"name":"la/platform/external/dbus-binding-generator","clone_url":"https://git.codelinaro.org/clo/la/platform/external/dbus-binding-generator.git","description":null}
{"name":"yocto-mirrors/github/ros2-gbp/domain_bridge-release","clone_url":"https://git.codelinaro.org/clo/yocto-mirrors/github/ros2-gbp/domain_bridge-release.git","description":null}
{"name":"yocto-mirrors/github/cespare/xxhash","clone_url":"https://git.codelinaro.org/clo/yocto-mirrors/github/cespare/xxhash.git","description":null}
{"name":"la/platform/tools/external/go/src/golang.org/x_group/tools","clone_url":"https://git.codelinaro.org/clo/la/platform/tools/external/go/src/golang.org/x_group/tools.git","description":null}
{"name":"la/platform/external/vm_tools/p9","clone_url":"https://git.codelinaro.org/clo/la/platform/external/vm_tools/p9.git","description":null}
{"name":"la/platform/external/boost-submodules/smart_ptr","clone_url":"https://git.codelinaro.org/clo/la/platform/external/boost-submodules/smart_ptr.git","description":null}
{"name":"la/platform/vendor/opensource/camera-kernel","clone_url":"https://git.codelinaro.org/clo/la/platform/vendor/opensource/camera-kernel.git","description":null}
{"name":"la/platform/external/libdivsufsort","clone_url":"https://git.codelinaro.org/clo/la/platform/external/libdivsufsort.git","description":null}
{"name":"testproject/platform/external/seccomp-tests","clone_url":"https://git.codelinaro.org/clo/testproject/platform/external/seccomp-tests.git","description":null}
{"name":"le/gstreamer-1.14.4/gst-plugins-bad","clone_url":"https://git.codelinaro.org/clo/le/gstreamer-1.14.4/gst-plugins-bad.git","description":null}
{"name":"qsdk/lklm/nss-ppe","clone_url":"https://git.codelinaro.org/clo/qsdk/lklm/nss-ppe.git","description":null}
{"name":"la/platform/external/boost-submodules/bimap","clone_url":"https://git.codelinaro.org/clo/la/platform/external/boost-submodules/bimap.git","description":null}
{"name":"le/platform/external/ROBOTIS-GIT/turtlebot3","clone_url":"https://git.codelinaro.org/clo/le/platform/external/ROBOTIS-GIT/turtlebot3.git","description":null}
{"name":"la/trusty/app/nvram","clone_url":"https://git.codelinaro.org/clo/la/trusty/app/nvram.git","description":null}
{"name":"la/platform/external/netperf","clone_url":"https://git.codelinaro.org/clo/la/platform/external/netperf.git","description":null}
{"name":"le/abctl","clone_url":"https://git.codelinaro.org/clo/le/abctl.git","description":null}
{"name":"qrdk/rdkcentral/rfc","clone_url":"https://git.codelinaro.org/clo/qrdk/rdkcentral/rfc.git","description":null}
{"name":"qcc7xx/patches","clone_url":"https://git.codelinaro.org/clo/qcc7xx/patches.git","description":null}
{"name":"dpdk/patches","clone_url":"https://git.codelinaro.org/clo/dpdk/patches.git","description":null}
{"name":"yocto-mirrors/github/denisenkom/go-mssqldb","clone_url":"https://git.codelinaro.org/clo/yocto-mirrors/github/denisenkom/go-mssqldb.git","description":null}
{"name":"yocto-mirrors/github/jinzhu/inflection","clone_url":"https://git.codelinaro.org/clo/yocto-mirrors/github/jinzhu/inflection.git","description":null}
{"name":"le/qcom-opensource/mdm-init","clone_url":"https://git.codelinaro.org/clo/le/qcom-opensource/mdm-init.git","description":null}
{"name":"la/platform/external/google-auth-library-java","clone_url":"https://git.codelinaro.org/clo/la/platform/external/google-auth-library-java.git","description":null}
{"name":"la/platform/build/release","clone_url":"https://git.codelinaro.org/clo/la/platform/build/release.git","description":null}
{"name":"la/platform/external/boost-submodules/container_hash","clone_url":"https://git.codelinaro.org/clo/la/platform/external/boost-submodules/container_hash.git","description":null}
{"name":"le/centos/automotive/sample-images","clone_url":"https://git.codelinaro.org/clo/le/centos/automotive/sample-images.git","description":null}
{"name":"la/platform/external/python/cachetools","clone_url":"https://git.codelinaro.org/clo/la/platform/external/python/cachetools.git","description":null}
{"name":"la/platform/external/libcxx","clone_url":"https://git.codelinaro.org/clo/la/platform/external/libcxx.git","description":null}
{"name":"la/platform/external/bazelbuild-rules_cc","clone_url":"https://git.codelinaro.org/clo/la/platform/external/bazelbuild-rules_cc.git","description":null}
{"name":"la/platform/system/libsysprop","clone_url":"https://git.codelinaro.org/clo/la/platform/system/libsysprop.git","description":null}
{"name":"yocto-mirrors/github/bugsnag/panicwrap","clone_url":"https://git.codelinaro.org/clo/yocto-mirrors/github/bugsnag/panicwrap.git","description":null}
{"name":"yocto-mirrors/oci-systemd-hook","clone_url":"https://git.codelinaro.org/clo/yocto-mirrors/oci-systemd-hook.git","description":null}
{"name":"testproject/platform/tools/ndkports","clone_url":"https://git.codelinaro.org/clo/testproject/platform/tools/ndkports.git","description":null}
{"name":"yocto-mirrors/protobuf","clone_url":"https://git.codelinaro.org/clo/yocto-mirrors/protobuf.git","description":null}
{"name":"qsdk/ot-br-posix","clone_url":"https://git.codelinaro.org/clo/qsdk/ot-br-posix.git","description":null}
{"name":"yocto-mirrors/github/shibumi/go-pathspec","clone_url":"https://git.codelinaro.org/clo/yocto-mirrors/github/shibumi/go-pathspec.git","description":null}
{"name":"lc/external/github.com/contain-rs/vec-map","clone_url":"https://git.codelinaro.org/clo/lc/external/github.com/contain-rs/vec-map.git","description":null}
{"name":"lc/chromiumos/platform/tast","clone_url":"https://git.codelinaro.org/clo/lc/chromiumos/platform/tast.git","description":null}
{"name":"lc/external/coreboot.org/flashrom","clone_url":"https://git.codelinaro.org/clo/lc/external/coreboot.org/flashrom.git","description":null}
{"name":"la/platform/system/memory/mmd","clone_url":"https://git.codelinaro.org/clo/la/platform/system/memory/mmd.git","description":null}
{"name":"qyocto/yocto/meta-java","clone_url":"https://git.codelinaro.org/clo/qyocto/yocto/meta-java.git","description":null}
{"name":"la/platform/external/pdfium","clone_url":"https://git.codelinaro.org/clo/la/platform/external/pdfium.git","description":null}
{"name":"la/device/google/contexthub","clone_url":"https://git.codelinaro.org/clo/la/device/google/contexthub.git","description":null}
{"name":"qcomlt/ci/staging/linux-stable","clone_url":"https://git.codelinaro.org/clo/qcomlt/ci/staging/linux-stable.git","description":""}
{"name":"la/platform/external/boost-submodules/optional","clone_url":"https://git.codelinaro.org/clo/la/platform/external/boost-submodules/optional.git","description":null}
{"name":"la/platform/external/google-highway","clone_url":"https://git.codelinaro.org/clo/la/platform/external/google-highway.git","description":null}
{"name":"femto5g/oss/lklm/nss-clients","clone_url":"https://git.codelinaro.org/clo/femto5g/oss/lklm/nss-clients.git","description":null}
{"name":"yocto-mirrors/openjpeg","clone_url":"https://git.codelinaro.org/clo/yocto-mirrors/openjpeg.git","description":null}
{"name":"la/platform/vendor/qcom/tellurium_64","clone_url":"https://git.codelinaro.org/clo/la/platform/vendor/qcom/tellurium_64.git","description":null}
{"name":"lc/external/github.com/sybrenstuvel/python-rsa","clone_url":"https://git.codelinaro.org/clo/lc/external/github.com/sybrenstuvel/python-rsa.git","description":null}
{"name":"qsdk/wifi/iw-patches-oss","clone_url":"https://git.codelinaro.org/clo/qsdk/wifi/iw-patches-oss.git","description":null}
{"name":"la/platform/external/rust/crates/remain","clone_url":"https://git.codelinaro.org/clo/la/platform/external/rust/crates/remain.git","description":null}
{"name":"le-au-os/platform/vendor/opensource/dataipa","clone_url":"https://git.codelinaro.org/clo/le-au-os/platform/vendor/opensource/dataipa.git","description":null}
{"name":"la/platform/external/chromium_org/sdch/open-vcdiff","clone_url":"https://git.codelinaro.org/clo/la/platform/external/chromium_org/sdch/open-vcdiff.git","description":null}
{"name":"la/kernel/amlogic-tv-modules/media_modules","clone_url":"https://git.codelinaro.org/clo/la/kernel/amlogic-tv-modules/media_modules.git","description":null}
{"name":"la/device/linaro/poplar-kernel","clone_url":"https://git.codelinaro.org/clo/la/device/linaro/poplar-kernel.git","description":null}
{"name":"la/platform/external/libcxxabi","clone_url":"https://git.codelinaro.org/clo/la/platform/external/libcxxabi.git","description":null}
{"name":"testproject/platform/external/jsmn","clone_url":"https://git.codelinaro.org/clo/testproject/platform/external/jsmn.git","description":null}
{"name":"le/virtio/qcvirtio-uvlt-driver-linux","clone_url":"https://git.codelinaro.org/clo/le/virtio/qcvirtio-uvlt-driver-linux.git","description":null}
{"name":"le/platform/vendor/qcom-opensource/ts_firmware","clone_url":"https://git.codelinaro.org/clo/le/platform/vendor/qcom-opensource/ts_firmware.git","description":null}
{"name":"la/platform/external/libfuse","clone_url":"https://git.codelinaro.org/clo/la/platform/external/libfuse.git","description":null}
{"name":"femto5g/oss/lklm/nss-nsm","clone_url":"https://git.codelinaro.org/clo/femto5g/oss/lklm/nss-nsm.git","description":null}
{"name":"la/platform/external/vsomeip","clone_url":"https://git.codelinaro.org/clo/la/platform/external/vsomeip.git","description":null}
{"name":"le/techpack/display/manifest","clone_url":"https://git.codelinaro.org/clo/le/techpack/display/manifest.git","description":null}
{"name":"qsdk/oss/system/openwrt/feeds/qca-wifi-10.4","clone_url":"https://git.codelinaro.org/clo/qsdk/oss/system/openwrt/feeds/qca-wifi-10.4.git","description":null}
{"name":"le/snap/yaml","clone_url":"https://git.codelinaro.org/clo/le/snap/yaml.git","description":null}
{"name":"la/platform/external/boost-submodules/uuid","clone_url":"https://git.codelinaro.org/clo/la/platform/external/boost-submodules/uuid.git","description":null}
{"name":"la/kernel/google-modules/fingerprint/fpc","clone_url":"https://git.codelinaro.org/clo/la/kernel/google-modules/fingerprint/fpc.git","description":null}
{"name":"qrdk/rdkcentral/persistent-storage-manager","clone_url":"https://git.codelinaro.org/clo/qrdk/rdkcentral/persistent-storage-manager.git","description":null}
{"name":"le/owrt/feeds/packages","clone_url":"https://git.codelinaro.org/clo/le/owrt/feeds/packages.git","description":null}
{"name":"la/platform/device/stm","clone_url":"https://git.codelinaro.org/clo/la/platform/device/stm.git","description":null}
{"name":"la/platform/external/rust/crates/threadpool","clone_url":"https://git.codelinaro.org/clo/la/platform/external/rust/crates/threadpool.git","description":null}
{"name":"la/platform/prebuilts/fullsdk/platforms/android-26","clone_url":"https://git.codelinaro.org/clo/la/platform/prebuilts/fullsdk/platforms/android-26.git","description":null}
{"name":"lc/chromium/tools/command_wrapper/bin","clone_url":"https://git.codelinaro.org/clo/lc/chromium/tools/command_wrapper/bin.git","description":null}
{"name":"la/platform/external/rust/crates/instant","clone_url":"https://git.codelinaro.org/clo/la/platform/external/rust/crates/instant.git","description":null}
{"name":"yocto-mirrors/github/ros2-gbp/rcl_interfaces-release","clone_url":"https://git.codelinaro.org/clo/yocto-mirrors/github/ros2-gbp/rcl_interfaces-release.git","description":null}
{"name":"yocto-mirrors/github/qemu/dtc","clone_url":"https://git.codelinaro.org/clo/yocto-mirrors/github/qemu/dtc.git","description":null}
{"name":"iris-video-driver/patches","clone_url":"https://git.codelinaro.org/clo/iris-video-driver/patches.git","description":null}
{"name":"le/coqoshv/coqoshv-abi","clone_url":"https://git.codelinaro.org/clo/le/coqoshv/coqoshv-abi.git","description":null}
{"name":"yocto-mirrors/github/smuellerdd/libkcapi","clone_url":"https://git.codelinaro.org/clo/yocto-mirrors/github/smuellerdd/libkcapi.git","description":null}
{"name":"la/platform/hardware/intel/audio_media","clone_url":"https://git.codelinaro.org/clo/la/platform/hardware/intel/audio_media.git","description":null}
{"name":"yocto-mirrors/Vulkan-Headers","clone_url":"https://git.codelinaro.org/clo/yocto-mirrors/Vulkan-Headers.git","description":null}
{"name":"la/platform/external/rust/crates/walkdir","clone_url":"https://git.codelinaro.org/clo/la/platform/external/rust/crates/walkdir.git","description":null}
{"name":"yocto-mirrors/github/tetratelabs/wazero","clone_url":"https://git.codelinaro.org/clo/yocto-mirrors/github/tetratelabs/wazero.git","description":null}
{"name":"femto5g/oss/lklm/nss-cfi","clone_url":"https://git.codelinaro.org/clo/femto5g/oss/lklm/nss-cfi.git","description":null}
{"name":"la/platform/prebuilts/gcc/darwin-x86/arm/arm-linux-androideabi-4.9","clone_url":"https://git.codelinaro.org/clo/la/platform/prebuilts/gcc/darwin-x86/arm/arm-linux-androideabi-4.9.git","description":null}
{"name":"testproject/platform/hardware/nxp/nfc","clone_url":"https://git.codelinaro.org/clo/testproject/platform/hardware/nxp/nfc.git","description":null}
{"name":"lc/external/github.com/dart-lang/resource","clone_url":"https://git.codelinaro.org/clo/lc/external/github.com/dart-lang/resource.git","description":null}
{"name":"qsdk/tools/nss-mconf","clone_url":"https://git.codelinaro.org/clo/qsdk/tools/nss-mconf.git","description":null}
{"name":"le/platform/vendor/qcom-opensource/wlan/qcawifi-cmn-dev","clone_url":"https://git.codelinaro.org/clo/le/platform/vendor/qcom-opensource/wlan/qcawifi-cmn-dev.git","description":null}
{"name":"qrdk/code.rdkcentral.com/rdkb/components/opensource/ccsp/hal_group/rdk-wifi-hal","clone_url":"https://git.codelinaro.org/clo/qrdk/code.rdkcentral.com/rdkb/components/opensource/ccsp/hal_group/rdk-wifi-hal.git","description":null}
{"name":"la/platform/external/valgrind","clone_url":"https://git.codelinaro.org/clo/la/platform/external/valgrind.git","description":null}
{"name":"le-au-os/kernel/msm-5.4","clone_url":"https://git.codelinaro.org/clo/le-au-os/kernel/msm-5.4.git","description":null}
{"name":"la/device/qcom/qssi_auto","clone_url":"https://git.codelinaro.org/clo/la/device/qcom/qssi_auto.git","description":null}
{"name":"la/platform/prebuilts/r8","clone_url":"https://git.codelinaro.org/clo/la/platform/prebuilts/r8.git","description":null}
{"name":"la/platform/prebuilts/module_sdk/conscrypt","clone_url":"https://git.codelinaro.org/clo/la/platform/prebuilts/module_sdk/conscrypt.git","description":null}
{"name":"le/kmod","clone_url":"https://git.codelinaro.org/clo/le/kmod.git","description":null}
{"name":"la/kernel/prebuilts/common-modules/virtual-device/6.1/x86-64","clone_url":"https://git.codelinaro.org/clo/la/kernel/prebuilts/common-modules/virtual-device/6.1/x86-64.git","description":null}
{"name":"la/platform/external/rust/crates/winnow","clone_url":"https://git.codelinaro.org/clo/la/platform/external/rust/crates/winnow.git","description":null}
