{"name":"le/qccsdk/oss/exhost","clone_url":"https://git.codelinaro.org/clo/le/qccsdk/oss/exhost.git","description":null}
{"name":"le/external/onnx","clone_url":"https://git.codelinaro.org/clo/le/external/onnx.git","description":null}
{"name":"boot/edk2-platforms","clone_url":"https://git.codelinaro.org/clo/boot/edk2-platforms.git","description":null}
{"name":"yocto-mirrors/gitlab/xorg/lib/libxcvt","clone_url":"https://git.codelinaro.org/clo/yocto-mirrors/gitlab/xorg/lib/libxcvt.git","description":null}
{"name":"la/platform/vendor/qcom/opensource/bt-external","clone_url":"https://git.codelinaro.org/clo/la/platform/vendor/qcom/opensource/bt-external.git","description":null}
{"name":"la/platform/vendor/qcom-opensource/wlan/gen4-5/qcacld-3.0","clone_url":"https://git.codelinaro.org/clo/la/platform/vendor/qcom-opensource/wlan/gen4-5/qcacld-3.0.git","description":null}
{"name":"qsdk/oss/nss/ubi32-nssmconf","clone_url":"https://git.codelinaro.org/clo/qsdk/oss/nss/ubi32-nssmconf.git","description":null}
{"name":"lc/external/github.com/lann/builder","clone_url":"https://git.codelinaro.org/clo/lc/external/github.com/lann/builder.git","description":null}
{"name":"la/platform/external/deqp-deps/SPIRV-Headers","clone_url":"https://git.codelinaro.org/clo/la/platform/external/deqp-deps/SPIRV-Headers.git","description":null}
{"name":"la/platform/hardware/ti/am57x","clone_url":"https://git.codelinaro.org/clo/la/platform/hardware/ti/am57x.git","description":null}
{"name":"le/platform/external/mtpserver","clone_url":"https://git.codelinaro.org/clo/le/platform/external/mtpserver.git","description":null}
{"name":"qsdk/oss/system/feeds/wlan-iw","clone_url":"https://git.codelinaro.org/clo/qsdk/oss/system/feeds/wlan-iw.git","description":null}
{"name":"qsdk/pigweed","clone_url":"https://git.codelinaro.org/clo/qsdk/pigweed.git","description":null}
{"name":"la/kernel/google-modules/wlan/bcmdhd/bcm4390","clone_url":"https://git.codelinaro.org/clo/la/kernel/google-modules/wlan/bcmdhd/bcm4390.git","description":null}
{"name":"la/platform/packages/apps/SoundRecorder","clone_url":"https://git.codelinaro.org/clo/la/platform/packages/apps/SoundRecorder.git","description":null}
{"name":"qsdk/oss/lklm/nss-gmac","clone_url":"https://git.codelinaro.org/clo/qsdk/oss/lklm/nss-gmac.git","description":null}
{"name":"yocto-mirrors/gstd-1.x","clone_url":"https://git.codelinaro.org/clo/yocto-mirrors/gstd-1.x.git","description":null}
{"name":"la/platform/external/rust/crates/debug_tree","clone_url":"https://git.codelinaro.org/clo/la/platform/external/rust/crates/debug_tree.git","description":null}
{"name":"la/external/github.com/quic-qrb-ros/qrb_ros_samples/sample_object_segmentation","clone_url":"https://git.codelinaro.org/clo/la/external/github.com/quic-qrb-ros/qrb_ros_samples/sample_object_segmentation.git","description":null}
{"name":"la/device/lge/bullhead-kernel","clone_url":"https://git.codelinaro.org/clo/la/device/lge/bullhead-kernel.git","description":null}
{"name":"qsdk/platform/vendor/qcom/opensource/data/hostsw/networkmanager","clone_url":"https://git.codelinaro.org/clo/qsdk/platform/vendor/qcom/opensource/data/hostsw/networkmanager.git","description":null}
{"name":"yocto-mirrors/github/moby/profiles/seccomp","clone_url":"https://git.codelinaro.org/clo/yocto-mirrors/github/moby/profiles/seccomp.git","description":null}
{"name":"sba-patches/romeau_patches","clone_url":"https://git.codelinaro.org/clo/sba-patches/romeau_patches.git","description":null}
{"name":"qrdk/parodus2ccsp","clone_url":"https://git.codelinaro.org/clo/qrdk/parodus2ccsp.git","description":null}
{"name":"lc/external/github.com/golang/oauth2","clone_url":"https://git.codelinaro.org/clo/lc/external/github.com/golang/oauth2.git","description":null}
{"name":"la/kernel/exynos-modules/devicetree","clone_url":"https://git.codelinaro.org/clo/la/kernel/exynos-modules/devicetree.git","description":null}
{"name":"la/platform/prebuilts/fullsdk/build-tools/22-linux","clone_url":"https://git.codelinaro.org/clo/la/platform/prebuilts/fullsdk/build-tools/22-linux.git","description":null}
{"name":"qcomlt/pkg/qdsp-config","clone_url":"https://git.codelinaro.org/clo/qcomlt/pkg/qdsp-config.git","description":null}
{"name":"rdkb/rdk/components/generic/rdkssa","clone_url":"https://git.codelinaro.org/clo/rdkb/rdk/components/generic/rdkssa.git","description":null}
{"name":"qsdk/iwinfo","clone_url":"https://git.codelinaro.org/clo/qsdk/iwinfo.git","description":null}
{"name":"la/platform/external/apache-apr-util","clone_url":"https://git.codelinaro.org/clo/la/platform/external/apache-apr-util.git","description":null}
{"name":"le/platform/vendor/qcom/wlan","clone_url":"https://git.codelinaro.org/clo/le/platform/vendor/qcom/wlan.git","description":null}
{"name":"la/kernel/msm-extra_group/config","clone_url":"https://git.codelinaro.org/clo/la/kernel/msm-extra_group/config.git","description":null}
{"name":"la/platform/external/ims","clone_url":"https://git.codelinaro.org/clo/la/platform/external/ims.git","description":null}
{"name":"sba-patches/s32ds_patches","clone_url":"https://git.codelinaro.org/clo/sba-patches/s32ds_patches.git","description":null}
{"name":"la/platform/vendor/htc/common-open","clone_url":"https://git.codelinaro.org/clo/la/platform/vendor/htc/common-open.git","description":null}
{"name":"la/platform/external/rust/crates/crossbeam","clone_url":"https://git.codelinaro.org/clo/la/platform/external/rust/crates/crossbeam.git","description":null}
{"name":"rdkb/rdkb/components/opensource/ccsp/CcspXDNS","clone_url":"https://git.codelinaro.org/clo/rdkb/rdkb/components/opensource/ccsp/CcspXDNS.git","description":null}
{"name":"la/platform/packages/providers/TelephonyProvider","clone_url":"https://git.codelinaro.org/clo/la/platform/packages/providers/TelephonyProvider.git","description":null}
{"name":"la/toolchain/mpc-1.2.1","clone_url":"https://git.codelinaro.org/clo/la/toolchain/mpc-1.2.1.git","description":null}
{"name":"lc/external/github.com/google/googletest_repo","clone_url":"https://git.codelinaro.org/clo/lc/external/github.com/google/googletest_repo.git","description":null}
{"name":"lc/chromium/deps/mozinfo","clone_url":"https://git.codelinaro.org/clo/lc/chromium/deps/mozinfo.git","description":null}
{"name":"rdkb/rdkb/components/generic/startParodus","clone_url":"https://git.codelinaro.org/clo/rdkb/rdkb/components/generic/startParodus.git","description":null}
{"name":"la/platform/external/aehd","clone_url":"https://git.codelinaro.org/clo/la/platform/external/aehd.git","description":null}
{"name":"le/meta-qti-camera","clone_url":"https://git.codelinaro.org/clo/le/meta-qti-camera.git","description":null}
{"name":"femto5g/external/github.com/meta-clang","clone_url":"https://git.codelinaro.org/clo/femto5g/external/github.com/meta-clang.git","description":null}
{"name":"la/platform/sdk","clone_url":"https://git.codelinaro.org/clo/la/platform/sdk.git","description":null}
{"name":"la/kernel/msm-extra_group/wlan-devicetree","clone_url":"https://git.codelinaro.org/clo/la/kernel/msm-extra_group/wlan-devicetree.git","description":null}
{"name":"le/platform/vendor/qcom-opensource/robot-base","clone_url":"https://git.codelinaro.org/clo/le/platform/vendor/qcom-opensource/robot-base.git","description":null}
{"name":"la/platform/external/rust/crates/fixedbitset","clone_url":"https://git.codelinaro.org/clo/la/platform/external/rust/crates/fixedbitset.git","description":null}
{"name":"la/platform/external/aac","clone_url":"https://git.codelinaro.org/clo/la/platform/external/aac.git","description":null}
{"name":"sba-patches/qdt_dfc_patches","clone_url":"https://git.codelinaro.org/clo/sba-patches/qdt_dfc_patches.git","description":null}
{"name":"la/device/qcom/monaco/wlan","clone_url":"https://git.codelinaro.org/clo/la/device/qcom/monaco/wlan.git","description":null}
{"name":"yocto-mirrors/github/go-openapi/swag","clone_url":"https://git.codelinaro.org/clo/yocto-mirrors/github/go-openapi/swag.git","description":null}
{"name":"le/external/qtwayland","clone_url":"https://git.codelinaro.org/clo/le/external/qtwayland.git","description":null}
{"name":"yocto-mirrors/github/ros2-gbp/pcl_msgs-release","clone_url":"https://git.codelinaro.org/clo/yocto-mirrors/github/ros2-gbp/pcl_msgs-release.git","description":null}
{"name":"yocto-mirrors/github/beorn7/perks","clone_url":"https://git.codelinaro.org/clo/yocto-mirrors/github/beorn7/perks.git","description":null}
{"name":"la/platform/prebuilts/clang/host/darwin-universal","clone_url":"https://git.codelinaro.org/clo/la/platform/prebuilts/clang/host/darwin-universal.git","description":null}
{"name":"le/libsolv","clone_url":"https://git.codelinaro.org/clo/le/libsolv.git","description":null}
{"name":"lc/native_client/nacl-binutils","clone_url":"https://git.codelinaro.org/clo/lc/native_client/nacl-binutils.git","description":null}
{"name":"yocto-mirrors/github/microsoft/go-winio","clone_url":"https://git.codelinaro.org/clo/yocto-mirrors/github/microsoft/go-winio.git","description":null}
{"name":"la/device/linaro/dragonboard-kernel","clone_url":"https://git.codelinaro.org/clo/la/device/linaro/dragonboard-kernel.git","description":null}
{"name":"le/tar","clone_url":"https://git.codelinaro.org/clo/le/tar.git","description":null}
{"name":"external-wlan/supplicant","clone_url":"https://git.codelinaro.org/clo/external-wlan/supplicant.git","description":null}
{"name":"yocto-mirrors/github/aws/aws-sdk-go-v2","clone_url":"https://git.codelinaro.org/clo/yocto-mirrors/github/aws/aws-sdk-go-v2.git","description":null}
{"name":"la/kernel/google-modules/touch/synaptics_touch","clone_url":"https://git.codelinaro.org/clo/la/kernel/google-modules/touch/synaptics_touch.git","description":null}
{"name":"la/platform/superproject_group/main","clone_url":"https://git.codelinaro.org/clo/la/platform/superproject_group/main.git","description":null}
{"name":"le/qzephyr/upstream/qhal","clone_url":"https://git.codelinaro.org/clo/le/qzephyr/upstream/qhal.git","description":null}
{"name":"la/platform/external/lz4","clone_url":"https://git.codelinaro.org/clo/la/platform/external/lz4.git","description":null}
{"name":"la/platform/system/memory/guardian","clone_url":"https://git.codelinaro.org/clo/la/platform/system/memory/guardian.git","description":null}
{"name":"le/qzephyr/zephyrproject-rtos/tf-psa-crypto","clone_url":"https://git.codelinaro.org/clo/le/qzephyr/zephyrproject-rtos/tf-psa-crypto.git","description":null}
{"name":"la/platform/hardware/nxp/secure_element","clone_url":"https://git.codelinaro.org/clo/la/platform/hardware/nxp/secure_element.git","description":null}
{"name":"la/platform/vendor/qcom-opensource/androidui","clone_url":"https://git.codelinaro.org/clo/la/platform/vendor/qcom-opensource/androidui.git","description":null}
{"name":"qsdk/mmcclint-qca","clone_url":"https://git.codelinaro.org/clo/qsdk/mmcclint-qca.git","description":null}
{"name":"le/platform/vendor/qcom-opensource/rgs","clone_url":"https://git.codelinaro.org/clo/le/platform/vendor/qcom-opensource/rgs.git","description":null}
{"name":"lc/chromiumos/platform/tremplin","clone_url":"https://git.codelinaro.org/clo/lc/chromiumos/platform/tremplin.git","description":null}
{"name":"la/platform/external/javaparser","clone_url":"https://git.codelinaro.org/clo/la/platform/external/javaparser.git","description":null}
{"name":"la/platform/vendor/qcom-opensource/ufs-tools","clone_url":"https://git.codelinaro.org/clo/la/platform/vendor/qcom-opensource/ufs-tools.git","description":null}
{"name":"yocto-mirrors/meta-rust","clone_url":"https://git.codelinaro.org/clo/yocto-mirrors/meta-rust.git","description":null}
{"name":"ath-firmware/ath10k-firmware","clone_url":"https://git.codelinaro.org/clo/ath-firmware/ath10k-firmware.git","description":null}
{"name":"la/toolchain/jdk/jdk25","clone_url":"https://git.codelinaro.org/clo/la/toolchain/jdk/jdk25.git","description":null}
{"name":"le/snap/yaml-kernel-debug","clone_url":"https://git.codelinaro.org/clo/le/snap/yaml-kernel-debug.git","description":null}
{"name":"la/platform/tools/rootcanal","clone_url":"https://git.codelinaro.org/clo/la/platform/tools/rootcanal.git","description":null}
{"name":"la/platform/vendor/codeaurora/packages/apps/Dialer","clone_url":"https://git.codelinaro.org/clo/la/platform/vendor/codeaurora/packages/apps/Dialer.git","description":null}
{"name":"la/external/github.com/quic-qrb-ros/qrb_ros_transport","clone_url":"https://git.codelinaro.org/clo/la/external/github.com/quic-qrb-ros/qrb_ros_transport.git","description":null}
{"name":"le/platform/vendor/opensource/video-driver","clone_url":"https://git.codelinaro.org/clo/le/platform/vendor/opensource/video-driver.git","description":null}
{"name":"la/platform/external/berkeley-softfloat-3","clone_url":"https://git.codelinaro.org/clo/la/platform/external/berkeley-softfloat-3.git","description":null}
{"name":"la/platform/external/python/futures","clone_url":"https://git.codelinaro.org/clo/la/platform/external/python/futures.git","description":null}
{"name":"qyocto/oss/system/recipes/recipes-packages","clone_url":"https://git.codelinaro.org/clo/qyocto/oss/system/recipes/recipes-packages.git","description":null}
{"name":"le/external/oracle/ktf","clone_url":"https://git.codelinaro.org/clo/le/external/oracle/ktf.git","description":null}
{"name":"la/platform/vendor/qcom-opensource/wlan/rpc/wifi","clone_url":"https://git.codelinaro.org/clo/la/platform/vendor/qcom-opensource/wlan/rpc/wifi.git","description":null}
{"name":"la/platform/external/netperf","clone_url":"https://git.codelinaro.org/clo/la/platform/external/netperf.git","description":null}
{"name":"la/platform/vendor/codeaurora/android-watch/packages/apps/WatchGallery","clone_url":"https://git.codelinaro.org/clo/la/platform/vendor/codeaurora/android-watch/packages/apps/WatchGallery.git","description":null}
{"name":"la/kernel/google-modules/touch/common_wearable","clone_url":"https://git.codelinaro.org/clo/la/kernel/google-modules/touch/common_wearable.git","description":null}
{"name":"la/platform/packages/providers/ApplicationsProvider","clone_url":"https://git.codelinaro.org/clo/la/platform/packages/providers/ApplicationsProvider.git","description":null}
{"name":"le/meta-qti-Modem-ALD-Transport-Simulation-prop","clone_url":"https://git.codelinaro.org/clo/le/meta-qti-Modem-ALD-Transport-Simulation-prop.git","description":null}
{"name":"le/ros2-gbp/rcl-release","clone_url":"https://git.codelinaro.org/clo/le/ros2-gbp/rcl-release.git","description":null}
{"name":"la/platform/external/google-fruit","clone_url":"https://git.codelinaro.org/clo/la/platform/external/google-fruit.git","description":null}
{"name":"lc/chromiumos/third_party/sound-open-firmware-tools","clone_url":"https://git.codelinaro.org/clo/lc/chromiumos/third_party/sound-open-firmware-tools.git","description":null}
{"name":"la/meta-qti-qcawifi","clone_url":"https://git.codelinaro.org/clo/la/meta-qti-qcawifi.git","description":null}
{"name":"qsdk/verdex-uboot","clone_url":"https://git.codelinaro.org/clo/qsdk/verdex-uboot.git","description":null}
{"name":"la/platform/system/bpfprogs","clone_url":"https://git.codelinaro.org/clo/la/platform/system/bpfprogs.git","description":null}
{"name":"le/platform/vendor/qcom-opensource/dp-lib","clone_url":"https://git.codelinaro.org/clo/le/platform/vendor/qcom-opensource/dp-lib.git","description":null}
{"name":"lc/native_client/pnacl-clang","clone_url":"https://git.codelinaro.org/clo/lc/native_client/pnacl-clang.git","description":null}
{"name":"la/platform/external/boost-submodules/bind","clone_url":"https://git.codelinaro.org/clo/la/platform/external/boost-submodules/bind.git","description":null}
{"name":"la/platform/external/boost-submodules/bcp","clone_url":"https://git.codelinaro.org/clo/la/platform/external/boost-submodules/bcp.git","description":null}
{"name":"le/owrt/feeds/feed_tr69","clone_url":"https://git.codelinaro.org/clo/le/owrt/feeds/feed_tr69.git","description":null}
{"name":"ype/external/github.com/meta-clang","clone_url":"https://git.codelinaro.org/clo/ype/external/github.com/meta-clang.git","description":null}
{"name":"lc/infra/third_party/appengine-pipeline","clone_url":"https://git.codelinaro.org/clo/lc/infra/third_party/appengine-pipeline.git","description":null}
{"name":"la/platform/external/weave-common","clone_url":"https://git.codelinaro.org/clo/la/platform/external/weave-common.git","description":null}
{"name":"la/platform/external/radvd","clone_url":"https://git.codelinaro.org/clo/la/platform/external/radvd.git","description":null}
{"name":"la/platform/test/graphics","clone_url":"https://git.codelinaro.org/clo/la/platform/test/graphics.git","description":null}
{"name":"la/platform/test/vts-testcase/performance","clone_url":"https://git.codelinaro.org/clo/la/platform/test/vts-testcase/performance.git","description":null}
{"name":"la/platform/vendor/qcom/opensource/audioreach/audioreach-pal","clone_url":"https://git.codelinaro.org/clo/la/platform/vendor/qcom/opensource/audioreach/audioreach-pal.git","description":null}
{"name":"le/snap/yaml-kernel","clone_url":"https://git.codelinaro.org/clo/le/snap/yaml-kernel.git","description":null}
{"name":"la/platform/external/TestParameterInjector","clone_url":"https://git.codelinaro.org/clo/la/platform/external/TestParameterInjector.git","description":null}
{"name":"la/platform/external/rust/crates/poll_token_derive","clone_url":"https://git.codelinaro.org/clo/la/platform/external/rust/crates/poll_token_derive.git","description":null}
{"name":"lc/chromium/deps/xulrunner-sdk","clone_url":"https://git.codelinaro.org/clo/lc/chromium/deps/xulrunner-sdk.git","description":null}
{"name":"lf/releases/l10n/hr/gaia","clone_url":"https://git.codelinaro.org/clo/lf/releases/l10n/hr/gaia.git","description":null}
{"name":"le/AGL/meta-amb","clone_url":"https://git.codelinaro.org/clo/le/AGL/meta-amb.git","description":null}
{"name":"la/platform/packages/modules/GeoTZ","clone_url":"https://git.codelinaro.org/clo/la/platform/packages/modules/GeoTZ.git","description":null}
{"name":"le/external/yoctoproject.org/meta-selinux","clone_url":"https://git.codelinaro.org/clo/le/external/yoctoproject.org/meta-selinux.git","description":null}
{"name":"yocto-mirrors/github/opencontainers/image-spec","clone_url":"https://git.codelinaro.org/clo/yocto-mirrors/github/opencontainers/image-spec.git","description":null}
{"name":"automotive/platform/external/capicxx-core-runtime","clone_url":"https://git.codelinaro.org/clo/automotive/platform/external/capicxx-core-runtime.git","description":null}
{"name":"la/platform/prebuilts/maven_repo/bumptech","clone_url":"https://git.codelinaro.org/clo/la/platform/prebuilts/maven_repo/bumptech.git","description":null}
{"name":"lc/external/github.com/xeipuuv/gojsonreference","clone_url":"https://git.codelinaro.org/clo/lc/external/github.com/xeipuuv/gojsonreference.git","description":null}
{"name":"le/qcom-auto-manifest","clone_url":"https://git.codelinaro.org/clo/le/qcom-auto-manifest.git","description":null}
{"name":"la/kernel/google-modules/aoc-ipc","clone_url":"https://git.codelinaro.org/clo/la/kernel/google-modules/aoc-ipc.git","description":null}
{"name":"imx-support/meta-fsl-bsp-release","clone_url":"https://git.codelinaro.org/clo/imx-support/meta-fsl-bsp-release.git","description":null}
{"name":"la/platform/external/boost-submodules/mpl","clone_url":"https://git.codelinaro.org/clo/la/platform/external/boost-submodules/mpl.git","description":null}
{"name":"la/platform/external/rust/crates/rand","clone_url":"https://git.codelinaro.org/clo/la/platform/external/rust/crates/rand.git","description":null}
{"name":"lc/external/github.com/jmoiron/sqlx","clone_url":"https://git.codelinaro.org/clo/lc/external/github.com/jmoiron/sqlx.git","description":null}
{"name":"lf/releases/l10n/nl/gaia","clone_url":"https://git.codelinaro.org/clo/lf/releases/l10n/nl/gaia.git","description":null}
{"name":"qsdk/oss/system/openwrt/feeds/qca-wifi-10.4","clone_url":"https://git.codelinaro.org/clo/qsdk/oss/system/openwrt/feeds/qca-wifi-10.4.git","description":null}
{"name":"la/device/moto/shamu","clone_url":"https://git.codelinaro.org/clo/la/device/moto/shamu.git","description":null}
{"name":"le/binutils-gdb","clone_url":"https://git.codelinaro.org/clo/le/binutils-gdb.git","description":null}
{"name":"le/distribution/build-utils","clone_url":"https://git.codelinaro.org/clo/le/distribution/build-utils.git","description":null}
{"name":"lc/codecs/infra","clone_url":"https://git.codelinaro.org/clo/lc/codecs/infra.git","description":null}
{"name":"la/platform/vendor/qcom/opensource/Qcbor","clone_url":"https://git.codelinaro.org/clo/la/platform/vendor/qcom/opensource/Qcbor.git","description":null}
{"name":"qcomlt/pkg/initramfs-tools","clone_url":"https://git.codelinaro.org/clo/qcomlt/pkg/initramfs-tools.git","description":null}
{"name":"yocto-mirrors/ltp","clone_url":"https://git.codelinaro.org/clo/yocto-mirrors/ltp.git","description":null}
{"name":"la/device/google/caimito-sepolicy","clone_url":"https://git.codelinaro.org/clo/la/device/google/caimito-sepolicy.git","description":null}
{"name":"la/camera-samples","clone_url":"https://git.codelinaro.org/clo/la/camera-samples.git","description":null}
{"name":"le/platform/vendor/opensource/iot-power-module","clone_url":"https://git.codelinaro.org/clo/le/platform/vendor/opensource/iot-power-module.git","description":null}
{"name":"la/device/generic/car","clone_url":"https://git.codelinaro.org/clo/la/device/generic/car.git","description":null}
{"name":"la/platform/prebuilts/fullsdk-linux/build-tools","clone_url":"https://git.codelinaro.org/clo/la/platform/prebuilts/fullsdk-linux/build-tools.git","description":null}
{"name":"yocto-mirrors/text","clone_url":"https://git.codelinaro.org/clo/yocto-mirrors/text.git","description":null}
{"name":"la/platform/prebuilts/vndk/v31","clone_url":"https://git.codelinaro.org/clo/la/platform/prebuilts/vndk/v31.git","description":null}
{"name":"la/platform/external/v4l2_codec2","clone_url":"https://git.codelinaro.org/clo/la/platform/external/v4l2_codec2.git","description":null}
{"name":"la/platform/hardware/nxp/nfc","clone_url":"https://git.codelinaro.org/clo/la/platform/hardware/nxp/nfc.git","description":null}
{"name":"qsdk/luci","clone_url":"https://git.codelinaro.org/clo/qsdk/luci.git","description":null}
{"name":"la/platform/external/boost-submodules/ublas","clone_url":"https://git.codelinaro.org/clo/la/platform/external/boost-submodules/ublas.git","description":null}
{"name":"la/platform/external/boost-submodules/property_tree","clone_url":"https://git.codelinaro.org/clo/la/platform/external/boost-submodules/property_tree.git","description":null}
{"name":"yocto-mirrors/github/docker/go-connections","clone_url":"https://git.codelinaro.org/clo/yocto-mirrors/github/docker/go-connections.git","description":null}
{"name":"qrdk/lvm2","clone_url":"https://git.codelinaro.org/clo/qrdk/lvm2.git","description":null}
{"name":"le/patches","clone_url":"https://git.codelinaro.org/clo/le/patches.git","description":null}
{"name":"yocto-mirrors/gnome-desktop-testing","clone_url":"https://git.codelinaro.org/clo/yocto-mirrors/gnome-desktop-testing.git","description":null}
{"name":"lc/external/github.com/khronosgroup/OpenGL-Registry","clone_url":"https://git.codelinaro.org/clo/lc/external/github.com/khronosgroup/OpenGL-Registry.git","description":null}
{"name":"la/trusty/device/common","clone_url":"https://git.codelinaro.org/clo/la/trusty/device/common.git","description":null}
{"name":"la/device/google/atv","clone_url":"https://git.codelinaro.org/clo/la/device/google/atv.git","description":null}
{"name":"yocto-mirrors/github/cloudflare/circl","clone_url":"https://git.codelinaro.org/clo/yocto-mirrors/github/cloudflare/circl.git","description":null}
{"name":"la/kernel/google-modules/soc/msm","clone_url":"https://git.codelinaro.org/clo/la/kernel/google-modules/soc/msm.git","description":null}
{"name":"la/platform/external/go-subcommands","clone_url":"https://git.codelinaro.org/clo/la/platform/external/go-subcommands.git","description":null}
{"name":"la/platform/packages/apps/ContactsPicker","clone_url":"https://git.codelinaro.org/clo/la/platform/packages/apps/ContactsPicker.git","description":null}
{"name":"la/platform/system/software_defined_vehicle/telemetry","clone_url":"https://git.codelinaro.org/clo/la/platform/system/software_defined_vehicle/telemetry.git","description":null}
{"name":"la/platform/vendor/opensource/display-devicetree","clone_url":"https://git.codelinaro.org/clo/la/platform/vendor/opensource/display-devicetree.git","description":null}
{"name":"la/platform/external/flashrom","clone_url":"https://git.codelinaro.org/clo/la/platform/external/flashrom.git","description":null}
{"name":"la/trusty/app/nvram","clone_url":"https://git.codelinaro.org/clo/la/trusty/app/nvram.git","description":null}
{"name":"la/platform/vendor/qcom-opensource/soa-infra","clone_url":"https://git.codelinaro.org/clo/la/platform/vendor/qcom-opensource/soa-infra.git","description":null}
{"name":"la/platform/system/software_defined_vehicle/platform","clone_url":"https://git.codelinaro.org/clo/la/platform/system/software_defined_vehicle/platform.git","description":null}
{"name":"la/platform/external/can-utils","clone_url":"https://git.codelinaro.org/clo/la/platform/external/can-utils.git","description":null}
{"name":"lc/external/github.com/seleniumhq/selenium/py","clone_url":"https://git.codelinaro.org/clo/lc/external/github.com/seleniumhq/selenium/py.git","description":null}
{"name":"qcomlt/ci/staging/meta-qcom-ci","clone_url":"https://git.codelinaro.org/clo/qcomlt/ci/staging/meta-qcom-ci.git","description":null}
{"name":"la/gcdb-kernel","clone_url":"https://git.codelinaro.org/clo/la/gcdb-kernel.git","description":null}
{"name":"le/platform/vendor/qcom-opensource/wlan/qcawifi-cmn-dev","clone_url":"https://git.codelinaro.org/clo/le/platform/vendor/qcom-opensource/wlan/qcawifi-cmn-dev.git","description":null}
{"name":"le/platform/vendor/qcom-opensource/qrb-ros-service","clone_url":"https://git.codelinaro.org/clo/le/platform/vendor/qcom-opensource/qrb-ros-service.git","description":null}
{"name":"le/platform/vendor/qcom-opensource/snaptel-sdk","clone_url":"https://git.codelinaro.org/clo/le/platform/vendor/qcom-opensource/snaptel-sdk.git","description":null}
{"name":"qrdk/dibbler","clone_url":"https://git.codelinaro.org/clo/qrdk/dibbler.git","description":null}
{"name":"la/platform/external/ms-tpm-20-ref","clone_url":"https://git.codelinaro.org/clo/la/platform/external/ms-tpm-20-ref.git","description":null}
{"name":"la/platform/external/expat","clone_url":"https://git.codelinaro.org/clo/la/platform/external/expat.git","description":null}
{"name":"le/meta-qcom","clone_url":"https://git.codelinaro.org/clo/le/meta-qcom.git","description":null}
{"name":"la/platform/external/boost-submodules/unordered","clone_url":"https://git.codelinaro.org/clo/la/platform/external/boost-submodules/unordered.git","description":null}
{"name":"la/platform/packages/modules/MediaSwCodec","clone_url":"https://git.codelinaro.org/clo/la/platform/packages/modules/MediaSwCodec.git","description":null}
{"name":"la/platform/external/rust/crates/uniffi_core","clone_url":"https://git.codelinaro.org/clo/la/platform/external/rust/crates/uniffi_core.git","description":null}
{"name":"qsdk/googletest","clone_url":"https://git.codelinaro.org/clo/qsdk/googletest.git","description":null}
{"name":"la/platform/external/libjpeg-turbo","clone_url":"https://git.codelinaro.org/clo/la/platform/external/libjpeg-turbo.git","description":null}
{"name":"qrdk/rdkcentral/gw-provisioning-application","clone_url":"https://git.codelinaro.org/clo/qrdk/rdkcentral/gw-provisioning-application.git","description":null}
{"name":"yocto-mirrors/github/gofrs/flock","clone_url":"https://git.codelinaro.org/clo/yocto-mirrors/github/gofrs/flock.git","description":null}
{"name":"femto5g/oss/system/feeds/packages","clone_url":"https://git.codelinaro.org/clo/femto5g/oss/system/feeds/packages.git","description":null}
{"name":"le/platform/vendor/qcom-opensource/dataservices","clone_url":"https://git.codelinaro.org/clo/le/platform/vendor/qcom-opensource/dataservices.git","description":null}
{"name":"la/platform/prebuilts/module_sdk/AdServices","clone_url":"https://git.codelinaro.org/clo/la/platform/prebuilts/module_sdk/AdServices.git","description":null}
{"name":"le/external/protobuf","clone_url":"https://git.codelinaro.org/clo/le/external/protobuf.git","description":null}
{"name":"la/platform/vendor/qcom/apq8026_lw","clone_url":"https://git.codelinaro.org/clo/la/platform/vendor/qcom/apq8026_lw.git","description":null}
{"name":"le/platform/external/slam_gmapping","clone_url":"https://git.codelinaro.org/clo/le/platform/external/slam_gmapping.git","description":null}
{"name":"le/robosdk/oss/auto-explore","clone_url":"https://git.codelinaro.org/clo/le/robosdk/oss/auto-explore.git","description":null}
{"name":"lc/chromiumos/third_party/bluez","clone_url":"https://git.codelinaro.org/clo/lc/chromiumos/third_party/bluez.git","description":null}
{"name":"dataservices/modem-data-manager","clone_url":"https://git.codelinaro.org/clo/dataservices/modem-data-manager.git","description":null}
{"name":"le/platform/vendor/qcom-opensource/adk-managers","clone_url":"https://git.codelinaro.org/clo/le/platform/vendor/qcom-opensource/adk-managers.git","description":null}
{"name":"lc/chromiumos/platform/cromo","clone_url":"https://git.codelinaro.org/clo/lc/chromiumos/platform/cromo.git","description":null}
{"name":"le/qc/components/qesdk-core-le.lnx/oe-recipes-oss","clone_url":"https://git.codelinaro.org/clo/le/qc/components/qesdk-core-le.lnx/oe-recipes-oss.git","description":null}
{"name":"qrdk/releases/manifest/qrdk","clone_url":"https://git.codelinaro.org/clo/qrdk/releases/manifest/qrdk.git","description":null}
{"name":"la/platform/external/rust/crates/tower-service","clone_url":"https://git.codelinaro.org/clo/la/platform/external/rust/crates/tower-service.git","description":null}
{"name":"la/platform/external/FreeRTOS/coreMQTT","clone_url":"https://git.codelinaro.org/clo/la/platform/external/FreeRTOS/coreMQTT.git","description":null}
{"name":"la/platform/external/gmmlib","clone_url":"https://git.codelinaro.org/clo/la/platform/external/gmmlib.git","description":null}
{"name":"la/platform/vendor/qcom-opensource/twowheeler/apps/Settings","clone_url":"https://git.codelinaro.org/clo/la/platform/vendor/qcom-opensource/twowheeler/apps/Settings.git","description":null}
{"name":"qsdk/platform/vendor/qcom/opensource/data/hostsw/libqmi","clone_url":"https://git.codelinaro.org/clo/qsdk/platform/vendor/qcom/opensource/data/hostsw/libqmi.git","description":null}
{"name":"qrdk/code.rdkcentral.com/rdk/components/generic/rdk-oe/meta-rdk-ext","clone_url":"https://git.codelinaro.org/clo/qrdk/code.rdkcentral.com/rdk/components/generic/rdk-oe/meta-rdk-ext.git","description":null}
{"name":"la/platform/vendor/qcom/opensource/dsp-kernel","clone_url":"https://git.codelinaro.org/clo/la/platform/vendor/qcom/opensource/dsp-kernel.git","description":null}
{"name":"le/qccsdk/oss/qtcapy","clone_url":"https://git.codelinaro.org/clo/le/qccsdk/oss/qtcapy.git","description":null}
{"name":"la/platform/vendor/nxp/opensource/monaco/halimpl","clone_url":"https://git.codelinaro.org/clo/la/platform/vendor/nxp/opensource/monaco/halimpl.git","description":null}
{"name":"qcomlt/demos/linux","clone_url":"https://git.codelinaro.org/clo/qcomlt/demos/linux.git","description":"Qualcomm Landing Team Linux Demo trees\r\n\r\nDo not remove branches or tags, those are expected to be stable and valid for blog posts and marketing purposes.\r\n\r\ntopic/* branches are protected against modifications, do not change.\r\n\r\nDo not push work-in-progress or working branches here, only marketing/demo material."}
{"name":"lc/codesearch/infra/infra","clone_url":"https://git.codelinaro.org/clo/lc/codesearch/infra/infra.git","description":null}
{"name":"la/platform/external/rust/crates/arbitrary","clone_url":"https://git.codelinaro.org/clo/la/platform/external/rust/crates/arbitrary.git","description":null}
{"name":"yocto-mirrors/time","clone_url":"https://git.codelinaro.org/clo/yocto-mirrors/time.git","description":null}
{"name":"la/platform/external/python/google-auth-httplib2","clone_url":"https://git.codelinaro.org/clo/la/platform/external/python/google-auth-httplib2.git","description":null}
{"name":"ype/meta-openwrt","clone_url":"https://git.codelinaro.org/clo/ype/meta-openwrt.git","description":null}
{"name":"la/tools/test/project4","clone_url":"https://git.codelinaro.org/clo/la/tools/test/project4.git","description":null}
{"name":"la/platform/external/federated-compute","clone_url":"https://git.codelinaro.org/clo/la/platform/external/federated-compute.git","description":null}
{"name":"la/platform/packages/modules/bootprebuilt/5.10/arm64","clone_url":"https://git.codelinaro.org/clo/la/platform/packages/modules/bootprebuilt/5.10/arm64.git","description":null}
{"name":"le/platform/vendor/qcom-opensource/data-kernel","clone_url":"https://git.codelinaro.org/clo/le/platform/vendor/qcom-opensource/data-kernel.git","description":null}
{"name":"qsdk/tensorflow","clone_url":"https://git.codelinaro.org/clo/qsdk/tensorflow.git","description":null}
{"name":"la/techpack/display/manifest","clone_url":"https://git.codelinaro.org/clo/la/techpack/display/manifest.git","description":null}
{"name":"le/platform/vendor/qcom-opensource/usb","clone_url":"https://git.codelinaro.org/clo/le/platform/vendor/qcom-opensource/usb.git","description":null}
{"name":"la/platform/external/rust/crates/winnow","clone_url":"https://git.codelinaro.org/clo/la/platform/external/rust/crates/winnow.git","description":null}
{"name":"la/platform/vendor/qcom-opensource/hsi2s-kernel","clone_url":"https://git.codelinaro.org/clo/la/platform/vendor/qcom-opensource/hsi2s-kernel.git","description":null}
{"name":"la/platform/packages/apps/GoogleSearch","clone_url":"https://git.codelinaro.org/clo/la/platform/packages/apps/GoogleSearch.git","description":null}
{"name":"la/device/google/sdv_display_safety","clone_url":"https://git.codelinaro.org/clo/la/device/google/sdv_display_safety.git","description":null}
{"name":"transport-monitoring-wifi-and-cellular-traffic/patches","clone_url":"https://git.codelinaro.org/clo/transport-monitoring-wifi-and-cellular-traffic/patches.git","description":null}
{"name":"la/kernel/google-modules/raviole-device","clone_url":"https://git.codelinaro.org/clo/la/kernel/google-modules/raviole-device.git","description":null}
{"name":"la/platform/vendor/qcom/msm8910","clone_url":"https://git.codelinaro.org/clo/la/platform/vendor/qcom/msm8910.git","description":null}
{"name":"le/virtio/qcvirtio-rtc-host-driver-linux","clone_url":"https://git.codelinaro.org/clo/le/virtio/qcvirtio-rtc-host-driver-linux.git","description":null}
{"name":"mcs/patches","clone_url":"https://git.codelinaro.org/clo/mcs/patches.git","description":null}
{"name":"kernel-platform-2-0-os/kernel_platform/prebuilts/bazel/linux-x86_64","clone_url":"https://git.codelinaro.org/clo/kernel-platform-2-0-os/kernel_platform/prebuilts/bazel/linux-x86_64.git","description":null}
{"name":"le/platform/eks-sw-oss","clone_url":"https://git.codelinaro.org/clo/le/platform/eks-sw-oss.git","description":null}
{"name":"la/platform/external/autotest","clone_url":"https://git.codelinaro.org/clo/la/platform/external/autotest.git","description":null}
{"name":"la/platform/vendor/qcom-opensource/location","clone_url":"https://git.codelinaro.org/clo/la/platform/vendor/qcom-opensource/location.git","description":null}
{"name":"la/platform/external/jetbrains/jdk8u_jaxp","clone_url":"https://git.codelinaro.org/clo/la/platform/external/jetbrains/jdk8u_jaxp.git","description":null}
{"name":"lc/chromium/deps/ffmpeg/binaries/win","clone_url":"https://git.codelinaro.org/clo/lc/chromium/deps/ffmpeg/binaries/win.git","description":null}
{"name":"qsdk/oss/system/feeds/data-oss","clone_url":"https://git.codelinaro.org/clo/qsdk/oss/system/feeds/data-oss.git","description":null}
{"name":"la/device/google/shusky","clone_url":"https://git.codelinaro.org/clo/la/device/google/shusky.git","description":null}
{"name":"la/platform/vendor/qcom/msm7627_surf","clone_url":"https://git.codelinaro.org/clo/la/platform/vendor/qcom/msm7627_surf.git","description":null}
{"name":"rdkb/rdkb/components/opensource/ccsp/hotspot","clone_url":"https://git.codelinaro.org/clo/rdkb/rdkb/components/opensource/ccsp/hotspot.git","description":null}
{"name":"femto/platform/system/core","clone_url":"https://git.codelinaro.org/clo/femto/platform/system/core.git","description":null}
{"name":"lc/chromiumos/third_party/ktop","clone_url":"https://git.codelinaro.org/clo/lc/chromiumos/third_party/ktop.git","description":null}
{"name":"femto5g/external/yoctoproject.org/meta-gplv2","clone_url":"https://git.codelinaro.org/clo/femto5g/external/yoctoproject.org/meta-gplv2.git","description":null}
{"name":"le/platform/external/rust/crates/android_logger","clone_url":"https://git.codelinaro.org/clo/le/platform/external/rust/crates/android_logger.git","description":null}
{"name":"la/platform/external/cros/system_api","clone_url":"https://git.codelinaro.org/clo/la/platform/external/cros/system_api.git","description":null}
{"name":"la/platform/superproject_group/main-with-phones","clone_url":"https://git.codelinaro.org/clo/la/platform/superproject_group/main-with-phones.git","description":null}
{"name":"la/platform/vendor/qcom/opensource/graphics-devicetree","clone_url":"https://git.codelinaro.org/clo/la/platform/vendor/qcom/opensource/graphics-devicetree.git","description":null}
{"name":"lc/external/github.com/golang/lint","clone_url":"https://git.codelinaro.org/clo/lc/external/github.com/golang/lint.git","description":null}
{"name":"le/pseudo","clone_url":"https://git.codelinaro.org/clo/le/pseudo.git","description":null}
{"name":"la/platform/external/moshi","clone_url":"https://git.codelinaro.org/clo/la/platform/external/moshi.git","description":null}
{"name":"qsdk/openthread","clone_url":"https://git.codelinaro.org/clo/qsdk/openthread.git","description":null}
{"name":"lf/releases/l10n/tr/gecko","clone_url":"https://git.codelinaro.org/clo/lf/releases/l10n/tr/gecko.git","description":null}
{"name":"la/platform/prebuilts/gcc/linux-x86/arm/arm-linux-androideabi-4.6","clone_url":"https://git.codelinaro.org/clo/la/platform/prebuilts/gcc/linux-x86/arm/arm-linux-androideabi-4.6.git","description":null}
{"name":"la/platform/vendor/qcom/peafowl","clone_url":"https://git.codelinaro.org/clo/la/platform/vendor/qcom/peafowl.git","description":null}
{"name":"la/platform/external/archive-patcher","clone_url":"https://git.codelinaro.org/clo/la/platform/external/archive-patcher.git","description":null}
{"name":"le/platform/vendor/opensource/eva-kernel","clone_url":"https://git.codelinaro.org/clo/le/platform/vendor/opensource/eva-kernel.git","description":null}
{"name":"le/qrcp","clone_url":"https://git.codelinaro.org/clo/le/qrcp.git","description":null}
{"name":"qsdk/platform/vendor/opensource/audio-kernel","clone_url":"https://git.codelinaro.org/clo/qsdk/platform/vendor/opensource/audio-kernel.git","description":null}
{"name":"la/platform/external/google-fonts/arbutus-slab","clone_url":"https://git.codelinaro.org/clo/la/platform/external/google-fonts/arbutus-slab.git","description":null}
{"name":"la/platform/packages/modules/Telecom","clone_url":"https://git.codelinaro.org/clo/la/platform/packages/modules/Telecom.git","description":null}
{"name":"la/platform/vendor/qcom/msm8625","clone_url":"https://git.codelinaro.org/clo/la/platform/vendor/qcom/msm8625.git","description":null}
{"name":"qsdk/oss/system/openwrt/feeds/openthread","clone_url":"https://git.codelinaro.org/clo/qsdk/oss/system/openwrt/feeds/openthread.git","description":null}
{"name":"la/platform/external/obex","clone_url":"https://git.codelinaro.org/clo/la/platform/external/obex.git","description":null}
{"name":"la/platform/tools/external/go/src/github.com/go-gl-legacy/gl","clone_url":"https://git.codelinaro.org/clo/la/platform/tools/external/go/src/github.com/go-gl-legacy/gl.git","description":null}
{"name":"le/meta-qti-ml","clone_url":"https://git.codelinaro.org/clo/le/meta-qti-ml.git","description":null}
{"name":"le/gorilla/context","clone_url":"https://git.codelinaro.org/clo/le/gorilla/context.git","description":null}
{"name":"la/platform/external/boost-submodules/fiber","clone_url":"https://git.codelinaro.org/clo/la/platform/external/boost-submodules/fiber.git","description":null}
{"name":"la/platform/hardware/google/interfaces","clone_url":"https://git.codelinaro.org/clo/la/platform/hardware/google/interfaces.git","description":null}
{"name":"la/platform/external/jackson-databind","clone_url":"https://git.codelinaro.org/clo/la/platform/external/jackson-databind.git","description":null}
{"name":"la/device/google/felix-kernel","clone_url":"https://git.codelinaro.org/clo/la/device/google/felix-kernel.git","description":null}
{"name":"rdkb/rdk/components/generic/libSyscallWrapper","clone_url":"https://git.codelinaro.org/clo/rdkb/rdk/components/generic/libSyscallWrapper.git","description":null}
{"name":"la/platform/prebuilts/clang/darwin-x86/host/3.4","clone_url":"https://git.codelinaro.org/clo/la/platform/prebuilts/clang/darwin-x86/host/3.4.git","description":null}
{"name":"yocto-mirrors/github/linux-msm/pd-mapper","clone_url":"https://git.codelinaro.org/clo/yocto-mirrors/github/linux-msm/pd-mapper.git","description":null}
{"name":"la/platform/external/turbine","clone_url":"https://git.codelinaro.org/clo/la/platform/external/turbine.git","description":null}
{"name":"la/platform/hardware/qcom/sdm429w/wlan","clone_url":"https://git.codelinaro.org/clo/la/platform/hardware/qcom/sdm429w/wlan.git","description":null}
{"name":"la/platform/prebuilts/fullsdk/build-tools/21-darwin","clone_url":"https://git.codelinaro.org/clo/la/platform/prebuilts/fullsdk/build-tools/21-darwin.git","description":null}
{"name":"la/platform/external/boost-submodules/mp11","clone_url":"https://git.codelinaro.org/clo/la/platform/external/boost-submodules/mp11.git","description":null}
{"name":"kernel-platform-2-0-os/kernel_platform/toolchain/prebuilts/ndk/r23","clone_url":"https://git.codelinaro.org/clo/kernel-platform-2-0-os/kernel_platform/toolchain/prebuilts/ndk/r23.git","description":null}
{"name":"boot/zephyr","clone_url":"https://git.codelinaro.org/clo/boot/zephyr.git","description":null}
{"name":"rdkb/rdk/components/opensource/oe/meta-python2","clone_url":"https://git.codelinaro.org/clo/rdkb/rdk/components/opensource/oe/meta-python2.git","description":null}
{"name":"la/kernel/prebuilts/4.19/arm64","clone_url":"https://git.codelinaro.org/clo/la/kernel/prebuilts/4.19/arm64.git","description":null}
{"name":"la/usr/local/google/partner/kernel/private/msm-google-modules/data-kernel","clone_url":"https://git.codelinaro.org/clo/la/usr/local/google/partner/kernel/private/msm-google-modules/data-kernel.git","description":null}
{"name":"la/device/qcom/vendor-common","clone_url":"https://git.codelinaro.org/clo/la/device/qcom/vendor-common.git","description":null}
{"name":"la/platform/build/soong","clone_url":"https://git.codelinaro.org/clo/la/platform/build/soong.git","description":null}
{"name":"la/platform/external/libcups","clone_url":"https://git.codelinaro.org/clo/la/platform/external/libcups.git","description":null}
{"name":"la/platform/packages/apps/Car/Dashcam","clone_url":"https://git.codelinaro.org/clo/la/platform/packages/apps/Car/Dashcam.git","description":null}
{"name":"la/device/google/wahoo-kernel","clone_url":"https://git.codelinaro.org/clo/la/device/google/wahoo-kernel.git","description":null}
{"name":"le/mdm/webserver","clone_url":"https://git.codelinaro.org/clo/le/mdm/webserver.git","description":null}
{"name":"le/ros2-gbp/iceoryx-release","clone_url":"https://git.codelinaro.org/clo/le/ros2-gbp/iceoryx-release.git","description":null}
{"name":"la/platform/external/rust/crates/ciborium-ll","clone_url":"https://git.codelinaro.org/clo/la/platform/external/rust/crates/ciborium-ll.git","description":null}
{"name":"la/platform/vendor/qcom-opensource/core-utils-vendor","clone_url":"https://git.codelinaro.org/clo/la/platform/vendor/qcom-opensource/core-utils-vendor.git","description":null}
{"name":"la/platform/system/linkerconfig","clone_url":"https://git.codelinaro.org/clo/la/platform/system/linkerconfig.git","description":null}
{"name":"la/platform/external/boost-submodules/multi_array","clone_url":"https://git.codelinaro.org/clo/la/platform/external/boost-submodules/multi_array.git","description":null}
{"name":"le/qzephyr/zephyrproject-rtos/littlefs","clone_url":"https://git.codelinaro.org/clo/le/qzephyr/zephyrproject-rtos/littlefs.git","description":null}
{"name":"qyocto/patches","clone_url":"https://git.codelinaro.org/clo/qyocto/patches.git","description":null}
{"name":"la/platform/external/python/google-cloud-pubsub","clone_url":"https://git.codelinaro.org/clo/la/platform/external/python/google-cloud-pubsub.git","description":null}
{"name":"le/external/github.com/tdk_robotics_rbx_drivers_code","clone_url":"https://git.codelinaro.org/clo/le/external/github.com/tdk_robotics_rbx_drivers_code.git","description":null}
{"name":"la/platform/vendor/google_shared/build/release","clone_url":"https://git.codelinaro.org/clo/la/platform/vendor/google_shared/build/release.git","description":null}
{"name":"la/toolchain/prebuilts/ndk/r14","clone_url":"https://git.codelinaro.org/clo/la/toolchain/prebuilts/ndk/r14.git","description":null}
{"name":"la/device/freescale/picoimx","clone_url":"https://git.codelinaro.org/clo/la/device/freescale/picoimx.git","description":null}
{"name":"la/device/asus/tilapia","clone_url":"https://git.codelinaro.org/clo/la/device/asus/tilapia.git","description":null}
{"name":"rdkb/rdk/components/generic/sys_mon_tools/mem_analyser_tools","clone_url":"https://git.codelinaro.org/clo/rdkb/rdk/components/generic/sys_mon_tools/mem_analyser_tools.git","description":null}
{"name":"qsdk/oss/qca/feeds/qca-rsrcmgr/driver","clone_url":"https://git.codelinaro.org/clo/qsdk/oss/qca/feeds/qca-rsrcmgr/driver.git","description":null}
{"name":"la/platform/hardware/qcom/boot-ctl","clone_url":"https://git.codelinaro.org/clo/la/platform/hardware/qcom/boot-ctl.git","description":null}
{"name":"la/platform/external/rust/crates/proc-macro-hack","clone_url":"https://git.codelinaro.org/clo/la/platform/external/rust/crates/proc-macro-hack.git","description":null}
{"name":"la/device/google/cuttlefish_common","clone_url":"https://git.codelinaro.org/clo/la/device/google/cuttlefish_common.git","description":null}
{"name":"la/platform/vendor/qcom/lahaina612","clone_url":"https://git.codelinaro.org/clo/la/platform/vendor/qcom/lahaina612.git","description":null}
{"name":"lc/chromium/src/tools/mb","clone_url":"https://git.codelinaro.org/clo/lc/chromium/src/tools/mb.git","description":null}
{"name":"le/hyperlocal-windows","clone_url":"https://git.codelinaro.org/clo/le/hyperlocal-windows.git","description":null}
{"name":"la/platform/external/bluetooth/btconfig","clone_url":"https://git.codelinaro.org/clo/la/platform/external/bluetooth/btconfig.git","description":null}
{"name":"la/platform/external/rust/crates/cc","clone_url":"https://git.codelinaro.org/clo/la/platform/external/rust/crates/cc.git","description":null}
{"name":"la/trusty/lib","clone_url":"https://git.codelinaro.org/clo/la/trusty/lib.git","description":null}
{"name":"la/platform/external/zstd","clone_url":"https://git.codelinaro.org/clo/la/platform/external/zstd.git","description":null}
{"name":"la/external/github.com/quic-qrb-ros/qrb_ros_nn_inference","clone_url":"https://git.codelinaro.org/clo/la/external/github.com/quic-qrb-ros/qrb_ros_nn_inference.git","description":null}
{"name":"iris-video-driver/iris-v3","clone_url":"https://git.codelinaro.org/clo/iris-video-driver/iris-v3.git","description":null}
{"name":"yocto-mirrors/github/mattn/go-shellwords","clone_url":"https://git.codelinaro.org/clo/yocto-mirrors/github/mattn/go-shellwords.git","description":null}
{"name":"le/rosidl_typesupport_fastrtps-release","clone_url":"https://git.codelinaro.org/clo/le/rosidl_typesupport_fastrtps-release.git","description":null}
{"name":"le/qzephyr/zephyrproject-rtos/segger","clone_url":"https://git.codelinaro.org/clo/le/qzephyr/zephyrproject-rtos/segger.git","description":null}
{"name":"la/kernel/arcvm-modules/common","clone_url":"https://git.codelinaro.org/clo/la/kernel/arcvm-modules/common.git","description":null}
{"name":"la/device/qcom/qssi_32","clone_url":"https://git.codelinaro.org/clo/la/device/qcom/qssi_32.git","description":null}
{"name":"la/platform/external/boost-submodules/bimap","clone_url":"https://git.codelinaro.org/clo/la/platform/external/boost-submodules/bimap.git","description":null}
{"name":"la/platform/external/tlsdate","clone_url":"https://git.codelinaro.org/clo/la/platform/external/tlsdate.git","description":null}
{"name":"la/platform/external/marisa-trie","clone_url":"https://git.codelinaro.org/clo/la/platform/external/marisa-trie.git","description":null}
{"name":"lc/infra/luci/luci-py_repo","clone_url":"https://git.codelinaro.org/clo/lc/infra/luci/luci-py_repo.git","description":null}
{"name":"la/platform/external/ant-wireless/ant_client","clone_url":"https://git.codelinaro.org/clo/la/platform/external/ant-wireless/ant_client.git","description":null}
{"name":"yocto-mirrors/github/systemd/systemd","clone_url":"https://git.codelinaro.org/clo/yocto-mirrors/github/systemd/systemd.git","description":null}
{"name":"la/platform/tools/content_addressed_storage/prebuilts","clone_url":"https://git.codelinaro.org/clo/la/platform/tools/content_addressed_storage/prebuilts.git","description":null}
{"name":"la/kernelplatform/prebuilts-master/clang/host/linux-x86","clone_url":"https://git.codelinaro.org/clo/la/kernelplatform/prebuilts-master/clang/host/linux-x86.git","description":null}
{"name":"yocto-mirrors/github/go-ole/go-ole","clone_url":"https://git.codelinaro.org/clo/yocto-mirrors/github/go-ole/go-ole.git","description":null}
{"name":"lc/external/coreboot.org/flashrom","clone_url":"https://git.codelinaro.org/clo/lc/external/coreboot.org/flashrom.git","description":null}
{"name":"la/platform/hardware/bsp/kernel/rockchip","clone_url":"https://git.codelinaro.org/clo/la/platform/hardware/bsp/kernel/rockchip.git","description":null}
{"name":"la/platform/external/messageformat","clone_url":"https://git.codelinaro.org/clo/la/platform/external/messageformat.git","description":null}
{"name":"la/platform/vendor/opensource/hexlp-oss","clone_url":"https://git.codelinaro.org/clo/la/platform/vendor/opensource/hexlp-oss.git","description":null}
{"name":"la/platform/prebuilts/rust-toolchain/darwin","clone_url":"https://git.codelinaro.org/clo/la/platform/prebuilts/rust-toolchain/darwin.git","description":null}
{"name":"yocto-mirrors/platform","clone_url":"https://git.codelinaro.org/clo/yocto-mirrors/platform.git","description":null}
{"name":"lf/releases/l10n/ar/gaia","clone_url":"https://git.codelinaro.org/clo/lf/releases/l10n/ar/gaia.git","description":null}
{"name":"yocto-mirrors/github/stackexchange/wmi","clone_url":"https://git.codelinaro.org/clo/yocto-mirrors/github/stackexchange/wmi.git","description":null}
{"name":"la/kernel/msm-modules_group/graphics","clone_url":"https://git.codelinaro.org/clo/la/kernel/msm-modules_group/graphics.git","description":null}
{"name":"la/platform/vendor/opensource/gen4-5/virtio-video","clone_url":"https://git.codelinaro.org/clo/la/platform/vendor/opensource/gen4-5/virtio-video.git","description":null}
{"name":"femto5g/oss/system/feeds/platform/bootloader","clone_url":"https://git.codelinaro.org/clo/femto5g/oss/system/feeds/platform/bootloader.git","description":null}
{"name":"la/platform/external/boost-submodules/compute","clone_url":"https://git.codelinaro.org/clo/la/platform/external/boost-submodules/compute.git","description":null}
{"name":"iot-solutions-microservices/tripwire-analytics","clone_url":"https://git.codelinaro.org/clo/iot-solutions-microservices/tripwire-analytics.git","description":null}
{"name":"arriver-archive/patches","clone_url":"https://git.codelinaro.org/clo/arriver-archive/patches.git","description":null}
{"name":"le/owrt/feeds/feed_qos_firewall","clone_url":"https://git.codelinaro.org/clo/le/owrt/feeds/feed_qos_firewall.git","description":null}
{"name":"qsdk/URI.js","clone_url":"https://git.codelinaro.org/clo/qsdk/URI.js.git","description":null}
{"name":"la/platform/vendor/csr/unifi-60xx","clone_url":"https://git.codelinaro.org/clo/la/platform/vendor/csr/unifi-60xx.git","description":null}
{"name":"le/platform/vendor/qcom-opensource/wlan/cawifi-cmn-dev","clone_url":"https://git.codelinaro.org/clo/le/platform/vendor/qcom-opensource/wlan/cawifi-cmn-dev.git","description":null}
{"name":"la/platform/external/wayland-protocols","clone_url":"https://git.codelinaro.org/clo/la/platform/external/wayland-protocols.git","description":null}
{"name":"la/platform/external/mockwebserver","clone_url":"https://git.codelinaro.org/clo/la/platform/external/mockwebserver.git","description":null}
{"name":"la/kernel_platform/toolchain/prebuilts/ndk/r23","clone_url":"https://git.codelinaro.org/clo/la/kernel_platform/toolchain/prebuilts/ndk/r23.git","description":null}
{"name":"lc/native_client/src/native_client/site_scons","clone_url":"https://git.codelinaro.org/clo/lc/native_client/src/native_client/site_scons.git","description":null}
{"name":"le/external/github.com/quic-qrb-ros/qrb_ros_samples","clone_url":"https://git.codelinaro.org/clo/le/external/github.com/quic-qrb-ros/qrb_ros_samples.git","description":null}
{"name":"la/platform/vendor/stm/opensource/keymaster","clone_url":"https://git.codelinaro.org/clo/la/platform/vendor/stm/opensource/keymaster.git","description":null}
{"name":"lc/chromiumos/containers/crostini-theme","clone_url":"https://git.codelinaro.org/clo/lc/chromiumos/containers/crostini-theme.git","description":null}
{"name":"la/platform/hardware/qcom/media","clone_url":"https://git.codelinaro.org/clo/la/platform/hardware/qcom/media.git","description":null}
{"name":"le/external/date","clone_url":"https://git.codelinaro.org/clo/le/external/date.git","description":null}
{"name":"la/platform/hardware/qcom/msm8994","clone_url":"https://git.codelinaro.org/clo/la/platform/hardware/qcom/msm8994.git","description":null}
{"name":"rdkb/rdkb/components/opensource/ccsp/TestAndDiagnostic","clone_url":"https://git.codelinaro.org/clo/rdkb/rdkb/components/opensource/ccsp/TestAndDiagnostic.git","description":null}
{"name":"femto5g/fsm/external/qoriq-components/linux_5.4-rt","clone_url":"https://git.codelinaro.org/clo/femto5g/fsm/external/qoriq-components/linux_5.4-rt.git","description":null}
{"name":"la/platform/vendor/qcom-opensource/fm","clone_url":"https://git.codelinaro.org/clo/la/platform/vendor/qcom-opensource/fm.git","description":null}
{"name":"le/platform/vendor/qcom-opensource/vhost-user-lib","clone_url":"https://git.codelinaro.org/clo/le/platform/vendor/qcom-opensource/vhost-user-lib.git","description":null}
{"name":"la/platform/external/rust/crates/openmls","clone_url":"https://git.codelinaro.org/clo/la/platform/external/rust/crates/openmls.git","description":null}
{"name":"qsdk/odhcpd","clone_url":"https://git.codelinaro.org/clo/qsdk/odhcpd.git","description":null}
{"name":"la/platform/prebuilts/go/darwin-x86","clone_url":"https://git.codelinaro.org/clo/la/platform/prebuilts/go/darwin-x86.git","description":null}
{"name":"la/platform/frameworks/libs/service_entitlement","clone_url":"https://git.codelinaro.org/clo/la/platform/frameworks/libs/service_entitlement.git","description":null}
{"name":"la/platform/external/shaderc/spirv-tools","clone_url":"https://git.codelinaro.org/clo/la/platform/external/shaderc/spirv-tools.git","description":null}
{"name":"lc/chromiumos/platform/monitor_reconfig","clone_url":"https://git.codelinaro.org/clo/lc/chromiumos/platform/monitor_reconfig.git","description":null}
{"name":"lf/releases/l10n/sr/gecko","clone_url":"https://git.codelinaro.org/clo/lf/releases/l10n/sr/gecko.git","description":null}
{"name":"le/ros2-gbp/rclc-release","clone_url":"https://git.codelinaro.org/clo/le/ros2-gbp/rclc-release.git","description":null}
{"name":"la/platform/external/mm-dash","clone_url":"https://git.codelinaro.org/clo/la/platform/external/mm-dash.git","description":null}
{"name":"qsdk/oss/src/qca-extns/wlan-app-extns","clone_url":"https://git.codelinaro.org/clo/qsdk/oss/src/qca-extns/wlan-app-extns.git","description":null}
{"name":"la/platform/packages/apps/WallpaperPicker","clone_url":"https://git.codelinaro.org/clo/la/platform/packages/apps/WallpaperPicker.git","description":null}
{"name":"la/kernel_platform/external/openssl","clone_url":"https://git.codelinaro.org/clo/la/kernel_platform/external/openssl.git","description":null}
{"name":"la/platform/packages/modules/CellBroadcastService","clone_url":"https://git.codelinaro.org/clo/la/platform/packages/modules/CellBroadcastService.git","description":null}
{"name":"la/platform/external/open-vcdiff","clone_url":"https://git.codelinaro.org/clo/la/platform/external/open-vcdiff.git","description":null}
{"name":"yocto-mirrors/github/spf13/jwalterweatherman","clone_url":"https://git.codelinaro.org/clo/yocto-mirrors/github/spf13/jwalterweatherman.git","description":null}
{"name":"la/platform/packages/modules/ImsStack","clone_url":"https://git.codelinaro.org/clo/la/platform/packages/modules/ImsStack.git","description":null}
{"name":"qsdk/android-x86/kernel","clone_url":"https://git.codelinaro.org/clo/qsdk/android-x86/kernel.git","description":null}
{"name":"rdkb/rdkb/components/generic/harvester","clone_url":"https://git.codelinaro.org/clo/rdkb/rdkb/components/generic/harvester.git","description":null}
{"name":"le/qcom-gstreamer","clone_url":"https://git.codelinaro.org/clo/le/qcom-gstreamer.git","description":null}
{"name":"la/platform/vendor/qcom/sa2390_au","clone_url":"https://git.codelinaro.org/clo/la/platform/vendor/qcom/sa2390_au.git","description":null}
{"name":"le/vlm/asn1c","clone_url":"https://git.codelinaro.org/clo/le/vlm/asn1c.git","description":null}
{"name":"lc/external/github.com/eliben/pycparser","clone_url":"https://git.codelinaro.org/clo/lc/external/github.com/eliben/pycparser.git","description":null}
{"name":"la/toolchain/gcc-12.2.0","clone_url":"https://git.codelinaro.org/clo/la/toolchain/gcc-12.2.0.git","description":null}
{"name":"qrdk/glog","clone_url":"https://git.codelinaro.org/clo/qrdk/glog.git","description":null}
{"name":"la/platform/packages/apps/Car/SystemUI","clone_url":"https://git.codelinaro.org/clo/la/platform/packages/apps/Car/SystemUI.git","description":null}
{"name":"qsdk/ltp","clone_url":"https://git.codelinaro.org/clo/qsdk/ltp.git","description":null}
{"name":"la/platform/smaratorg","clone_url":"https://git.codelinaro.org/clo/la/platform/smaratorg.git","description":null}
{"name":"lc/external/angle","clone_url":"https://git.codelinaro.org/clo/lc/external/angle.git","description":null}
{"name":"la/platform/external/jetbrains/jdk8u_jaxws","clone_url":"https://git.codelinaro.org/clo/la/platform/external/jetbrains/jdk8u_jaxws.git","description":null}
{"name":"qsdk/oss/system/feeds/luci","clone_url":"https://git.codelinaro.org/clo/qsdk/oss/system/feeds/luci.git","description":null}
{"name":"le/owrt/feeds/feed_netmodel","clone_url":"https://git.codelinaro.org/clo/le/owrt/feeds/feed_netmodel.git","description":null}
{"name":"la/platform/external/libutf","clone_url":"https://git.codelinaro.org/clo/la/platform/external/libutf.git","description":null}
{"name":"la/platform/external/rust/crates/windows","clone_url":"https://git.codelinaro.org/clo/la/platform/external/rust/crates/windows.git","description":null}
{"name":"la/platform/external/boost-submodules/leaf","clone_url":"https://git.codelinaro.org/clo/la/platform/external/boost-submodules/leaf.git","description":null}
{"name":"la/platform/tools/external/go/src/github.com/go-gl/glfw","clone_url":"https://git.codelinaro.org/clo/la/platform/tools/external/go/src/github.com/go-gl/glfw.git","description":null}
{"name":"la/platform/external/junit","clone_url":"https://git.codelinaro.org/clo/la/platform/external/junit.git","description":null}
{"name":"yocto-mirrors/github/ros2-gbp/eigen_stl_containers-release","clone_url":"https://git.codelinaro.org/clo/yocto-mirrors/github/ros2-gbp/eigen_stl_containers-release.git","description":null}
{"name":"yocto-mirrors/github/thomasdickey/ncurses-snapshots","clone_url":"https://git.codelinaro.org/clo/yocto-mirrors/github/thomasdickey/ncurses-snapshots.git","description":null}
{"name":"la/device/google/cuttlefish_kernel","clone_url":"https://git.codelinaro.org/clo/la/device/google/cuttlefish_kernel.git","description":null}
{"name":"la/platform/system/libvintf","clone_url":"https://git.codelinaro.org/clo/la/platform/system/libvintf.git","description":null}
{"name":"le/ros2-gbp/rclpy-release","clone_url":"https://git.codelinaro.org/clo/le/ros2-gbp/rclpy-release.git","description":null}
{"name":"la/platform/external/rust/crates/psci","clone_url":"https://git.codelinaro.org/clo/la/platform/external/rust/crates/psci.git","description":null}
