{"name":"la/platform/external/nanopb-c","clone_url":"https://git.codelinaro.org/clo/la/platform/external/nanopb-c.git","description":null}
{"name":"la/platform/tools/test/mobly_snippets","clone_url":"https://git.codelinaro.org/clo/la/platform/tools/test/mobly_snippets.git","description":null}
{"name":"yocto-mirrors/github/jinzhu/now","clone_url":"https://git.codelinaro.org/clo/yocto-mirrors/github/jinzhu/now.git","description":null}
{"name":"le/virtio/qcvirtio-vhost-usb-gadget-driver-linux","clone_url":"https://git.codelinaro.org/clo/le/virtio/qcvirtio-vhost-usb-gadget-driver-linux.git","description":null}
{"name":"la/kernel/common","clone_url":"https://git.codelinaro.org/clo/la/kernel/common.git","description":null}
{"name":"la/platform/packages/apps/Car/LensPicker","clone_url":"https://git.codelinaro.org/clo/la/platform/packages/apps/Car/LensPicker.git","description":null}
{"name":"le/meta-qti-ros","clone_url":"https://git.codelinaro.org/clo/le/meta-qti-ros.git","description":null}
{"name":"la/kernel_platform/external/bazelbuild-rules_rust","clone_url":"https://git.codelinaro.org/clo/la/kernel_platform/external/bazelbuild-rules_rust.git","description":null}
{"name":"lf/releases/l10n/de/gaia","clone_url":"https://git.codelinaro.org/clo/lf/releases/l10n/de/gaia.git","description":null}
{"name":"yocto-mirrors/github/reference-lapack/lapack","clone_url":"https://git.codelinaro.org/clo/yocto-mirrors/github/reference-lapack/lapack.git","description":null}
{"name":"lc/external/github.com/google/material-text-accessibility-ios","clone_url":"https://git.codelinaro.org/clo/lc/external/github.com/google/material-text-accessibility-ios.git","description":null}
{"name":"la/device/google/shusky-sepolicy","clone_url":"https://git.codelinaro.org/clo/la/device/google/shusky-sepolicy.git","description":null}
{"name":"la/platform/external/rust/crates/clap_lex","clone_url":"https://git.codelinaro.org/clo/la/platform/external/rust/crates/clap_lex.git","description":null}
{"name":"le/ros2-gbp/rcl_logging-release","clone_url":"https://git.codelinaro.org/clo/le/ros2-gbp/rcl_logging-release.git","description":null}
{"name":"la/openocd-org/openocd","clone_url":"https://git.codelinaro.org/clo/la/openocd-org/openocd.git","description":null}
{"name":"la/platform/system/security","clone_url":"https://git.codelinaro.org/clo/la/platform/system/security.git","description":null}
{"name":"la/platform/packages/apps/DevCamera","clone_url":"https://git.codelinaro.org/clo/la/platform/packages/apps/DevCamera.git","description":null}
{"name":"qsdk/oss/system/tools/meta","clone_url":"https://git.codelinaro.org/clo/qsdk/oss/system/tools/meta.git","description":null}
{"name":"lf/releases/l10n/hu/gaia","clone_url":"https://git.codelinaro.org/clo/lf/releases/l10n/hu/gaia.git","description":null}
{"name":"la/platform/vendor/qcom-opensource/hsi2s-kernel","clone_url":"https://git.codelinaro.org/clo/la/platform/vendor/qcom-opensource/hsi2s-kernel.git","description":null}
{"name":"lc/external/github.com/golang/lint","clone_url":"https://git.codelinaro.org/clo/lc/external/github.com/golang/lint.git","description":null}
{"name":"la/kernel/amlogic-tv-modules/wifi_rtl8822BS","clone_url":"https://git.codelinaro.org/clo/la/kernel/amlogic-tv-modules/wifi_rtl8822BS.git","description":null}
{"name":"la/toolchain/ccache","clone_url":"https://git.codelinaro.org/clo/la/toolchain/ccache.git","description":null}
{"name":"la/platform/external/lohit-fonts","clone_url":"https://git.codelinaro.org/clo/la/platform/external/lohit-fonts.git","description":null}
{"name":"la/platform/packages/apps/HTMLViewer","clone_url":"https://git.codelinaro.org/clo/la/platform/packages/apps/HTMLViewer.git","description":null}
{"name":"femto5g/lldp/meta-freescale-distro","clone_url":"https://git.codelinaro.org/clo/femto5g/lldp/meta-freescale-distro.git","description":null}
{"name":"la/platform/test/vts-testcase/nbu","clone_url":"https://git.codelinaro.org/clo/la/platform/test/vts-testcase/nbu.git","description":null}
{"name":"la/platform/prebuilts/fullsdk-darwin/build-tools","clone_url":"https://git.codelinaro.org/clo/la/platform/prebuilts/fullsdk-darwin/build-tools.git","description":null}
{"name":"la/platform/external/stardoc","clone_url":"https://git.codelinaro.org/clo/la/platform/external/stardoc.git","description":null}
{"name":"qcomlt/ci/u-boot/u-boot-test-hooks","clone_url":"https://git.codelinaro.org/clo/qcomlt/ci/u-boot/u-boot-test-hooks.git","description":""}
{"name":"la/platform/tools/emulator","clone_url":"https://git.codelinaro.org/clo/la/platform/tools/emulator.git","description":null}
{"name":"la/platform/tools/apkzlib","clone_url":"https://git.codelinaro.org/clo/la/platform/tools/apkzlib.git","description":null}
{"name":"la/platform/external/r8","clone_url":"https://git.codelinaro.org/clo/la/platform/external/r8.git","description":null}
{"name":"la/platform/tools/apifinder","clone_url":"https://git.codelinaro.org/clo/la/platform/tools/apifinder.git","description":null}
{"name":"qsdk/wireless-regdb","clone_url":"https://git.codelinaro.org/clo/qsdk/wireless-regdb.git","description":null}
{"name":"yocto-mirrors/github/google/uuid","clone_url":"https://git.codelinaro.org/clo/yocto-mirrors/github/google/uuid.git","description":null}
{"name":"yocto-mirrors/github/ros2-gbp/perception_pcl-release","clone_url":"https://git.codelinaro.org/clo/yocto-mirrors/github/ros2-gbp/perception_pcl-release.git","description":null}
{"name":"lc/external/github.com/llvm-mirror/llvm","clone_url":"https://git.codelinaro.org/clo/lc/external/github.com/llvm-mirror/llvm.git","description":null}
{"name":"la/platform/vendor/qcom/opensource/audio-vibrator","clone_url":"https://git.codelinaro.org/clo/la/platform/vendor/qcom/opensource/audio-vibrator.git","description":null}
{"name":"la/kernel/prebuilts/common-modules/virtual-device/6.12/arm64","clone_url":"https://git.codelinaro.org/clo/la/kernel/prebuilts/common-modules/virtual-device/6.12/arm64.git","description":null}
{"name":"la/platform/tools/studio/cloud","clone_url":"https://git.codelinaro.org/clo/la/platform/tools/studio/cloud.git","description":null}
{"name":"yocto-mirrors/github/ros2-gbp/eigen_stl_containers-release","clone_url":"https://git.codelinaro.org/clo/yocto-mirrors/github/ros2-gbp/eigen_stl_containers-release.git","description":null}
{"name":"la/device/google/felix-kernels/5.10","clone_url":"https://git.codelinaro.org/clo/la/device/google/felix-kernels/5.10.git","description":null}
{"name":"femto5g/platform/external/libdrm","clone_url":"https://git.codelinaro.org/clo/femto5g/platform/external/libdrm.git","description":null}
{"name":"la/platform/external/rust/crates/predicates-core","clone_url":"https://git.codelinaro.org/clo/la/platform/external/rust/crates/predicates-core.git","description":null}
{"name":"le/AGL/apps/mediaplayer","clone_url":"https://git.codelinaro.org/clo/le/AGL/apps/mediaplayer.git","description":null}
{"name":"le/platform/vendor/opensource/display/libdrm","clone_url":"https://git.codelinaro.org/clo/le/platform/vendor/opensource/display/libdrm.git","description":null}
{"name":"testproject/platform/external/fastrpc","clone_url":"https://git.codelinaro.org/clo/testproject/platform/external/fastrpc.git","description":null}
{"name":"testproject/platform/packages/apps/SoundRecorder","clone_url":"https://git.codelinaro.org/clo/testproject/platform/packages/apps/SoundRecorder.git","description":null}
{"name":"la/platform/external/rust/crates/rustc-demangle-capi","clone_url":"https://git.codelinaro.org/clo/la/platform/external/rust/crates/rustc-demangle-capi.git","description":null}
{"name":"vmbsp/patches","clone_url":"https://git.codelinaro.org/clo/vmbsp/patches.git","description":null}
{"name":"la/platform/external/boost-submodules/optional","clone_url":"https://git.codelinaro.org/clo/la/platform/external/boost-submodules/optional.git","description":null}
{"name":"rdkb/rdkcentral/zilker-sdk","clone_url":"https://git.codelinaro.org/clo/rdkb/rdkcentral/zilker-sdk.git","description":null}
{"name":"lc/native_client/pnacl-llvm","clone_url":"https://git.codelinaro.org/clo/lc/native_client/pnacl-llvm.git","description":null}
{"name":"le/WPEBackend-fdo","clone_url":"https://git.codelinaro.org/clo/le/WPEBackend-fdo.git","description":null}
{"name":"qsdk/oss/feeds/nss","clone_url":"https://git.codelinaro.org/clo/qsdk/oss/feeds/nss.git","description":null}
{"name":"testproject/platform/external/libbackup","clone_url":"https://git.codelinaro.org/clo/testproject/platform/external/libbackup.git","description":null}
{"name":"testproject/platform/external/libsrtp2","clone_url":"https://git.codelinaro.org/clo/testproject/platform/external/libsrtp2.git","description":null}
{"name":"la/toolchain/lld","clone_url":"https://git.codelinaro.org/clo/la/toolchain/lld.git","description":null}
{"name":"la/platform/external/rust/crates/etherparse","clone_url":"https://git.codelinaro.org/clo/la/platform/external/rust/crates/etherparse.git","description":null}
{"name":"la/platform/external/rust/crates/time-macros-impl","clone_url":"https://git.codelinaro.org/clo/la/platform/external/rust/crates/time-macros-impl.git","description":null}
{"name":"la/framework/system/dlog","clone_url":"https://git.codelinaro.org/clo/la/framework/system/dlog.git","description":null}
{"name":"qsdk/oss/ubi32-toolchain/gcc","clone_url":"https://git.codelinaro.org/clo/qsdk/oss/ubi32-toolchain/gcc.git","description":null}
{"name":"la/platform/packages/services/eSETerminal","clone_url":"https://git.codelinaro.org/clo/la/platform/packages/services/eSETerminal.git","description":null}
{"name":"le/platform/hardware/qcom/camera","clone_url":"https://git.codelinaro.org/clo/le/platform/hardware/qcom/camera.git","description":null}
{"name":"qrdk/rdkcentral/broadband-utils","clone_url":"https://git.codelinaro.org/clo/qrdk/rdkcentral/broadband-utils.git","description":null}
{"name":"qcomlt/perf-benchmark-scripts","clone_url":"https://git.codelinaro.org/clo/qcomlt/perf-benchmark-scripts.git","description":null}
{"name":"yocto-mirrors/github/sparkleholic/ltrace","clone_url":"https://git.codelinaro.org/clo/yocto-mirrors/github/sparkleholic/ltrace.git","description":null}
{"name":"le/owrt-qti-conf","clone_url":"https://git.codelinaro.org/clo/le/owrt-qti-conf.git","description":null}
{"name":"la/platform/external/boost-submodules/uuid","clone_url":"https://git.codelinaro.org/clo/la/platform/external/boost-submodules/uuid.git","description":null}
{"name":"yocto-mirrors/github/esnet/iperf","clone_url":"https://git.codelinaro.org/clo/yocto-mirrors/github/esnet/iperf.git","description":null}
{"name":"testproject/device/qcom/sepolicy","clone_url":"https://git.codelinaro.org/clo/testproject/device/qcom/sepolicy.git","description":null}
{"name":"yocto-mirrors/github/moby/locker","clone_url":"https://git.codelinaro.org/clo/yocto-mirrors/github/moby/locker.git","description":null}
{"name":"testproject/platform/frameworks/hardware/interfaces","clone_url":"https://git.codelinaro.org/clo/testproject/platform/frameworks/hardware/interfaces.git","description":null}
{"name":"la/platform/external/boost-submodules/format","clone_url":"https://git.codelinaro.org/clo/la/platform/external/boost-submodules/format.git","description":null}
{"name":"yocto-mirrors/crypto","clone_url":"https://git.codelinaro.org/clo/yocto-mirrors/crypto.git","description":null}
{"name":"la/platform/hardware/bsp/kernel/freescale_group/picoimx-3.14","clone_url":"https://git.codelinaro.org/clo/la/platform/hardware/bsp/kernel/freescale_group/picoimx-3.14.git","description":null}
{"name":"yocto-mirrors/github/mobile-broadband/libqrtr-glib","clone_url":"https://git.codelinaro.org/clo/yocto-mirrors/github/mobile-broadband/libqrtr-glib.git","description":null}
{"name":"la/platform/external/go-etree","clone_url":"https://git.codelinaro.org/clo/la/platform/external/go-etree.git","description":null}
{"name":"la/platform/vendor/qcom-opensource/mmtests","clone_url":"https://git.codelinaro.org/clo/la/platform/vendor/qcom-opensource/mmtests.git","description":null}
{"name":"la/build/core","clone_url":"https://git.codelinaro.org/clo/la/build/core.git","description":null}
{"name":"le/OTA/build","clone_url":"https://git.codelinaro.org/clo/le/OTA/build.git","description":null}
{"name":"le/platform/vendor/qcom-opensource/adk-utils","clone_url":"https://git.codelinaro.org/clo/le/platform/vendor/qcom-opensource/adk-utils.git","description":null}
{"name":"lc/arm-trusted-firmware","clone_url":"https://git.codelinaro.org/clo/lc/arm-trusted-firmware.git","description":null}
{"name":"la/platform/packages/modules/NetworkPermissionConfig","clone_url":"https://git.codelinaro.org/clo/la/platform/packages/modules/NetworkPermissionConfig.git","description":null}
{"name":"la/platform/external/rust/crates/rand_core","clone_url":"https://git.codelinaro.org/clo/la/platform/external/rust/crates/rand_core.git","description":null}
{"name":"le/owrt/feeds/feed_net_hl_services","clone_url":"https://git.codelinaro.org/clo/le/owrt/feeds/feed_net_hl_services.git","description":null}
{"name":"automotive/platform/external/Open-AVB","clone_url":"https://git.codelinaro.org/clo/automotive/platform/external/Open-AVB.git","description":null}
{"name":"yocto-mirrors/github/docker/go-metrics","clone_url":"https://git.codelinaro.org/clo/yocto-mirrors/github/docker/go-metrics.git","description":null}
{"name":"la/platform/vendor/qcom-opensource/soa-infra","clone_url":"https://git.codelinaro.org/clo/la/platform/vendor/qcom-opensource/soa-infra.git","description":null}
{"name":"le/platform/external/boot-time-analysis-tools","clone_url":"https://git.codelinaro.org/clo/le/platform/external/boot-time-analysis-tools.git","description":null}
{"name":"la/trusty/device/nxp/imx6ul","clone_url":"https://git.codelinaro.org/clo/la/trusty/device/nxp/imx6ul.git","description":null}
{"name":"le/platform/hardware/qcom/display","clone_url":"https://git.codelinaro.org/clo/le/platform/hardware/qcom/display.git","description":null}
{"name":"testproject/platform/external/google-fonts/lato","clone_url":"https://git.codelinaro.org/clo/testproject/platform/external/google-fonts/lato.git","description":null}
{"name":"la/platform/external/volley","clone_url":"https://git.codelinaro.org/clo/la/platform/external/volley.git","description":null}
{"name":"qcomlt/db-boot-tools","clone_url":"https://git.codelinaro.org/clo/qcomlt/db-boot-tools.git","description":null}
{"name":"testproject/platform/external/subsampling-scale-image-view","clone_url":"https://git.codelinaro.org/clo/testproject/platform/external/subsampling-scale-image-view.git","description":null}
{"name":"la/toolchain/riscv_gnu_toolchain","clone_url":"https://git.codelinaro.org/clo/la/toolchain/riscv_gnu_toolchain.git","description":null}
{"name":"la/kernel_platform/external/bazel-skylib","clone_url":"https://git.codelinaro.org/clo/la/kernel_platform/external/bazel-skylib.git","description":null}
{"name":"la/platform/external/boost","clone_url":"https://git.codelinaro.org/clo/la/platform/external/boost.git","description":null}
{"name":"lc/chromium/src/components/arc/mojom","clone_url":"https://git.codelinaro.org/clo/lc/chromium/src/components/arc/mojom.git","description":null}
{"name":"testproject/platform/external/guice","clone_url":"https://git.codelinaro.org/clo/testproject/platform/external/guice.git","description":null}
{"name":"la/platform/packages/apps/Car/LocalMediaPlayer","clone_url":"https://git.codelinaro.org/clo/la/platform/packages/apps/Car/LocalMediaPlayer.git","description":null}
{"name":"yocto-mirrors/pflag","clone_url":"https://git.codelinaro.org/clo/yocto-mirrors/pflag.git","description":null}
{"name":"la/toolchain/mpc-1.2.1","clone_url":"https://git.codelinaro.org/clo/la/toolchain/mpc-1.2.1.git","description":null}
{"name":"la/platform/test/vts-testcase/performance","clone_url":"https://git.codelinaro.org/clo/la/platform/test/vts-testcase/performance.git","description":null}
{"name":"le/meta-imx","clone_url":"https://git.codelinaro.org/clo/le/meta-imx.git","description":null}
{"name":"la/platform/external/rust/crates/proc-macro-nested","clone_url":"https://git.codelinaro.org/clo/la/platform/external/rust/crates/proc-macro-nested.git","description":null}
{"name":"la/platform/prebuilts/gcc/linux-x86/aarch64/aarch64-linux-android-4.9","clone_url":"https://git.codelinaro.org/clo/la/platform/prebuilts/gcc/linux-x86/aarch64/aarch64-linux-android-4.9.git","description":null}
{"name":"lc/custom-tabs-client","clone_url":"https://git.codelinaro.org/clo/lc/custom-tabs-client.git","description":null}
{"name":"la/platform/external/epid-sdk","clone_url":"https://git.codelinaro.org/clo/la/platform/external/epid-sdk.git","description":null}
{"name":"lc/chromiumos/platform2/system_api","clone_url":"https://git.codelinaro.org/clo/lc/chromiumos/platform2/system_api.git","description":null}
{"name":"femto5g/oss/lklm/nss-ppe","clone_url":"https://git.codelinaro.org/clo/femto5g/oss/lklm/nss-ppe.git","description":null}
{"name":"la/platform/frameworks/opt/datetimepicker","clone_url":"https://git.codelinaro.org/clo/la/platform/frameworks/opt/datetimepicker.git","description":null}
{"name":"qsdk/oss/prpl-foundation/prplos/feeds/feed_board_configuration","clone_url":"https://git.codelinaro.org/clo/qsdk/oss/prpl-foundation/prplos/feeds/feed_board_configuration.git","description":null}
{"name":"yocto-mirrors/protobuf","clone_url":"https://git.codelinaro.org/clo/yocto-mirrors/protobuf.git","description":null}
{"name":"femto/oss/lklm/nss-drv","clone_url":"https://git.codelinaro.org/clo/femto/oss/lklm/nss-drv.git","description":null}
{"name":"qrdk/c-ares","clone_url":"https://git.codelinaro.org/clo/qrdk/c-ares.git","description":null}
{"name":"la/platform/vendor/qcom-opensource/nfc-devicetree","clone_url":"https://git.codelinaro.org/clo/la/platform/vendor/qcom-opensource/nfc-devicetree.git","description":null}
{"name":"la/platform/hardware/qcom/audio-ar","clone_url":"https://git.codelinaro.org/clo/la/platform/hardware/qcom/audio-ar.git","description":null}
{"name":"la/platform/system/tpm","clone_url":"https://git.codelinaro.org/clo/la/platform/system/tpm.git","description":null}
{"name":"la/platform/external/rust/crates/async-stream-impl","clone_url":"https://git.codelinaro.org/clo/la/platform/external/rust/crates/async-stream-impl.git","description":null}
{"name":"la/platform/external/licenseclassifier","clone_url":"https://git.codelinaro.org/clo/la/platform/external/licenseclassifier.git","description":null}
{"name":"la/platform/external/libopus","clone_url":"https://git.codelinaro.org/clo/la/platform/external/libopus.git","description":null}
{"name":"la/platform/vendor/qcom/peafowl","clone_url":"https://git.codelinaro.org/clo/la/platform/vendor/qcom/peafowl.git","description":null}
{"name":"la/platform/external/spdx-tools","clone_url":"https://git.codelinaro.org/clo/la/platform/external/spdx-tools.git","description":null}
{"name":"qsdk/platform/vendor/qcom/opensource/datarmnet","clone_url":"https://git.codelinaro.org/clo/qsdk/platform/vendor/qcom/opensource/datarmnet.git","description":null}
{"name":"qcc7xx/patches","clone_url":"https://git.codelinaro.org/clo/qcc7xx/patches.git","description":null}
{"name":"yocto-mirrors/github/golang/protobuf","clone_url":"https://git.codelinaro.org/clo/yocto-mirrors/github/golang/protobuf.git","description":null}
{"name":"le/mdm/wlan","clone_url":"https://git.codelinaro.org/clo/le/mdm/wlan.git","description":null}
{"name":"la/platform/external/elfcopy","clone_url":"https://git.codelinaro.org/clo/la/platform/external/elfcopy.git","description":null}
{"name":"le/platform/external/libchromeos-rs","clone_url":"https://git.codelinaro.org/clo/le/platform/external/libchromeos-rs.git","description":null}
{"name":"la/platform/vendor/qcom-opensource/lights","clone_url":"https://git.codelinaro.org/clo/la/platform/vendor/qcom-opensource/lights.git","description":null}
{"name":"la/device/google/raviole","clone_url":"https://git.codelinaro.org/clo/la/device/google/raviole.git","description":null}
{"name":"qsdk/netifd","clone_url":"https://git.codelinaro.org/clo/qsdk/netifd.git","description":null}
{"name":"lc/external/github.com/maruel/ut","clone_url":"https://git.codelinaro.org/clo/lc/external/github.com/maruel/ut.git","description":null}
{"name":"testproject/platform/packages/apps/OneTimeInitializer","clone_url":"https://git.codelinaro.org/clo/testproject/platform/packages/apps/OneTimeInitializer.git","description":null}
{"name":"la/platform/system/iorap","clone_url":"https://git.codelinaro.org/clo/la/platform/system/iorap.git","description":null}
{"name":"la/kernel/hikey-modules","clone_url":"https://git.codelinaro.org/clo/la/kernel/hikey-modules.git","description":null}
{"name":"la/platform/external/rust/crates/rayon","clone_url":"https://git.codelinaro.org/clo/la/platform/external/rust/crates/rayon.git","description":null}
{"name":"le/platform/vendor/qcom-opensource/adk-voice-ui-framework","clone_url":"https://git.codelinaro.org/clo/le/platform/vendor/qcom-opensource/adk-voice-ui-framework.git","description":null}
{"name":"lc/chromiumos/overlays/chromiumos-overlay__gob_meta__","clone_url":"https://git.codelinaro.org/clo/lc/chromiumos/overlays/chromiumos-overlay__gob_meta__.git","description":null}
{"name":"la/platform/vendor/qcom/copper","clone_url":"https://git.codelinaro.org/clo/la/platform/vendor/qcom/copper.git","description":null}
{"name":"la/platform/external/eyes-free","clone_url":"https://git.codelinaro.org/clo/la/platform/external/eyes-free.git","description":null}
{"name":"la/platform/external/httpcomponents","clone_url":"https://git.codelinaro.org/clo/la/platform/external/httpcomponents.git","description":null}
{"name":"la/platform/prebuilts/vndk/v28","clone_url":"https://git.codelinaro.org/clo/la/platform/prebuilts/vndk/v28.git","description":null}
{"name":"testproject/platform/external/minigbm","clone_url":"https://git.codelinaro.org/clo/testproject/platform/external/minigbm.git","description":null}
{"name":"qcomlt/pkg/gst-plugins-ugly1.0","clone_url":"https://git.codelinaro.org/clo/qcomlt/pkg/gst-plugins-ugly1.0.git","description":null}
{"name":"la/kernel/google-modules/bms","clone_url":"https://git.codelinaro.org/clo/la/kernel/google-modules/bms.git","description":null}
{"name":"la/platform/packages/modules/Virtualization","clone_url":"https://git.codelinaro.org/clo/la/platform/packages/modules/Virtualization.git","description":null}
{"name":"la/platform/external/rust/crates/hyper-timeout","clone_url":"https://git.codelinaro.org/clo/la/platform/external/rust/crates/hyper-timeout.git","description":null}
{"name":"testproject/platform/system/extras","clone_url":"https://git.codelinaro.org/clo/testproject/platform/system/extras.git","description":null}
{"name":"qsdk/oss/boot/u-boot-2025","clone_url":"https://git.codelinaro.org/clo/qsdk/oss/boot/u-boot-2025.git","description":null}
{"name":"la/platform/packages/apps/ImsServiceEntitlement","clone_url":"https://git.codelinaro.org/clo/la/platform/packages/apps/ImsServiceEntitlement.git","description":null}
{"name":"la/device/qcom/sdm429w/sepolicy","clone_url":"https://git.codelinaro.org/clo/la/device/qcom/sdm429w/sepolicy.git","description":null}
{"name":"la/kernel/msm-modules_group/graphics","clone_url":"https://git.codelinaro.org/clo/la/kernel/msm-modules_group/graphics.git","description":null}
{"name":"qsdk/platform/vendor/qcom/opensource/audio-le-platform-utils-mk","clone_url":"https://git.codelinaro.org/clo/qsdk/platform/vendor/qcom/opensource/audio-le-platform-utils-mk.git","description":null}
{"name":"lc/native_client/nacl_vs_addin","clone_url":"https://git.codelinaro.org/clo/lc/native_client/nacl_vs_addin.git","description":null}
{"name":"yocto-mirrors/github/google/certificate-transparency-go","clone_url":"https://git.codelinaro.org/clo/yocto-mirrors/github/google/certificate-transparency-go.git","description":null}
{"name":"la/platform/packages/services/DroidfoodAttestationFixer","clone_url":"https://git.codelinaro.org/clo/la/platform/packages/services/DroidfoodAttestationFixer.git","description":null}
{"name":"la/platform/external/libnl-headers","clone_url":"https://git.codelinaro.org/clo/la/platform/external/libnl-headers.git","description":null}
{"name":"la/platform/hardware/bsp/kernel/raspberrypi/pi-v4.1","clone_url":"https://git.codelinaro.org/clo/la/platform/hardware/bsp/kernel/raspberrypi/pi-v4.1.git","description":null}
{"name":"testproject/platform/external/google-fonts/fraunces","clone_url":"https://git.codelinaro.org/clo/testproject/platform/external/google-fonts/fraunces.git","description":null}
{"name":"la/platform/external/boringssl","clone_url":"https://git.codelinaro.org/clo/la/platform/external/boringssl.git","description":null}
{"name":"la/platform/external/rust/crates/structopt","clone_url":"https://git.codelinaro.org/clo/la/platform/external/rust/crates/structopt.git","description":null}
{"name":"le/meta-qti-telematics","clone_url":"https://git.codelinaro.org/clo/le/meta-qti-telematics.git","description":null}
{"name":"la/platform/vendor/qcom/sun","clone_url":"https://git.codelinaro.org/clo/la/platform/vendor/qcom/sun.git","description":null}
{"name":"la/platform/hardware/qcom/data/ipacfg-mgr","clone_url":"https://git.codelinaro.org/clo/la/platform/hardware/qcom/data/ipacfg-mgr.git","description":null}
{"name":"la/platform/packages/apps/Test/connectivity","clone_url":"https://git.codelinaro.org/clo/la/platform/packages/apps/Test/connectivity.git","description":null}
{"name":"la/platform/external/jemalloc","clone_url":"https://git.codelinaro.org/clo/la/platform/external/jemalloc.git","description":null}
{"name":"atlas7-automotive-linux/build/meta-csr-bsp","clone_url":"https://git.codelinaro.org/clo/atlas7-automotive-linux/build/meta-csr-bsp.git","description":null}
{"name":"yocto-mirrors/github/kr/pty","clone_url":"https://git.codelinaro.org/clo/yocto-mirrors/github/kr/pty.git","description":null}
{"name":"mcs/releases/manifest/mcs","clone_url":"https://git.codelinaro.org/clo/mcs/releases/manifest/mcs.git","description":null}
{"name":"la/platform/prebuilts/gcc/linux-x86/arm/arm-eabi-4.6","clone_url":"https://git.codelinaro.org/clo/la/platform/prebuilts/gcc/linux-x86/arm/arm-eabi-4.6.git","description":null}
{"name":"le/platform/external/mtpserver","clone_url":"https://git.codelinaro.org/clo/le/platform/external/mtpserver.git","description":null}
{"name":"la/platform/external/skia","clone_url":"https://git.codelinaro.org/clo/la/platform/external/skia.git","description":null}
{"name":"la/platform/packages/apps/DeskClock","clone_url":"https://git.codelinaro.org/clo/la/platform/packages/apps/DeskClock.git","description":null}
{"name":"la/platform/external/nanoprintf","clone_url":"https://git.codelinaro.org/clo/la/platform/external/nanoprintf.git","description":null}
{"name":"la/platform/vendor/qcom/bengal","clone_url":"https://git.codelinaro.org/clo/la/platform/vendor/qcom/bengal.git","description":null}
{"name":"le/platform/vendor/qcom-opensource/multimodule-mgr-oss","clone_url":"https://git.codelinaro.org/clo/le/platform/vendor/qcom-opensource/multimodule-mgr-oss.git","description":null}
{"name":"le-au-os/platform/hardware/ril","clone_url":"https://git.codelinaro.org/clo/le-au-os/platform/hardware/ril.git","description":null}
{"name":"la/platform/vendor/opensource/arspf-headers","clone_url":"https://git.codelinaro.org/clo/la/platform/vendor/opensource/arspf-headers.git","description":null}
{"name":"qcomlt/pkg/adreno-egl","clone_url":"https://git.codelinaro.org/clo/qcomlt/pkg/adreno-egl.git","description":null}
{"name":"yocto-mirrors/github/docker/docker-credential-helpers","clone_url":"https://git.codelinaro.org/clo/yocto-mirrors/github/docker/docker-credential-helpers.git","description":null}
{"name":"qsdk/qrtr","clone_url":"https://git.codelinaro.org/clo/qsdk/qrtr.git","description":null}
{"name":"la/platform/tools/test/openhst","clone_url":"https://git.codelinaro.org/clo/la/platform/tools/test/openhst.git","description":null}
{"name":"la/platform/tools/appbundle","clone_url":"https://git.codelinaro.org/clo/la/platform/tools/appbundle.git","description":null}
{"name":"le/owrt/feeds/feed_opensource","clone_url":"https://git.codelinaro.org/clo/le/owrt/feeds/feed_opensource.git","description":null}
{"name":"la/platform/vendor/qcom-opensource/fingerprint","clone_url":"https://git.codelinaro.org/clo/la/platform/vendor/qcom-opensource/fingerprint.git","description":null}
{"name":"yocto-mirrors/github/knqyf263/go-plugin","clone_url":"https://git.codelinaro.org/clo/yocto-mirrors/github/knqyf263/go-plugin.git","description":null}
{"name":"la/platform/prebuilts/gcc/darwin-x86/arm/arm-linux-androideabi-4.8","clone_url":"https://git.codelinaro.org/clo/la/platform/prebuilts/gcc/darwin-x86/arm/arm-linux-androideabi-4.8.git","description":null}
{"name":"le/meta-qti-gfx-devicetree","clone_url":"https://git.codelinaro.org/clo/le/meta-qti-gfx-devicetree.git","description":null}
{"name":"la/tools/aospstats","clone_url":"https://git.codelinaro.org/clo/la/tools/aospstats.git","description":null}
{"name":"kernel-platform-2-0-os/patches","clone_url":"https://git.codelinaro.org/clo/kernel-platform-2-0-os/patches.git","description":null}
{"name":"lc/external/github.com/golang/oauth2","clone_url":"https://git.codelinaro.org/clo/lc/external/github.com/golang/oauth2.git","description":null}
{"name":"la/platform/external/apache-harmony","clone_url":"https://git.codelinaro.org/clo/la/platform/external/apache-harmony.git","description":null}
{"name":"la/device/google/lynx-kernel","clone_url":"https://git.codelinaro.org/clo/la/device/google/lynx-kernel.git","description":null}
{"name":"testproject/platform/external/python/pyasn1","clone_url":"https://git.codelinaro.org/clo/testproject/platform/external/python/pyasn1.git","description":null}
{"name":"lc/external/bitbucket.org/birkenfeld/pygments-main","clone_url":"https://git.codelinaro.org/clo/lc/external/bitbucket.org/birkenfeld/pygments-main.git","description":null}
{"name":"la/platform/external/rapidjson","clone_url":"https://git.codelinaro.org/clo/la/platform/external/rapidjson.git","description":null}
{"name":"la/kernel_platform/external/zopfli","clone_url":"https://git.codelinaro.org/clo/la/kernel_platform/external/zopfli.git","description":null}
{"name":"la/device/google/tegu-kernels/6.1","clone_url":"https://git.codelinaro.org/clo/la/device/google/tegu-kernels/6.1.git","description":null}
{"name":"yocto-mirrors/code","clone_url":"https://git.codelinaro.org/clo/yocto-mirrors/code.git","description":null}
{"name":"la/platform/build/soong","clone_url":"https://git.codelinaro.org/clo/la/platform/build/soong.git","description":null}
{"name":"lc/chromiumos/chromite/abuildbot_config","clone_url":"https://git.codelinaro.org/clo/lc/chromiumos/chromite/abuildbot_config.git","description":null}
{"name":"qrdk/code.rdkcentral.com/rdk/components/generic/dca","clone_url":"https://git.codelinaro.org/clo/qrdk/code.rdkcentral.com/rdk/components/generic/dca.git","description":null}
{"name":"qcomlt/pkg/alsa-lib","clone_url":"https://git.codelinaro.org/clo/qcomlt/pkg/alsa-lib.git","description":null}
{"name":"ype/external/github.com/meta-clang","clone_url":"https://git.codelinaro.org/clo/ype/external/github.com/meta-clang.git","description":null}
{"name":"la/platform/external/hyphenation-patterns","clone_url":"https://git.codelinaro.org/clo/la/platform/external/hyphenation-patterns.git","description":null}
{"name":"la/platform/external/boost-submodules/concept_check","clone_url":"https://git.codelinaro.org/clo/la/platform/external/boost-submodules/concept_check.git","description":null}
{"name":"la/platform/external/python/more-itertools","clone_url":"https://git.codelinaro.org/clo/la/platform/external/python/more-itertools.git","description":null}
{"name":"le/AGL/staging/qtmultimedia-rtlfm-radio-plugin","clone_url":"https://git.codelinaro.org/clo/le/AGL/staging/qtmultimedia-rtlfm-radio-plugin.git","description":null}
{"name":"qcomlt/boot/optee_os","clone_url":"https://git.codelinaro.org/clo/qcomlt/boot/optee_os.git","description":""}
{"name":"la/platform/vendor/qcom/sdm429w/codeaurora/vibrator","clone_url":"https://git.codelinaro.org/clo/la/platform/vendor/qcom/sdm429w/codeaurora/vibrator.git","description":null}
{"name":"lc/arc/arc","clone_url":"https://git.codelinaro.org/clo/lc/arc/arc.git","description":null}
{"name":"testproject/platform/external/python/funcsigs","clone_url":"https://git.codelinaro.org/clo/testproject/platform/external/python/funcsigs.git","description":null}
{"name":"la/platform/vendor/qcom-opensource/rpc-util","clone_url":"https://git.codelinaro.org/clo/la/platform/vendor/qcom-opensource/rpc-util.git","description":null}
{"name":"yocto-mirrors/github/golang-jwt/jwt","clone_url":"https://git.codelinaro.org/clo/yocto-mirrors/github/golang-jwt/jwt.git","description":null}
{"name":"la/platform/external/golang-groupcache","clone_url":"https://git.codelinaro.org/clo/la/platform/external/golang-groupcache.git","description":null}
{"name":"adreno-opensource-ai/patches","clone_url":"https://git.codelinaro.org/clo/adreno-opensource-ai/patches.git","description":null}
{"name":"la/platform/hardware/qcom/thermal","clone_url":"https://git.codelinaro.org/clo/la/platform/hardware/qcom/thermal.git","description":null}
{"name":"le/ros2-gbp/image_transport_plugins-release","clone_url":"https://git.codelinaro.org/clo/le/ros2-gbp/image_transport_plugins-release.git","description":null}
{"name":"la/platform/external/rust/crates/percent-encoding","clone_url":"https://git.codelinaro.org/clo/la/platform/external/rust/crates/percent-encoding.git","description":null}
{"name":"la/platform/prebuilts/ndk","clone_url":"https://git.codelinaro.org/clo/la/platform/prebuilts/ndk.git","description":null}
{"name":"la/platform/external/python/ipaddress","clone_url":"https://git.codelinaro.org/clo/la/platform/external/python/ipaddress.git","description":null}
{"name":"lf/releases/l10n/pt-br/gaia","clone_url":"https://git.codelinaro.org/clo/lf/releases/l10n/pt-br/gaia.git","description":null}
{"name":"la/platform/external/egl-registry","clone_url":"https://git.codelinaro.org/clo/la/platform/external/egl-registry.git","description":null}
{"name":"le/platform/vendor/qcom-opensource/args","clone_url":"https://git.codelinaro.org/clo/le/platform/vendor/qcom-opensource/args.git","description":null}
{"name":"qsdk/easy-rsa","clone_url":"https://git.codelinaro.org/clo/qsdk/easy-rsa.git","description":null}
{"name":"qsdk/oss/lklm/nss-ae-clients","clone_url":"https://git.codelinaro.org/clo/qsdk/oss/lklm/nss-ae-clients.git","description":null}
{"name":"la/device/qcom/sepolicy","clone_url":"https://git.codelinaro.org/clo/la/device/qcom/sepolicy.git","description":null}
{"name":"la/platform/packages/apps/Bluetooth","clone_url":"https://git.codelinaro.org/clo/la/platform/packages/apps/Bluetooth.git","description":null}
{"name":"lf/releases/l10n/es/gaia","clone_url":"https://git.codelinaro.org/clo/lf/releases/l10n/es/gaia.git","description":null}
{"name":"wiki2022/notice","clone_url":"https://git.codelinaro.org/clo/wiki2022/notice.git","description":null}
{"name":"le/AGL/apps/low-level-can-service","clone_url":"https://git.codelinaro.org/clo/le/AGL/apps/low-level-can-service.git","description":null}
{"name":"le/platform/vendor/qcom-opensource/data-kernel_group/drivers/alphawave","clone_url":"https://git.codelinaro.org/clo/le/platform/vendor/qcom-opensource/data-kernel_group/drivers/alphawave.git","description":null}
{"name":"femto/oss/lklm/qca-nss-ecm","clone_url":"https://git.codelinaro.org/clo/femto/oss/lklm/qca-nss-ecm.git","description":null}
{"name":"la/platform/hardware/qcom/gps","clone_url":"https://git.codelinaro.org/clo/la/platform/hardware/qcom/gps.git","description":null}
{"name":"lc/chromiumos/platform/vboot_reference__gob_meta__","clone_url":"https://git.codelinaro.org/clo/lc/chromiumos/platform/vboot_reference__gob_meta__.git","description":null}
{"name":"la/platform/external/rust/crates/gdbstub","clone_url":"https://git.codelinaro.org/clo/la/platform/external/rust/crates/gdbstub.git","description":null}
{"name":"la/platform/hardware/qcom/sdm845/thermal","clone_url":"https://git.codelinaro.org/clo/la/platform/hardware/qcom/sdm845/thermal.git","description":null}
{"name":"lc/chromium/src/third_party/khronos","clone_url":"https://git.codelinaro.org/clo/lc/chromium/src/third_party/khronos.git","description":null}
{"name":"qsdk/hostap","clone_url":"https://git.codelinaro.org/clo/qsdk/hostap.git","description":null}
{"name":"la/kernel/msm-extra_group/devicetree","clone_url":"https://git.codelinaro.org/clo/la/kernel/msm-extra_group/devicetree.git","description":null}
{"name":"yocto-mirrors/github/ros2-gbp/ros2_tracing-release","clone_url":"https://git.codelinaro.org/clo/yocto-mirrors/github/ros2-gbp/ros2_tracing-release.git","description":null}
{"name":"la/platform/external/openthread","clone_url":"https://git.codelinaro.org/clo/la/platform/external/openthread.git","description":null}
{"name":"la/platform/packages/apps/LegacyCamera","clone_url":"https://git.codelinaro.org/clo/la/platform/packages/apps/LegacyCamera.git","description":null}
{"name":"lc/apps/screensaver","clone_url":"https://git.codelinaro.org/clo/lc/apps/screensaver.git","description":null}
{"name":"le/platform/external/connman","clone_url":"https://git.codelinaro.org/clo/le/platform/external/connman.git","description":null}
{"name":"qsdk/oss/system/feeds/shortcut-fe","clone_url":"https://git.codelinaro.org/clo/qsdk/oss/system/feeds/shortcut-fe.git","description":null}
{"name":"yocto-mirrors/containerd","clone_url":"https://git.codelinaro.org/clo/yocto-mirrors/containerd.git","description":null}
{"name":"la/platform/external/boost-submodules/intrusive","clone_url":"https://git.codelinaro.org/clo/la/platform/external/boost-submodules/intrusive.git","description":null}
{"name":"yocto-mirrors/github/codahale/rfc6979","clone_url":"https://git.codelinaro.org/clo/yocto-mirrors/github/codahale/rfc6979.git","description":null}
{"name":"la/platform/external/boost-submodules/log","clone_url":"https://git.codelinaro.org/clo/la/platform/external/boost-submodules/log.git","description":null}
{"name":"qsdk/acl","clone_url":"https://git.codelinaro.org/clo/qsdk/acl.git","description":null}
{"name":"le/AGLExport/mapviwer","clone_url":"https://git.codelinaro.org/clo/le/AGLExport/mapviwer.git","description":null}
{"name":"lc/external/github.com/dynamorio/drmemory","clone_url":"https://git.codelinaro.org/clo/lc/external/github.com/dynamorio/drmemory.git","description":null}
{"name":"lc/chromiumos/platform/mist","clone_url":"https://git.codelinaro.org/clo/lc/chromiumos/platform/mist.git","description":null}
{"name":"la/platform/external/python/absl-py","clone_url":"https://git.codelinaro.org/clo/la/platform/external/python/absl-py.git","description":null}
{"name":"la/platform/vendor/nxp/opensource/external/p61-jcop-kit","clone_url":"https://git.codelinaro.org/clo/la/platform/vendor/nxp/opensource/external/p61-jcop-kit.git","description":null}
{"name":"le-au-os/qcom-opensource/mdm-init","clone_url":"https://git.codelinaro.org/clo/le-au-os/qcom-opensource/mdm-init.git","description":null}
{"name":"femto5g/oss/releases/configs/qsdk","clone_url":"https://git.codelinaro.org/clo/femto5g/oss/releases/configs/qsdk.git","description":null}
{"name":"la/platform/external/deqp-deps/SPIRV-Tools","clone_url":"https://git.codelinaro.org/clo/la/platform/external/deqp-deps/SPIRV-Tools.git","description":null}
{"name":"la/platform/vendor/qcom/msm8660_surf","clone_url":"https://git.codelinaro.org/clo/la/platform/vendor/qcom/msm8660_surf.git","description":null}
{"name":"la/platform/external/boost-submodules/functional","clone_url":"https://git.codelinaro.org/clo/la/platform/external/boost-submodules/functional.git","description":null}
{"name":"la/platform/external/libcups","clone_url":"https://git.codelinaro.org/clo/la/platform/external/libcups.git","description":null}
{"name":"la/platform/vendor/qcom-opensource/someip-commonsys-intf","clone_url":"https://git.codelinaro.org/clo/la/platform/vendor/qcom-opensource/someip-commonsys-intf.git","description":null}
{"name":"la/platform/test/vti/test_serving","clone_url":"https://git.codelinaro.org/clo/la/platform/test/vti/test_serving.git","description":null}
{"name":"la/platform/bootable/deprecated-ota","clone_url":"https://git.codelinaro.org/clo/la/platform/bootable/deprecated-ota.git","description":null}
{"name":"lc/external/github.com/pkg/sftp","clone_url":"https://git.codelinaro.org/clo/lc/external/github.com/pkg/sftp.git","description":null}
{"name":"qsdk/android-x86/frameworks/base","clone_url":"https://git.codelinaro.org/clo/qsdk/android-x86/frameworks/base.git","description":null}
{"name":"la/platform/external/libchrome","clone_url":"https://git.codelinaro.org/clo/la/platform/external/libchrome.git","description":null}
{"name":"lc/chromium/src/android_webview/support_library/boundary_interfaces","clone_url":"https://git.codelinaro.org/clo/lc/chromium/src/android_webview/support_library/boundary_interfaces.git","description":null}
{"name":"lc/external/github.com/khronosgroup/Vulkan-Loader","clone_url":"https://git.codelinaro.org/clo/lc/external/github.com/khronosgroup/Vulkan-Loader.git","description":null}
{"name":"la/platform/vendor/qcom-opensource/wlan/qca-wifi-host-cmn","clone_url":"https://git.codelinaro.org/clo/la/platform/vendor/qcom-opensource/wlan/qca-wifi-host-cmn.git","description":null}
{"name":"qcomlt/lt-testplans","clone_url":"https://git.codelinaro.org/clo/qcomlt/lt-testplans.git","description":null}
{"name":"la/platform/prebuilts/clang/linux-x86/host/3.4","clone_url":"https://git.codelinaro.org/clo/la/platform/prebuilts/clang/linux-x86/host/3.4.git","description":null}
{"name":"qsdk/FFT_eval","clone_url":"https://git.codelinaro.org/clo/qsdk/FFT_eval.git","description":null}
{"name":"la/toolchain/valgrind","clone_url":"https://git.codelinaro.org/clo/la/toolchain/valgrind.git","description":null}
{"name":"qrdk/jsonpath","clone_url":"https://git.codelinaro.org/clo/qrdk/jsonpath.git","description":null}
{"name":"la/platform/external/jetbrains/jcef","clone_url":"https://git.codelinaro.org/clo/la/platform/external/jetbrains/jcef.git","description":null}
{"name":"la/platform/test/vts-testcase/fuzz","clone_url":"https://git.codelinaro.org/clo/la/platform/test/vts-testcase/fuzz.git","description":null}
{"name":"la/platform/hardware/stm","clone_url":"https://git.codelinaro.org/clo/la/platform/hardware/stm.git","description":null}
{"name":"la/platform/external/boost-submodules/interprocess","clone_url":"https://git.codelinaro.org/clo/la/platform/external/boost-submodules/interprocess.git","description":null}
{"name":"aisw/patches","clone_url":"https://git.codelinaro.org/clo/aisw/patches.git","description":null}
{"name":"testproject/platform/external/grpc-grpc-java","clone_url":"https://git.codelinaro.org/clo/testproject/platform/external/grpc-grpc-java.git","description":null}
{"name":"lc/chromium/deps/mozdownload","clone_url":"https://git.codelinaro.org/clo/lc/chromium/deps/mozdownload.git","description":null}
{"name":"yocto-mirrors/github/fsnotify/fsnotify","clone_url":"https://git.codelinaro.org/clo/yocto-mirrors/github/fsnotify/fsnotify.git","description":null}
{"name":"la/camera-samples","clone_url":"https://git.codelinaro.org/clo/la/camera-samples.git","description":null}
{"name":"la/platform/packages/apps/SystemUIGo","clone_url":"https://git.codelinaro.org/clo/la/platform/packages/apps/SystemUIGo.git","description":null}
{"name":"le/robosdk/qrsdk_tools","clone_url":"https://git.codelinaro.org/clo/le/robosdk/qrsdk_tools.git","description":null}
{"name":"yocto-mirrors/github/ros2-gbp/rmw-release","clone_url":"https://git.codelinaro.org/clo/yocto-mirrors/github/ros2-gbp/rmw-release.git","description":null}
{"name":"yocto-mirrors/github/google/certtostore","clone_url":"https://git.codelinaro.org/clo/yocto-mirrors/github/google/certtostore.git","description":null}
{"name":"la/kernel/google-modules/soc/gs","clone_url":"https://git.codelinaro.org/clo/la/kernel/google-modules/soc/gs.git","description":null}
{"name":"yocto-mirrors/github/khronosgroup/SPIRV-Tools","clone_url":"https://git.codelinaro.org/clo/yocto-mirrors/github/khronosgroup/SPIRV-Tools.git","description":null}
{"name":"yocto-mirrors/github/vishvananda/netns","clone_url":"https://git.codelinaro.org/clo/yocto-mirrors/github/vishvananda/netns.git","description":null}
{"name":"la/platform/packages/apps/InCallUI","clone_url":"https://git.codelinaro.org/clo/la/platform/packages/apps/InCallUI.git","description":null}
{"name":"la/platform/external/rust/crates/unsafe-libyaml","clone_url":"https://git.codelinaro.org/clo/la/platform/external/rust/crates/unsafe-libyaml.git","description":null}
{"name":"rdkb/rdkb/components/opensource/ccsp/CcspEthAgent","clone_url":"https://git.codelinaro.org/clo/rdkb/rdkb/components/opensource/ccsp/CcspEthAgent.git","description":null}
{"name":"lc/chromiumos/third_party/leveldb","clone_url":"https://git.codelinaro.org/clo/lc/chromiumos/third_party/leveldb.git","description":null}
{"name":"la/platform/external/rust/crates/smccc","clone_url":"https://git.codelinaro.org/clo/la/platform/external/rust/crates/smccc.git","description":null}
{"name":"testproject/platform/external/libyuv","clone_url":"https://git.codelinaro.org/clo/testproject/platform/external/libyuv.git","description":null}
{"name":"qrdk/rdkcentral/utopia","clone_url":"https://git.codelinaro.org/clo/qrdk/rdkcentral/utopia.git","description":null}
{"name":"la/platform/external/libssh2","clone_url":"https://git.codelinaro.org/clo/la/platform/external/libssh2.git","description":null}
{"name":"yocto-mirrors/Vulkan-Headers","clone_url":"https://git.codelinaro.org/clo/yocto-mirrors/Vulkan-Headers.git","description":null}
{"name":"testproject/platform/tools/trebuchet","clone_url":"https://git.codelinaro.org/clo/testproject/platform/tools/trebuchet.git","description":null}
{"name":"sba-patches/imxsupport_patches","clone_url":"https://git.codelinaro.org/clo/sba-patches/imxsupport_patches.git","description":null}
{"name":"le/qzephyr/zephyrproject-rtos/segger","clone_url":"https://git.codelinaro.org/clo/le/qzephyr/zephyrproject-rtos/segger.git","description":null}
{"name":"la/platform/external/python/typing","clone_url":"https://git.codelinaro.org/clo/la/platform/external/python/typing.git","description":null}
{"name":"qsdk/atf-qsdk/arm-trusted-firmware","clone_url":"https://git.codelinaro.org/clo/qsdk/atf-qsdk/arm-trusted-firmware.git","description":null}
{"name":"la/platform/external/rust/crates/hashbrown","clone_url":"https://git.codelinaro.org/clo/la/platform/external/rust/crates/hashbrown.git","description":null}
{"name":"la/platform/packages/apps/Gallery2","clone_url":"https://git.codelinaro.org/clo/la/platform/packages/apps/Gallery2.git","description":null}
{"name":"la/platform/packages/modules/DnsResolver","clone_url":"https://git.codelinaro.org/clo/la/platform/packages/modules/DnsResolver.git","description":null}
{"name":"la/platform/external/neven","clone_url":"https://git.codelinaro.org/clo/la/platform/external/neven.git","description":null}
{"name":"le/coqos/linux-kernel-drivers/bootloader-reboot-driver-linux","clone_url":"https://git.codelinaro.org/clo/le/coqos/linux-kernel-drivers/bootloader-reboot-driver-linux.git","description":null}
{"name":"yocto-mirrors/slirp4netns","clone_url":"https://git.codelinaro.org/clo/yocto-mirrors/slirp4netns.git","description":null}
{"name":"le/rtsp-linux-v2.6","clone_url":"https://git.codelinaro.org/clo/le/rtsp-linux-v2.6.git","description":null}
{"name":"yocto-mirrors/github/go-stack/stack","clone_url":"https://git.codelinaro.org/clo/yocto-mirrors/github/go-stack/stack.git","description":null}
{"name":"lc/external/github.com/dart-lang/markdown","clone_url":"https://git.codelinaro.org/clo/lc/external/github.com/dart-lang/markdown.git","description":null}
{"name":"yocto-mirrors/github/hpcloud/tail","clone_url":"https://git.codelinaro.org/clo/yocto-mirrors/github/hpcloud/tail.git","description":null}
{"name":"qsdk/pulseaudio","clone_url":"https://git.codelinaro.org/clo/qsdk/pulseaudio.git","description":null}
{"name":"femto5g/platform/external/Open-AVB","clone_url":"https://git.codelinaro.org/clo/femto5g/platform/external/Open-AVB.git","description":null}
{"name":"la/platform/vendor/qcom/monaco_group/codeaurora/dpm","clone_url":"https://git.codelinaro.org/clo/la/platform/vendor/qcom/monaco_group/codeaurora/dpm.git","description":null}
{"name":"le/meta-qti-ros-oss","clone_url":"https://git.codelinaro.org/clo/le/meta-qti-ros-oss.git","description":null}
{"name":"la/platform/external/rust/crates/bzip2","clone_url":"https://git.codelinaro.org/clo/la/platform/external/rust/crates/bzip2.git","description":null}
{"name":"lc/chromium/deps/nasm","clone_url":"https://git.codelinaro.org/clo/lc/chromium/deps/nasm.git","description":null}
{"name":"la/platform/external/bazelbuild-rules_fuzzing","clone_url":"https://git.codelinaro.org/clo/la/platform/external/bazelbuild-rules_fuzzing.git","description":null}
{"name":"lc/chromium/pipa","clone_url":"https://git.codelinaro.org/clo/lc/chromium/pipa.git","description":null}
{"name":"qrdk/libarchive","clone_url":"https://git.codelinaro.org/clo/qrdk/libarchive.git","description":null}
{"name":"la/platform/external/rust/crates/configparser","clone_url":"https://git.codelinaro.org/clo/la/platform/external/rust/crates/configparser.git","description":null}
{"name":"qrdk/config","clone_url":"https://git.codelinaro.org/clo/qrdk/config.git","description":null}
{"name":"la/platform/external/rust/crates/lock_api","clone_url":"https://git.codelinaro.org/clo/la/platform/external/rust/crates/lock_api.git","description":null}
{"name":"la/platform/frameworks/opt/net/ethernet","clone_url":"https://git.codelinaro.org/clo/la/platform/frameworks/opt/net/ethernet.git","description":null}
{"name":"testproject/platform/external/avb","clone_url":"https://git.codelinaro.org/clo/testproject/platform/external/avb.git","description":null}
{"name":"la/platform/prebuilts/module_sdk/StatsD","clone_url":"https://git.codelinaro.org/clo/la/platform/prebuilts/module_sdk/StatsD.git","description":null}
{"name":"la/platform/packages/wallpapers/MusicVisualization","clone_url":"https://git.codelinaro.org/clo/la/platform/packages/wallpapers/MusicVisualization.git","description":null}
{"name":"la/platform/external/rust/crates/crossbeam-epoch","clone_url":"https://git.codelinaro.org/clo/la/platform/external/rust/crates/crossbeam-epoch.git","description":null}
{"name":"la/platform/external/tremor","clone_url":"https://git.codelinaro.org/clo/la/platform/external/tremor.git","description":null}
{"name":"la/toolchain/go","clone_url":"https://git.codelinaro.org/clo/la/toolchain/go.git","description":null}
{"name":"le-au-os/external/yoctoproject.org/poky","clone_url":"https://git.codelinaro.org/clo/le-au-os/external/yoctoproject.org/poky.git","description":null}
{"name":"la/platform/external/unikraft/lib-newlib","clone_url":"https://git.codelinaro.org/clo/la/platform/external/unikraft/lib-newlib.git","description":null}
{"name":"la/platform/external/rust/crates/ciborium","clone_url":"https://git.codelinaro.org/clo/la/platform/external/rust/crates/ciborium.git","description":null}
{"name":"yocto-mirrors/github/codegangsta/cli","clone_url":"https://git.codelinaro.org/clo/yocto-mirrors/github/codegangsta/cli.git","description":null}
{"name":"la/toolchain/cargo-vet","clone_url":"https://git.codelinaro.org/clo/la/toolchain/cargo-vet.git","description":null}
{"name":"lc/infra/testing_support","clone_url":"https://git.codelinaro.org/clo/lc/infra/testing_support.git","description":null}
{"name":"le/external/daniles/weston","clone_url":"https://git.codelinaro.org/clo/le/external/daniles/weston.git","description":null}
{"name":"qsdk/oss/ath11k-bdf","clone_url":"https://git.codelinaro.org/clo/qsdk/oss/ath11k-bdf.git","description":null}
{"name":"la/kernel/google-modules/touch/synaptics_touch","clone_url":"https://git.codelinaro.org/clo/la/kernel/google-modules/touch/synaptics_touch.git","description":null}
{"name":"linux-kernel/gunyah-linux","clone_url":"https://git.codelinaro.org/clo/linux-kernel/gunyah-linux.git","description":null}
{"name":"la/platform/prebuilts/fullsdk/platforms/android-29","clone_url":"https://git.codelinaro.org/clo/la/platform/prebuilts/fullsdk/platforms/android-29.git","description":null}
{"name":"la/platform/external/apache-http","clone_url":"https://git.codelinaro.org/clo/la/platform/external/apache-http.git","description":null}
{"name":"la/platform/vendor/qcom/opensource/harry-pal","clone_url":"https://git.codelinaro.org/clo/la/platform/vendor/qcom/opensource/harry-pal.git","description":null}
{"name":"qrdk/code.rdkcentral.com/rdkb/components/opensource/ccsp/hal","clone_url":"https://git.codelinaro.org/clo/qrdk/code.rdkcentral.com/rdkb/components/opensource/ccsp/hal.git","description":null}
{"name":"testproject/platform/packages/apps/car/Launcher","clone_url":"https://git.codelinaro.org/clo/testproject/platform/packages/apps/car/Launcher.git","description":null}
{"name":"la/platform/external/boost-submodules/polygon","clone_url":"https://git.codelinaro.org/clo/la/platform/external/boost-submodules/polygon.git","description":null}
{"name":"yocto-mirrors/github/hashicorp/go-immutable-radix","clone_url":"https://git.codelinaro.org/clo/yocto-mirrors/github/hashicorp/go-immutable-radix.git","description":null}
{"name":"la/device/freescale/picoimx","clone_url":"https://git.codelinaro.org/clo/la/device/freescale/picoimx.git","description":null}
{"name":"la/platform/packages/apps/TvSettings","clone_url":"https://git.codelinaro.org/clo/la/platform/packages/apps/TvSettings.git","description":null}
{"name":"la/platform/prebuilts/studio/skiaparser","clone_url":"https://git.codelinaro.org/clo/la/platform/prebuilts/studio/skiaparser.git","description":null}
{"name":"la/device/linaro/dragonboard","clone_url":"https://git.codelinaro.org/clo/la/device/linaro/dragonboard.git","description":null}
{"name":"testproject/platform/packages/apps/Browser2","clone_url":"https://git.codelinaro.org/clo/testproject/platform/packages/apps/Browser2.git","description":null}
{"name":"la/external/libnfc-nci","clone_url":"https://git.codelinaro.org/clo/la/external/libnfc-nci.git","description":null}
{"name":"le/external/qtsvg","clone_url":"https://git.codelinaro.org/clo/le/external/qtsvg.git","description":null}
{"name":"la/platform/prebuilts/rust-toolchain/darwin","clone_url":"https://git.codelinaro.org/clo/la/platform/prebuilts/rust-toolchain/darwin.git","description":null}
{"name":"testproject/platform/external/google-fonts/big-shoulders-text","clone_url":"https://git.codelinaro.org/clo/testproject/platform/external/google-fonts/big-shoulders-text.git","description":null}
{"name":"yocto-mirrors/github/ros2-gbp/cyclonedds-release","clone_url":"https://git.codelinaro.org/clo/yocto-mirrors/github/ros2-gbp/cyclonedds-release.git","description":null}
{"name":"le/XNNPACK","clone_url":"https://git.codelinaro.org/clo/le/XNNPACK.git","description":null}
{"name":"qsdk/oss/lklm/qca-mcs","clone_url":"https://git.codelinaro.org/clo/qsdk/oss/lklm/qca-mcs.git","description":null}
{"name":"la/device/qcom/sdm429w/common","clone_url":"https://git.codelinaro.org/clo/la/device/qcom/sdm429w/common.git","description":null}
{"name":"le/qccsdk/oss/cmsis_4","clone_url":"https://git.codelinaro.org/clo/le/qccsdk/oss/cmsis_4.git","description":null}
{"name":"la/platform/packages/modules/vndk","clone_url":"https://git.codelinaro.org/clo/la/platform/packages/modules/vndk.git","description":null}
{"name":"la/platform/external/gturri-aXMLRPC","clone_url":"https://git.codelinaro.org/clo/la/platform/external/gturri-aXMLRPC.git","description":null}
{"name":"qsdk/platform/vendor/qcom-opensource/drone/QOpenHD","clone_url":"https://git.codelinaro.org/clo/qsdk/platform/vendor/qcom-opensource/drone/QOpenHD.git","description":null}
{"name":"filesystems/patches","clone_url":"https://git.codelinaro.org/clo/filesystems/patches.git","description":null}
{"name":"qsdk/qca/feeds/qca-son-mem-debug","clone_url":"https://git.codelinaro.org/clo/qsdk/qca/feeds/qca-son-mem-debug.git","description":null}
{"name":"lc/chromium/src/test/data/reliability","clone_url":"https://git.codelinaro.org/clo/lc/chromium/src/test/data/reliability.git","description":null}
{"name":"testproject/platform/packages/apps/SecureElement","clone_url":"https://git.codelinaro.org/clo/testproject/platform/packages/apps/SecureElement.git","description":null}
{"name":"yocto-mirrors/github/google/fscryptctl","clone_url":"https://git.codelinaro.org/clo/yocto-mirrors/github/google/fscryptctl.git","description":null}
{"name":"qsdk/oss/system/feeds/control-app","clone_url":"https://git.codelinaro.org/clo/qsdk/oss/system/feeds/control-app.git","description":null}
{"name":"la/platform/vendor/qcom/msm7627_surf","clone_url":"https://git.codelinaro.org/clo/la/platform/vendor/qcom/msm7627_surf.git","description":null}
{"name":"lc/android_tools","clone_url":"https://git.codelinaro.org/clo/lc/android_tools.git","description":null}
{"name":"testproject/platform/prebuilts/tools","clone_url":"https://git.codelinaro.org/clo/testproject/platform/prebuilts/tools.git","description":null}
{"name":"la/platform/external/rust/crates/textwrap","clone_url":"https://git.codelinaro.org/clo/la/platform/external/rust/crates/textwrap.git","description":null}
{"name":"la/platform/vendor/qcom/mpq8092","clone_url":"https://git.codelinaro.org/clo/la/platform/vendor/qcom/mpq8092.git","description":null}
{"name":"lc/aosp/platform/frameworks/proto_logging","clone_url":"https://git.codelinaro.org/clo/lc/aosp/platform/frameworks/proto_logging.git","description":null}
{"name":"yocto-mirrors/poky","clone_url":"https://git.codelinaro.org/clo/yocto-mirrors/poky.git","description":null}
{"name":"la/platform/vendor/htc/common-open","clone_url":"https://git.codelinaro.org/clo/la/platform/vendor/htc/common-open.git","description":null}
{"name":"le/meta-qti-eap","clone_url":"https://git.codelinaro.org/clo/le/meta-qti-eap.git","description":null}
{"name":"la/platform/external/ot-br-posix","clone_url":"https://git.codelinaro.org/clo/la/platform/external/ot-br-posix.git","description":null}
{"name":"testproject/platform/external/ant-glob","clone_url":"https://git.codelinaro.org/clo/testproject/platform/external/ant-glob.git","description":null}
{"name":"la/platform/external/rust/crates/libfuzzer-sys","clone_url":"https://git.codelinaro.org/clo/la/platform/external/rust/crates/libfuzzer-sys.git","description":null}
{"name":"la/platform/packages/apps/FastPowerOn","clone_url":"https://git.codelinaro.org/clo/la/platform/packages/apps/FastPowerOn.git","description":null}
{"name":"la/platform/external/setupcompat","clone_url":"https://git.codelinaro.org/clo/la/platform/external/setupcompat.git","description":null}
{"name":"le/platform/external/turtlebot4_tutorials","clone_url":"https://git.codelinaro.org/clo/le/platform/external/turtlebot4_tutorials.git","description":null}
{"name":"testproject/platform/prebuilts/gcc/linux-x86/x86/x86_64-linux-android-4.9","clone_url":"https://git.codelinaro.org/clo/testproject/platform/prebuilts/gcc/linux-x86/x86/x86_64-linux-android-4.9.git","description":null}
{"name":"yocto-mirrors/github/felixge/fgprof","clone_url":"https://git.codelinaro.org/clo/yocto-mirrors/github/felixge/fgprof.git","description":null}
{"name":"la/platform/packages/wallpapers/Galaxy4","clone_url":"https://git.codelinaro.org/clo/la/platform/packages/wallpapers/Galaxy4.git","description":null}
{"name":"la/platform/vendor/qcom/opensource/audio-kernel-ar","clone_url":"https://git.codelinaro.org/clo/la/platform/vendor/qcom/opensource/audio-kernel-ar.git","description":null}
{"name":"femto5g/oss/lklm/shortcut-fe","clone_url":"https://git.codelinaro.org/clo/femto5g/oss/lklm/shortcut-fe.git","description":null}
{"name":"yocto-mirrors/github/xrash/smetrics","clone_url":"https://git.codelinaro.org/clo/yocto-mirrors/github/xrash/smetrics.git","description":null}
{"name":"la/platform/external/glide_4.16","clone_url":"https://git.codelinaro.org/clo/la/platform/external/glide_4.16.git","description":null}
{"name":"le/platform/external/tinyalsa","clone_url":"https://git.codelinaro.org/clo/le/platform/external/tinyalsa.git","description":null}
{"name":"la/platform/external/rust/crates/foreign-types","clone_url":"https://git.codelinaro.org/clo/la/platform/external/rust/crates/foreign-types.git","description":null}
{"name":"le/openembedded/meta-linaro","clone_url":"https://git.codelinaro.org/clo/le/openembedded/meta-linaro.git","description":null}
{"name":"la/platform/external/go-creachadair-stringset","clone_url":"https://git.codelinaro.org/clo/la/platform/external/go-creachadair-stringset.git","description":null}
{"name":"la/platform/external/ims","clone_url":"https://git.codelinaro.org/clo/la/platform/external/ims.git","description":null}
{"name":"qsdk/oss/feeds/trex/drivers","clone_url":"https://git.codelinaro.org/clo/qsdk/oss/feeds/trex/drivers.git","description":null}
{"name":"yocto-mirrors/github/ros2-gbp/octomap-release","clone_url":"https://git.codelinaro.org/clo/yocto-mirrors/github/ros2-gbp/octomap-release.git","description":null}
{"name":"la/platform/packages/modules/bootprebuilt/5.10/arm64","clone_url":"https://git.codelinaro.org/clo/la/platform/packages/modules/bootprebuilt/5.10/arm64.git","description":null}
{"name":"le/owrt/feeds/feed-prplmesh","clone_url":"https://git.codelinaro.org/clo/le/owrt/feeds/feed-prplmesh.git","description":null}
{"name":"la/device/google/wahoo","clone_url":"https://git.codelinaro.org/clo/la/device/google/wahoo.git","description":null}
{"name":"le/external/node","clone_url":"https://git.codelinaro.org/clo/le/external/node.git","description":null}
{"name":"la/platform/prebuilts/gcc/linux-x86/mips/mips64el-linux-android-4.9","clone_url":"https://git.codelinaro.org/clo/la/platform/prebuilts/gcc/linux-x86/mips/mips64el-linux-android-4.9.git","description":null}
{"name":"la/platform/external/rust/crates/futures-channel","clone_url":"https://git.codelinaro.org/clo/la/platform/external/rust/crates/futures-channel.git","description":null}
{"name":"le/vendor/qcom/opensource/eavb","clone_url":"https://git.codelinaro.org/clo/le/vendor/qcom/opensource/eavb.git","description":null}
{"name":"external-wlan/prima","clone_url":"https://git.codelinaro.org/clo/external-wlan/prima.git","description":null}
{"name":"la/kernel/prebuilts/common-modules/virtual-device/4.19/arm64","clone_url":"https://git.codelinaro.org/clo/la/kernel/prebuilts/common-modules/virtual-device/4.19/arm64.git","description":null}
{"name":"qsdk/meta-qti-qal","clone_url":"https://git.codelinaro.org/clo/qsdk/meta-qti-qal.git","description":null}
{"name":"rdkb/mobile-broadband/libqmi","clone_url":"https://git.codelinaro.org/clo/rdkb/mobile-broadband/libqmi.git","description":null}
{"name":"la/platform/external/dng_sdk","clone_url":"https://git.codelinaro.org/clo/la/platform/external/dng_sdk.git","description":null}
{"name":"le/platform/vendor/qcom-opensource/vhost-user-lib","clone_url":"https://git.codelinaro.org/clo/le/platform/vendor/qcom-opensource/vhost-user-lib.git","description":null}
{"name":"la/platform/external/boost-submodules/endian","clone_url":"https://git.codelinaro.org/clo/la/platform/external/boost-submodules/endian.git","description":null}
{"name":"la/platform/external/rust/crates/equivalent","clone_url":"https://git.codelinaro.org/clo/la/platform/external/rust/crates/equivalent.git","description":null}
{"name":"la/platform/external/threetenbp","clone_url":"https://git.codelinaro.org/clo/la/platform/external/threetenbp.git","description":null}
{"name":"la/platform/external/libmnl","clone_url":"https://git.codelinaro.org/clo/la/platform/external/libmnl.git","description":null}
{"name":"qsdk/system/owrt-qti-ipq-ezmesh","clone_url":"https://git.codelinaro.org/clo/qsdk/system/owrt-qti-ipq-ezmesh.git","description":null}
{"name":"yocto-mirrors/github/ros2-gbp/common_interfaces-release","clone_url":"https://git.codelinaro.org/clo/yocto-mirrors/github/ros2-gbp/common_interfaces-release.git","description":null}
{"name":"yocto-mirrors/github/osrf/negotiated","clone_url":"https://git.codelinaro.org/clo/yocto-mirrors/github/osrf/negotiated.git","description":null}
{"name":"la/platform/prebuilts/clang/darwin-x86/sdk/3.5","clone_url":"https://git.codelinaro.org/clo/la/platform/prebuilts/clang/darwin-x86/sdk/3.5.git","description":null}
{"name":"lc/codesearch/infra/infra","clone_url":"https://git.codelinaro.org/clo/lc/codesearch/infra/infra.git","description":null}
