{"name":"la/platform/external/rust/crates/structopt-derive","clone_url":"https://git.codelinaro.org/clo/la/platform/external/rust/crates/structopt-derive.git","description":null}
{"name":"la/platform/external/clspv","clone_url":"https://git.codelinaro.org/clo/la/platform/external/clspv.git","description":null}
{"name":"la/platform/external/google-cloud-go","clone_url":"https://git.codelinaro.org/clo/la/platform/external/google-cloud-go.git","description":null}
{"name":"la/platform/external/argp-standalone","clone_url":"https://git.codelinaro.org/clo/la/platform/external/argp-standalone.git","description":null}
{"name":"la/platform/external/apache-apr","clone_url":"https://git.codelinaro.org/clo/la/platform/external/apache-apr.git","description":null}
{"name":"la/platform/external/nos/host/generic","clone_url":"https://git.codelinaro.org/clo/la/platform/external/nos/host/generic.git","description":null}
{"name":"la/platform/prebuilts/cipd","clone_url":"https://git.codelinaro.org/clo/la/platform/prebuilts/cipd.git","description":null}
{"name":"yocto-mirrors/github/aanand/compose-file","clone_url":"https://git.codelinaro.org/clo/yocto-mirrors/github/aanand/compose-file.git","description":null}
{"name":"la/platform/ndk","clone_url":"https://git.codelinaro.org/clo/la/platform/ndk.git","description":null}
{"name":"la/kernel/x86","clone_url":"https://git.codelinaro.org/clo/la/kernel/x86.git","description":null}
{"name":"le/platform/external/intel-ros/realsense","clone_url":"https://git.codelinaro.org/clo/le/platform/external/intel-ros/realsense.git","description":null}
{"name":"la/platform/external/ltrace","clone_url":"https://git.codelinaro.org/clo/la/platform/external/ltrace.git","description":null}
{"name":"automotive/alsa-lib","clone_url":"https://git.codelinaro.org/clo/automotive/alsa-lib.git","description":null}
{"name":"lf/l10n/compare-locales","clone_url":"https://git.codelinaro.org/clo/lf/l10n/compare-locales.git","description":null}
{"name":"la/platform/external/jemalloc_new","clone_url":"https://git.codelinaro.org/clo/la/platform/external/jemalloc_new.git","description":null}
{"name":"la/platform/external/boost-submodules/type_erasure","clone_url":"https://git.codelinaro.org/clo/la/platform/external/boost-submodules/type_erasure.git","description":null}
{"name":"la/platform/hardware/intel/common/libstagefrighthw","clone_url":"https://git.codelinaro.org/clo/la/platform/hardware/intel/common/libstagefrighthw.git","description":null}
{"name":"femto5g/platform/vendor/qcom-opensource/hsi2s-kernel","clone_url":"https://git.codelinaro.org/clo/femto5g/platform/vendor/qcom-opensource/hsi2s-kernel.git","description":null}
{"name":"la/platform/external/cbor-java","clone_url":"https://git.codelinaro.org/clo/la/platform/external/cbor-java.git","description":null}
{"name":"la/platform/packages/providers/BookmarkProvider","clone_url":"https://git.codelinaro.org/clo/la/platform/packages/providers/BookmarkProvider.git","description":null}
{"name":"le/qcom-device-config","clone_url":"https://git.codelinaro.org/clo/le/qcom-device-config.git","description":null}
{"name":"le/AGL/apps/agl-service-geofence","clone_url":"https://git.codelinaro.org/clo/le/AGL/apps/agl-service-geofence.git","description":null}
{"name":"qcomlt/pkg/adreno-egl","clone_url":"https://git.codelinaro.org/clo/qcomlt/pkg/adreno-egl.git","description":null}
{"name":"la/platform/external/tagsoup","clone_url":"https://git.codelinaro.org/clo/la/platform/external/tagsoup.git","description":null}
{"name":"la/platform/external/usrsctp","clone_url":"https://git.codelinaro.org/clo/la/platform/external/usrsctp.git","description":null}
{"name":"la/accessories/manifest","clone_url":"https://git.codelinaro.org/clo/la/accessories/manifest.git","description":null}
{"name":"testproject/platform/external/cn-cbor","clone_url":"https://git.codelinaro.org/clo/testproject/platform/external/cn-cbor.git","description":null}
{"name":"yocto-mirrors/pd-mapper","clone_url":"https://git.codelinaro.org/clo/yocto-mirrors/pd-mapper.git","description":null}
{"name":"qrdk/rdkcentral/snmp-protocol-agent","clone_url":"https://git.codelinaro.org/clo/qrdk/rdkcentral/snmp-protocol-agent.git","description":null}
{"name":"la/platform/external/golang-pkg-xattr","clone_url":"https://git.codelinaro.org/clo/la/platform/external/golang-pkg-xattr.git","description":null}
{"name":"lc/external/linux-syscall-support/lss","clone_url":"https://git.codelinaro.org/clo/lc/external/linux-syscall-support/lss.git","description":null}
{"name":"testproject/platform/external/volley","clone_url":"https://git.codelinaro.org/clo/testproject/platform/external/volley.git","description":null}
{"name":"la/platform/external/rust/crates/crossbeam-epoch","clone_url":"https://git.codelinaro.org/clo/la/platform/external/rust/crates/crossbeam-epoch.git","description":null}
{"name":"la/platform/prebuilts/gcc/linux-x86/arm/arm-linux-androideabi-4.7","clone_url":"https://git.codelinaro.org/clo/la/platform/prebuilts/gcc/linux-x86/arm/arm-linux-androideabi-4.7.git","description":null}
{"name":"qsdk/oss/system/feeds/swupdate","clone_url":"https://git.codelinaro.org/clo/qsdk/oss/system/feeds/swupdate.git","description":null}
{"name":"le/platform/external/crosvm","clone_url":"https://git.codelinaro.org/clo/le/platform/external/crosvm.git","description":null}
{"name":"le/gnome/gtk-doc-stub","clone_url":"https://git.codelinaro.org/clo/le/gnome/gtk-doc-stub.git","description":null}
{"name":"la/platform/hardware/qcom/sm7150/gps","clone_url":"https://git.codelinaro.org/clo/la/platform/hardware/qcom/sm7150/gps.git","description":null}
{"name":"la/platform/external/ARMmbed/mbedtls","clone_url":"https://git.codelinaro.org/clo/la/platform/external/ARMmbed/mbedtls.git","description":null}
{"name":"la/platform/tools/studio/google/login","clone_url":"https://git.codelinaro.org/clo/la/platform/tools/studio/google/login.git","description":null}
{"name":"le/platform/vendor/qcom-opensource/vhost-user-scmi","clone_url":"https://git.codelinaro.org/clo/le/platform/vendor/qcom-opensource/vhost-user-scmi.git","description":null}
{"name":"la/platform/packages/apps/TvFeedbackConsent","clone_url":"https://git.codelinaro.org/clo/la/platform/packages/apps/TvFeedbackConsent.git","description":null}
{"name":"la/device/qcom/dragonboard","clone_url":"https://git.codelinaro.org/clo/la/device/qcom/dragonboard.git","description":null}
{"name":"la/platform/prebuilts/gcc/linux-x86/x86/i686-android-linux-4.6","clone_url":"https://git.codelinaro.org/clo/la/platform/prebuilts/gcc/linux-x86/x86/i686-android-linux-4.6.git","description":null}
{"name":"rdkb/rdkb/components/opensource/ccsp/MeshAgent","clone_url":"https://git.codelinaro.org/clo/rdkb/rdkb/components/opensource/ccsp/MeshAgent.git","description":null}
{"name":"yocto-mirrors/github/tonistiigi/go-csvvalue","clone_url":"https://git.codelinaro.org/clo/yocto-mirrors/github/tonistiigi/go-csvvalue.git","description":null}
{"name":"la/platform/external/rust/crates/annotate-snippets","clone_url":"https://git.codelinaro.org/clo/la/platform/external/rust/crates/annotate-snippets.git","description":null}
{"name":"la/toolchain/ccache","clone_url":"https://git.codelinaro.org/clo/la/toolchain/ccache.git","description":null}
{"name":"qrdk/cracklib","clone_url":"https://git.codelinaro.org/clo/qrdk/cracklib.git","description":null}
{"name":"la/platform/external/libcupsfilters","clone_url":"https://git.codelinaro.org/clo/la/platform/external/libcupsfilters.git","description":null}
{"name":"la/platform/vendor/opensource/camera-devicetree","clone_url":"https://git.codelinaro.org/clo/la/platform/vendor/opensource/camera-devicetree.git","description":null}
{"name":"qnbrd/patches","clone_url":"https://git.codelinaro.org/clo/qnbrd/patches.git","description":null}
{"name":"la/kernel/linux-2.6","clone_url":"https://git.codelinaro.org/clo/la/kernel/linux-2.6.git","description":null}
{"name":"lf/releases/l10n/ru/gaia","clone_url":"https://git.codelinaro.org/clo/lf/releases/l10n/ru/gaia.git","description":null}
{"name":"la/device/generic/car","clone_url":"https://git.codelinaro.org/clo/la/device/generic/car.git","description":null}
{"name":"la/device/google/bluejay-kernels/6.1","clone_url":"https://git.codelinaro.org/clo/la/device/google/bluejay-kernels/6.1.git","description":null}
{"name":"la/platform/external/antlr","clone_url":"https://git.codelinaro.org/clo/la/platform/external/antlr.git","description":null}
{"name":"la/platform/prebuilts/bazel/linux-x86_64","clone_url":"https://git.codelinaro.org/clo/la/platform/prebuilts/bazel/linux-x86_64.git","description":null}
{"name":"la/device/qcom/sepolicy","clone_url":"https://git.codelinaro.org/clo/la/device/qcom/sepolicy.git","description":null}
{"name":"la/platform/external/googleclient","clone_url":"https://git.codelinaro.org/clo/la/platform/external/googleclient.git","description":null}
{"name":"la/gcdb-user-space","clone_url":"https://git.codelinaro.org/clo/la/gcdb-user-space.git","description":null}
{"name":"la/platform/hardware/google/display/common","clone_url":"https://git.codelinaro.org/clo/la/platform/hardware/google/display/common.git","description":null}
{"name":"dataservices/modem-data-manager","clone_url":"https://git.codelinaro.org/clo/dataservices/modem-data-manager.git","description":null}
{"name":"la/platform/external/hsqldb","clone_url":"https://git.codelinaro.org/clo/la/platform/external/hsqldb.git","description":null}
{"name":"yocto-mirrors/github/miekg/pkcs11","clone_url":"https://git.codelinaro.org/clo/yocto-mirrors/github/miekg/pkcs11.git","description":null}
{"name":"le/owrt/feeds/feed_opensource","clone_url":"https://git.codelinaro.org/clo/le/owrt/feeds/feed_opensource.git","description":null}
{"name":"la/platform/vendor/qcom/opensource/graphics-hgsl","clone_url":"https://git.codelinaro.org/clo/la/platform/vendor/qcom/opensource/graphics-hgsl.git","description":null}
{"name":"la/platform/packages/modules/Virtualization","clone_url":"https://git.codelinaro.org/clo/la/platform/packages/modules/Virtualization.git","description":null}
{"name":"la/platform/vendor/qcom-opensource/fm","clone_url":"https://git.codelinaro.org/clo/la/platform/vendor/qcom-opensource/fm.git","description":null}
{"name":"la/platform/external/rust/crates/uniffi_checksum_derive","clone_url":"https://git.codelinaro.org/clo/la/platform/external/rust/crates/uniffi_checksum_derive.git","description":null}
{"name":"femto5g/platform/vendor/qcom-opensource/location","clone_url":"https://git.codelinaro.org/clo/femto5g/platform/vendor/qcom-opensource/location.git","description":null}
{"name":"la/platform/external/rust/crates/plotters-svg","clone_url":"https://git.codelinaro.org/clo/la/platform/external/rust/crates/plotters-svg.git","description":null}
{"name":"le/oe/build","clone_url":"https://git.codelinaro.org/clo/le/oe/build.git","description":null}
{"name":"qrdk/smcroute","clone_url":"https://git.codelinaro.org/clo/qrdk/smcroute.git","description":null}
{"name":"la/toolchain/openmp_llvm","clone_url":"https://git.codelinaro.org/clo/la/toolchain/openmp_llvm.git","description":null}
{"name":"le/coqos/linux-kernel-drivers/bootloader-reboot-driver-linux","clone_url":"https://git.codelinaro.org/clo/le/coqos/linux-kernel-drivers/bootloader-reboot-driver-linux.git","description":null}
{"name":"la/platform/external/rust/crates/pin-project-internal","clone_url":"https://git.codelinaro.org/clo/la/platform/external/rust/crates/pin-project-internal.git","description":null}
{"name":"la/platform/external/chromium_org/third_party/libphonenumber/src/resources","clone_url":"https://git.codelinaro.org/clo/la/platform/external/chromium_org/third_party/libphonenumber/src/resources.git","description":null}
{"name":"la/platform/hardware/qcom/neuralnetworks/hvxservice","clone_url":"https://git.codelinaro.org/clo/la/platform/hardware/qcom/neuralnetworks/hvxservice.git","description":null}
{"name":"qsdk/oss/system/feeds/bluetooth","clone_url":"https://git.codelinaro.org/clo/qsdk/oss/system/feeds/bluetooth.git","description":null}
{"name":"qrdk/pkg-config","clone_url":"https://git.codelinaro.org/clo/qrdk/pkg-config.git","description":null}
{"name":"testproject/platform/system/libhidl","clone_url":"https://git.codelinaro.org/clo/testproject/platform/system/libhidl.git","description":null}
{"name":"rdkb/rdkb/components/generic/startParodus","clone_url":"https://git.codelinaro.org/clo/rdkb/rdkb/components/generic/startParodus.git","description":null}
{"name":"sba-patches/wil6210_patches","clone_url":"https://git.codelinaro.org/clo/sba-patches/wil6210_patches.git","description":null}
{"name":"la/platform/external/rust/crates/webpki","clone_url":"https://git.codelinaro.org/clo/la/platform/external/rust/crates/webpki.git","description":null}
{"name":"yocto-mirrors/github/linux-msm/qrtr","clone_url":"https://git.codelinaro.org/clo/yocto-mirrors/github/linux-msm/qrtr.git","description":null}
{"name":"la/kernel/google-modules/wlan/bcmdhd/bcm43752","clone_url":"https://git.codelinaro.org/clo/la/kernel/google-modules/wlan/bcmdhd/bcm43752.git","description":null}
{"name":"la/platform/vendor/qcom-opensource/kernel/kernel-tests","clone_url":"https://git.codelinaro.org/clo/la/platform/vendor/qcom-opensource/kernel/kernel-tests.git","description":null}
{"name":"la/platform/prebuilts/deqp","clone_url":"https://git.codelinaro.org/clo/la/platform/prebuilts/deqp.git","description":null}
{"name":"yocto-mirrors/github/khronosgroup/glslang","clone_url":"https://git.codelinaro.org/clo/yocto-mirrors/github/khronosgroup/glslang.git","description":null}
{"name":"le/owrt/feeds/feed_debug","clone_url":"https://git.codelinaro.org/clo/le/owrt/feeds/feed_debug.git","description":null}
{"name":"la/platform/external/GhostAWT","clone_url":"https://git.codelinaro.org/clo/la/platform/external/GhostAWT.git","description":null}
{"name":"la/platform/external/rust/crates/regex-automata","clone_url":"https://git.codelinaro.org/clo/la/platform/external/rust/crates/regex-automata.git","description":null}
{"name":"la/platform/tools/adt/eclipse","clone_url":"https://git.codelinaro.org/clo/la/platform/tools/adt/eclipse.git","description":null}
{"name":"le/sdkrobotics/ros/manifest","clone_url":"https://git.codelinaro.org/clo/le/sdkrobotics/ros/manifest.git","description":null}
{"name":"qsdk/oss/system/feeds/wlan-ath","clone_url":"https://git.codelinaro.org/clo/qsdk/oss/system/feeds/wlan-ath.git","description":null}
{"name":"la/platform/system/vold","clone_url":"https://git.codelinaro.org/clo/la/platform/system/vold.git","description":null}
{"name":"la/platform/vendor/qcom/lahaina","clone_url":"https://git.codelinaro.org/clo/la/platform/vendor/qcom/lahaina.git","description":null}
{"name":"la/platform/frameworks/opt/mailcommon","clone_url":"https://git.codelinaro.org/clo/la/platform/frameworks/opt/mailcommon.git","description":null}
{"name":"yocto-mirrors/github/sparkleholic/ltrace","clone_url":"https://git.codelinaro.org/clo/yocto-mirrors/github/sparkleholic/ltrace.git","description":null}
{"name":"la/platform/external/boost-submodules/compute","clone_url":"https://git.codelinaro.org/clo/la/platform/external/boost-submodules/compute.git","description":null}
{"name":"yocto-mirrors/yocto-kernel-tools","clone_url":"https://git.codelinaro.org/clo/yocto-mirrors/yocto-kernel-tools.git","description":null}
{"name":"le/mobile-broadband/libqrtr-glib","clone_url":"https://git.codelinaro.org/clo/le/mobile-broadband/libqrtr-glib.git","description":null}
{"name":"yocto-mirrors/github/kr/text","clone_url":"https://git.codelinaro.org/clo/yocto-mirrors/github/kr/text.git","description":null}
{"name":"testproject/platform/packages/modules/ArtPrebuilt","clone_url":"https://git.codelinaro.org/clo/testproject/platform/packages/modules/ArtPrebuilt.git","description":null}
{"name":"lc/chromiumos/third_party/ltp","clone_url":"https://git.codelinaro.org/clo/lc/chromiumos/third_party/ltp.git","description":null}
{"name":"la/platform/external/rust/crates/libfuzzer-sys","clone_url":"https://git.codelinaro.org/clo/la/platform/external/rust/crates/libfuzzer-sys.git","description":null}
{"name":"la/platform/external/libpalmrejection","clone_url":"https://git.codelinaro.org/clo/la/platform/external/libpalmrejection.git","description":null}
{"name":"la/platform/external/mesa3d","clone_url":"https://git.codelinaro.org/clo/la/platform/external/mesa3d.git","description":null}
{"name":"filesystems/fs/external/e2fsprogs","clone_url":"https://git.codelinaro.org/clo/filesystems/fs/external/e2fsprogs.git","description":null}
{"name":"la/trusty/external/qemu-meson","clone_url":"https://git.codelinaro.org/clo/la/trusty/external/qemu-meson.git","description":null}
{"name":"la/platform/vendor/qcom/msm7201a_ffa","clone_url":"https://git.codelinaro.org/clo/la/platform/vendor/qcom/msm7201a_ffa.git","description":null}
{"name":"filesystems/fs/external/f2fs-tools","clone_url":"https://git.codelinaro.org/clo/filesystems/fs/external/f2fs-tools.git","description":null}
{"name":"la/platform/prebuilts/swig/linux-x86","clone_url":"https://git.codelinaro.org/clo/la/platform/prebuilts/swig/linux-x86.git","description":null}
{"name":"la/platform/external/rappor","clone_url":"https://git.codelinaro.org/clo/la/platform/external/rappor.git","description":null}
{"name":"lf/releases/l10n/el/gaia","clone_url":"https://git.codelinaro.org/clo/lf/releases/l10n/el/gaia.git","description":null}
{"name":"le/qirp-oss","clone_url":"https://git.codelinaro.org/clo/le/qirp-oss.git","description":null}
{"name":"testproject/platform/art","clone_url":"https://git.codelinaro.org/clo/testproject/platform/art.git","description":null}
{"name":"la/platform/external/x264","clone_url":"https://git.codelinaro.org/clo/la/platform/external/x264.git","description":null}
{"name":"le/owrt/feeds/feed-prpl","clone_url":"https://git.codelinaro.org/clo/le/owrt/feeds/feed-prpl.git","description":null}
{"name":"la/platform/external/apache-commons-io","clone_url":"https://git.codelinaro.org/clo/la/platform/external/apache-commons-io.git","description":null}
{"name":"la/kernel/devices/google/shusky","clone_url":"https://git.codelinaro.org/clo/la/kernel/devices/google/shusky.git","description":null}
{"name":"testproject/platform/external/mtpd","clone_url":"https://git.codelinaro.org/clo/testproject/platform/external/mtpd.git","description":null}
{"name":"la/platform/external/valgrind","clone_url":"https://git.codelinaro.org/clo/la/platform/external/valgrind.git","description":null}
{"name":"le-au-os/platform/vendor/qcom-opensource/vnw-eth-sw-kernel","clone_url":"https://git.codelinaro.org/clo/le-au-os/platform/vendor/qcom-opensource/vnw-eth-sw-kernel.git","description":null}
{"name":"testproject/platform/hardware/nxp/nfc","clone_url":"https://git.codelinaro.org/clo/testproject/platform/hardware/nxp/nfc.git","description":null}
{"name":"ype/external/github.com/meta-openwrt","clone_url":"https://git.codelinaro.org/clo/ype/external/github.com/meta-openwrt.git","description":null}
{"name":"la/platform/vendor/opensource/mmrm-devicetree","clone_url":"https://git.codelinaro.org/clo/la/platform/vendor/opensource/mmrm-devicetree.git","description":null}
{"name":"ype/meta-qcom-distro","clone_url":"https://git.codelinaro.org/clo/ype/meta-qcom-distro.git","description":null}
{"name":"qsdk/oss/system/feeds/nss-host","clone_url":"https://git.codelinaro.org/clo/qsdk/oss/system/feeds/nss-host.git","description":null}
{"name":"yocto-mirrors/github/mgutz/ansi","clone_url":"https://git.codelinaro.org/clo/yocto-mirrors/github/mgutz/ansi.git","description":null}
{"name":"la/platform/packages/experimental","clone_url":"https://git.codelinaro.org/clo/la/platform/packages/experimental.git","description":null}
{"name":"lc/chromiumos/platform/modem-utilities","clone_url":"https://git.codelinaro.org/clo/lc/chromiumos/platform/modem-utilities.git","description":null}
{"name":"la/platform/external/rust/crates/addr2line","clone_url":"https://git.codelinaro.org/clo/la/platform/external/rust/crates/addr2line.git","description":null}
{"name":"la/platform/external/unikraft/lib-newlib","clone_url":"https://git.codelinaro.org/clo/la/platform/external/unikraft/lib-newlib.git","description":null}
{"name":"la/platform/prebuilts/module_sdk/IPsec","clone_url":"https://git.codelinaro.org/clo/la/platform/prebuilts/module_sdk/IPsec.git","description":null}
{"name":"la/platform/external/OpenCSD","clone_url":"https://git.codelinaro.org/clo/la/platform/external/OpenCSD.git","description":null}
{"name":"yocto-mirrors/github/kisielk/gotool","clone_url":"https://git.codelinaro.org/clo/yocto-mirrors/github/kisielk/gotool.git","description":null}
{"name":"la/platform/system/libvintf","clone_url":"https://git.codelinaro.org/clo/la/platform/system/libvintf.git","description":null}
{"name":"la/platform/external/bazelbuild-platforms","clone_url":"https://git.codelinaro.org/clo/la/platform/external/bazelbuild-platforms.git","description":null}
{"name":"qrdk/avro","clone_url":"https://git.codelinaro.org/clo/qrdk/avro.git","description":null}
{"name":"la/platform/external/jsoup-1p-stubs","clone_url":"https://git.codelinaro.org/clo/la/platform/external/jsoup-1p-stubs.git","description":null}
{"name":"rdkb/rdk/components/generic/WebconfigFramework","clone_url":"https://git.codelinaro.org/clo/rdkb/rdk/components/generic/WebconfigFramework.git","description":null}
{"name":"yocto-mirrors/github/aws/aws-sdk-go-v2","clone_url":"https://git.codelinaro.org/clo/yocto-mirrors/github/aws/aws-sdk-go-v2.git","description":null}
{"name":"qsdk/trace-cmd","clone_url":"https://git.codelinaro.org/clo/qsdk/trace-cmd.git","description":null}
{"name":"testproject/platform/external/python/google-api-python-client","clone_url":"https://git.codelinaro.org/clo/testproject/platform/external/python/google-api-python-client.git","description":null}
{"name":"qrdk/dibbler","clone_url":"https://git.codelinaro.org/clo/qrdk/dibbler.git","description":null}
{"name":"qsdk/oss/system/openwrt/feeds/qca-wifi","clone_url":"https://git.codelinaro.org/clo/qsdk/oss/system/openwrt/feeds/qca-wifi.git","description":null}
{"name":"la/platform/external/objenesis","clone_url":"https://git.codelinaro.org/clo/la/platform/external/objenesis.git","description":null}
{"name":"yocto-mirrors/github/intel/goresctrl","clone_url":"https://git.codelinaro.org/clo/yocto-mirrors/github/intel/goresctrl.git","description":null}
{"name":"la/platform/external/messageformat","clone_url":"https://git.codelinaro.org/clo/la/platform/external/messageformat.git","description":null}
{"name":"lc/chromium/tools/third_party/xvfb","clone_url":"https://git.codelinaro.org/clo/lc/chromium/tools/third_party/xvfb.git","description":null}
{"name":"la/platform/test/framework","clone_url":"https://git.codelinaro.org/clo/la/platform/test/framework.git","description":null}
{"name":"qsdk/oss/boot/uboot-ipq-files","clone_url":"https://git.codelinaro.org/clo/qsdk/oss/boot/uboot-ipq-files.git","description":null}
{"name":"la/platform/external/rust/autocxx","clone_url":"https://git.codelinaro.org/clo/la/platform/external/rust/autocxx.git","description":null}
{"name":"testproject/platform/external/cbor-java","clone_url":"https://git.codelinaro.org/clo/testproject/platform/external/cbor-java.git","description":null}
{"name":"la/kernel/google-modules/trusty","clone_url":"https://git.codelinaro.org/clo/la/kernel/google-modules/trusty.git","description":null}
{"name":"la/platform/build/bazel_common_rules","clone_url":"https://git.codelinaro.org/clo/la/platform/build/bazel_common_rules.git","description":null}
{"name":"la/platform/vendor/qcom/opensource/spu-kernel","clone_url":"https://git.codelinaro.org/clo/la/platform/vendor/qcom/opensource/spu-kernel.git","description":null}
{"name":"lc/chromiumos/platform/webplot","clone_url":"https://git.codelinaro.org/clo/lc/chromiumos/platform/webplot.git","description":null}
{"name":"la/platform/external/rust/crates/protobuf","clone_url":"https://git.codelinaro.org/clo/la/platform/external/rust/crates/protobuf.git","description":null}
{"name":"la/platform/prebuilts/checkcolor","clone_url":"https://git.codelinaro.org/clo/la/platform/prebuilts/checkcolor.git","description":null}
{"name":"le/platform/vendor/qcom/opensource/datarmnet-ext","clone_url":"https://git.codelinaro.org/clo/le/platform/vendor/qcom/opensource/datarmnet-ext.git","description":null}
{"name":"testproject/platform/packages/apps/car/LinkViewer","clone_url":"https://git.codelinaro.org/clo/testproject/platform/packages/apps/car/LinkViewer.git","description":null}
{"name":"lc/chromium/android_webview_next","clone_url":"https://git.codelinaro.org/clo/lc/chromium/android_webview_next.git","description":null}
{"name":"la/platform/external/rust/crates/hex","clone_url":"https://git.codelinaro.org/clo/la/platform/external/rust/crates/hex.git","description":null}
{"name":"yocto-mirrors/github/quic/cbsp-boot-utilities","clone_url":"https://git.codelinaro.org/clo/yocto-mirrors/github/quic/cbsp-boot-utilities.git","description":null}
{"name":"testproject/platform/external/google-fonts/big-shoulders-text","clone_url":"https://git.codelinaro.org/clo/testproject/platform/external/google-fonts/big-shoulders-text.git","description":null}
{"name":"qsdk/oss/lklm/shortcut-fe","clone_url":"https://git.codelinaro.org/clo/qsdk/oss/lklm/shortcut-fe.git","description":null}
{"name":"la/platform/vendor/qcom/gen5_gvm_qmaa","clone_url":"https://git.codelinaro.org/clo/la/platform/vendor/qcom/gen5_gvm_qmaa.git","description":null}
{"name":"lc/chromiumos/platform/factory_test_tools","clone_url":"https://git.codelinaro.org/clo/lc/chromiumos/platform/factory_test_tools.git","description":null}
{"name":"la/platform/packages/providers/TelephonyProvider","clone_url":"https://git.codelinaro.org/clo/la/platform/packages/providers/TelephonyProvider.git","description":null}
{"name":"la/platform/external/golang-x-text","clone_url":"https://git.codelinaro.org/clo/la/platform/external/golang-x-text.git","description":null}
{"name":"la/platform/external/rust/crates/uuid","clone_url":"https://git.codelinaro.org/clo/la/platform/external/rust/crates/uuid.git","description":null}
{"name":"la/platform/vendor/nxp/opensource/monaco/hidlimpl","clone_url":"https://git.codelinaro.org/clo/la/platform/vendor/nxp/opensource/monaco/hidlimpl.git","description":null}
{"name":"le/gorilla/websocket","clone_url":"https://git.codelinaro.org/clo/le/gorilla/websocket.git","description":null}
{"name":"le/owrt/targets","clone_url":"https://git.codelinaro.org/clo/le/owrt/targets.git","description":null}
{"name":"la/platform/system/authgraph","clone_url":"https://git.codelinaro.org/clo/la/platform/system/authgraph.git","description":null}
{"name":"la/platform/external/chromium_org/third_party/freetype","clone_url":"https://git.codelinaro.org/clo/la/platform/external/chromium_org/third_party/freetype.git","description":null}
{"name":"lc/external/github.com/llvm-mirror/llvm","clone_url":"https://git.codelinaro.org/clo/lc/external/github.com/llvm-mirror/llvm.git","description":null}
{"name":"la/platform/prebuilts/fullsdk-darwin/build-tools_group/30.0.2","clone_url":"https://git.codelinaro.org/clo/la/platform/prebuilts/fullsdk-darwin/build-tools_group/30.0.2.git","description":null}
{"name":"sba-patches/qdt_openresty_patches","clone_url":"https://git.codelinaro.org/clo/sba-patches/qdt_openresty_patches.git","description":null}
{"name":"la/platform/external/brctl","clone_url":"https://git.codelinaro.org/clo/la/platform/external/brctl.git","description":null}
{"name":"testproject/platform/prebuilts/maven_repo/android","clone_url":"https://git.codelinaro.org/clo/testproject/platform/prebuilts/maven_repo/android.git","description":null}
{"name":"lc/external/github.com/seleniumhq/selenium/py","clone_url":"https://git.codelinaro.org/clo/lc/external/github.com/seleniumhq/selenium/py.git","description":null}
{"name":"la/platform/external/scapy","clone_url":"https://git.codelinaro.org/clo/la/platform/external/scapy.git","description":null}
{"name":"le/platform/vendor/qcom-opensource/ramparser","clone_url":"https://git.codelinaro.org/clo/le/platform/vendor/qcom-opensource/ramparser.git","description":null}
{"name":"la/platform/hardware/qcom/gestures","clone_url":"https://git.codelinaro.org/clo/la/platform/hardware/qcom/gestures.git","description":null}
{"name":"yocto-mirrors/libosinfo","clone_url":"https://git.codelinaro.org/clo/yocto-mirrors/libosinfo.git","description":null}
{"name":"la/device/imagination/creatorci41","clone_url":"https://git.codelinaro.org/clo/la/device/imagination/creatorci41.git","description":null}
{"name":"femto/fsm/rules","clone_url":"https://git.codelinaro.org/clo/femto/fsm/rules.git","description":null}
{"name":"la/platform/external/gentoo/integration","clone_url":"https://git.codelinaro.org/clo/la/platform/external/gentoo/integration.git","description":null}
{"name":"yocto-mirrors/github/selinuxproject/setools","clone_url":"https://git.codelinaro.org/clo/yocto-mirrors/github/selinuxproject/setools.git","description":null}
{"name":"la/platform/vendor/qcom/monaco_go_aon","clone_url":"https://git.codelinaro.org/clo/la/platform/vendor/qcom/monaco_go_aon.git","description":null}
{"name":"la/platform/packages/providers/ImProvider","clone_url":"https://git.codelinaro.org/clo/la/platform/packages/providers/ImProvider.git","description":null}
{"name":"imx-support/meta-imx","clone_url":"https://git.codelinaro.org/clo/imx-support/meta-imx.git","description":null}
{"name":"la/platform/external/boost-submodules/callable_traits","clone_url":"https://git.codelinaro.org/clo/la/platform/external/boost-submodules/callable_traits.git","description":null}
{"name":"la/kernel/ark-5.14","clone_url":"https://git.codelinaro.org/clo/la/kernel/ark-5.14.git","description":null}
{"name":"lc/webm/vpx_codec_comparison","clone_url":"https://git.codelinaro.org/clo/lc/webm/vpx_codec_comparison.git","description":null}
{"name":"la/platform/packages/modules/desktop/Serviceability","clone_url":"https://git.codelinaro.org/clo/la/platform/packages/modules/desktop/Serviceability.git","description":null}
{"name":"le/meta-qti-gfx-kernel","clone_url":"https://git.codelinaro.org/clo/le/meta-qti-gfx-kernel.git","description":null}
{"name":"la/platform/external/noto-fonts","clone_url":"https://git.codelinaro.org/clo/la/platform/external/noto-fonts.git","description":null}
{"name":"qrdk/linenoise","clone_url":"https://git.codelinaro.org/clo/qrdk/linenoise.git","description":null}
{"name":"la/platform/packages/modules/SEPolicy","clone_url":"https://git.codelinaro.org/clo/la/platform/packages/modules/SEPolicy.git","description":null}
{"name":"yocto-mirrors/github/nixos/patchelf","clone_url":"https://git.codelinaro.org/clo/yocto-mirrors/github/nixos/patchelf.git","description":null}
{"name":"testproject/platform/prebuilts/go/linux-x86","clone_url":"https://git.codelinaro.org/clo/testproject/platform/prebuilts/go/linux-x86.git","description":null}
{"name":"la/device/huawei/angler","clone_url":"https://git.codelinaro.org/clo/la/device/huawei/angler.git","description":null}
{"name":"testproject/platform/external/crcalc","clone_url":"https://git.codelinaro.org/clo/testproject/platform/external/crcalc.git","description":null}
{"name":"la/platform/vendor/qcom/msmnileau_gvmq_ext4","clone_url":"https://git.codelinaro.org/clo/la/platform/vendor/qcom/msmnileau_gvmq_ext4.git","description":null}
{"name":"la/platform/external/libnfc-nci","clone_url":"https://git.codelinaro.org/clo/la/platform/external/libnfc-nci.git","description":null}
{"name":"la/trusty/device/desktop","clone_url":"https://git.codelinaro.org/clo/la/trusty/device/desktop.git","description":null}
{"name":"le-au-os/platform/external/eclipse/mosquitto","clone_url":"https://git.codelinaro.org/clo/le-au-os/platform/external/eclipse/mosquitto.git","description":null}
{"name":"la/platform/external/rust/crates/tower","clone_url":"https://git.codelinaro.org/clo/la/platform/external/rust/crates/tower.git","description":null}
{"name":"qsdk/oss/lklm/nss-ppe-uio","clone_url":"https://git.codelinaro.org/clo/qsdk/oss/lklm/nss-ppe-uio.git","description":null}
{"name":"la/platform/external/aes","clone_url":"https://git.codelinaro.org/clo/la/platform/external/aes.git","description":null}
{"name":"lf/ProtoBuf.js","clone_url":"https://git.codelinaro.org/clo/lf/ProtoBuf.js.git","description":null}
{"name":"qsdk/oss/lklm/nss-debug","clone_url":"https://git.codelinaro.org/clo/qsdk/oss/lklm/nss-debug.git","description":null}
{"name":"la/device/qcom/bengal_515","clone_url":"https://git.codelinaro.org/clo/la/device/qcom/bengal_515.git","description":null}
{"name":"yocto-mirrors/github/spf13/cobra","clone_url":"https://git.codelinaro.org/clo/yocto-mirrors/github/spf13/cobra.git","description":null}
{"name":"la/platform/external/libusb","clone_url":"https://git.codelinaro.org/clo/la/platform/external/libusb.git","description":null}
{"name":"yocto-mirrors/lapack","clone_url":"https://git.codelinaro.org/clo/yocto-mirrors/lapack.git","description":null}
{"name":"le/platform/vendor/qcom-opensource/auto-linux-unit-test-app","clone_url":"https://git.codelinaro.org/clo/le/platform/vendor/qcom-opensource/auto-linux-unit-test-app.git","description":null}
{"name":"qrdk/ninja","clone_url":"https://git.codelinaro.org/clo/qrdk/ninja.git","description":null}
{"name":"la/platform/packages/services/DroidfoodAttestationFixer","clone_url":"https://git.codelinaro.org/clo/la/platform/packages/services/DroidfoodAttestationFixer.git","description":null}
{"name":"la/platform/external/sepolicy","clone_url":"https://git.codelinaro.org/clo/la/platform/external/sepolicy.git","description":null}
{"name":"yocto-mirrors/github/ros2-gbp/console_bridge_vendor-release","clone_url":"https://git.codelinaro.org/clo/yocto-mirrors/github/ros2-gbp/console_bridge_vendor-release.git","description":null}
{"name":"la/platform/prebuilts/fullsdk/sources/android-TPS","clone_url":"https://git.codelinaro.org/clo/la/platform/prebuilts/fullsdk/sources/android-TPS.git","description":null}
{"name":"la/platform/tools/metalava","clone_url":"https://git.codelinaro.org/clo/la/platform/tools/metalava.git","description":null}
{"name":"yocto-mirrors/github/dlclark/regexp2","clone_url":"https://git.codelinaro.org/clo/yocto-mirrors/github/dlclark/regexp2.git","description":null}
{"name":"la/platform/external/pixman","clone_url":"https://git.codelinaro.org/clo/la/platform/external/pixman.git","description":null}
{"name":"la/platform/vendor/qcom/qsd8650a_st1x","clone_url":"https://git.codelinaro.org/clo/la/platform/vendor/qcom/qsd8650a_st1x.git","description":null}
{"name":"testproject/platform/frameworks/hardware/interfaces","clone_url":"https://git.codelinaro.org/clo/testproject/platform/frameworks/hardware/interfaces.git","description":null}
{"name":"la/platform/external/freedesktop.org/wayland/wayland","clone_url":"https://git.codelinaro.org/clo/la/platform/external/freedesktop.org/wayland/wayland.git","description":null}
{"name":"la/platform/external/rust/crates/remove_dir_all","clone_url":"https://git.codelinaro.org/clo/la/platform/external/rust/crates/remove_dir_all.git","description":null}
{"name":"la/platform/external/google-fonts/arvo","clone_url":"https://git.codelinaro.org/clo/la/platform/external/google-fonts/arvo.git","description":null}
{"name":"la/platform/prebuilts/manifest-merger","clone_url":"https://git.codelinaro.org/clo/la/platform/prebuilts/manifest-merger.git","description":null}
{"name":"yocto-mirrors/github/xrash/smetrics","clone_url":"https://git.codelinaro.org/clo/yocto-mirrors/github/xrash/smetrics.git","description":null}
{"name":"testproject/platform/external/libavc","clone_url":"https://git.codelinaro.org/clo/testproject/platform/external/libavc.git","description":null}
{"name":"la/kernel/google-modules/gpu","clone_url":"https://git.codelinaro.org/clo/la/kernel/google-modules/gpu.git","description":null}
{"name":"lc/native_client/nacl-bionic","clone_url":"https://git.codelinaro.org/clo/lc/native_client/nacl-bionic.git","description":null}
{"name":"qsdk/oss/lklm/qca-ssdk","clone_url":"https://git.codelinaro.org/clo/qsdk/oss/lklm/qca-ssdk.git","description":null}
{"name":"la/device/generic/mini-emulator-x86","clone_url":"https://git.codelinaro.org/clo/la/device/generic/mini-emulator-x86.git","description":null}
{"name":"qrdk/breakpad","clone_url":"https://git.codelinaro.org/clo/qrdk/breakpad.git","description":null}
{"name":"la/platform/packages/apps/Launcher3","clone_url":"https://git.codelinaro.org/clo/la/platform/packages/apps/Launcher3.git","description":null}
{"name":"yocto-mirrors/github/pub/scm/linux/kernel/git/stable/linux","clone_url":"https://git.codelinaro.org/clo/yocto-mirrors/github/pub/scm/linux/kernel/git/stable/linux.git","description":null}
{"name":"la/platform/external/rust/crates/android_system_properties","clone_url":"https://git.codelinaro.org/clo/la/platform/external/rust/crates/android_system_properties.git","description":null}
{"name":"yocto-mirrors/github/cloudflare/circl","clone_url":"https://git.codelinaro.org/clo/yocto-mirrors/github/cloudflare/circl.git","description":null}
{"name":"la/platform/external/bc","clone_url":"https://git.codelinaro.org/clo/la/platform/external/bc.git","description":null}
{"name":"la/kernel/ark-6","clone_url":"https://git.codelinaro.org/clo/la/kernel/ark-6.git","description":null}
{"name":"la/platform/external/rust/crates/downcast","clone_url":"https://git.codelinaro.org/clo/la/platform/external/rust/crates/downcast.git","description":null}
{"name":"la/All-Users","clone_url":"https://git.codelinaro.org/clo/la/All-Users.git","description":null}
{"name":"le/platform/external/libuv","clone_url":"https://git.codelinaro.org/clo/le/platform/external/libuv.git","description":null}
{"name":"qsdk/libmicroxml","clone_url":"https://git.codelinaro.org/clo/qsdk/libmicroxml.git","description":null}
{"name":"la/platform/hardware/ti/omap4xxx","clone_url":"https://git.codelinaro.org/clo/la/platform/hardware/ti/omap4xxx.git","description":null}
{"name":"la/platform/frameworks/compile/mclinker","clone_url":"https://git.codelinaro.org/clo/la/platform/frameworks/compile/mclinker.git","description":null}
{"name":"femto5g/kernel/msm-5.4","clone_url":"https://git.codelinaro.org/clo/femto5g/kernel/msm-5.4.git","description":null}
{"name":"lc/chromium/src/media_repo","clone_url":"https://git.codelinaro.org/clo/lc/chromium/src/media_repo.git","description":null}
{"name":"le/golang/net","clone_url":"https://git.codelinaro.org/clo/le/golang/net.git","description":null}
{"name":"la/platform/packages/modules/NetworkPermissionConfig","clone_url":"https://git.codelinaro.org/clo/la/platform/packages/modules/NetworkPermissionConfig.git","description":null}
{"name":"la/platform/external/opencv","clone_url":"https://git.codelinaro.org/clo/la/platform/external/opencv.git","description":null}
{"name":"la/platform/external/webrtc_legacy","clone_url":"https://git.codelinaro.org/clo/la/platform/external/webrtc_legacy.git","description":null}
{"name":"yocto-mirrors/debianutils","clone_url":"https://git.codelinaro.org/clo/yocto-mirrors/debianutils.git","description":null}
{"name":"la/platform/packages/apps/ContactsPicker","clone_url":"https://git.codelinaro.org/clo/la/platform/packages/apps/ContactsPicker.git","description":null}
{"name":"la/platform/external/boost-submodules/thread","clone_url":"https://git.codelinaro.org/clo/la/platform/external/boost-submodules/thread.git","description":null}
{"name":"la/platform/external/libprotobuf-mutator","clone_url":"https://git.codelinaro.org/clo/la/platform/external/libprotobuf-mutator.git","description":null}
{"name":"lc/external/github.com/xeipuuv/gojsonschema","clone_url":"https://git.codelinaro.org/clo/lc/external/github.com/xeipuuv/gojsonschema.git","description":null}
{"name":"la/platform/system/testing/gtest_extras","clone_url":"https://git.codelinaro.org/clo/la/platform/system/testing/gtest_extras.git","description":null}
{"name":"testproject/platform/packages/apps/WallpaperPicker","clone_url":"https://git.codelinaro.org/clo/testproject/platform/packages/apps/WallpaperPicker.git","description":null}
{"name":"rdkb/rdkb/components/opensource/ccsp/sysint","clone_url":"https://git.codelinaro.org/clo/rdkb/rdkb/components/opensource/ccsp/sysint.git","description":null}
{"name":"la/platform/external/rust/crates/time-macros-impl","clone_url":"https://git.codelinaro.org/clo/la/platform/external/rust/crates/time-macros-impl.git","description":null}
{"name":"la/platform/external/boost-submodules/iostreams","clone_url":"https://git.codelinaro.org/clo/la/platform/external/boost-submodules/iostreams.git","description":null}
{"name":"external-wlan/tools","clone_url":"https://git.codelinaro.org/clo/external-wlan/tools.git","description":null}
{"name":"la/platform/vendor/qcom/plutonium","clone_url":"https://git.codelinaro.org/clo/la/platform/vendor/qcom/plutonium.git","description":null}
{"name":"kernel-platform-2-0-os/kernel_platform/prebuilts/bazel/linux-x86_64","clone_url":"https://git.codelinaro.org/clo/kernel-platform-2-0-os/kernel_platform/prebuilts/bazel/linux-x86_64.git","description":null}
{"name":"la/external/github.com/quic-qrb-ros/ros2_benchmark","clone_url":"https://git.codelinaro.org/clo/la/external/github.com/quic-qrb-ros/ros2_benchmark.git","description":null}
{"name":"rdkb/rdkb/components/generic/notify_comp","clone_url":"https://git.codelinaro.org/clo/rdkb/rdkb/components/generic/notify_comp.git","description":null}
{"name":"la/kernel/google-modules/edgetpu_group/rio","clone_url":"https://git.codelinaro.org/clo/la/kernel/google-modules/edgetpu_group/rio.git","description":null}
{"name":"la/platform/prebuilts/clang/linux-x86/3.1","clone_url":"https://git.codelinaro.org/clo/la/platform/prebuilts/clang/linux-x86/3.1.git","description":null}
{"name":"le/external/qtscript","clone_url":"https://git.codelinaro.org/clo/le/external/qtscript.git","description":null}
{"name":"yocto-mirrors/github/andersson/qdl","clone_url":"https://git.codelinaro.org/clo/yocto-mirrors/github/andersson/qdl.git","description":null}
{"name":"qsdk/wifi/iw-patches-oss","clone_url":"https://git.codelinaro.org/clo/qsdk/wifi/iw-patches-oss.git","description":null}
{"name":"external-ubicom/ubicom32-android","clone_url":"https://git.codelinaro.org/clo/external-ubicom/ubicom32-android.git","description":null}
{"name":"yocto-mirrors/github/agext/levenshtein","clone_url":"https://git.codelinaro.org/clo/yocto-mirrors/github/agext/levenshtein.git","description":null}
{"name":"la/platform/external/archive-patcher","clone_url":"https://git.codelinaro.org/clo/la/platform/external/archive-patcher.git","description":null}
{"name":"la/platform/vendor/qcom/opensource/datarmnet-ext","clone_url":"https://git.codelinaro.org/clo/la/platform/vendor/qcom/opensource/datarmnet-ext.git","description":null}
{"name":"qcomlt/pkg/linux-board-support-package-dragonboard410c","clone_url":"https://git.codelinaro.org/clo/qcomlt/pkg/linux-board-support-package-dragonboard410c.git","description":null}
{"name":"yocto-mirrors/github/ros2-gbp/pybind11_vendor-release","clone_url":"https://git.codelinaro.org/clo/yocto-mirrors/github/ros2-gbp/pybind11_vendor-release.git","description":null}
{"name":"la/platform/external/rust/crates/darling_core","clone_url":"https://git.codelinaro.org/clo/la/platform/external/rust/crates/darling_core.git","description":null}
{"name":"la/platform/external/python/pexpect","clone_url":"https://git.codelinaro.org/clo/la/platform/external/python/pexpect.git","description":null}
{"name":"testproject/device/qcom/qssi_32go","clone_url":"https://git.codelinaro.org/clo/testproject/device/qcom/qssi_32go.git","description":null}
{"name":"la/kernel_platform/system/tools/mkbootimg","clone_url":"https://git.codelinaro.org/clo/la/kernel_platform/system/tools/mkbootimg.git","description":null}
{"name":"la/platform/external/ImageMagick","clone_url":"https://git.codelinaro.org/clo/la/platform/external/ImageMagick.git","description":null}
{"name":"external-ubicom/ubi32-toolchain","clone_url":"https://git.codelinaro.org/clo/external-ubicom/ubi32-toolchain.git","description":null}
{"name":"la/platform/test/mlts/models","clone_url":"https://git.codelinaro.org/clo/la/platform/test/mlts/models.git","description":null}
{"name":"la/platform/hardware/qcom/audio","clone_url":"https://git.codelinaro.org/clo/la/platform/hardware/qcom/audio.git","description":null}
{"name":"qsdk/oss/lklm/nss-gmac","clone_url":"https://git.codelinaro.org/clo/qsdk/oss/lklm/nss-gmac.git","description":null}
{"name":"la/platform/packages/apps/Launcher","clone_url":"https://git.codelinaro.org/clo/la/platform/packages/apps/Launcher.git","description":null}
{"name":"la/toolchain/llvm-project","clone_url":"https://git.codelinaro.org/clo/la/toolchain/llvm-project.git","description":null}
{"name":"testproject/platform/external/rust/crates/libc","clone_url":"https://git.codelinaro.org/clo/testproject/platform/external/rust/crates/libc.git","description":null}
{"name":"la/external/github.com/quic-qrb-ros/lib_mem_dmabuf","clone_url":"https://git.codelinaro.org/clo/la/external/github.com/quic-qrb-ros/lib_mem_dmabuf.git","description":null}
{"name":"le/ros2-gbp/launch_ros-release","clone_url":"https://git.codelinaro.org/clo/le/ros2-gbp/launch_ros-release.git","description":null}
{"name":"rdkb/rdkb/components/opensource/ccsp/RdkGponManager","clone_url":"https://git.codelinaro.org/clo/rdkb/rdkb/components/opensource/ccsp/RdkGponManager.git","description":null}
{"name":"yocto-mirrors/github/linux-msm/pd-mapper","clone_url":"https://git.codelinaro.org/clo/yocto-mirrors/github/linux-msm/pd-mapper.git","description":null}
{"name":"la/platform/vendor/google_tradefederation/power","clone_url":"https://git.codelinaro.org/clo/la/platform/vendor/google_tradefederation/power.git","description":null}
{"name":"la/platform/vendor/qcom/qcs605_32","clone_url":"https://git.codelinaro.org/clo/la/platform/vendor/qcom/qcs605_32.git","description":null}
{"name":"lc/chromium/deps/xz","clone_url":"https://git.codelinaro.org/clo/lc/chromium/deps/xz.git","description":null}
{"name":"la/vendor/maxim/tfcrypt","clone_url":"https://git.codelinaro.org/clo/la/vendor/maxim/tfcrypt.git","description":null}
{"name":"la/trusty/app/nvram","clone_url":"https://git.codelinaro.org/clo/la/trusty/app/nvram.git","description":null}
{"name":"yocto-mirrors/github/tesseract-ocr/tessdata","clone_url":"https://git.codelinaro.org/clo/yocto-mirrors/github/tesseract-ocr/tessdata.git","description":null}
{"name":"le/meta-qti-automotive","clone_url":"https://git.codelinaro.org/clo/le/meta-qti-automotive.git","description":null}
{"name":"la/platform/external/rust/crates/libbpf-sys","clone_url":"https://git.codelinaro.org/clo/la/platform/external/rust/crates/libbpf-sys.git","description":null}
{"name":"qsdk/platform/vendor/qcom/opensource/audio-le-platform-utils","clone_url":"https://git.codelinaro.org/clo/qsdk/platform/vendor/qcom/opensource/audio-le-platform-utils.git","description":null}
{"name":"le/platform/external/wireshark-fapi-ecpri","clone_url":"https://git.codelinaro.org/clo/le/platform/external/wireshark-fapi-ecpri.git","description":null}
{"name":"la/platform/vendor/qcom-opensource/bluetooth_ext","clone_url":"https://git.codelinaro.org/clo/la/platform/vendor/qcom-opensource/bluetooth_ext.git","description":null}
{"name":"la/platform/vendor/qcom/monaco_group/codeaurora/usb","clone_url":"https://git.codelinaro.org/clo/la/platform/vendor/qcom/monaco_group/codeaurora/usb.git","description":null}
{"name":"testproject/platform/external/sfntly","clone_url":"https://git.codelinaro.org/clo/testproject/platform/external/sfntly.git","description":null}
{"name":"la/platform/external/kotlinpoet","clone_url":"https://git.codelinaro.org/clo/la/platform/external/kotlinpoet.git","description":null}
{"name":"la/platform/external/rust/crates/parking_lot","clone_url":"https://git.codelinaro.org/clo/la/platform/external/rust/crates/parking_lot.git","description":null}
{"name":"qrdk/rdkcentral/rdkb-halif-dhcp","clone_url":"https://git.codelinaro.org/clo/qrdk/rdkcentral/rdkb-halif-dhcp.git","description":null}
{"name":"lc/chromiumos/platform/vboot_reference","clone_url":"https://git.codelinaro.org/clo/lc/chromiumos/platform/vboot_reference.git","description":null}
{"name":"la/device/google/bramble-kernel","clone_url":"https://git.codelinaro.org/clo/la/device/google/bramble-kernel.git","description":null}
{"name":"yocto-mirrors/github/xhit/go-str2duration","clone_url":"https://git.codelinaro.org/clo/yocto-mirrors/github/xhit/go-str2duration.git","description":null}
{"name":"la/platform/external/chromium_org/third_party/angle","clone_url":"https://git.codelinaro.org/clo/la/platform/external/chromium_org/third_party/angle.git","description":null}
{"name":"le/graphics/libgenlock","clone_url":"https://git.codelinaro.org/clo/le/graphics/libgenlock.git","description":null}
{"name":"testproject/platform/external/ethtool","clone_url":"https://git.codelinaro.org/clo/testproject/platform/external/ethtool.git","description":null}
{"name":"la/kernel/msm-modules_group/securemsm","clone_url":"https://git.codelinaro.org/clo/la/kernel/msm-modules_group/securemsm.git","description":null}
{"name":"le/platform/linux/apps/camera-daemon","clone_url":"https://git.codelinaro.org/clo/le/platform/linux/apps/camera-daemon.git","description":null}
{"name":"la/device/qcom/qssi_auto","clone_url":"https://git.codelinaro.org/clo/la/device/qcom/qssi_auto.git","description":null}
{"name":"la/platform/vendor/qcom/msm7627_7x_surf","clone_url":"https://git.codelinaro.org/clo/la/platform/vendor/qcom/msm7627_7x_surf.git","description":null}
{"name":"la/platform/prebuilts/fullsdk/sources/android-31","clone_url":"https://git.codelinaro.org/clo/la/platform/prebuilts/fullsdk/sources/android-31.git","description":null}
{"name":"la/platform/external/gdata","clone_url":"https://git.codelinaro.org/clo/la/platform/external/gdata.git","description":null}
{"name":"la/platform/vendor/qcom/sdm429w_law","clone_url":"https://git.codelinaro.org/clo/la/platform/vendor/qcom/sdm429w_law.git","description":null}
{"name":"yocto-mirrors/github/ros2-gbp/yaml_cpp_vendor-release","clone_url":"https://git.codelinaro.org/clo/yocto-mirrors/github/ros2-gbp/yaml_cpp_vendor-release.git","description":null}
{"name":"la/platform/external/paho.mqtt.cpp","clone_url":"https://git.codelinaro.org/clo/la/platform/external/paho.mqtt.cpp.git","description":null}
{"name":"le/platform/vendor/qcom/opensource/agm","clone_url":"https://git.codelinaro.org/clo/le/platform/vendor/qcom/opensource/agm.git","description":null}
{"name":"yocto-mirrors/github/mattn/go-runewidth","clone_url":"https://git.codelinaro.org/clo/yocto-mirrors/github/mattn/go-runewidth.git","description":null}
{"name":"le/AGL/staging/qtmultimedia-rtlfm-radio-plugin","clone_url":"https://git.codelinaro.org/clo/le/AGL/staging/qtmultimedia-rtlfm-radio-plugin.git","description":null}
{"name":"la/platform/packages/modules/ApiExtensions","clone_url":"https://git.codelinaro.org/clo/la/platform/packages/modules/ApiExtensions.git","description":null}
{"name":"le/andersson/qrtr","clone_url":"https://git.codelinaro.org/clo/le/andersson/qrtr.git","description":null}
{"name":"testproject/platform/system/media","clone_url":"https://git.codelinaro.org/clo/testproject/platform/system/media.git","description":null}
{"name":"testproject/platform/external/guice","clone_url":"https://git.codelinaro.org/clo/testproject/platform/external/guice.git","description":null}
{"name":"la/platform/external/python/uritemplates","clone_url":"https://git.codelinaro.org/clo/la/platform/external/python/uritemplates.git","description":null}
{"name":"femto5g/external/yoctoproject.org/meta-security","clone_url":"https://git.codelinaro.org/clo/femto5g/external/yoctoproject.org/meta-security.git","description":null}
{"name":"la/kernel_platform/external/stardoc","clone_url":"https://git.codelinaro.org/clo/la/kernel_platform/external/stardoc.git","description":null}
{"name":"qsdk/cups","clone_url":"https://git.codelinaro.org/clo/qsdk/cups.git","description":null}
{"name":"testproject/platform/external/google-fonts/arvo","clone_url":"https://git.codelinaro.org/clo/testproject/platform/external/google-fonts/arvo.git","description":null}
{"name":"lc/external/github.com/jmoiron/sqlx","clone_url":"https://git.codelinaro.org/clo/lc/external/github.com/jmoiron/sqlx.git","description":null}
{"name":"la/platform/external/gentoo/overlays/gentoo","clone_url":"https://git.codelinaro.org/clo/la/platform/external/gentoo/overlays/gentoo.git","description":null}
{"name":"la/platform/tools/acloud","clone_url":"https://git.codelinaro.org/clo/la/platform/tools/acloud.git","description":null}
{"name":"qrdk/cpeabs","clone_url":"https://git.codelinaro.org/clo/qrdk/cpeabs.git","description":null}
{"name":"la/platform/external/boost-submodules/coroutine","clone_url":"https://git.codelinaro.org/clo/la/platform/external/boost-submodules/coroutine.git","description":null}
{"name":"yocto-mirrors/meta-virtualization","clone_url":"https://git.codelinaro.org/clo/yocto-mirrors/meta-virtualization.git","description":null}
{"name":"la/platform/external/boost-submodules/boostdep","clone_url":"https://git.codelinaro.org/clo/la/platform/external/boost-submodules/boostdep.git","description":null}
{"name":"la/platform/tools/external/go/src/golang.org/x_group/tools","clone_url":"https://git.codelinaro.org/clo/la/platform/tools/external/go/src/golang.org/x_group/tools.git","description":null}
{"name":"la/platform/external/timezonepicker-support","clone_url":"https://git.codelinaro.org/clo/la/platform/external/timezonepicker-support.git","description":null}
{"name":"la/platform/external/rust/crates/openmls_traits","clone_url":"https://git.codelinaro.org/clo/la/platform/external/rust/crates/openmls_traits.git","description":null}
{"name":"qsdk/oss/prpl-foundation/prplos/feeds/feed-qca","clone_url":"https://git.codelinaro.org/clo/qsdk/oss/prpl-foundation/prplos/feeds/feed-qca.git","description":null}
{"name":"la/tools/plugin-testing","clone_url":"https://git.codelinaro.org/clo/la/tools/plugin-testing.git","description":null}
{"name":"lc/external/github.com/neverware/shim-build","clone_url":"https://git.codelinaro.org/clo/lc/external/github.com/neverware/shim-build.git","description":null}
{"name":"la/platform/external/rust/crates/futures-test","clone_url":"https://git.codelinaro.org/clo/la/platform/external/rust/crates/futures-test.git","description":null}
{"name":"la/platform/external/crashpad","clone_url":"https://git.codelinaro.org/clo/la/platform/external/crashpad.git","description":null}
{"name":"testproject/platform/external/ppp","clone_url":"https://git.codelinaro.org/clo/testproject/platform/external/ppp.git","description":null}
{"name":"le/platform/vendor/qcom-opensource/wlan/cawifi-cmn-dev","clone_url":"https://git.codelinaro.org/clo/le/platform/vendor/qcom-opensource/wlan/cawifi-cmn-dev.git","description":null}
{"name":"la/platform/system/peerd","clone_url":"https://git.codelinaro.org/clo/la/platform/system/peerd.git","description":null}
{"name":"la/platform/external/rust/crates/tikv-jemalloc-sys","clone_url":"https://git.codelinaro.org/clo/la/platform/external/rust/crates/tikv-jemalloc-sys.git","description":null}
{"name":"qsdk/oss/lklm/nss-nsm","clone_url":"https://git.codelinaro.org/clo/qsdk/oss/lklm/nss-nsm.git","description":null}
{"name":"la/platform/external/rust/crates/winapi-util","clone_url":"https://git.codelinaro.org/clo/la/platform/external/rust/crates/winapi-util.git","description":null}
{"name":"la/platform/vendor/qcom/msm7630_1x_surf","clone_url":"https://git.codelinaro.org/clo/la/platform/vendor/qcom/msm7630_1x_surf.git","description":null}
{"name":"la/platform/frameworks/opt/com.google.android.googlelogin","clone_url":"https://git.codelinaro.org/clo/la/platform/frameworks/opt/com.google.android.googlelogin.git","description":null}
{"name":"la/kernel/msm-modules_group/mm","clone_url":"https://git.codelinaro.org/clo/la/kernel/msm-modules_group/mm.git","description":null}
{"name":"la/platform/packages/inputmethods/PinyinIME","clone_url":"https://git.codelinaro.org/clo/la/platform/packages/inputmethods/PinyinIME.git","description":null}
{"name":"la/platform/packages/apps/Stk","clone_url":"https://git.codelinaro.org/clo/la/platform/packages/apps/Stk.git","description":null}
{"name":"la/platform/prebuilts/clang/darwin-x86/3.1","clone_url":"https://git.codelinaro.org/clo/la/platform/prebuilts/clang/darwin-x86/3.1.git","description":null}
{"name":"le/platform/vendor/qcom-opensource/vibrator","clone_url":"https://git.codelinaro.org/clo/le/platform/vendor/qcom-opensource/vibrator.git","description":null}
{"name":"la/device/lge/mako-kernel","clone_url":"https://git.codelinaro.org/clo/la/device/lge/mako-kernel.git","description":null}
{"name":"la/platform/external/rust/crates/rust-stemmers","clone_url":"https://git.codelinaro.org/clo/la/platform/external/rust/crates/rust-stemmers.git","description":null}
{"name":"la/platform/packages/apps/InCallUI","clone_url":"https://git.codelinaro.org/clo/la/platform/packages/apps/InCallUI.git","description":null}
{"name":"la/platform/external/Microsoft-GSL","clone_url":"https://git.codelinaro.org/clo/la/platform/external/Microsoft-GSL.git","description":null}
{"name":"la/device/qcom/qssi_lily","clone_url":"https://git.codelinaro.org/clo/la/device/qcom/qssi_lily.git","description":null}
{"name":"la/platform/packages/modules/Media","clone_url":"https://git.codelinaro.org/clo/la/platform/packages/modules/Media.git","description":null}
{"name":"la/platform/vendor/qcom/tellurium_32","clone_url":"https://git.codelinaro.org/clo/la/platform/vendor/qcom/tellurium_32.git","description":null}
{"name":"lc/chromiumos/libv4lplugins","clone_url":"https://git.codelinaro.org/clo/lc/chromiumos/libv4lplugins.git","description":null}
{"name":"la/platform/vendor/qcom/msmnile","clone_url":"https://git.codelinaro.org/clo/la/platform/vendor/qcom/msmnile.git","description":null}
{"name":"qcomlt/ci/staging/docker-image","clone_url":"https://git.codelinaro.org/clo/qcomlt/ci/staging/docker-image.git","description":null}
{"name":"la/platform/external/v4l-utils","clone_url":"https://git.codelinaro.org/clo/la/platform/external/v4l-utils.git","description":null}
{"name":"le/meta-qti-adk","clone_url":"https://git.codelinaro.org/clo/le/meta-qti-adk.git","description":null}
{"name":"la/platform/external/jazzer-api","clone_url":"https://git.codelinaro.org/clo/la/platform/external/jazzer-api.git","description":null}
{"name":"la/platform/external/libcxxabi","clone_url":"https://git.codelinaro.org/clo/la/platform/external/libcxxabi.git","description":null}
{"name":"lc/chromium/deps/yasm/patched-yasm","clone_url":"https://git.codelinaro.org/clo/lc/chromium/deps/yasm/patched-yasm.git","description":null}
{"name":"qsdk/oss/releases/configs/qsdk","clone_url":"https://git.codelinaro.org/clo/qsdk/oss/releases/configs/qsdk.git","description":null}
{"name":"la/device/ti/beagle-x15","clone_url":"https://git.codelinaro.org/clo/la/device/ti/beagle-x15.git","description":null}
{"name":"la/platform/external/libusb_aah","clone_url":"https://git.codelinaro.org/clo/la/platform/external/libusb_aah.git","description":null}
{"name":"qsdk/boot/u-boot","clone_url":"https://git.codelinaro.org/clo/qsdk/boot/u-boot.git","description":null}
{"name":"la/platform/external/rust/crates/parking_lot_core","clone_url":"https://git.codelinaro.org/clo/la/platform/external/rust/crates/parking_lot_core.git","description":null}
{"name":"la/platform/external/rust/crates/h2","clone_url":"https://git.codelinaro.org/clo/la/platform/external/rust/crates/h2.git","description":null}
{"name":"la/device/qcom/qssi_au_vcu","clone_url":"https://git.codelinaro.org/clo/la/device/qcom/qssi_au_vcu.git","description":null}
{"name":"la/platform/external/arm-neon-tests","clone_url":"https://git.codelinaro.org/clo/la/platform/external/arm-neon-tests.git","description":null}
{"name":"qsdk/qsdk/qca/src/owrt-qti-ipq-open","clone_url":"https://git.codelinaro.org/clo/qsdk/qsdk/qca/src/owrt-qti-ipq-open.git","description":null}
{"name":"la/platform/prebuilts/gcc/linux-x86/x86/i686-linux-android-4.6","clone_url":"https://git.codelinaro.org/clo/la/platform/prebuilts/gcc/linux-x86/x86/i686-linux-android-4.6.git","description":null}
{"name":"la/platform/external/jsoup","clone_url":"https://git.codelinaro.org/clo/la/platform/external/jsoup.git","description":null}
{"name":"la/platform/external/rust/crates/thiserror","clone_url":"https://git.codelinaro.org/clo/la/platform/external/rust/crates/thiserror.git","description":null}
{"name":"lc/external/github.com/google/gemmlowp","clone_url":"https://git.codelinaro.org/clo/lc/external/github.com/google/gemmlowp.git","description":null}
{"name":"k2c-yocto-track1/meta-qcom-hwe","clone_url":"https://git.codelinaro.org/clo/k2c-yocto-track1/meta-qcom-hwe.git","description":null}
{"name":"la/platform/prebuilts/clang/darwin-x86/3.2","clone_url":"https://git.codelinaro.org/clo/la/platform/prebuilts/clang/darwin-x86/3.2.git","description":null}
{"name":"testproject/platform/vendor/qcom-opensource/audio","clone_url":"https://git.codelinaro.org/clo/testproject/platform/vendor/qcom-opensource/audio.git","description":null}
{"name":"la/platform/external/rust/crates/mockall","clone_url":"https://git.codelinaro.org/clo/la/platform/external/rust/crates/mockall.git","description":null}
{"name":"qsdk/bower-angular-mocks","clone_url":"https://git.codelinaro.org/clo/qsdk/bower-angular-mocks.git","description":null}
{"name":"la/toolchain/prebuilts/ndk/r19","clone_url":"https://git.codelinaro.org/clo/la/toolchain/prebuilts/ndk/r19.git","description":null}
{"name":"la/platform/hardware/libhardware","clone_url":"https://git.codelinaro.org/clo/la/platform/hardware/libhardware.git","description":null}
{"name":"qcomlt/pkg/gst-plugins-bad1.0","clone_url":"https://git.codelinaro.org/clo/qcomlt/pkg/gst-plugins-bad1.0.git","description":null}
{"name":"qsdk/oss/system/openwrt/feeds/qca-wifi-10.4","clone_url":"https://git.codelinaro.org/clo/qsdk/oss/system/openwrt/feeds/qca-wifi-10.4.git","description":null}
{"name":"la/external/github.com/quic-qrb-ros/qrb_ros_tensor_process","clone_url":"https://git.codelinaro.org/clo/la/external/github.com/quic-qrb-ros/qrb_ros_tensor_process.git","description":null}
{"name":"yocto-mirrors/github/gofrs/flock","clone_url":"https://git.codelinaro.org/clo/yocto-mirrors/github/gofrs/flock.git","description":null}
{"name":"le/meta-qti-psdk-core","clone_url":"https://git.codelinaro.org/clo/le/meta-qti-psdk-core.git","description":null}
{"name":"testproject/platform/packages/apps/car/Launcher","clone_url":"https://git.codelinaro.org/clo/testproject/platform/packages/apps/car/Launcher.git","description":null}
{"name":"la/platform/packages/apps/DeviceDiagnostics","clone_url":"https://git.codelinaro.org/clo/la/platform/packages/apps/DeviceDiagnostics.git","description":null}
{"name":"le/meta-qti-sepolicy","clone_url":"https://git.codelinaro.org/clo/le/meta-qti-sepolicy.git","description":null}
{"name":"rdkb/patches","clone_url":"https://git.codelinaro.org/clo/rdkb/patches.git","description":null}
{"name":"la/platform/external/rust/crates/serde_yaml","clone_url":"https://git.codelinaro.org/clo/la/platform/external/rust/crates/serde_yaml.git","description":null}
{"name":"la/platform/external/perfetto","clone_url":"https://git.codelinaro.org/clo/la/platform/external/perfetto.git","description":null}
{"name":"la/platform/prebuilts/gcc/linux-x86/x86/i686-android-linux-4.4.3","clone_url":"https://git.codelinaro.org/clo/la/platform/prebuilts/gcc/linux-x86/x86/i686-android-linux-4.4.3.git","description":null}
{"name":"external-ubicom/ubi32-newlib","clone_url":"https://git.codelinaro.org/clo/external-ubicom/ubi32-newlib.git","description":null}
{"name":"yocto-mirrors/docker/cli","clone_url":"https://git.codelinaro.org/clo/yocto-mirrors/docker/cli.git","description":null}
{"name":"le/genivi/lifecycle/node-state-manager","clone_url":"https://git.codelinaro.org/clo/le/genivi/lifecycle/node-state-manager.git","description":null}
{"name":"clo-example/patches","clone_url":"https://git.codelinaro.org/clo/clo-example/patches.git","description":null}
{"name":"yocto-mirrors/github/prometheus/client_golang","clone_url":"https://git.codelinaro.org/clo/yocto-mirrors/github/prometheus/client_golang.git","description":null}
{"name":"le/external/eigen","clone_url":"https://git.codelinaro.org/clo/le/external/eigen.git","description":null}
{"name":"le-au-os/ota/system/extras","clone_url":"https://git.codelinaro.org/clo/le-au-os/ota/system/extras.git","description":null}
{"name":"testproject/platform/external/sonivox","clone_url":"https://git.codelinaro.org/clo/testproject/platform/external/sonivox.git","description":null}
