{"name":"la/platform/prebuilts/fuchsia_sdk","clone_url":"https://git.codelinaro.org/clo/la/platform/prebuilts/fuchsia_sdk.git","description":null}
{"name":"la/device/asus/fugu","clone_url":"https://git.codelinaro.org/clo/la/device/asus/fugu.git","description":null}
{"name":"la/platform/external/ceres-solver","clone_url":"https://git.codelinaro.org/clo/la/platform/external/ceres-solver.git","description":null}
{"name":"la/platform/external/python/typing_extensions","clone_url":"https://git.codelinaro.org/clo/la/platform/external/python/typing_extensions.git","description":null}
{"name":"qcomlt/pkg/96boards-installer","clone_url":"https://git.codelinaro.org/clo/qcomlt/pkg/96boards-installer.git","description":null}
{"name":"la/wayland/weston","clone_url":"https://git.codelinaro.org/clo/la/wayland/weston.git","description":null}
{"name":"la/platform/external/ant-wireless/hidl","clone_url":"https://git.codelinaro.org/clo/la/platform/external/ant-wireless/hidl.git","description":null}
{"name":"la/platform/external/iw","clone_url":"https://git.codelinaro.org/clo/la/platform/external/iw.git","description":null}
{"name":"le/yocto-kernel-tools","clone_url":"https://git.codelinaro.org/clo/le/yocto-kernel-tools.git","description":null}
{"name":"la/device/google/bluejay-kernels/5.10","clone_url":"https://git.codelinaro.org/clo/la/device/google/bluejay-kernels/5.10.git","description":null}
{"name":"la/platform/vendor/qcom-opensource/crosvm-gunyah","clone_url":"https://git.codelinaro.org/clo/la/platform/vendor/qcom-opensource/crosvm-gunyah.git","description":null}
{"name":"la/platform/external/boost-submodules/format","clone_url":"https://git.codelinaro.org/clo/la/platform/external/boost-submodules/format.git","description":null}
{"name":"la/platform/external/safe-iop","clone_url":"https://git.codelinaro.org/clo/la/platform/external/safe-iop.git","description":null}
{"name":"le/platform/vendor/qcom-opensource/wlan/utils/miracast","clone_url":"https://git.codelinaro.org/clo/le/platform/vendor/qcom-opensource/wlan/utils/miracast.git","description":null}
{"name":"la/platform/prebuilts/gcc/linux-x86/host/x86_64-linux-glibc2.17-4.8","clone_url":"https://git.codelinaro.org/clo/la/platform/prebuilts/gcc/linux-x86/host/x86_64-linux-glibc2.17-4.8.git","description":null}
{"name":"la/kernel/google-modules/edgetpu_group/janeiro","clone_url":"https://git.codelinaro.org/clo/la/kernel/google-modules/edgetpu_group/janeiro.git","description":null}
{"name":"lc/external/github.com/flintwork/mccabe","clone_url":"https://git.codelinaro.org/clo/lc/external/github.com/flintwork/mccabe.git","description":null}
{"name":"lc/chromiumos/platform/firmware-utils","clone_url":"https://git.codelinaro.org/clo/lc/chromiumos/platform/firmware-utils.git","description":null}
{"name":"la/platform/external/jetbrains/jdk8u_jfx","clone_url":"https://git.codelinaro.org/clo/la/platform/external/jetbrains/jdk8u_jfx.git","description":null}
{"name":"la/platform/external/python/pyserial","clone_url":"https://git.codelinaro.org/clo/la/platform/external/python/pyserial.git","description":null}
{"name":"la/platform/vendor/qcom/msm8625","clone_url":"https://git.codelinaro.org/clo/la/platform/vendor/qcom/msm8625.git","description":null}
{"name":"le/external/qt/qtscxml","clone_url":"https://git.codelinaro.org/clo/le/external/qt/qtscxml.git","description":null}
{"name":"la/platform/prebuilts/r8","clone_url":"https://git.codelinaro.org/clo/la/platform/prebuilts/r8.git","description":null}
{"name":"la/platform/external/rust/crates/crossbeam-epoch","clone_url":"https://git.codelinaro.org/clo/la/platform/external/rust/crates/crossbeam-epoch.git","description":null}
{"name":"la/platform/prebuilts/jdk/jdk11","clone_url":"https://git.codelinaro.org/clo/la/platform/prebuilts/jdk/jdk11.git","description":null}
{"name":"la/platform/external/boost-submodules/build","clone_url":"https://git.codelinaro.org/clo/la/platform/external/boost-submodules/build.git","description":null}
{"name":"la/platform/vendor/qcom/msm8909w","clone_url":"https://git.codelinaro.org/clo/la/platform/vendor/qcom/msm8909w.git","description":null}
{"name":"qrdk/libsolv","clone_url":"https://git.codelinaro.org/clo/qrdk/libsolv.git","description":null}
{"name":"la/platform/prebuilts/gcc/linux-x86/x86/i686-android-linux-4.6","clone_url":"https://git.codelinaro.org/clo/la/platform/prebuilts/gcc/linux-x86/x86/i686-android-linux-4.6.git","description":null}
{"name":"la/platform/vendor/qcom-opensource/platform-devicetree","clone_url":"https://git.codelinaro.org/clo/la/platform/vendor/qcom-opensource/platform-devicetree.git","description":null}
{"name":"la/platform/external/clang","clone_url":"https://git.codelinaro.org/clo/la/platform/external/clang.git","description":null}
{"name":"la/platform/external/mtpd","clone_url":"https://git.codelinaro.org/clo/la/platform/external/mtpd.git","description":null}
{"name":"yocto-mirrors/github/mattn/go-shellwords","clone_url":"https://git.codelinaro.org/clo/yocto-mirrors/github/mattn/go-shellwords.git","description":null}
{"name":"la/platform/external/google-fonts/carrois-gothic-sc","clone_url":"https://git.codelinaro.org/clo/la/platform/external/google-fonts/carrois-gothic-sc.git","description":null}
{"name":"qrdk/code.rdkcentral.com/rdkb/components/opensource/ccsp/sysint","clone_url":"https://git.codelinaro.org/clo/qrdk/code.rdkcentral.com/rdkb/components/opensource/ccsp/sysint.git","description":null}
{"name":"la/platform/packages/apps/QualcommSoftAP","clone_url":"https://git.codelinaro.org/clo/la/platform/packages/apps/QualcommSoftAP.git","description":null}
{"name":"la/platform/packages/services/Rcs","clone_url":"https://git.codelinaro.org/clo/la/platform/packages/services/Rcs.git","description":null}
{"name":"la/platform/packages/apps/VoiceDialer","clone_url":"https://git.codelinaro.org/clo/la/platform/packages/apps/VoiceDialer.git","description":null}
{"name":"la/platform/external/jsr330","clone_url":"https://git.codelinaro.org/clo/la/platform/external/jsr330.git","description":null}
{"name":"le/platform/external/libusb","clone_url":"https://git.codelinaro.org/clo/le/platform/external/libusb.git","description":null}
{"name":"la/platform/vendor/qcom-opensource/diag","clone_url":"https://git.codelinaro.org/clo/la/platform/vendor/qcom-opensource/diag.git","description":null}
{"name":"la/device/moto/shamu","clone_url":"https://git.codelinaro.org/clo/la/device/moto/shamu.git","description":null}
{"name":"le/genivi/persistence/persistence-administrator","clone_url":"https://git.codelinaro.org/clo/le/genivi/persistence/persistence-administrator.git","description":null}
{"name":"la/platform/external/rust/crates/vmm_vhost","clone_url":"https://git.codelinaro.org/clo/la/platform/external/rust/crates/vmm_vhost.git","description":null}
{"name":"yocto-mirrors/github/prometheus/common","clone_url":"https://git.codelinaro.org/clo/yocto-mirrors/github/prometheus/common.git","description":null}
{"name":"qrdk/nanomsg","clone_url":"https://git.codelinaro.org/clo/qrdk/nanomsg.git","description":null}
{"name":"la/platform/external/lfi/lfi-runtime","clone_url":"https://git.codelinaro.org/clo/la/platform/external/lfi/lfi-runtime.git","description":null}
{"name":"qcomlt/ci/mock","clone_url":"https://git.codelinaro.org/clo/qcomlt/ci/mock.git","description":null}
{"name":"qsdk/oss/lklm/gobinet","clone_url":"https://git.codelinaro.org/clo/qsdk/oss/lklm/gobinet.git","description":null}
{"name":"la/kernel/exynos-modules/config","clone_url":"https://git.codelinaro.org/clo/la/kernel/exynos-modules/config.git","description":null}
{"name":"la/platform/external/boost-submodules/dll","clone_url":"https://git.codelinaro.org/clo/la/platform/external/boost-submodules/dll.git","description":null}
{"name":"le/platform/meta-qcom-x100","clone_url":"https://git.codelinaro.org/clo/le/platform/meta-qcom-x100.git","description":null}
{"name":"la/video-test-app","clone_url":"https://git.codelinaro.org/clo/la/video-test-app.git","description":null}
{"name":"la/Platform-Unrestricted-Projects","clone_url":"https://git.codelinaro.org/clo/la/Platform-Unrestricted-Projects.git","description":null}
{"name":"le/external/nnsuite/meta-neural-network","clone_url":"https://git.codelinaro.org/clo/le/external/nnsuite/meta-neural-network.git","description":null}
{"name":"la/platform/vendor/qcom-opensource/display-frameworks","clone_url":"https://git.codelinaro.org/clo/la/platform/vendor/qcom-opensource/display-frameworks.git","description":null}
{"name":"la/platform/external/rust/crates/openmls","clone_url":"https://git.codelinaro.org/clo/la/platform/external/rust/crates/openmls.git","description":null}
{"name":"yocto-mirrors/github/bitly/go-simplejson","clone_url":"https://git.codelinaro.org/clo/yocto-mirrors/github/bitly/go-simplejson.git","description":null}
{"name":"rdkb/clo/rdkb/rdk/components/generic/breakpad_wrapper","clone_url":"https://git.codelinaro.org/clo/rdkb/clo/rdkb/rdk/components/generic/breakpad_wrapper.git","description":null}
{"name":"lc/aosp/platform/hardware/libhardware","clone_url":"https://git.codelinaro.org/clo/lc/aosp/platform/hardware/libhardware.git","description":null}
{"name":"lc/chromiumos/third_party/coreboot/intel-microcode","clone_url":"https://git.codelinaro.org/clo/lc/chromiumos/third_party/coreboot/intel-microcode.git","description":null}
{"name":"la/kernel_platform/prebuilts/asuite","clone_url":"https://git.codelinaro.org/clo/la/kernel_platform/prebuilts/asuite.git","description":null}
{"name":"dpdk/dpdk-stable","clone_url":"https://git.codelinaro.org/clo/dpdk/dpdk-stable.git","description":null}
{"name":"yocto-mirrors/github/file/file","clone_url":"https://git.codelinaro.org/clo/yocto-mirrors/github/file/file.git","description":null}
{"name":"lc/external/skia_repo","clone_url":"https://git.codelinaro.org/clo/lc/external/skia_repo.git","description":null}
{"name":"la/product/google/common","clone_url":"https://git.codelinaro.org/clo/la/product/google/common.git","description":null}
{"name":"la/toolchain/prebuilts/sysroot/platform/riscv64-linux-android","clone_url":"https://git.codelinaro.org/clo/la/toolchain/prebuilts/sysroot/platform/riscv64-linux-android.git","description":null}
{"name":"le/platform/vendor/qcom/opensource/datarmnet-ext","clone_url":"https://git.codelinaro.org/clo/le/platform/vendor/qcom/opensource/datarmnet-ext.git","description":null}
{"name":"la/device/google/comet-kernels/6.1","clone_url":"https://git.codelinaro.org/clo/la/device/google/comet-kernels/6.1.git","description":null}
{"name":"yocto-mirrors/github/leethomason/tinyxml2","clone_url":"https://git.codelinaro.org/clo/yocto-mirrors/github/leethomason/tinyxml2.git","description":null}
{"name":"le/qccsdk/oss/exhost","clone_url":"https://git.codelinaro.org/clo/le/qccsdk/oss/exhost.git","description":null}
{"name":"la/platform/system/libartpalette","clone_url":"https://git.codelinaro.org/clo/la/platform/system/libartpalette.git","description":null}
{"name":"le/meta-qti-transceiver-driver","clone_url":"https://git.codelinaro.org/clo/le/meta-qti-transceiver-driver.git","description":null}
{"name":"la/platform/external/boost-submodules/sort","clone_url":"https://git.codelinaro.org/clo/la/platform/external/boost-submodules/sort.git","description":null}
{"name":"qsdk/system/owrt-qti-ipq-ezmesh","clone_url":"https://git.codelinaro.org/clo/qsdk/system/owrt-qti-ipq-ezmesh.git","description":null}
{"name":"lc/external/gsutil/src","clone_url":"https://git.codelinaro.org/clo/lc/external/gsutil/src.git","description":null}
{"name":"le/meta-qti-rb-ros","clone_url":"https://git.codelinaro.org/clo/le/meta-qti-rb-ros.git","description":null}
{"name":"lc/external/skia/gyp","clone_url":"https://git.codelinaro.org/clo/lc/external/skia/gyp.git","description":null}
{"name":"la/platform/packages/providers/ApplicationsProvider","clone_url":"https://git.codelinaro.org/clo/la/platform/packages/providers/ApplicationsProvider.git","description":null}
{"name":"le-au-os/platform/vendor/qcom-opensource/dataservices","clone_url":"https://git.codelinaro.org/clo/le-au-os/platform/vendor/qcom-opensource/dataservices.git","description":null}
{"name":"le/platform/external/can-utils","clone_url":"https://git.codelinaro.org/clo/le/platform/external/can-utils.git","description":null}
{"name":"le/external/github/google/farmhash","clone_url":"https://git.codelinaro.org/clo/le/external/github/google/farmhash.git","description":null}
{"name":"la/platform/tools/apksig","clone_url":"https://git.codelinaro.org/clo/la/platform/tools/apksig.git","description":null}
{"name":"la/platform/external/rust/crates/tinyjson","clone_url":"https://git.codelinaro.org/clo/la/platform/external/rust/crates/tinyjson.git","description":null}
{"name":"la/platform/external/vogar","clone_url":"https://git.codelinaro.org/clo/la/platform/external/vogar.git","description":null}
{"name":"la/platform/packages/apps/EyeDropper","clone_url":"https://git.codelinaro.org/clo/la/platform/packages/apps/EyeDropper.git","description":null}
{"name":"qrdk/libarchive","clone_url":"https://git.codelinaro.org/clo/qrdk/libarchive.git","description":null}
{"name":"la/platform/system/software_defined_vehicle/health_monitor","clone_url":"https://git.codelinaro.org/clo/la/platform/system/software_defined_vehicle/health_monitor.git","description":null}
{"name":"caf-patches/patches","clone_url":"https://git.codelinaro.org/clo/caf-patches/patches.git","description":null}
{"name":"ype/external/gstreamer.org/gstreamer/gst-plugins-bad","clone_url":"https://git.codelinaro.org/clo/ype/external/gstreamer.org/gstreamer/gst-plugins-bad.git","description":null}
{"name":"la/platform/packages/providers/CallLogProvider","clone_url":"https://git.codelinaro.org/clo/la/platform/packages/providers/CallLogProvider.git","description":null}
{"name":"rdkb/apache/avro","clone_url":"https://git.codelinaro.org/clo/rdkb/apache/avro.git","description":null}
{"name":"la/platform/external/rust/crates/petgraph","clone_url":"https://git.codelinaro.org/clo/la/platform/external/rust/crates/petgraph.git","description":null}
{"name":"la/techpack/sensors/manifest","clone_url":"https://git.codelinaro.org/clo/la/techpack/sensors/manifest.git","description":null}
{"name":"le/AGL/apps/mixer","clone_url":"https://git.codelinaro.org/clo/le/AGL/apps/mixer.git","description":null}
{"name":"rdkb/rdk/components/generic/lxccpid","clone_url":"https://git.codelinaro.org/clo/rdkb/rdk/components/generic/lxccpid.git","description":null}
{"name":"la/platform/external/rust/crates/ppv-lite86","clone_url":"https://git.codelinaro.org/clo/la/platform/external/rust/crates/ppv-lite86.git","description":null}
{"name":"la/platform/packages/apps/AlarmClock","clone_url":"https://git.codelinaro.org/clo/la/platform/packages/apps/AlarmClock.git","description":null}
{"name":"la/platform/hardware/bsp/kernel/qcom/qcom-msm-v4.9","clone_url":"https://git.codelinaro.org/clo/la/platform/hardware/bsp/kernel/qcom/qcom-msm-v4.9.git","description":null}
{"name":"la/device/qcom/qssi_xrl","clone_url":"https://git.codelinaro.org/clo/la/device/qcom/qssi_xrl.git","description":null}
{"name":"la/platform/external/boost-submodules/date_time","clone_url":"https://git.codelinaro.org/clo/la/platform/external/boost-submodules/date_time.git","description":null}
{"name":"le/OTA/device/qcom/common","clone_url":"https://git.codelinaro.org/clo/le/OTA/device/qcom/common.git","description":null}
{"name":"yocto-mirrors/gitlab/rossburton/python-unittest-automake-output","clone_url":"https://git.codelinaro.org/clo/yocto-mirrors/gitlab/rossburton/python-unittest-automake-output.git","description":null}
{"name":"la/platform/external/pogreb","clone_url":"https://git.codelinaro.org/clo/la/platform/external/pogreb.git","description":null}
{"name":"lc/chromiumos/third_party/linux-firmware","clone_url":"https://git.codelinaro.org/clo/lc/chromiumos/third_party/linux-firmware.git","description":null}
{"name":"la/platform/frameworks/opt/calendar","clone_url":"https://git.codelinaro.org/clo/la/platform/frameworks/opt/calendar.git","description":null}
{"name":"lc/external/github.com/dart-lang/which","clone_url":"https://git.codelinaro.org/clo/lc/external/github.com/dart-lang/which.git","description":null}
{"name":"la/platform/tools/security","clone_url":"https://git.codelinaro.org/clo/la/platform/tools/security.git","description":null}
{"name":"yocto-mirrors/github/qemu/dtc","clone_url":"https://git.codelinaro.org/clo/yocto-mirrors/github/qemu/dtc.git","description":null}
{"name":"qrdk/libssh","clone_url":"https://git.codelinaro.org/clo/qrdk/libssh.git","description":null}
{"name":"la/platform/packages/modules/CellBroadcastService","clone_url":"https://git.codelinaro.org/clo/la/platform/packages/modules/CellBroadcastService.git","description":null}
{"name":"la/platform/prebuilts/module_sdk/Nfc","clone_url":"https://git.codelinaro.org/clo/la/platform/prebuilts/module_sdk/Nfc.git","description":null}
{"name":"le/platform/vendor/qcom-opensource/adk-tools","clone_url":"https://git.codelinaro.org/clo/le/platform/vendor/qcom-opensource/adk-tools.git","description":null}
{"name":"la/platform/external/webkit","clone_url":"https://git.codelinaro.org/clo/la/platform/external/webkit.git","description":null}
{"name":"la/platform/prebuilts/android-emulator","clone_url":"https://git.codelinaro.org/clo/la/platform/prebuilts/android-emulator.git","description":null}
{"name":"la/platform/tools/external/go/src/github.com/go-gl/gl","clone_url":"https://git.codelinaro.org/clo/la/platform/tools/external/go/src/github.com/go-gl/gl.git","description":null}
{"name":"lc/coreboot","clone_url":"https://git.codelinaro.org/clo/lc/coreboot.git","description":null}
{"name":"le/meta-qti-auto-sepolicy","clone_url":"https://git.codelinaro.org/clo/le/meta-qti-auto-sepolicy.git","description":null}
{"name":"la/platform/external/googleapis-go-genproto","clone_url":"https://git.codelinaro.org/clo/la/platform/external/googleapis-go-genproto.git","description":null}
{"name":"la/platform/system/software_defined_vehicle/automotive_services","clone_url":"https://git.codelinaro.org/clo/la/platform/system/software_defined_vehicle/automotive_services.git","description":null}
{"name":"la/platform/vendor/qcom/monaco_group/codeaurora/data-ipa-cfg-mgr","clone_url":"https://git.codelinaro.org/clo/la/platform/vendor/qcom/monaco_group/codeaurora/data-ipa-cfg-mgr.git","description":null}
{"name":"la/platform/external/boost-submodules/describe","clone_url":"https://git.codelinaro.org/clo/la/platform/external/boost-submodules/describe.git","description":null}
{"name":"la/platform/external/bson","clone_url":"https://git.codelinaro.org/clo/la/platform/external/bson.git","description":null}
{"name":"le/AGLExport/genivi-navi-yelp-client","clone_url":"https://git.codelinaro.org/clo/le/AGLExport/genivi-navi-yelp-client.git","description":null}
{"name":"la/platform/hardware/bsp/imagination","clone_url":"https://git.codelinaro.org/clo/la/platform/hardware/bsp/imagination.git","description":null}
{"name":"yocto-mirrors/github/mgutz/ansi","clone_url":"https://git.codelinaro.org/clo/yocto-mirrors/github/mgutz/ansi.git","description":null}
{"name":"la/platform/external/bluetooth/bluez","clone_url":"https://git.codelinaro.org/clo/la/platform/external/bluetooth/bluez.git","description":null}
{"name":"la/device/moto/wingray","clone_url":"https://git.codelinaro.org/clo/la/device/moto/wingray.git","description":null}
{"name":"la/platform/external/spirv-llvm","clone_url":"https://git.codelinaro.org/clo/la/platform/external/spirv-llvm.git","description":null}
{"name":"lc/chromium/tools/perf","clone_url":"https://git.codelinaro.org/clo/lc/chromium/tools/perf.git","description":null}
{"name":"la/kernel/msm-4.14","clone_url":"https://git.codelinaro.org/clo/la/kernel/msm-4.14.git","description":null}
{"name":"la/platform/prebuilts/gcc/darwin-x86/aarch64/aarch64-linux-android-4.8","clone_url":"https://git.codelinaro.org/clo/la/platform/prebuilts/gcc/darwin-x86/aarch64/aarch64-linux-android-4.8.git","description":null}
{"name":"lc/external/github.com/google/gemmlowp","clone_url":"https://git.codelinaro.org/clo/lc/external/github.com/google/gemmlowp.git","description":null}
{"name":"la/platform/external/hafnium","clone_url":"https://git.codelinaro.org/clo/la/platform/external/hafnium.git","description":null}
{"name":"rdkb/rdkb/components/opensource/ccsp/CcspWifiAgent","clone_url":"https://git.codelinaro.org/clo/rdkb/rdkb/components/opensource/ccsp/CcspWifiAgent.git","description":null}
{"name":"la/device/generic/mini-emulator-arm64","clone_url":"https://git.codelinaro.org/clo/la/device/generic/mini-emulator-arm64.git","description":null}
{"name":"iris-video-driver/patches","clone_url":"https://git.codelinaro.org/clo/iris-video-driver/patches.git","description":null}
{"name":"dpdk/patches","clone_url":"https://git.codelinaro.org/clo/dpdk/patches.git","description":null}
{"name":"la/platform/vendor/qcom/neo","clone_url":"https://git.codelinaro.org/clo/la/platform/vendor/qcom/neo.git","description":null}
{"name":"lc/infra/gerrit-plugins/git-numbering-service","clone_url":"https://git.codelinaro.org/clo/lc/infra/gerrit-plugins/git-numbering-service.git","description":null}
{"name":"imx-support/imx-linux-kirkstone","clone_url":"https://git.codelinaro.org/clo/imx-support/imx-linux-kirkstone.git","description":null}
{"name":"la/platform/external/rust/crates/thiserror","clone_url":"https://git.codelinaro.org/clo/la/platform/external/rust/crates/thiserror.git","description":null}
{"name":"la/platform/external/bouncycastle","clone_url":"https://git.codelinaro.org/clo/la/platform/external/bouncycastle.git","description":null}
{"name":"jae-public-test-3/patches","clone_url":"https://git.codelinaro.org/clo/jae-public-test-3/patches.git","description":null}
{"name":"la/platform/vendor/qcom-opensource/tools","clone_url":"https://git.codelinaro.org/clo/la/platform/vendor/qcom-opensource/tools.git","description":null}
{"name":"la/platform/vendor/qcom/gen4_gvm_sdv","clone_url":"https://git.codelinaro.org/clo/la/platform/vendor/qcom/gen4_gvm_sdv.git","description":null}
{"name":"la/platform/vendor/qcom/opensource/github/audioreach/Audioreach-engine","clone_url":"https://git.codelinaro.org/clo/la/platform/vendor/qcom/opensource/github/audioreach/Audioreach-engine.git","description":null}
{"name":"la/platform/external/moltenvk","clone_url":"https://git.codelinaro.org/clo/la/platform/external/moltenvk.git","description":null}
{"name":"la/platform/external/libtruezip","clone_url":"https://git.codelinaro.org/clo/la/platform/external/libtruezip.git","description":null}
{"name":"la/device/samsung_slsi/arndale","clone_url":"https://git.codelinaro.org/clo/la/device/samsung_slsi/arndale.git","description":null}
{"name":"la/platform/packages/modules/DnsResolver","clone_url":"https://git.codelinaro.org/clo/la/platform/packages/modules/DnsResolver.git","description":null}
{"name":"le/WebPlatformForEmbedded/WPEBackend-rdk","clone_url":"https://git.codelinaro.org/clo/le/WebPlatformForEmbedded/WPEBackend-rdk.git","description":null}
{"name":"la/platform/vendor/qcom/msmnileau_s_u","clone_url":"https://git.codelinaro.org/clo/la/platform/vendor/qcom/msmnileau_s_u.git","description":null}
{"name":"la/platform/vendor/qcom/taro612","clone_url":"https://git.codelinaro.org/clo/la/platform/vendor/qcom/taro612.git","description":null}
{"name":"la/platform/external/rust/crates/spin","clone_url":"https://git.codelinaro.org/clo/la/platform/external/rust/crates/spin.git","description":null}
{"name":"dataservices/modem-data-manager","clone_url":"https://git.codelinaro.org/clo/dataservices/modem-data-manager.git","description":null}
{"name":"la/platform/tools/repohooks-trampoline","clone_url":"https://git.codelinaro.org/clo/la/platform/tools/repohooks-trampoline.git","description":null}
{"name":"la/platform/external/rust/crates/serde-xml-rs","clone_url":"https://git.codelinaro.org/clo/la/platform/external/rust/crates/serde-xml-rs.git","description":null}
{"name":"la/kernel_platform/external/bazelbuild-rules_java","clone_url":"https://git.codelinaro.org/clo/la/kernel_platform/external/bazelbuild-rules_java.git","description":null}
{"name":"le/platform/vendor/qcom-opensource/robot-control","clone_url":"https://git.codelinaro.org/clo/le/platform/vendor/qcom-opensource/robot-control.git","description":null}
{"name":"yocto-mirrors/github/jbeder/yaml-cpp","clone_url":"https://git.codelinaro.org/clo/yocto-mirrors/github/jbeder/yaml-cpp.git","description":null}
{"name":"kernel-platform-2-0-os/kernel/build","clone_url":"https://git.codelinaro.org/clo/kernel-platform-2-0-os/kernel/build.git","description":null}
{"name":"la/platform/external/ethtool","clone_url":"https://git.codelinaro.org/clo/la/platform/external/ethtool.git","description":null}
{"name":"la/toolchain/libcxxabi","clone_url":"https://git.codelinaro.org/clo/la/toolchain/libcxxabi.git","description":null}
{"name":"yocto-mirrors/github/tonistiigi/go-actions-cache","clone_url":"https://git.codelinaro.org/clo/yocto-mirrors/github/tonistiigi/go-actions-cache.git","description":null}
{"name":"la/platform/external/boost-submodules/property_map_parallel","clone_url":"https://git.codelinaro.org/clo/la/platform/external/boost-submodules/property_map_parallel.git","description":null}
{"name":"qsdk/oss/system/feeds/nss-apps","clone_url":"https://git.codelinaro.org/clo/qsdk/oss/system/feeds/nss-apps.git","description":null}
{"name":"la/kernel/common-modules/virtual-device","clone_url":"https://git.codelinaro.org/clo/la/kernel/common-modules/virtual-device.git","description":null}
{"name":"lc/chromium/src/courgette","clone_url":"https://git.codelinaro.org/clo/lc/chromium/src/courgette.git","description":null}
{"name":"la/platform/vendor/opensource/gen4-5/virtio-video","clone_url":"https://git.codelinaro.org/clo/la/platform/vendor/opensource/gen4-5/virtio-video.git","description":null}
{"name":"lc/chromium/pipa","clone_url":"https://git.codelinaro.org/clo/lc/chromium/pipa.git","description":null}
{"name":"le/platform/vendor/opensource/gen4-5/display-drivers","clone_url":"https://git.codelinaro.org/clo/le/platform/vendor/opensource/gen4-5/display-drivers.git","description":null}
{"name":"la/platform/vendor/qcom/bengal_612s","clone_url":"https://git.codelinaro.org/clo/la/platform/vendor/qcom/bengal_612s.git","description":null}
{"name":"la/platform/external/chromium_org/third_party/yasm/source/patched-yasm","clone_url":"https://git.codelinaro.org/clo/la/platform/external/chromium_org/third_party/yasm/source/patched-yasm.git","description":null}
{"name":"qrdk/rdkcentral/common-library","clone_url":"https://git.codelinaro.org/clo/qrdk/rdkcentral/common-library.git","description":null}
{"name":"la/platform/prebuilts/fullsdk-darwin/platform-tools","clone_url":"https://git.codelinaro.org/clo/la/platform/prebuilts/fullsdk-darwin/platform-tools.git","description":null}
{"name":"la/platform/external/tinyxml2","clone_url":"https://git.codelinaro.org/clo/la/platform/external/tinyxml2.git","description":null}
{"name":"la/platform/vendor/opensource/mm-drivers","clone_url":"https://git.codelinaro.org/clo/la/platform/vendor/opensource/mm-drivers.git","description":null}
{"name":"la/platform/vendor/qcom/msmnileau_gvmq_ext4","clone_url":"https://git.codelinaro.org/clo/la/platform/vendor/qcom/msmnileau_gvmq_ext4.git","description":null}
{"name":"la/device/pifoundation/rpi3","clone_url":"https://git.codelinaro.org/clo/la/device/pifoundation/rpi3.git","description":null}
{"name":"la/platform/prebuilts/clang/darwin-x86/sdk/3.5","clone_url":"https://git.codelinaro.org/clo/la/platform/prebuilts/clang/darwin-x86/sdk/3.5.git","description":null}
{"name":"la/platform/system/memory/amemdiff","clone_url":"https://git.codelinaro.org/clo/la/platform/system/memory/amemdiff.git","description":null}
{"name":"la/platform/external/bart","clone_url":"https://git.codelinaro.org/clo/la/platform/external/bart.git","description":null}
{"name":"la/platform/external/google-auth-library-java","clone_url":"https://git.codelinaro.org/clo/la/platform/external/google-auth-library-java.git","description":null}
{"name":"lc/infra/third_party/docutils","clone_url":"https://git.codelinaro.org/clo/lc/infra/third_party/docutils.git","description":null}
{"name":"la/platform/prebuilts/fullsdk-darwin/cmdline-tools","clone_url":"https://git.codelinaro.org/clo/la/platform/prebuilts/fullsdk-darwin/cmdline-tools.git","description":null}
{"name":"yocto-mirrors/github/jthornber/thin-provisioning-tools","clone_url":"https://git.codelinaro.org/clo/yocto-mirrors/github/jthornber/thin-provisioning-tools.git","description":null}
{"name":"le/data/hostsw/ModemManager","clone_url":"https://git.codelinaro.org/clo/le/data/hostsw/ModemManager.git","description":null}
{"name":"la/device/linaro/hikey","clone_url":"https://git.codelinaro.org/clo/la/device/linaro/hikey.git","description":null}
{"name":"la/platform/vendor/qcom/bengal_515_32go","clone_url":"https://git.codelinaro.org/clo/la/platform/vendor/qcom/bengal_515_32go.git","description":null}
{"name":"la/platform/external/boost-submodules/nowide","clone_url":"https://git.codelinaro.org/clo/la/platform/external/boost-submodules/nowide.git","description":null}
{"name":"la/platform/external/jetbrains/jdk8u_corba","clone_url":"https://git.codelinaro.org/clo/la/platform/external/jetbrains/jdk8u_corba.git","description":null}
{"name":"la/platform/external/python/parse_type","clone_url":"https://git.codelinaro.org/clo/la/platform/external/python/parse_type.git","description":null}
{"name":"le/meta-fsl-bsp-release","clone_url":"https://git.codelinaro.org/clo/le/meta-fsl-bsp-release.git","description":null}
{"name":"la/kernel_platform/external/bazelbuild-rules_cc","clone_url":"https://git.codelinaro.org/clo/la/kernel_platform/external/bazelbuild-rules_cc.git","description":null}
{"name":"rdkb/rdkb/components/generic/servicemanager","clone_url":"https://git.codelinaro.org/clo/rdkb/rdkb/components/generic/servicemanager.git","description":null}
{"name":"lc/aosp/platform/packages/modules/Bluetooth","clone_url":"https://git.codelinaro.org/clo/lc/aosp/platform/packages/modules/Bluetooth.git","description":null}
{"name":"la/platform/external/Microsoft-GSL","clone_url":"https://git.codelinaro.org/clo/la/platform/external/Microsoft-GSL.git","description":null}
{"name":"qsdk/system/openwrt_repo","clone_url":"https://git.codelinaro.org/clo/qsdk/system/openwrt_repo.git","description":null}
{"name":"yocto-mirrors/github/opencontainers/selinux","clone_url":"https://git.codelinaro.org/clo/yocto-mirrors/github/opencontainers/selinux.git","description":null}
{"name":"lc/chromium/src/tools/perf","clone_url":"https://git.codelinaro.org/clo/lc/chromium/src/tools/perf.git","description":null}
{"name":"qrdk/rdkcentral/provisioning-and-management","clone_url":"https://git.codelinaro.org/clo/qrdk/rdkcentral/provisioning-and-management.git","description":null}
{"name":"la/platform/build/abfs","clone_url":"https://git.codelinaro.org/clo/la/platform/build/abfs.git","description":null}
{"name":"la/trusty/lk/nxp","clone_url":"https://git.codelinaro.org/clo/la/trusty/lk/nxp.git","description":null}
{"name":"lf/releases/l10n/pt-br/gecko","clone_url":"https://git.codelinaro.org/clo/lf/releases/l10n/pt-br/gecko.git","description":null}
{"name":"la/platform/packages/apps/WallpaperPicker","clone_url":"https://git.codelinaro.org/clo/la/platform/packages/apps/WallpaperPicker.git","description":null}
{"name":"la/platform/vendor/qcom/opensource/audioreach/audioreach-pipewire-plugin","clone_url":"https://git.codelinaro.org/clo/la/platform/vendor/qcom/opensource/audioreach/audioreach-pipewire-plugin.git","description":null}
{"name":"la/platform/vendor/qcom-opensource/audio-hal/st-hal","clone_url":"https://git.codelinaro.org/clo/la/platform/vendor/qcom-opensource/audio-hal/st-hal.git","description":null}
{"name":"la/platform/vendor/qcom/lahaina","clone_url":"https://git.codelinaro.org/clo/la/platform/vendor/qcom/lahaina.git","description":null}
{"name":"qsdk/oss/prpl-foundation/prplos/feeds/feed_netmodel","clone_url":"https://git.codelinaro.org/clo/qsdk/oss/prpl-foundation/prplos/feeds/feed_netmodel.git","description":null}
{"name":"la/platform/hardware/bsp/kernel/intel/edison-v4.4","clone_url":"https://git.codelinaro.org/clo/la/platform/hardware/bsp/kernel/intel/edison-v4.4.git","description":null}
{"name":"la/platform/prebuilts/clang/linux-x86/x86/3.3","clone_url":"https://git.codelinaro.org/clo/la/platform/prebuilts/clang/linux-x86/x86/3.3.git","description":null}
{"name":"atlas7-automotive-linux/multimedia/gst-omx","clone_url":"https://git.codelinaro.org/clo/atlas7-automotive-linux/multimedia/gst-omx.git","description":null}
{"name":"le/AGL/src/inputeventmanager","clone_url":"https://git.codelinaro.org/clo/le/AGL/src/inputeventmanager.git","description":null}
{"name":"qrdk/code.rdkcentral.com/rdkb/devices/raspberrypi/hal","clone_url":"https://git.codelinaro.org/clo/qrdk/code.rdkcentral.com/rdkb/devices/raspberrypi/hal.git","description":null}
{"name":"la/platform/vendor/qcom/bengal","clone_url":"https://git.codelinaro.org/clo/la/platform/vendor/qcom/bengal.git","description":null}
{"name":"la/platform/prebuilts/gcc/linux-x86/host/x86_64-linux-glibc2.7-4.6","clone_url":"https://git.codelinaro.org/clo/la/platform/prebuilts/gcc/linux-x86/host/x86_64-linux-glibc2.7-4.6.git","description":null}
{"name":"yocto-mirrors/github/moby/spdystream","clone_url":"https://git.codelinaro.org/clo/yocto-mirrors/github/moby/spdystream.git","description":null}
{"name":"le/ros2-gbp/rclc-release","clone_url":"https://git.codelinaro.org/clo/le/ros2-gbp/rclc-release.git","description":null}
{"name":"lc/external/github.com/google/dart-gl","clone_url":"https://git.codelinaro.org/clo/lc/external/github.com/google/dart-gl.git","description":null}
{"name":"la/platform/vendor/qcom/bengal_612","clone_url":"https://git.codelinaro.org/clo/la/platform/vendor/qcom/bengal_612.git","description":null}
{"name":"le/andersson/qmi-ping","clone_url":"https://git.codelinaro.org/clo/le/andersson/qmi-ping.git","description":null}
{"name":"sba-patches/telematics_eap_patches","clone_url":"https://git.codelinaro.org/clo/sba-patches/telematics_eap_patches.git","description":null}
{"name":"la/platform/external/rust/crates/strsim","clone_url":"https://git.codelinaro.org/clo/la/platform/external/rust/crates/strsim.git","description":null}
{"name":"le/external/googletest","clone_url":"https://git.codelinaro.org/clo/le/external/googletest.git","description":null}
{"name":"le/robos/robotics-os","clone_url":"https://git.codelinaro.org/clo/le/robos/robotics-os.git","description":null}
{"name":"qyocto/oss/system/recipes/recipes-packages","clone_url":"https://git.codelinaro.org/clo/qyocto/oss/system/recipes/recipes-packages.git","description":null}
{"name":"le/meta-qti-mmframeworks","clone_url":"https://git.codelinaro.org/clo/le/meta-qti-mmframeworks.git","description":null}
{"name":"la/platform/external/gcc-demangle","clone_url":"https://git.codelinaro.org/clo/la/platform/external/gcc-demangle.git","description":null}
{"name":"le/AGL/apps/agl-service-geofence","clone_url":"https://git.codelinaro.org/clo/le/AGL/apps/agl-service-geofence.git","description":null}
{"name":"lc/external/github.com/klauspost/crc32","clone_url":"https://git.codelinaro.org/clo/lc/external/github.com/klauspost/crc32.git","description":null}
{"name":"la/toolchain/cloog","clone_url":"https://git.codelinaro.org/clo/la/toolchain/cloog.git","description":null}
{"name":"la/platform/prebuilts/fullsdk-darwin/build-tools_group/31.0.0","clone_url":"https://git.codelinaro.org/clo/la/platform/prebuilts/fullsdk-darwin/build-tools_group/31.0.0.git","description":null}
{"name":"la/platform/external/libffi","clone_url":"https://git.codelinaro.org/clo/la/platform/external/libffi.git","description":null}
{"name":"rdkb/netfilter/ipset","clone_url":"https://git.codelinaro.org/clo/rdkb/netfilter/ipset.git","description":null}
{"name":"la/kernel/prebuilts/common-modules/virtual-device/4.19/arm64","clone_url":"https://git.codelinaro.org/clo/la/kernel/prebuilts/common-modules/virtual-device/4.19/arm64.git","description":null}
{"name":"lc/external/github.com/toji/webvr.info","clone_url":"https://git.codelinaro.org/clo/lc/external/github.com/toji/webvr.info.git","description":null}
{"name":"yocto-mirrors/github/hiddeco/sshsig","clone_url":"https://git.codelinaro.org/clo/yocto-mirrors/github/hiddeco/sshsig.git","description":null}
{"name":"la/platform/packages/apps/Launcher","clone_url":"https://git.codelinaro.org/clo/la/platform/packages/apps/Launcher.git","description":null}
{"name":"le/platform/vendor/qcom-opensource/mmc-utils","clone_url":"https://git.codelinaro.org/clo/le/platform/vendor/qcom-opensource/mmc-utils.git","description":null}
{"name":"le/external/qtlocation","clone_url":"https://git.codelinaro.org/clo/le/external/qtlocation.git","description":null}
{"name":"la/platform/external/rust/crates/tinyvec_macros","clone_url":"https://git.codelinaro.org/clo/la/platform/external/rust/crates/tinyvec_macros.git","description":null}
{"name":"la/platform/vendor/qcom/falcon_64","clone_url":"https://git.codelinaro.org/clo/la/platform/vendor/qcom/falcon_64.git","description":null}
{"name":"la/platform/packages/apps/Car/MediaPrebuilt","clone_url":"https://git.codelinaro.org/clo/la/platform/packages/apps/Car/MediaPrebuilt.git","description":null}
{"name":"la/platform/vendor/qcom/opensource/audioreach/audioreach-kernel","clone_url":"https://git.codelinaro.org/clo/la/platform/vendor/qcom/opensource/audioreach/audioreach-kernel.git","description":null}
{"name":"le/external/github.com/ridgerun/gstd-1.x","clone_url":"https://git.codelinaro.org/clo/le/external/github.com/ridgerun/gstd-1.x.git","description":null}
{"name":"sba-patches/autobsps32_patches","clone_url":"https://git.codelinaro.org/clo/sba-patches/autobsps32_patches.git","description":null}
{"name":"la/platform/external/protobuf-javalite","clone_url":"https://git.codelinaro.org/clo/la/platform/external/protobuf-javalite.git","description":null}
{"name":"la/platform/system/memory/mm_eventsd","clone_url":"https://git.codelinaro.org/clo/la/platform/system/memory/mm_eventsd.git","description":null}
{"name":"qsdk/oss/firmware/ath10k-firmware","clone_url":"https://git.codelinaro.org/clo/qsdk/oss/firmware/ath10k-firmware.git","description":null}
{"name":"la/platform/external/libvorbis","clone_url":"https://git.codelinaro.org/clo/la/platform/external/libvorbis.git","description":null}
{"name":"la/toolchain/gmp","clone_url":"https://git.codelinaro.org/clo/la/toolchain/gmp.git","description":null}
{"name":"la/platform/external/sil-fonts","clone_url":"https://git.codelinaro.org/clo/la/platform/external/sil-fonts.git","description":null}
{"name":"la/platform/vendor/opensource/camera-kernel","clone_url":"https://git.codelinaro.org/clo/la/platform/vendor/opensource/camera-kernel.git","description":null}
{"name":"le/platform/vendor/qcom-opensource/vm-tools","clone_url":"https://git.codelinaro.org/clo/le/platform/vendor/qcom-opensource/vm-tools.git","description":null}
{"name":"yocto-mirrors/github/pmezard/go-difflib","clone_url":"https://git.codelinaro.org/clo/yocto-mirrors/github/pmezard/go-difflib.git","description":null}
{"name":"la/platform/build_repo","clone_url":"https://git.codelinaro.org/clo/la/platform/build_repo.git","description":null}
{"name":"la/platform/external/python/liboqs-python","clone_url":"https://git.codelinaro.org/clo/la/platform/external/python/liboqs-python.git","description":null}
{"name":"la/meta-qti-qcawifi","clone_url":"https://git.codelinaro.org/clo/la/meta-qti-qcawifi.git","description":null}
{"name":"la/platform/external/rust/crates/epoll","clone_url":"https://git.codelinaro.org/clo/la/platform/external/rust/crates/epoll.git","description":null}
{"name":"femto5g/agl/meta-agl-devel","clone_url":"https://git.codelinaro.org/clo/femto5g/agl/meta-agl-devel.git","description":null}
{"name":"la/platform/prebuilts/cipd","clone_url":"https://git.codelinaro.org/clo/la/platform/prebuilts/cipd.git","description":null}
{"name":"la/platform/vendor/qcom/steppeau_gvmq","clone_url":"https://git.codelinaro.org/clo/la/platform/vendor/qcom/steppeau_gvmq.git","description":null}
{"name":"la/device/google/gs101-sepolicy","clone_url":"https://git.codelinaro.org/clo/la/device/google/gs101-sepolicy.git","description":null}
{"name":"lc/webm/libwebm","clone_url":"https://git.codelinaro.org/clo/lc/webm/libwebm.git","description":null}
{"name":"la/platform/external/rust/crates/bit_field","clone_url":"https://git.codelinaro.org/clo/la/platform/external/rust/crates/bit_field.git","description":null}
{"name":"la/platform/external/SPIRV-Reflect","clone_url":"https://git.codelinaro.org/clo/la/platform/external/SPIRV-Reflect.git","description":null}
{"name":"la/platform/external/jack","clone_url":"https://git.codelinaro.org/clo/la/platform/external/jack.git","description":null}
{"name":"la/platform/prebuilts/gradle-plugin","clone_url":"https://git.codelinaro.org/clo/la/platform/prebuilts/gradle-plugin.git","description":null}
{"name":"la/kernel/goldfish-modules","clone_url":"https://git.codelinaro.org/clo/la/kernel/goldfish-modules.git","description":null}
{"name":"la/toolchain/openmp_llvm","clone_url":"https://git.codelinaro.org/clo/la/toolchain/openmp_llvm.git","description":null}
{"name":"la/platform/external/drm_hwcomposer","clone_url":"https://git.codelinaro.org/clo/la/platform/external/drm_hwcomposer.git","description":null}
{"name":"la/platform/external/swig","clone_url":"https://git.codelinaro.org/clo/la/platform/external/swig.git","description":null}
{"name":"la/platform/vendor/qcom/copper","clone_url":"https://git.codelinaro.org/clo/la/platform/vendor/qcom/copper.git","description":null}
{"name":"le/AGL/src/most","clone_url":"https://git.codelinaro.org/clo/le/AGL/src/most.git","description":null}
{"name":"rdkb/clo/rdkb/rdkb/components/generic/notify_comp","clone_url":"https://git.codelinaro.org/clo/rdkb/clo/rdkb/rdkb/components/generic/notify_comp.git","description":null}
{"name":"rdkb/clo/rdkb/rdkb/components/opensource/ccsp/CcspTr069Pa","clone_url":"https://git.codelinaro.org/clo/rdkb/clo/rdkb/rdkb/components/opensource/ccsp/CcspTr069Pa.git","description":null}
{"name":"la/platform/external/rust/crates/fallible-streaming-iterator","clone_url":"https://git.codelinaro.org/clo/la/platform/external/rust/crates/fallible-streaming-iterator.git","description":null}
{"name":"la/platform/external/libhevc","clone_url":"https://git.codelinaro.org/clo/la/platform/external/libhevc.git","description":null}
{"name":"la/meta-qti-display","clone_url":"https://git.codelinaro.org/clo/la/meta-qti-display.git","description":null}
{"name":"qrdk/rdkcentral/gw-provisioning-application","clone_url":"https://git.codelinaro.org/clo/qrdk/rdkcentral/gw-provisioning-application.git","description":null}
{"name":"le/platform/external/iproute2","clone_url":"https://git.codelinaro.org/clo/le/platform/external/iproute2.git","description":null}
{"name":"la/platform/external/bazelbuild-remote-apis-sdks","clone_url":"https://git.codelinaro.org/clo/la/platform/external/bazelbuild-remote-apis-sdks.git","description":null}
{"name":"la/platform/external/python/enum","clone_url":"https://git.codelinaro.org/clo/la/platform/external/python/enum.git","description":null}
{"name":"lc/native_client/pnacl-llvm","clone_url":"https://git.codelinaro.org/clo/lc/native_client/pnacl-llvm.git","description":null}
{"name":"rdkb/rdkb/components/opensource/ccsp/CcspHomeSecurity","clone_url":"https://git.codelinaro.org/clo/rdkb/rdkb/components/opensource/ccsp/CcspHomeSecurity.git","description":null}
{"name":"le/coqos/linux-kernel-drivers/bootloader-reboot-driver-linux","clone_url":"https://git.codelinaro.org/clo/le/coqos/linux-kernel-drivers/bootloader-reboot-driver-linux.git","description":null}
{"name":"la/platform/vendor/qcom/msm8909go","clone_url":"https://git.codelinaro.org/clo/la/platform/vendor/qcom/msm8909go.git","description":null}
{"name":"la/device/google/felix-kernels/6.1","clone_url":"https://git.codelinaro.org/clo/la/device/google/felix-kernels/6.1.git","description":null}
{"name":"la/platform/external/rust/crates/parking_lot_core","clone_url":"https://git.codelinaro.org/clo/la/platform/external/rust/crates/parking_lot_core.git","description":null}
{"name":"qcomlt/ci/staging/Configs","clone_url":"https://git.codelinaro.org/clo/qcomlt/ci/staging/Configs.git","description":""}
{"name":"yocto-mirrors/github/cloudflare/circl","clone_url":"https://git.codelinaro.org/clo/yocto-mirrors/github/cloudflare/circl.git","description":null}
{"name":"qcomlt/ci/oe-scarthgap","clone_url":"https://git.codelinaro.org/clo/qcomlt/ci/oe-scarthgap.git","description":null}
{"name":"le/platform/external/mtpserver","clone_url":"https://git.codelinaro.org/clo/le/platform/external/mtpserver.git","description":null}
{"name":"rdkb/rdk/components/generic/rdm","clone_url":"https://git.codelinaro.org/clo/rdkb/rdk/components/generic/rdm.git","description":null}
{"name":"la/platform/vendor/qcom/monaco_group/codeaurora/power","clone_url":"https://git.codelinaro.org/clo/la/platform/vendor/qcom/monaco_group/codeaurora/power.git","description":null}
{"name":"la/platform/external/android-cmake","clone_url":"https://git.codelinaro.org/clo/la/platform/external/android-cmake.git","description":null}
{"name":"le/meta-qti-distro","clone_url":"https://git.codelinaro.org/clo/le/meta-qti-distro.git","description":null}
{"name":"la/kernel/msm-extra_group/video-devicetree","clone_url":"https://git.codelinaro.org/clo/la/kernel/msm-extra_group/video-devicetree.git","description":null}
{"name":"qsdk/pkcs11-provider","clone_url":"https://git.codelinaro.org/clo/qsdk/pkcs11-provider.git","description":null}
{"name":"la/platform/external/rust/crates/clap_lex","clone_url":"https://git.codelinaro.org/clo/la/platform/external/rust/crates/clap_lex.git","description":null}
{"name":"la/platform/packages/modules/UprobeStats","clone_url":"https://git.codelinaro.org/clo/la/platform/packages/modules/UprobeStats.git","description":null}
{"name":"qcomlt/pkg/cogl","clone_url":"https://git.codelinaro.org/clo/qcomlt/pkg/cogl.git","description":null}
{"name":"la/platform/external/rust/crates/annotate-snippets","clone_url":"https://git.codelinaro.org/clo/la/platform/external/rust/crates/annotate-snippets.git","description":null}
{"name":"la/platform/external/rust/crates/standback","clone_url":"https://git.codelinaro.org/clo/la/platform/external/rust/crates/standback.git","description":null}
{"name":"la/platform/hardware/bsp/kernel/rockchip","clone_url":"https://git.codelinaro.org/clo/la/platform/hardware/bsp/kernel/rockchip.git","description":null}
{"name":"la/device/linaro/dragonboard-kernel","clone_url":"https://git.codelinaro.org/clo/la/device/linaro/dragonboard-kernel.git","description":null}
{"name":"lc/chromiumos/third_party/displaylink-updater","clone_url":"https://git.codelinaro.org/clo/lc/chromiumos/third_party/displaylink-updater.git","description":null}
{"name":"la/platform/vendor/codeaurora/telephony","clone_url":"https://git.codelinaro.org/clo/la/platform/vendor/codeaurora/telephony.git","description":null}
{"name":"lc/infra/gerrit-plugins/binary-size","clone_url":"https://git.codelinaro.org/clo/lc/infra/gerrit-plugins/binary-size.git","description":null}
{"name":"la/platform/packages/apps/Car/Launcher","clone_url":"https://git.codelinaro.org/clo/la/platform/packages/apps/Car/Launcher.git","description":null}
{"name":"le/genivi/persistence/persistence-common-object","clone_url":"https://git.codelinaro.org/clo/le/genivi/persistence/persistence-common-object.git","description":null}
{"name":"le/platform/external/ROBOTIS-GIT/hls_lfcd_lds_driver","clone_url":"https://git.codelinaro.org/clo/le/platform/external/ROBOTIS-GIT/hls_lfcd_lds_driver.git","description":null}
{"name":"le/platform/vendor/qcom-opensource/wlan/utils/libhardware_legacy","clone_url":"https://git.codelinaro.org/clo/le/platform/vendor/qcom-opensource/wlan/utils/libhardware_legacy.git","description":null}
{"name":"la/platform/external/boost-submodules/range","clone_url":"https://git.codelinaro.org/clo/la/platform/external/boost-submodules/range.git","description":null}
{"name":"la/platform/external/mockito","clone_url":"https://git.codelinaro.org/clo/la/platform/external/mockito.git","description":null}
{"name":"la/platform/external/deqp-deps/amber","clone_url":"https://git.codelinaro.org/clo/la/platform/external/deqp-deps/amber.git","description":null}
{"name":"la/device/google/pantah-kernels/6.1","clone_url":"https://git.codelinaro.org/clo/la/device/google/pantah-kernels/6.1.git","description":null}
{"name":"la/platform/vendor/qcom-opensource/eavb","clone_url":"https://git.codelinaro.org/clo/la/platform/vendor/qcom-opensource/eavb.git","description":null}
{"name":"la/platform/packages/modules/SdkExtensions","clone_url":"https://git.codelinaro.org/clo/la/platform/packages/modules/SdkExtensions.git","description":null}
{"name":"femto5g/agl/meta-agl-extra","clone_url":"https://git.codelinaro.org/clo/femto5g/agl/meta-agl-extra.git","description":null}
{"name":"le/virtio/qcvirtio-vhost-usb-gadget-driver-linux","clone_url":"https://git.codelinaro.org/clo/le/virtio/qcvirtio-vhost-usb-gadget-driver-linux.git","description":null}
{"name":"le/platform/external/navigation","clone_url":"https://git.codelinaro.org/clo/le/platform/external/navigation.git","description":null}
{"name":"la/platform/external/boost-submodules/foreach","clone_url":"https://git.codelinaro.org/clo/la/platform/external/boost-submodules/foreach.git","description":null}
{"name":"la/platform/external/linux-tools-perf","clone_url":"https://git.codelinaro.org/clo/la/platform/external/linux-tools-perf.git","description":null}
{"name":"la/platform/vendor/qcom/gen4_gvm_sdvcomm","clone_url":"https://git.codelinaro.org/clo/la/platform/vendor/qcom/gen4_gvm_sdvcomm.git","description":null}
{"name":"le/owrt/feeds/routing","clone_url":"https://git.codelinaro.org/clo/le/owrt/feeds/routing.git","description":null}
{"name":"la/platform/prebuilts/clang/host/windows-x86_32","clone_url":"https://git.codelinaro.org/clo/la/platform/prebuilts/clang/host/windows-x86_32.git","description":null}
{"name":"la/platform/vendor/qcom/msm7627_7x_ffa","clone_url":"https://git.codelinaro.org/clo/la/platform/vendor/qcom/msm7627_7x_ffa.git","description":null}
{"name":"le/oss/lklm/qca-macsec","clone_url":"https://git.codelinaro.org/clo/le/oss/lklm/qca-macsec.git","description":null}
{"name":"yocto-mirrors/github/checkpoint-restore/checkpointctl","clone_url":"https://git.codelinaro.org/clo/yocto-mirrors/github/checkpoint-restore/checkpointctl.git","description":null}
{"name":"la/platform/external/OpenCL-Headers","clone_url":"https://git.codelinaro.org/clo/la/platform/external/OpenCL-Headers.git","description":null}
{"name":"la/platform/external/rust/crates/arc-swap","clone_url":"https://git.codelinaro.org/clo/la/platform/external/rust/crates/arc-swap.git","description":null}
{"name":"qsdk/oss/lklm/nss-plugins","clone_url":"https://git.codelinaro.org/clo/qsdk/oss/lklm/nss-plugins.git","description":null}
{"name":"lc/ssg/trustzone/tfa_upstream","clone_url":"https://git.codelinaro.org/clo/lc/ssg/trustzone/tfa_upstream.git","description":null}
{"name":"la/platform/vendor/codeaurora/android-watch/packages/apps/WatchMessenger","clone_url":"https://git.codelinaro.org/clo/la/platform/vendor/codeaurora/android-watch/packages/apps/WatchMessenger.git","description":null}
{"name":"lc/external/github.com/sybrenstuvel/python-rsa","clone_url":"https://git.codelinaro.org/clo/lc/external/github.com/sybrenstuvel/python-rsa.git","description":null}
{"name":"qrdk/config","clone_url":"https://git.codelinaro.org/clo/qrdk/config.git","description":null}
{"name":"lc/external/github.com/tmc/scp","clone_url":"https://git.codelinaro.org/clo/lc/external/github.com/tmc/scp.git","description":null}
{"name":"la/platform/external/rust/crates/dashmap","clone_url":"https://git.codelinaro.org/clo/la/platform/external/rust/crates/dashmap.git","description":null}
{"name":"lc/external/colorama","clone_url":"https://git.codelinaro.org/clo/lc/external/colorama.git","description":null}
{"name":"rdkb/rdkb/rdkcentral/meta-rdk-wan","clone_url":"https://git.codelinaro.org/clo/rdkb/rdkb/rdkcentral/meta-rdk-wan.git","description":null}
{"name":"la/platform/external/python/ply","clone_url":"https://git.codelinaro.org/clo/la/platform/external/python/ply.git","description":null}
{"name":"la/kernel/msm-4.4","clone_url":"https://git.codelinaro.org/clo/la/kernel/msm-4.4.git","description":null}
{"name":"automotive/platform/xen","clone_url":"https://git.codelinaro.org/clo/automotive/platform/xen.git","description":null}
{"name":"le/centos/automotive/src/kernel","clone_url":"https://git.codelinaro.org/clo/le/centos/automotive/src/kernel.git","description":null}
{"name":"qrdk/rdkgithub/comcast/trower-base64","clone_url":"https://git.codelinaro.org/clo/qrdk/rdkgithub/comcast/trower-base64.git","description":null}
{"name":"la/platform/external/boost-submodules/wave","clone_url":"https://git.codelinaro.org/clo/la/platform/external/boost-submodules/wave.git","description":null}
{"name":"le/platform/external/yocto-kernel-tools","clone_url":"https://git.codelinaro.org/clo/le/platform/external/yocto-kernel-tools.git","description":null}
{"name":"la/device/google/akita-sepolicy","clone_url":"https://git.codelinaro.org/clo/la/device/google/akita-sepolicy.git","description":null}
{"name":"la/platform/external/icu","clone_url":"https://git.codelinaro.org/clo/la/platform/external/icu.git","description":null}
{"name":"la/platform/external/apache-commons-bcel","clone_url":"https://git.codelinaro.org/clo/la/platform/external/apache-commons-bcel.git","description":null}
{"name":"yocto-mirrors/logrus","clone_url":"https://git.codelinaro.org/clo/yocto-mirrors/logrus.git","description":null}
{"name":"la/platform/external/python/grpc-google-iam-v1","clone_url":"https://git.codelinaro.org/clo/la/platform/external/python/grpc-google-iam-v1.git","description":null}
{"name":"la/platform/vendor/nxp/opensource/external/p61-jcop-kit","clone_url":"https://git.codelinaro.org/clo/la/platform/vendor/nxp/opensource/external/p61-jcop-kit.git","description":null}
{"name":"le/platform/vendor/qcom/opensource/audio-kernel-virtio","clone_url":"https://git.codelinaro.org/clo/le/platform/vendor/qcom/opensource/audio-kernel-virtio.git","description":null}
{"name":"le/platform/vendor/csm-wireshark","clone_url":"https://git.codelinaro.org/clo/le/platform/vendor/csm-wireshark.git","description":null}
{"name":"la/platform/external/toshiba_mcu","clone_url":"https://git.codelinaro.org/clo/la/platform/external/toshiba_mcu.git","description":null}
{"name":"qsdk/mt76","clone_url":"https://git.codelinaro.org/clo/qsdk/mt76.git","description":null}
{"name":"la/platform/external/bazelbuild-kotlin-rules","clone_url":"https://git.codelinaro.org/clo/la/platform/external/bazelbuild-kotlin-rules.git","description":null}
{"name":"yocto-mirrors/github/ros2-gbp/octomap-release","clone_url":"https://git.codelinaro.org/clo/yocto-mirrors/github/ros2-gbp/octomap-release.git","description":null}
{"name":"qsdk/oss/system/openwrt-patches_group/package/kernel/wlan-open","clone_url":"https://git.codelinaro.org/clo/qsdk/oss/system/openwrt-patches_group/package/kernel/wlan-open.git","description":null}
{"name":"la/platform/test/dittosuite","clone_url":"https://git.codelinaro.org/clo/la/platform/test/dittosuite.git","description":null}
{"name":"qrdk/code.rdkcentral.com/rdkb/devices/intel-x86-pc/emulator/sysint","clone_url":"https://git.codelinaro.org/clo/qrdk/code.rdkcentral.com/rdkb/devices/intel-x86-pc/emulator/sysint.git","description":null}
{"name":"la/platform/vendor/qcom/monaco_group/codeaurora/bluetooth","clone_url":"https://git.codelinaro.org/clo/la/platform/vendor/qcom/monaco_group/codeaurora/bluetooth.git","description":null}
{"name":"la/platform/vendor/nxp/opensource/test","clone_url":"https://git.codelinaro.org/clo/la/platform/vendor/nxp/opensource/test.git","description":null}
{"name":"lc/external/github.com/valvesoftware/openvr","clone_url":"https://git.codelinaro.org/clo/lc/external/github.com/valvesoftware/openvr.git","description":null}
{"name":"lc/external/dynamorio","clone_url":"https://git.codelinaro.org/clo/lc/external/dynamorio.git","description":null}
{"name":"le/platform/external/SimpleJSON","clone_url":"https://git.codelinaro.org/clo/le/platform/external/SimpleJSON.git","description":null}
{"name":"la/kernel/prebuilts/5.10/arm64","clone_url":"https://git.codelinaro.org/clo/la/kernel/prebuilts/5.10/arm64.git","description":null}
{"name":"la/platform/packages/apps/InCallUI","clone_url":"https://git.codelinaro.org/clo/la/platform/packages/apps/InCallUI.git","description":null}
{"name":"la/device/generic/x86_64","clone_url":"https://git.codelinaro.org/clo/la/device/generic/x86_64.git","description":null}
{"name":"la/platform/hardware/msm7k","clone_url":"https://git.codelinaro.org/clo/la/platform/hardware/msm7k.git","description":null}
{"name":"la/platform/external/rust/crates/displaydoc","clone_url":"https://git.codelinaro.org/clo/la/platform/external/rust/crates/displaydoc.git","description":null}
{"name":"la/platform/external/ant-wireless/ant_native","clone_url":"https://git.codelinaro.org/clo/la/platform/external/ant-wireless/ant_native.git","description":null}
{"name":"la/platform/prebuilts/fullsdk/platforms/android-33","clone_url":"https://git.codelinaro.org/clo/la/platform/prebuilts/fullsdk/platforms/android-33.git","description":null}
{"name":"le/platform/external/teb_local_planner","clone_url":"https://git.codelinaro.org/clo/le/platform/external/teb_local_planner.git","description":null}
{"name":"la/platform/external/python/future","clone_url":"https://git.codelinaro.org/clo/la/platform/external/python/future.git","description":null}
{"name":"qrdk/iksemel","clone_url":"https://git.codelinaro.org/clo/qrdk/iksemel.git","description":null}
{"name":"la/platform/vendor/qcom/opensource/graphics-hgsl","clone_url":"https://git.codelinaro.org/clo/la/platform/vendor/qcom/opensource/graphics-hgsl.git","description":null}
{"name":"la/platform/vendor/qcom/apq8064","clone_url":"https://git.codelinaro.org/clo/la/platform/vendor/qcom/apq8064.git","description":null}
{"name":"la/platform/external/easymock","clone_url":"https://git.codelinaro.org/clo/la/platform/external/easymock.git","description":null}
{"name":"la/platform/test/vts-testcase/kernel","clone_url":"https://git.codelinaro.org/clo/la/platform/test/vts-testcase/kernel.git","description":null}
{"name":"la/platform/prebuilts/gcc/linux-x86/arm/arm-eabi-4.8","clone_url":"https://git.codelinaro.org/clo/la/platform/prebuilts/gcc/linux-x86/arm/arm-eabi-4.8.git","description":null}
{"name":"la/platform/vendor/qcom/msm7630_fusion","clone_url":"https://git.codelinaro.org/clo/la/platform/vendor/qcom/msm7630_fusion.git","description":null}
{"name":"le/platform/vendor/qcom-opensource/mmhab-drv","clone_url":"https://git.codelinaro.org/clo/le/platform/vendor/qcom-opensource/mmhab-drv.git","description":null}
{"name":"la/platform/external/libfdt","clone_url":"https://git.codelinaro.org/clo/la/platform/external/libfdt.git","description":null}
{"name":"la/platform/external/webrtc","clone_url":"https://git.codelinaro.org/clo/la/platform/external/webrtc.git","description":null}
{"name":"le/qzephyr/zephyrproject-rtos/segger","clone_url":"https://git.codelinaro.org/clo/le/qzephyr/zephyrproject-rtos/segger.git","description":null}
{"name":"yocto-mirrors/github/codegangsta/cli","clone_url":"https://git.codelinaro.org/clo/yocto-mirrors/github/codegangsta/cli.git","description":null}
{"name":"la/kernel/google-modules/amplifiers","clone_url":"https://git.codelinaro.org/clo/la/kernel/google-modules/amplifiers.git","description":null}
{"name":"le/poky/meta-qti-telaf","clone_url":"https://git.codelinaro.org/clo/le/poky/meta-qti-telaf.git","description":null}
{"name":"lc/test_analyzer","clone_url":"https://git.codelinaro.org/clo/lc/test_analyzer.git","description":null}
{"name":"la/platform/test/gots","clone_url":"https://git.codelinaro.org/clo/la/platform/test/gots.git","description":null}
{"name":"yocto-mirrors/github/bugsnag/panicwrap","clone_url":"https://git.codelinaro.org/clo/yocto-mirrors/github/bugsnag/panicwrap.git","description":null}
{"name":"aimet/simple-ci","clone_url":"https://git.codelinaro.org/clo/aimet/simple-ci.git","description":null}
{"name":"qsdk/boot/u-boot","clone_url":"https://git.codelinaro.org/clo/qsdk/boot/u-boot.git","description":null}
{"name":"femto5g/fsm/external/qoriq-components/linux_5.4-rt","clone_url":"https://git.codelinaro.org/clo/femto5g/fsm/external/qoriq-components/linux_5.4-rt.git","description":null}
{"name":"le/platform/hardware/qcom/thermal","clone_url":"https://git.codelinaro.org/clo/le/platform/hardware/qcom/thermal.git","description":null}
{"name":"la/platform/vendor/qcom/prime_gvm","clone_url":"https://git.codelinaro.org/clo/la/platform/vendor/qcom/prime_gvm.git","description":null}
